import {
  Bot,
  CalendarDays,
  Cloud,
  FileSpreadsheet,
  Github,
  HardDrive,
  MessageCircle,
  NotebookTabs,
  Palette,
  Send,
  Smartphone,
  Sparkles,
  Video,
  type LucideIcon,
} from "lucide-react";

export type IntegrationCategory = "Storage & knowledge" | "Work & productivity" | "Communication" | "AI assistants" | "Built into Kurukoo" | "Devices & resources";
export type IntegrationStatus = "available" | "native" | "planned";
export type Integration = {
  slug: string; name: string; category: IntegrationCategory; description: string; detail: string; icon: LucideIcon;
  status: IntegrationStatus; auth: "oauth" | "mcp" | "channel" | "native" | "resource"; capabilities: string[];
  connectionLabel: string; endpoint?: { method: "GET" | "POST"; path: string }; setupPath?: string; setupLabel?: string;
};

export const integrationCategories: IntegrationCategory[] = ["Storage & knowledge", "Work & productivity", "Communication", "AI assistants", "Built into Kurukoo", "Devices & resources"];

export const integrations: Integration[] = [
  { slug: "google-drive", name: "Google Drive", category: "Storage & knowledge", description: "Use your Drive files as authorised context for requests.", detail: "Connect Google Drive so Kurukoo can find and use files you authorise when they are relevant to a job.", icon: HardDrive, status: "available", auth: "oauth", capabilities: ["Files", "Docs", "Sheets", "Slides"], connectionLabel: "Connect Google Drive", endpoint: { method: "POST", path: "/api/artifacts/drive/connect" } },
  { slug: "google-sheets", name: "Google Sheets", category: "Storage & knowledge", description: "Bring authorised spreadsheet data into the flow.", detail: "Connect Sheets when a request needs structured information from one of your spreadsheets.", icon: FileSpreadsheet, status: "available", auth: "oauth", capabilities: ["Read spreadsheet data", "Select ranges", "Use as request context"], connectionLabel: "Connect Google Sheets", endpoint: { method: "POST", path: "/api/artifacts/sheets/connect" } },
  { slug: "notion", name: "Notion", category: "Storage & knowledge", description: "Search authorised Notion pages when useful context is needed.", detail: "Connect Notion so Kurukoo can search the pages and knowledge you choose to make available.", icon: NotebookTabs, status: "available", auth: "oauth", capabilities: ["Search pages", "Use authorised knowledge", "Keep access scoped"], connectionLabel: "Connect Notion", endpoint: { method: "POST", path: "/api/artifacts/notion/connect" } },
  { slug: "onedrive", name: "OneDrive", category: "Storage & knowledge", description: "Use authorised Microsoft files as request context.", detail: "Connect OneDrive to let Kurukoo find files from the Microsoft account you authorise.", icon: Cloud, status: "available", auth: "oauth", capabilities: ["Files", "Folders", "Searchable context"], connectionLabel: "Connect OneDrive", endpoint: { method: "POST", path: "/api/artifacts/microsoft/onedrive/connect" } },
  { slug: "outlook", name: "Outlook", category: "Work & productivity", description: "Use authorised Outlook mail when a request needs it.", detail: "Connect Outlook so supported requests can use relevant email context from the account you authorise.", icon: MessageCircle, status: "available", auth: "oauth", capabilities: ["Email context", "Search mail", "Scoped Microsoft access"], connectionLabel: "Connect Outlook", endpoint: { method: "POST", path: "/api/artifacts/microsoft/outlook/connect" } },
  { slug: "google-calendar", name: "Google Calendar", category: "Work & productivity", description: "Bring your schedule into planning and coordination.", detail: "Google Calendar is part of Kurukoo's scheduling source catalogue. The current backend does not yet expose a Google Calendar OAuth flow.", icon: CalendarDays, status: "planned", auth: "oauth", capabilities: ["Schedule context", "Availability", "Event coordination"], connectionLabel: "Coming soon" },
  { slug: "outlook-calendar", name: "Outlook Calendar", category: "Work & productivity", description: "Bring your Microsoft schedule into planning and coordination.", detail: "Calendar support is planned separately from the current Outlook mail connection.", icon: CalendarDays, status: "planned", auth: "oauth", capabilities: ["Schedule context", "Availability", "Event coordination"], connectionLabel: "Coming soon" },
  { slug: "whatsapp", name: "WhatsApp", category: "Communication", description: "Talk to Kurukoo and keep supported conversations in the flow.", detail: "WhatsApp is a Kurukoo communication channel. The platform already contains WhatsApp channel and linked-device infrastructure; account linking depends on the active deployment configuration.", icon: MessageCircle, status: "available", auth: "channel", capabilities: ["Chat with Kurukoo", "Receive updates", "Use supported request flows"], connectionLabel: "Set up WhatsApp", setupPath: "/connect?channel=whatsapp", setupLabel: "Open WhatsApp setup" },
  { slug: "telegram", name: "Telegram", category: "Communication", description: "Use Telegram as another way to talk to Kurukoo.", detail: "Telegram is supported as a Kurukoo channel, with webhook and linked-device infrastructure already present. The available setup depends on the deployment configuration.", icon: Send, status: "available", auth: "channel", capabilities: ["Chat with Kurukoo", "Receive updates", "Use supported request flows"], connectionLabel: "Set up Telegram", setupPath: "/connect?channel=telegram", setupLabel: "Open Telegram setup" },
  { slug: "chatgpt", name: "ChatGPT", category: "AI assistants", description: "Use ChatGPT as a doorway into your Kurukoo OS.", detail: "Kurukoo exposes a remote MCP app surface so compatible ChatGPT accounts can connect to the same Kurukoo identity, context, authorisation and execution layer.", icon: Bot, status: "available", auth: "mcp", capabilities: ["Chat", "Voice where supported", "Invoke Kurukoo capabilities"], connectionLabel: "Connect from ChatGPT", setupPath: "/integrations/chatgpt", setupLabel: "View ChatGPT setup" },
  { slug: "claude", name: "Claude", category: "AI assistants", description: "Connect Claude to the same Kurukoo execution layer where supported.", detail: "Claude is documented as a provider-neutral MCP client for Kurukoo. Connection happens through Claude's own connector/app flow when the relevant MCP support is enabled.", icon: Sparkles, status: "available", auth: "mcp", capabilities: ["Conversation", "Kurukoo context", "Supported actions"], connectionLabel: "Set up in Claude", setupPath: "/integrations/claude", setupLabel: "View Claude setup" },
  { slug: "gemini", name: "Gemini", category: "AI assistants", description: "Use Gemini as an external conversation surface for Kurukoo.", detail: "Gemini is included in Kurukoo's provider-neutral MCP direction. The external client remains the conversation surface while Kurukoo stays authoritative for execution and permissions.", icon: Sparkles, status: "available", auth: "mcp", capabilities: ["Conversation", "Kurukoo context", "Supported actions"], connectionLabel: "Set up in Gemini", setupPath: "/integrations/gemini", setupLabel: "View Gemini setup" },
  { slug: "grok", name: "Grok", category: "AI assistants", description: "Use Grok as another supported AI doorway into Kurukoo.", detail: "Grok is included in Kurukoo's provider-neutral external AI direction. Availability depends on the client's support for the required MCP or custom-app connection flow.", icon: Bot, status: "available", auth: "mcp", capabilities: ["Conversation", "Kurukoo context", "Supported actions"], connectionLabel: "Set up in Grok", setupPath: "/integrations/grok", setupLabel: "View Grok setup" },
  { slug: "perplexity", name: "Perplexity", category: "AI assistants", description: "A future external AI doorway for Kurukoo conversations.", detail: "Perplexity is listed among Kurukoo's supported-channel direction, but a dedicated authenticated MCP connection flow is not yet exposed by the current backend.", icon: Sparkles, status: "planned", auth: "mcp", capabilities: ["Conversation", "Kurukoo context"], connectionLabel: "Coming soon" },
  { slug: "copilot", name: "Microsoft Copilot", category: "AI assistants", description: "A Microsoft AI doorway into Kurukoo where supported.", detail: "Copilot is part of Kurukoo's provider-neutral external AI direction. A dedicated user connection flow is not yet exposed by the current frontend/backend surface.", icon: Bot, status: "planned", auth: "mcp", capabilities: ["Conversation", "Kurukoo context"], connectionLabel: "Coming soon" },
  { slug: "dola", name: "Dola", category: "AI assistants", description: "An external AI doorway for Kurukoo where supported.", detail: "Dola is named in Kurukoo's provider-neutral MCP direction. A dedicated user connection flow is not yet exposed by the current frontend/backend surface.", icon: Bot, status: "planned", auth: "mcp", capabilities: ["Conversation", "Kurukoo context"], connectionLabel: "Coming soon" },
  { slug: "kurukoo-voice", name: "Kurukoo Voice", category: "Built into Kurukoo", description: "Talk to Kurukoo without adding another account.", detail: "Kurukoo Voice is a native capability. There is no third-party account to connect; use the voice surface already available in Kurukoo.", icon: Video, status: "native", auth: "native", capabilities: ["Voice conversation", "Request context", "Same Kurukoo account"], connectionLabel: "Available in Kurukoo", setupPath: "/chat", setupLabel: "Open Chat" },
  { slug: "kurukoo-theme", name: "Kurukoo appearance", category: "Built into Kurukoo", description: "Change the Kurukoo experience without connecting another service.", detail: "Appearance is a native Kurukoo setting. It behaves like an installed capability rather than an external account connection.", icon: Palette, status: "native", auth: "native", capabilities: ["Appearance", "Theme", "Account setting"], connectionLabel: "Use in Kurukoo", setupPath: "/settings", setupLabel: "Open Settings" },
  { slug: "connected-devices", name: "Devices & IoT", category: "Devices & resources", description: "Link supported devices and physical resources to Kurukoo.", detail: "Kurukoo's connected-resource layer supports registered phones, TVs, cameras, CCTV, computers, tablets, vehicles and IoT resources with pairing, status and controlled actions.", icon: Smartphone, status: "available", auth: "resource", capabilities: ["Pair resources", "Inspect status", "Controlled actions"], connectionLabel: "Manage devices", setupPath: "/connect", setupLabel: "Open device connections" },
  { slug: "github", name: "GitHub", category: "Work & productivity", description: "Bring repositories and engineering context into Kurukoo when connected.", detail: "GitHub is part of the broader Kurukoo development and agent tooling environment. A dedicated end-user OAuth connection is not yet exposed in the current connection catalogue.", icon: Github, status: "planned", auth: "oauth", capabilities: ["Repositories", "Issues", "Pull requests"], connectionLabel: "Coming soon" },
];

export function getIntegration(slug: string) { return integrations.find((integration) => integration.slug === slug); }
