export type CapabilitySurface = "Conversation" | "Explore" | "Requests & Work" | "Nearby & Map" | "Shop & Checkout" | "Providers" | "Opportunities" | "Topics & Community" | "Wallet" | "Memory & Reminders" | "Connect & Devices" | "Voice" | "Safety" | "Creators" | "Events & Travel" | "Activity" | "Health" | "People";

export type SkillEntry = { id: string; category: string; label: string; surfaces: CapabilitySurface[] };
export type SkillCategory = { name: string; skills: SkillEntry[]; surfaces: CapabilitySurface[] };

const labelOverrides: Record<string, string> = {
  okada_rider: "Get an Okada", keke_driver: "Book a Keke", informal_taxi: "Get an Informal Taxi", shuttle_driver: "Book a Shuttle", wheelbarrow_boy: "Find a Wheelbarrow Carrier", truck_pusher: "Find a Truck Pusher", school_run: "Get a School Run", pet_taxi: "Get a Pet Taxi", ev_charging: "Find EV Charging", taxi_quick: "Get a Taxi", train_check: "Check Train Times", ride_request: "Get a Ride",
  suya_vendor: "Get Suya", orange_hawker: "Buy Oranges", street_food_cart: "Find Street Food", zobo_seller: "Get Zobo", kunu_seller: "Get Kunu", food_nearby: "Find Food Nearby", grocery_reminder: "Order Groceries", order_food: "Order Food",
  device_support: "Get Device Help", wifi_installer: "Fix My Wi-Fi", warranty_tracker: "Track My Warranty", digital_executor: "Get a Digital Task Done", digital_declutter: "Sort My Digital Files", inbox_zero: "Clear My Inbox",
  phone_repair: "Fix My Phone", phone_repairer: "Find a Phone Repairer", shoe_cobbler: "Fix My Shoes", generator_repairer: "Fix My Generator", plumber: "Find a Plumber", electrician: "Get an Electrician", mechanic: "Find a Mechanic", vulcaniser: "Get a Tyre Repair", boiler_service: "Service My Boiler", repair: "Book Repair",
  mobile_barber: "Book a Barber", home_hairdresser: "Get a Hairdresser", manicurist: "Book a Manicurist", laundry_man: "Book Laundry", house_cleaner: "Get a Cleaner",
  emergency: "Emergency Call", ambulance_finder: "Find an Ambulance", towing_service: "Get Roadside Help", fire_service_contact: "Call Fire Service", security_patrol: "Get Security Help", flood_line: "Get Flood Help", swep_alert: "Check Safety Alerts",
  medicine_delivery: "Get Medicine Delivered", nursery_nurse: "Find a Nurse", herbal_practitioner: "Find a Herbal Practitioner", doctor_appointment: "Book a Doctor", sleep_tracker: "Track Sleep", energy_logger: "Track Energy", sad_lamp: "Find a SAD Lamp", carer_break: "Find Carer Support",
  home_tutor: "Find a Tutor", jamb_form_assistant: "Get JAMB Help", language_tutor: "Find a Language Tutor", word_of_day: "Learn a Word",
  event_mc: "Book an Event MC", live_band: "Book a Live Band", verified_artist: "Find a Verified Artist", museum_quiet: "Find a Quiet Museum", vinyl_wantlist: "Find Vinyl", event_finder: "Find an Event", buy_ticket: "Buy Tickets", dj: "Book a DJ", comedian: "Book a Comedian",
  room_to_rent: "Find a Room", short_let_host: "Find a Short Let", house_agent: "Find a House Agent", moving_house: "Plan a Move", first_flat: "Find Your First Flat", hotel_deals: "Find a Hotel",
  poultry_farmer: "Find a Poultry Farmer", fish_seller: "Buy Fresh Fish", fresh_veg_hawker: "Find Fresh Vegetables", allotment_sitter: "Find an Allotment Sitter",
  accounting_clerk: "Find an Accounting Clerk", legal_draftsman: "Find a Legal Draftsman", tax_assistant: "Get Tax Help", job_tracker: "Track a Job",
  prayer_partner: "Find a Prayer Partner", counselor: "Find a Counsellor", religious_book_seller: "Find Religious Books",
  graphic_designer: "Find a Graphic Designer", copywriter: "Find a Copywriter", social_media_manager: "Find a Social Media Manager", side_hustle: "Find a Side Hustle",
  flyer_distributor: "Find a Flyer Distributor", queue_stander: "Find a Queue Stand-in", survey_taker: "Find Survey Work", find_worker: "Find Someone to Help",
  dispatch_rider: "Offer Delivery", grocery_shopper: "Get Groceries", bill_payment_runner: "Pay a Bill", document_courier: "Send Documents",
  recharge_card_seller: "Find Airtime Seller", buy_airtime: "Buy Airtime", data_reseller: "Find a Data Reseller", phone_accessory_hawker: "Find Phone Accessories", data_bundle: "Buy Data",
  haulage_driver: "Find Haulage", cold_chain_operator: "Find Cold-chain Delivery", boat_operator: "Find a Boat Operator",
  creek_guide: "Find a Creek Guide", city_tour_guide: "Book a City Tour", right_to_roam: "Find Places to Roam", urban_explorer: "Explore the City", flight_alert: "Get Flight Alerts",
  bead_maker: "Find a Bead Maker", tailor_fashion_designer: "Find a Fashion Designer", photographer: "Find a Photographer", sketch_prompt: "Get a Creative Prompt", creative_block: "Get Past a Creative Block",
  night_guard: "Find a Night Guard", event_bouncer: "Find an Event Bouncer", night_walk: "Get Night-walk Support", security_personnel: "Find Security Personnel",
  fitness_trainer: "Find a Fitness Trainer", running_beacon: "Find a Running Group", couch_to_5k: "Start Couch to 5K", walking_group: "Join a Walking Group",
  bar_triage: "Find a Lounge", lounge_promoter: "Find a Lounge Promoter",
  football_viewing_center: "Watch Football", sports_analyst: "Find Sports Analysis",
  thrift_collector_ajo: "Join a Savings Group", group_savings_organiser: "Organise Ajo",
  second_hand_phones: "Buy a Used Phone", clothes_bend_down: "Find Second-hand Clothes", car_boot: "Find a Car Boot Sale", charity_shop: "Find a Charity Shop", farm_shop: "Find a Farm Shop", gift_finder: "Find a Gift", buy_car: "Buy a Car", product_sourcing: "Source a Product",
  wholesale_rice_tracker: "Check Rice Prices", cement_price_checker: "Check Cement Prices",
  nin_passport_guidance: "Get NIN / Passport Help", bin_day: "Set Bin Reminders", council_tax: "Handle Council Tax", parking_appeal: "Appeal Parking", accessibility: "Find Accessibility Help",
  neighbourhood_watch: "Join Neighbourhood Watch", skill_swap: "Swap a Skill", funeral_wishes: "Record Funeral Wishes", bereavement_admin: "Get Bereavement Admin Help", street_party: "Organise a Street Party", borrowed_iou: "Track a Borrowed Item", micro_volunteer: "Find Micro-volunteering", pride_events: "Find Pride Events", genealogy: "Explore Family History",
  akara_hot_seller: "Get Akara", puff_puff_hawker: "Get Puff-Puff", roasted_corn_vendor: "Find Roasted Corn",
  lga_office_directory: "Find an LGA Office", artisan_registry: "Find a Registered Artisan",
  pidgin_interpreter: "Speak Pidgin", hausa_translator: "Translate Hausa", yoruba_transcriber: "Transcribe Yoruba", igbo_tutor: "Learn Igbo", ijaw_voice: "Use Ijaw Voice",
  roadside_mechanic: "Get Roadside Help", car_washer: "Book a Car Wash", mot_reminder: "Set MOT Reminder",
  micro_bookkeeper: "Find a Bookkeeper", insurance_renewal: "Set Insurance Reminder", energy_tariff: "Check Energy Tariffs", retirement_coach: "Plan for Retirement",
  dog_breeder: "Find a Dog Breeder", vet_assistant: "Get Vet Help", lost_pet: "Find a Lost Pet", pet_weight: "Track Pet Weight",
  land_surveyor: "Find a Land Surveyor", rental_tracker: "Track Rent",
  daycare_operator: "Find Daycare", babysitter: "Find a Babysitter",
  spa_masseuse: "Book a Massage", makeup_artist: "Book a Makeup Artist",
  fumigation_agent: "Book Fumigation", waste_collector: "Find Waste Collection",
  smart_tv_bridge: "Control My Smart TV", ac_remote_bridge: "Control My AC",
  contract_reviewer: "Review a Contract", affidavit_assistant: "Get Affidavit Help",
  ankara_seamstress: "Find an Ankara Seamstress", suit_tailor: "Find a Suit Tailor",
  inverter_installer: "Find an Inverter Installer", solar_panel_technician: "Find a Solar Technician",
  canopy_rental: "Rent a Canopy", public_address_system: "Rent a PA System",
  sachet_water_distributor: "Order Drinking Water", tanker_water_supplier: "Order Tanker Water",
  football_player: "Find Football Players", basketball_player: "Find Basketball Players", tennis_partner: "Find a Tennis Partner", sports_coach: "Find a Sports Coach", football_club_founder: "Start a Football Club", match_organizer: "Organise a Match", team_captain: "Find a Team Captain", league_admin: "Manage a League", pitch_manager: "Book a Pitch", sports_event_host: "Host a Sports Event"
};

const makeLabel = (id: string) => labelOverrides[id] ?? id.replace(/_/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
const groups: Array<[string, string[], CapabilitySurface[]]> = [
["Transport & mobility", ["rider","okada_rider","keke_driver","informal_taxi","shuttle_driver","wheelbarrow_boy","truck_pusher","school_run","pet_taxi","ev_charging","taxi_quick","train_check","ride_request"], ["Conversation","Explore","Requests & Work","Nearby & Map"]],
["Food & drink", ["suya_vendor","orange_hawker","street_food_cart","caterer","bakery","zobo_seller","kunu_seller","food_nearby","grocery_reminder","order_food"], ["Conversation","Explore","Requests & Work","Nearby & Map","Shop & Checkout"]],
["Digital services", ["device_support","wifi_installer","warranty_tracker","digital_executor","digital_declutter","inbox_zero"], ["Conversation","Requests & Work","Connect & Devices"]],
["Repairs & maintenance", ["phone_repair","phone_repairer","shoe_cobbler","generator_repairer","plumber","electrician","mechanic","vulcaniser","boiler_service","repair"], ["Conversation","Explore","Requests & Work","Providers","Shop & Checkout"]],
["Personal care", ["mobile_barber","home_hairdresser","manicurist","laundry_man","house_cleaner"], ["Conversation","Explore","Requests & Work","Providers"]],
["Emergency dispatch", ["emergency","ambulance_finder","towing_service","fire_service_contact","security_patrol","flood_line","swep_alert"], ["Conversation","Safety","Requests & Work","Activity"]],
["Health & medical", ["medicine_delivery","nursery_nurse","herbal_practitioner","doctor_appointment","sleep_tracker","energy_logger","sad_lamp","carer_break"], ["Conversation","Requests & Work","Health","Memory & Reminders"]],
["Education & learning", ["home_tutor","jamb_form_assistant","language_tutor","word_of_day"], ["Explore","Topics & Community","Conversation"]],
["Events & entertainment", ["event_mc","dj","live_band","comedian","verified_artist","museum_quiet","vinyl_wantlist","event_finder","buy_ticket"], ["Explore","Events & Travel","Topics & Community","Shop & Checkout"]],
["Accommodation & lodging", ["room_to_rent","short_let_host","house_agent","moving_house","first_flat","hotel_deals"], ["Explore","Requests & Work","Memory & Reminders","Nearby & Map"]],
["Agriculture & produce", ["poultry_farmer","fish_seller","fresh_veg_hawker","allotment_sitter"], ["Explore","Shop & Checkout","Nearby & Map","Topics & Community"]],
["Professional services", ["accounting_clerk","legal_draftsman","tax_assistant","job_tracker"], ["Requests & Work","Providers","Opportunities","Conversation"]],
["Spiritual & religious", ["prayer_partner","counselor","religious_book_seller"], ["Conversation","Topics & Community","Explore","People"]],
["Freelance services", ["graphic_designer","copywriter","social_media_manager","side_hustle"], ["Requests & Work","Providers","Opportunities"]],
["Gigs & microtasks", ["flyer_distributor","queue_stander","survey_taker","find_worker"], ["Requests & Work","Opportunities","Conversation"]],
["Errands & delivery", ["dispatch_rider","grocery_shopper","bill_payment_runner","document_courier","find_worker"], ["Requests & Work","Explore","Nearby & Map"]],
["Communication & telecom", ["recharge_card_seller","buy_airtime","data_reseller","phone_accessory_hawker","data_bundle"], ["Conversation","Shop & Checkout","Wallet"]],
["Logistics & freight", ["haulage_driver","cold_chain_operator","boat_operator"], ["Requests & Work","Providers","Opportunities"]],
["Tourism & travel", ["creek_guide","city_tour_guide","right_to_roam","urban_explorer","flight_alert"], ["Explore","Events & Travel","Nearby & Map","Activity"]],
["Creative arts", ["bead_maker","tailor_fashion_designer","photographer","sketch_prompt","creative_block"], ["Creators","Explore","Topics & Community","Conversation"]],
["Security & safety", ["night_guard","event_bouncer","night_walk","security_personnel"], ["Safety","Providers","Requests & Work"]],
["Fitness & coaching", ["fitness_trainer","running_beacon","couch_to_5k","walking_group"], ["Health","Topics & Community","Memory & Reminders","Explore"]],
["Nightlife & lounges", ["bar_triage","lounge_promoter"], ["Explore","Events & Travel","Opportunities"]],
["Sports & viewing", ["football_viewing_center","sports_analyst"], ["Explore","Topics & Community"]],
["Money circle", ["thrift_collector_ajo","group_savings_organiser"], ["Wallet","Topics & Community","Conversation"]],
["Classifieds & marketplace", ["second_hand_phones","clothes_bend_down","car_boot","charity_shop","farm_shop","gift_finder","buy_car","product_sourcing"], ["Explore","Shop & Checkout","Wallet","Opportunities"]],
["Price checking", ["wholesale_rice_tracker","cement_price_checker"], ["Explore","Conversation","Topics & Community"]],
["Government & civic", ["nin_passport_guidance","bin_day","council_tax","parking_appeal","accessibility"], ["Conversation","Memory & Reminders","Explore"]],
["Community & neighbourhood", ["neighbourhood_watch","skill_swap","funeral_wishes","bereavement_admin","street_party","borrowed_iou","micro_volunteer","pride_events","genealogy"], ["Topics & Community","Memory & Reminders","Explore","Activity"]],
["Cravings & street food", ["akara_hot_seller","puff_puff_hawker","roasted_corn_vendor"], ["Nearby & Map","Explore","Conversation"]],
["Reach & reference", ["lga_office_directory","artisan_registry"], ["Explore","Providers"]],
["Language services", ["pidgin_interpreter","hausa_translator","yoruba_transcriber","igbo_tutor","ijaw_voice"], ["Conversation","Voice","Connect & Devices"]],
["Automotive mechanics", ["roadside_mechanic","car_washer","mot_reminder"], ["Requests & Work","Providers","Memory & Reminders"]],
["Finance & tax", ["micro_bookkeeper","insurance_renewal","energy_tariff","retirement_coach"], ["Wallet","Conversation","Memory & Reminders"]],
["Pet & animal care", ["dog_breeder","vet_assistant","lost_pet","pet_weight"], ["Explore","Requests & Work","Memory & Reminders"]],
["Property & real estate", ["land_surveyor","rental_tracker"], ["Requests & Work","Memory & Reminders","Explore"]],
["Childcare & nanny", ["daycare_operator","babysitter"], ["Providers","Requests & Work","Explore"]],
["Beauty & wellness", ["spa_masseuse","makeup_artist"], ["Explore","Providers","Requests & Work"]],
["Cleaning & sanitation", ["fumigation_agent","waste_collector"], ["Explore","Providers","Requests & Work","Nearby & Map"]],
["Home automation", ["smart_tv_bridge","ac_remote_bridge"], ["Connect & Devices","Conversation"]],
["Legal & compliance", ["contract_reviewer","affidavit_assistant"], ["Conversation","Memory & Reminders","Connect & Devices"]],
["Fashion & apparel", ["ankara_seamstress","suit_tailor"], ["Explore","Providers","Shop & Checkout","Requests & Work"]],
["Solar & energy", ["inverter_installer","solar_panel_technician"], ["Providers","Requests & Work","Explore"]],
["Event rentals", ["canopy_rental","public_address_system"], ["Events & Travel","Providers","Shop & Checkout"]],
["Water & beverage", ["sachet_water_distributor","tanker_water_supplier"], ["Nearby & Map","Shop & Checkout","Requests & Work"]],
["Sports & recreation", ["football_player","basketball_player","tennis_partner","sports_coach","football_club_founder","match_organizer","team_captain","league_admin","pitch_manager","sports_event_host"], ["Topics & Community","Explore","Events & Travel","Opportunities"]]
];
export const skillCategories: SkillCategory[] = groups.map(([name, ids, surfaces]) => ({ name, surfaces, skills: ids.map((id) => ({ id, category: name, label: makeLabel(id), surfaces })) }));
export const skillFlows: SkillEntry[] = skillCategories.flatMap((category) => category.skills);
export const capabilityCount = skillFlows.length;
export const userJobs = ["Get a Ride", "Order Food", "Book Repair", "Find Work", "Buy an Item", "Sell an Item", "Offer Delivery", "Get Prayers", "Set a Reminder", "Find Nearby", "Get Price Alerts", "Emergency Call", "Find a Tutor", "Book a Doctor", "Find a Room", "Find a Cleaner", "Find a Tennis Partner", "Find a Photographer", "Buy a Car", "Source a Product", "Buy Airtime", "Buy Data", "Get Roadside Help"] as const;
export const canonicalRequestExamples = [{ prompt: "Get me a ride to the airport at 7 tomorrow.", label: "Get a Ride", skill: "ride_request" }, { prompt: "Find someone to repair my phone screen today.", label: "Book Repair", skill: "repair" }, { prompt: "Can you find me a job delivering food?", label: "Find Work", skill: "find_worker" }, { prompt: "I need suya near me.", label: "Get Suya", skill: "suya_vendor" }, { prompt: "Please get me prayers for today.", label: "Get Prayers", skill: "prayer_partner" }] as const;
