import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { PageHeader } from "@/components/app-shell";
import { Action } from "@/components/kurukoo/primitives";
import { AdSlot, Badge, Panel, Rows, SectionHeader, StatTile, Tabs } from "@/components/kurukoo/ui";
import { campaigns } from "@/lib/kurukoo-demo";
export const Route=createFileRoute("/advertising")({head:()=>({meta:[{title:"Advertising — Kurukoo"},{name:"description",content:"Create clearly labelled sponsored placements across Kurukoo, with campaigns, budgets, billing and measurement."}]}),component:AdvertisingPage});
const tabs=["Campaigns","Create","Placements","Billing"] as const;
function AdvertisingPage(){const [tab,setTab]=useState<string>(tabs[0]);return <><PageHeader title="Advertising" subtitle="Reach people when a relevant need or discovery moment makes your offer useful."/><Tabs items={tabs} value={tab} onChange={setTab}/>{tab==="Campaigns"&&<div className="mt-4 space-y-4"><div className="grid gap-3 sm:grid-cols-3"><StatTile label="Spend (30 days)" value="£170.10" note="Sample campaign data"/><StatTile label="Impressions" value="82,084" note="Sample campaign data"/><StatTile label="Conversions" value="125" note="Sample campaign data"/></div><Rows>{campaigns.map(c=><li key={c.id} className="px-4 py-4"><div className="flex items-center justify-between gap-3"><p className="text-[15.5px] font-medium">{c.name}</p><Badge tone={c.status==="active"?"success":"quiet"}>{c.status}</Badge></div><p className="mt-1 text-[13px] text-muted-foreground">{c.budget} · {c.spend} spent · {c.placement}</p><p className="mt-1 text-[13px] text-muted-foreground">{c.impressions} impressions · {c.clicks} clicks · {c.conversions} conversions</p></li>)}</Rows><p className="text-[12px] text-muted-foreground">Sample figures are for the frontend illustration; live campaign delivery and measurement are coming soon.</p></div>}{tab==="Create"&&<Panel className="mt-4 p-4"><SectionHeader title="Create a campaign" subtitle="Set the goal, audience, creative, placement and budget."/><ul className="space-y-3 text-[14px]">{["Goal — requests, follows or visits","Audience — topic, location and intent","Creative — headline, body and image","Placement — Explore feed, Daily Picks, search, topics or creator discovery","Budget and schedule"].map(f=><li key={f} className="rounded-lg border border-border px-3 py-2.5 text-muted-foreground">{f}</li>)}</ul><div className="mt-4"><Action variant="primary">Save campaign draft</Action></div></Panel>}{tab==="Placements"&&<div className="mt-4 space-y-3"><p className="text-[13.5px] text-muted-foreground">Sponsored content is clearly labelled and kept distinct from organic recommendations.</p>{["Explore feed","Daily Picks","Search results","Topic feed","Creator discovery"].map(p=><AdSlot key={p} placement={p} headline="Your sponsored placement" body="Relevant offers and services can appear here when connected." advertiser="Example advertiser"/>)}</div>}{tab==="Billing"&&<Panel className="mt-4 p-4"><p className="text-[15px] font-medium">Advertising billing</p><p className="mt-1 text-[13.5px] text-muted-foreground">Payment methods, invoices, spend limits and charges appear here when the advertising billing connection is enabled.</p></Panel>}</>}
