/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import { Router } from 'express';
import { authenticateAdmin, authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { createPaystackTransaction } from '../services/paystackPayment.js';
import { createStripePaymentIntent } from '../services/stripePayment.js';
import { activateNetworkAgent, chargeProviderLead, createPointsTopUpIntent, getAgentNetworkSummary, getNetworkAgentByPhone, getProviderLeadCost, listActiveNetworkAgents, recordPointsTopUpEvidence, registerNetworkAgent, settlePointsTopUp } from '../services/agentNetworkCommerce.js';
import { getAgentCommissionBalance, getAgentPayoutReadiness, requestAgentCommissionPayout, settleAgentCommissionPayout } from '../services/agentCommissionSettlement.js';
import { getPointsLabel } from '../services/pointsEngine.js';

const router=Router();
const paymentProvider=()=>String(process.env.KURUKOO_PAY_PROVIDER||'sandbox').trim().toLowerCase();

router.post('/agent-network/register',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'');const agent=await registerNetworkAgent({phone,name:req.body?.name,agentType:req.body?.agentType,country:req.body?.country,region:req.body?.region});res.status(201).json({success:true,agent});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to register as a Kurukoo agent.'});}});
router.get('/agent-network/me',authenticateUser,async(req:AuthRequest,res)=>{try{res.json({success:true,agent:await getNetworkAgentByPhone(String(req.user?.phone||''))});}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Unable to load network agent status.'});}});
router.get('/agent-network/available',authenticateUser,async(req:AuthRequest,res)=>{try{const agents=await listActiveNetworkAgents({country:req.query.country?String(req.query.country):'ng',region:req.query.region?String(req.query.region):undefined,limit:Number(req.query.limit)||20});res.json({success:true,agents:agents.map(agent=>({id:agent.id,name:agent.name,agentType:agent.agentType,country:agent.country,region:agent.region,status:agent.status,canSellPoints:agent.canSellPoints,canAcceptTopUps:agent.canAcceptTopUps}))});}catch(error){res.status(500).json({success:false,error:error instanceof Error?error.message:'Unable to load active Kurukoo agents.'});}});
router.post('/agent-network/points/topup-intents',authenticateUser,async(req:AuthRequest,res)=>{try{const agentId=String(req.body?.agentId||'').trim()||undefined;const customerPhone=String(req.user?.phone||'');const intent=await createPointsTopUpIntent({customerPhone,points:req.body?.points,fiatAmountMinor:req.body?.fiatAmountMinor,currency:req.body?.currency||'NGN',agentId,idempotencyKey:req.body?.idempotencyKey});if(intent.status==='settled')return res.status(200).json({success:true,topUp:intent,paymentRequired:false,settlement:'already-settled'});if(paymentProvider()==='paystack'){const email=String(req.body?.email||'').trim();if(!email)return res.status(400).json({success:false,error:'Customer email is required for Paystack checkout.'});const payment=await createPaystackTransaction({amountMinor:intent.fiatAmountMinor,currency:intent.currency,email,economicRequestId:`agent_points_topup:${intent.id}`,idempotencyKey:`kurukoo:agent_points_topup:${intent.id}`});return res.status(201).json({success:true,topUp:intent,paymentRequired:true,provider:'paystack',reference:payment.reference,authorizationUrl:payment.authorizationUrl,amountMinor:payment.amountMinor,currency:payment.currency,settlement:'server-side-verified'});}if(paymentProvider()==='stripe'){const payment=await createStripePaymentIntent({amountMinor:intent.fiatAmountMinor,currency:intent.currency,economicRequestId:`agent_points_topup:${intent.id}`,idempotencyKey:`kurukoo:agent_points_topup:${intent.id}`});return res.status(201).json({success:true,topUp:intent,paymentRequired:true,provider:'stripe',paymentIntentId:payment.id,clientSecret:payment.clientSecret,amountMinor:payment.amountMinor,currency:payment.currency,settlement:'verified-webhook-only'});}return res.status(503).json({error:'A verified Nigeria payment provider is required for network-unit purchase.',payment_required:true});}catch(error){res.status(503).json({error:error instanceof Error?error.message:'Unable to create network-unit purchase.',payment_required:true});}});
router.post('/agent-network/me/points/sales',authenticateUser,async(req:AuthRequest,res)=>{try{const agent=await getNetworkAgentByPhone(String(req.user?.phone||''));if(!agent||agent.status!=='active'||!agent.canSellPoints)return res.status(403).json({success:false,error:`Active authorised agent status is required to sell ${getPointsLabel()}.`});const customerPhone=String(req.body?.customerPhone||'').trim();if(!customerPhone||customerPhone.startsWith('anon_'))return res.status(400).json({success:false,error:'A verified customer phone is required.'});const intent=await createPointsTopUpIntent({customerPhone,points:Number(req.body?.points),fiatAmountMinor:Number(req.body?.fiatAmountMinor),currency:String(req.body?.currency||'NGN'),agentId:agent.id,idempotencyKey:req.body?.idempotencyKey});const evidence=String(req.body?.externalReference||'').trim();if(!evidence)return res.status(202).json({success:true,topUp:intent,settlement:'pending_external_payment_evidence',message:`Customer payment must be verified before ${getPointsLabel()} are credited.`});const recorded=await recordPointsTopUpEvidence(intent.id,agent.phone,evidence);res.status(202).json({success:true,topUp:recorded,settlement:'pending_verification',message:`Payment evidence recorded. ${getPointsLabel()} remain pending until the configured settlement authority verifies the transaction.`});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to create agent-assisted network-unit sale.'});}});
router.post('/agent-network/provider-leads/charge',authenticateUser,async(req:AuthRequest,res)=>{try{const providerPhone=String(req.body?.providerPhone||req.user?.phone||'');const result=await chargeProviderLead({providerPhone,category:req.body?.category,skill:req.body?.skill,requestId:req.body?.requestId});res.status(result.success?200:402).json({...result,success:result.success,unitLabel:getPointsLabel()});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to charge provider lead.'});}});
router.get('/agent-network/provider-leads/cost',authenticateUser,async(req:AuthRequest,res)=>res.json({success:true,points:await getProviderLeadCost(String(req.query.category||''),String(req.query.skill||'')),unitLabel:getPointsLabel()}));
router.get('/agent-network/me/commission',authenticateUser,async(req:AuthRequest,res)=>{try{const agent=await getNetworkAgentByPhone(String(req.user?.phone||''));if(!agent)return res.status(404).json({success:false,error:'Network agent not found.'});res.json({success:true,balance:await getAgentCommissionBalance(agent.id,String(req.query.currency||'NGN')),payout:getAgentPayoutReadiness()});}catch(error){res.status(500).json({success:false,error:error instanceof Error?error.message:'Unable to load agent commission.'});}});
router.post('/agent-network/me/commission/payout',authenticateUser,async(req:AuthRequest,res)=>{try{const agent=await getNetworkAgentByPhone(String(req.user?.phone||''));if(!agent)return res.status(404).json({success:false,error:'Network agent not found.'});const payout=await requestAgentCommissionPayout({agentId:agent.id,amountMinor:Number(req.body?.amountMinor),currency:String(req.body?.currency||'NGN'),rail:req.body?.rail,destinationRef:String(req.body?.destinationRef||''),idempotencyKey:req.body?.idempotencyKey});res.status(201).json({success:true,payout});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to request commission payout.'});}});
router.post('/admin/agent-network/:agentId/activate',authenticateAdmin,async(req:AuthRequest,res)=>{try{await activateNetworkAgent(String(req.params.agentId));res.json({success:true});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to activate network agent.'});}});
router.post('/admin/agent-network/points/topups/:topUpId/settle',authenticateAdmin,async(req:AuthRequest,res)=>{try{const result=await settlePointsTopUp(String(req.params.topUpId),String(req.body?.externalReference||''));res.json({...result,success:true,manualSettlement:true});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to settle network-unit top-up.'});}});
router.post('/admin/agent-network/commission/payouts/:payoutId/settle',authenticateAdmin,async(req:AuthRequest,res)=>{try{const result=await settleAgentCommissionPayout(String(req.params.payoutId),String(req.body?.externalReference||''));res.json({success:true,payout:result,externalSettlement:true});}catch(error){res.status(400).json({success:false,error:error instanceof Error?error.message:'Unable to settle agent commission payout.'});}});
router.get('/admin/agent-network/summary',authenticateAdmin,async(_req:AuthRequest,res)=>{try{res.json({success:true,...await getAgentNetworkSummary(),unitLabel:getPointsLabel()});}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Unable to load agent network summary.'});}});
export default router;
