/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import { Router } from 'express';
import { authenticateAdmin, authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { registerCatalogueSource, upsertCatalogueProduct, searchCatalogueProducts, type CatalogueSourceType } from '../services/catalogueSourceRegistry.js';
import { getDb } from '../database.js';

const router=Router();
router.post('/catalogue/sources',authenticateUser,async(req:AuthRequest,res)=>{try{const ownerPartyId=String(req.user?.phone||'').trim();const sourceType=String(req.body?.sourceType||'provider') as CatalogueSourceType;const source=await registerCatalogueSource({sourceType,name:req.body?.name,ownerPartyId,providerPhone:ownerPartyId,sourceUrl:req.body?.sourceUrl,connected:false,verified:false});res.status(201).json({success:true,source,verification:'pending'});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to register catalogue source.'});}});
router.post('/catalogue/products',authenticateUser,async(req:AuthRequest,res)=>{try{const sourceId=String(req.body?.sourceId||'').trim();const db=await getDb();const sourceRows=db.exec('SELECT owner_party_id FROM catalogue_sources WHERE id=? LIMIT 1',[sourceId]);if(!sourceRows[0]?.values?.length)return res.status(404).json({success:false,error:'Catalogue source not found.'});const owner=String(sourceRows[0].values[0][0]||'');if(owner!==String(req.user?.phone||''))return res.status(403).json({success:false,error:'This catalogue source is not owned by the authenticated account.'});const product=await upsertCatalogueProduct({sourceId,title:req.body?.title,description:req.body?.description,sku:req.body?.sku,category:req.body?.category,location:req.body?.location,price:req.body?.price,currency:req.body?.currency,available:req.body?.available,stock:req.body?.stock,sourceUrl:req.body?.sourceUrl,validUntil:req.body?.validUntil,verified:false});res.status(201).json({success:true,product,verification:'source-controlled'});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to register catalogue product.'});}});
router.get('/catalogue/products/search',authenticateUser,async(req:AuthRequest,res)=>{try{const products=await searchCatalogueProducts({query:String(req.query.q||''),category:req.query.category?String(req.query.category):undefined,location:req.query.location?String(req.query.location):undefined,limit:Number(req.query.limit||10),verifiedOnly:req.query.verified!=='false'});res.json({success:true,products});}catch(error){res.status(500).json({success:false,error:error instanceof Error?error.message:'Unable to search catalogue.'});}});
router.post('/admin/catalogue/affiliate/sources',authenticateAdmin,async(req:AuthRequest,res)=>{try{const source=await registerCatalogueSource({sourceType:'affiliate',name:req.body?.name,ownerPartyId:req.body?.partnerId,sourceUrl:req.body?.sourceUrl,connected:true,verified:true});res.status(201).json({success:true,source});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to register affiliate catalogue source.'});}});
export default router;
