import { createFileRoute, Link } from "@tanstack/react-router";
import { Cart, History, MessageCircle, Settings, Sparkles, X, ShieldCheck, ChevronRight, Clock3 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Composer } from "@/components/kurukoo/composer";
import { Message } from "@/components/kurukoo/primitives";
import { ChatDiscovery } from "@/components/kurukoo/chat-discovery";
import { LiveVoice } from "@/components/kurukoo/live-voice";
import { fetchChatHistory } from "@/lib/kurukoo-api";
import { useKurukoo } from "@/lib/kurukoo-store";

export const Route = createFileRoute("/chat")({ head: () => ({ meta: [{ title: "Chat / Voice — Kurukoo" }, { name: "description", content: "Talk to Kurukoo and tell it what needs doing." }, { name: "robots", content: "noindex" }] }), component: ChatPage });

const suggestions = ["Get me a ride.", "Find someone to fix my phone.", "Find a trusted plumber.", "Order something for me.", "Plan my day."];
const agentIntro = ["Hi, I'm Kurukoo. It's nice to meet you.", "Talk to me in your own words or by voice, starting with Hey Kurukoo.", "Tell me what needs doing. You don't need to know the right service, provider or next step.", "Start with an outcome and I will work out the route, involve you when a decision matters and show you what actually happened.", "You say it, I work it out and you decide."];
type TopicContext = { id: string; slug: string; title: string; type: string; category: string | null; city: string | null; lga: string | null };

function AgentMark({ active = false }: { active?: boolean }) { return <span className={`relative grid size-10 shrink-0 place-items-center rounded-[13px] border ${active ? "border-[var(--color-success)] bg-primary/10" : "border-border bg-elevated"}`} aria-label="Kurukoo agent"><span className="grid size-7 place-items-center rounded-full bg-primary/12 ring-1 ring-primary/20"><Sparkles className="size-[17px] text-primary" strokeWidth={1.8} /></span><span className={`absolute -bottom-0.5 -right-0.5 size-2.5 rounded-full border-2 border-background ${active ? "bg-[var(--color-success)]" : "bg-[var(--color-success)]"}`} /></span>; }
function AgentIntro() { const [visible, setVisible] = useState(0); useEffect(() => { setVisible(1); const timers = agentIntro.slice(1).map((_, index) => window.setTimeout(() => setVisible(index + 2), 2200 * (index + 1))); return () => timers.forEach(window.clearTimeout); }, []); return <div className="space-y-3" aria-live="polite">{agentIntro.slice(0, visible).map((text) => <div key={text} className="flex items-start gap-3 motion-safe:animate-[fade-in_240ms_ease-out]"><AgentMark/><div className="max-w-[760px] rounded-2xl rounded-tl-md border border-border bg-surface px-4 py-3 text-[13.5px] leading-6 shadow-sm">{text}</div></div>)}{visible < agentIntro.length ? <div className="flex items-center gap-3"><AgentMark active/><div className="rounded-2xl rounded-tl-md border border-border bg-surface px-4 py-3"><span className="inline-flex items-center gap-1" aria-label="Kurukoo is typing"><i className="size-1.5 animate-bounce rounded-full bg-muted-foreground"/><i className="size-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:120ms]"/><i className="size-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:240ms]"/></span></div></div> : null}</div>; }
function ActiveWork({ work }: { work: ReturnType<typeof useKurukoo>["work"] }) { const active = work.filter((item) => item.stage !== "done"); if (!active.length) return null; return <section aria-label="Kurukoo is taking care of" className="mx-auto mt-4 w-full max-w-[820px] border-y border-border py-3"><div className="flex items-center gap-2 text-[11px] font-medium"><Clock3 className="size-3.5 text-primary"/> Kurukoo is taking care of</div><div className="mt-2 divide-y divide-border/70">{active.slice(0, 3).map((item) => <Link key={item.id} to="/work/$workId" params={{ workId: item.id }} className="group flex items-center gap-3 py-2.5 hover:bg-elevated/50"><span className="size-1.5 shrink-0 rounded-full bg-primary motion-safe:animate-pulse"/><span className="min-w-0 flex-1 truncate text-[13px] font-medium">{item.title}</span><span className="shrink-0 text-[10.5px] text-muted-foreground">{item.updated}</span><ChevronRight className="size-3.5 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5"/></Link>)}</div></section>; }

function ChatSettings({ onClose }: { onClose: () => void }) {
  const [voiceStyle, setVoiceStyle] = useState("calm"); const [language, setLanguage] = useState("en-GB"); const [agentMode, setAgentMode] = useState("Kurukoo");
  useEffect(() => { try { const prefs = JSON.parse(localStorage.getItem("kurukoo-voice-preferences") || "{}"); if (prefs.style) setVoiceStyle(prefs.style); if (prefs.language) setLanguage(prefs.language); } catch {} }, []);
  function saveVoice(nextStyle: string, nextLanguage: string) { localStorage.setItem("kurukoo-voice-preferences", JSON.stringify({ style: nextStyle, language: nextLanguage })); window.dispatchEvent(new CustomEvent("kurukoo-voice-preferences", { detail: { style: nextStyle, language: nextLanguage } })); setVoiceStyle(nextStyle); setLanguage(nextLanguage); }
  return <div className="absolute right-2 top-[58px] z-40 w-[min(390px,calc(100vw-16px))] rounded-2xl border border-border bg-surface p-4 text-left shadow-[var(--shadow-lift)]"><div className="flex items-center justify-between"><div><p className="text-[12px] font-semibold">Chat & voice settings</p><p className="mt-0.5 text-[10.5px] text-muted-foreground">Control how Kurukoo talks and which agent handles your work.</p></div><button type="button" onClick={onClose} aria-label="Close settings" className="grid size-8 place-items-center rounded-full hover:bg-elevated"><X className="size-4"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Voice<select value={voiceStyle} onChange={(e) => saveVoice(e.target.value, language)} className="mt-1.5 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-[12px] font-medium outline-none"><option value="calm">Calm</option><option value="clear">Clear</option><option value="warm">Warm</option></select></label><label className="text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Language<select value={language} onChange={(e) => saveVoice(voiceStyle, e.target.value)} className="mt-1.5 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-[12px] font-medium outline-none"><option value="en-GB">English (UK)</option><option value="en-US">English (US)</option><option value="fr-FR">Français</option><option value="es-ES">Español</option><option value="pt-BR">Português</option><option value="sw-KE">Kiswahili</option></select></label></div><label className="mt-3 block text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Active AI agent<select value={agentMode} onChange={(e) => setAgentMode(e.target.value)} className="mt-1.5 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-[12px] font-medium outline-none"><option>Kurukoo</option><option>My personal agent</option><option>Choose another agent…</option></select></label><div className="mt-3 grid grid-cols-2 gap-2"><Link to="/agents" onClick={onClose} className="rounded-xl border border-border bg-background px-3 py-2.5 text-center text-[11px] font-medium hover:bg-elevated">Assign / deploy agent</Link><Link to="/cart" onClick={onClose} className="rounded-xl border border-border bg-background px-3 py-2.5 text-center text-[11px] font-medium hover:bg-elevated">Manage connected tools</Link></div><p className="mt-3 text-[10px] leading-relaxed text-muted-foreground">Voice preferences are saved on this device. Agent assignment controls are routed to the existing Agents surface; no deployment is claimed until it is actually completed there.</p></div>;
}

function ChatPage() {
  const { messages, send, loadConversation, work, isSending, isLoadingHistory, lastError } = useKurukoo();
  const endRef = useRef<HTMLDivElement>(null); const [initialDraft, setInitialDraft] = useState(""); const [historyOpen, setHistoryOpen] = useState(false); const [settingsOpen, setSettingsOpen] = useState(false); const [historyItems, setHistoryItems] = useState<Array<{ id: string; title?: string | null; updated_at?: string; channel?: string }>>([]); const [historyLoading, setHistoryLoading] = useState(false); const [topicContext, setTopicContext] = useState<TopicContext | null>(null);
  const latestRequestIndex = [...messages].map((message, index) => ({ message, index })).reverse().find(({ message }) => { const card = message.cardData; if (!card) return false; const type = String(card.type ?? "").toLowerCase(); return ["request", "agentic_storefront", "provider_match", "provider_card", "offer", "offer_card", "quote", "quote_card"].includes(type) && Boolean(card.requestId || ["request", "agentic_storefront", "offer", "offer_card", "quote", "quote_card"].includes(type)); });
  const latestRequest = latestRequestIndex?.message; const discoveryQuery = latestRequestIndex ? [...messages].slice(0, latestRequestIndex.index).reverse().find((message) => message.role === "you")?.text?.trim() || String(latestRequest?.cardData?.objective ?? latestRequest?.cardData?.product ?? latestRequest?.cardData?.skill ?? "") : "";
  useEffect(() => { const query = new URLSearchParams(window.location.search).get("query")?.trim() ?? ""; const draft = localStorage.getItem("kurukoo-chat-draft")?.trim() ?? ""; if (query) setInitialDraft(query); else if (draft) setInitialDraft(draft); if (draft) localStorage.removeItem("kurukoo-chat-draft"); const openConversation = localStorage.getItem("kurukoo-open-conversation"); if (openConversation) { localStorage.removeItem("kurukoo-open-conversation"); void loadConversation(openConversation); } const rawTopic = localStorage.getItem("kurukoo-topic-context"); if (rawTopic) { try { setTopicContext(JSON.parse(rawTopic) as TopicContext); } catch { localStorage.removeItem("kurukoo-topic-context"); } } }, [loadConversation]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [messages.length]);
  async function openHistory() { setHistoryOpen(true); setHistoryLoading(true); try { const data = await fetchChatHistory(undefined, 50); setHistoryItems(data.conversations ?? []); } catch { setHistoryItems([]); } finally { setHistoryLoading(false); } }
  function clearTopicContext() { localStorage.removeItem("kurukoo-topic-context"); setTopicContext(null); }

  return <div className="relative mx-auto flex min-h-[calc(100vh-5rem)] w-full max-w-[1040px] flex-col px-0">
    <header className="sticky top-0 z-30 flex h-[52px] shrink-0 items-center justify-between border-b border-border/70 bg-background/95 px-2 backdrop-blur-xl md:px-0"><div className="flex min-w-0 items-center gap-2.5"><AgentMark active/><div className="min-w-0"><p className="text-[13.5px] font-semibold tracking-[-0.01em]">Kurukoo</p><p className="mt-0.5 text-[10px] text-muted-foreground">{messages.length === 0 ? "Your AI agent for getting things done." : "I'm here. Keep going."}</p></div></div><div className="flex shrink-0 items-center gap-1"><div className="hidden items-center gap-1.5 border-r border-border pr-3 text-[9.5px] text-muted-foreground sm:flex"><ShieldCheck className="size-3.5 text-primary"/> You stay in control</div><Link to="/cart" aria-label="Open cart" title="Cart" className="grid size-8 place-items-center rounded-full text-muted-foreground hover:bg-elevated"><Cart className="size-4"/></Link><button type="button" onClick={() => void openHistory()} aria-label="Open conversation history" className="grid size-8 place-items-center rounded-full text-muted-foreground hover:bg-elevated"><History className="size-4"/></button><button type="button" onClick={() => setSettingsOpen((value) => !value)} aria-label="Chat and voice settings" aria-expanded={settingsOpen} title="Chat and voice settings" className="grid size-8 place-items-center rounded-full text-muted-foreground hover:bg-elevated"><Settings className="size-4"/></button></div></header>
    {settingsOpen ? <ChatSettings onClose={() => setSettingsOpen(false)}/> : null}
    {topicContext ? <section className="mt-2 border border-border bg-surface px-3.5 py-2.5"><div className="flex items-center gap-2.5"><span className="grid size-7 shrink-0 place-items-center bg-elevated"><MessageCircle className="size-3.5"/></span><div className="min-w-0 flex-1"><p className="text-[10.5px] text-muted-foreground">Using context from</p><Link to="/topics/$slug" params={{ slug: topicContext.slug }} className="block truncate text-[12.5px] font-medium hover:underline">{topicContext.title}</Link></div><button type="button" onClick={clearTopicContext} aria-label="Clear Topic context" className="grid size-7 place-items-center text-muted-foreground hover:bg-elevated"><X className="size-3.5"/></button></div></section> : null}
    {messages.length === 0 ? <main className="flex flex-1 flex-col pb-8 pt-5 md:pt-6"><div className="mx-auto w-full max-w-[820px]"><AgentIntro/><div className="mt-4 flex items-start gap-3"><AgentMark active/><div className="max-w-[760px] rounded-2xl rounded-tl-md border border-border bg-surface px-4 py-3 text-[13.5px] leading-6 shadow-sm"><p>Let me know if you'd like me to do any of the following:</p><div className="mt-3 flex flex-wrap gap-2">{suggestions.map((suggestion) => <button key={suggestion} type="button" disabled={isSending} onClick={() => void send(suggestion)} className="group inline-flex items-center gap-1.5 rounded-full border border-border bg-background px-3 py-2 text-left text-[11.5px] font-medium transition-colors hover:border-primary hover:bg-elevated disabled:opacity-40">{suggestion}<ChevronRight className="size-3 transition-transform group-hover:translate-x-0.5"/></button>)}</div></div></div><div className="mt-4 flex items-start gap-3"><AgentMark/><div className="max-w-[760px] rounded-2xl rounded-tl-md border border-border bg-surface px-4 py-3 text-[13.5px] leading-6 shadow-sm">What would you like to do today?</div></div></div><ActiveWork work={work}/></main> : <main className="flex-1 space-y-4 py-4 md:py-5"><div className="mx-auto max-w-[820px] space-y-5">{messages.map((message) => <Message key={message.id} message={message} onAction={(action) => { void send(action); }}/>)}</div>{latestRequest ? <ChatDiscovery query={discoveryQuery} onReview={(prompt) => { void send(prompt); }}/> : null}<ActiveWork work={work}/><div ref={endRef}/></main>}
    {lastError ? <p role="alert" className="pb-1 text-center text-[12px] text-destructive">{lastError}</p> : null}<div className="sticky bottom-0 z-10 bg-gradient-to-t from-background via-background to-transparent pb-2 pt-3"><div className="mx-auto max-w-[980px]"><p className="mb-1.5 text-center text-[10.5px] text-muted-foreground">Say “Hey Kurukoo” in voice mode, or type what needs doing.</p><Composer onSend={send} disabled={isSending} initialValue={initialDraft} voiceOverlayTargetId="kurukoo-chat-surface"/></div></div>
    {historyOpen ? <div className="fixed inset-0 z-[90] bg-foreground/15 backdrop-blur-[1px]" onClick={() => setHistoryOpen(false)}><aside aria-label="Conversation history" className="absolute bottom-0 left-0 top-0 w-[min(380px,92vw)] border-r border-border bg-surface p-4 shadow-[var(--shadow-lift)]" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-primary">Your conversations</p><h2 className="mt-1 text-[18px] font-semibold">History</h2></div><button type="button" onClick={() => setHistoryOpen(false)} aria-label="Close history" className="grid size-9 place-items-center rounded-full hover:bg-elevated"><X className="size-4"/></button></div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">Pick up where you left off. Kurukoo keeps the conversation context so you don't have to start again.</p><div className="mt-4 space-y-1.5">{historyLoading ? <div className="h-16 animate-pulse bg-elevated"/> : historyItems.length ? historyItems.map((item) => <button type="button" key={item.id} onClick={() => { setHistoryOpen(false); void loadConversation(item.id); }} className="w-full border border-border px-3 py-3 text-left hover:bg-elevated"><p className="truncate text-[12px] font-medium">{item.title || "Untitled conversation"}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.channel || "web"}{item.updated_at ? ` · ${new Date(item.updated_at).toLocaleString()}` : ""}</p></button>) : <div className="border border-dashed border-border px-3 py-4 text-[11.5px] text-muted-foreground">No saved conversations yet.</div>}</div></aside></div> : null}
  </div>;
}
