import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { PageHeader } from "@/components/app-shell";
import { EntityCard, VideoCard } from "@/components/kurukoo/cards";
import { Action, actionClass } from "@/components/kurukoo/primitives";
import { Rows, SectionHeader, StatTile, Tabs } from "@/components/kurukoo/ui";
import { entities, entityById, videos } from "@/lib/kurukoo-demo";
export const Route=createFileRoute("/creators")({head:()=>({meta:[{title:"Creators — Kurukoo"},{name:"description",content:"Watch useful content, discover creators, or build a channel with publishing, subscribers and revenue tools."}]}),component:CreatorsPage});
const tabs=["Watch","Creators","Creator studio"] as const;
function CreatorsPage(){const [tab,setTab]=useState<string>(tabs[0]);const creators=entities.filter((e)=>e.kind==="creator");return <><PageHeader title="Creators" subtitle="Useful content, creator channels and the tools to publish."/><Tabs items={tabs} value={tab} onChange={setTab}/>{tab==="Watch"&&<div className="mt-4 grid gap-4 sm:grid-cols-2">{videos.map(v=><VideoCard key={v.id} video={v} creatorName={entityById(v.creatorId)?.name??""}/>)}</div>}{tab==="Creators"&&<div className="mt-4 grid gap-3">{creators.map(c=><EntityCard key={c.id} entity={c}/>)}</div>}{tab==="Creator studio"&&<div className="mt-4 space-y-6"><section className="rounded-2xl border border-border bg-elevated/50 p-4"><p className="text-[15px] font-semibold">Build your creator presence</p><p className="mt-1.5 text-[12.5px] leading-relaxed text-muted-foreground">Publish useful videos, grow subscribers, place content into relevant topics and participate in revenue share as those services become connected.</p><div className="mt-3 flex flex-wrap gap-2"><Action variant="primary">New video</Action><Link to="/subscriptions" className={actionClass()}>Creator plan</Link><Link to="/wallet" className={actionClass()}>Wallet</Link></div></section><div className="grid gap-3 sm:grid-cols-3"><StatTile label="Subscribers" value="0" note="Ready when connected"/><StatTile label="Views (30 days)" value="0" note="Content measurement"/><StatTile label="Earnings" value="—" note="Revenue share when connected"/></div><section><SectionHeader title="Creator studio" subtitle="Everything needed to publish, grow and earn."/><Rows>{[["New video","Upload and add a thumbnail","/explore"],["Content library","Everything you've published","/explore"],["Topics and placement","Where your content appears","/topics"],["Comments and discussion","Replies from viewers","/activity"],["Channel settings","Name, description and links","/settings"],["Subscribers","Audience and membership","/network"],["Earnings","Revenue share and payouts","/wallet"]].map(([title,note,to])=><li key={title} className="flex items-center justify-between gap-4 px-4 py-3.5"><span className="min-w-0"><span className="block text-[15px]">{title}</span><span className="block text-[13px] text-muted-foreground">{note}</span></span><Link to={to as never} className="shrink-0 text-[12px] font-medium underline">Open</Link></li>)}</Rows></section></div>}</>}
