/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import { Router } from 'express';
import { authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { broadcastDispatch, acceptDispatchLead, markDispatchArrived, completeDispatch, confirmDispatchCompletion } from '../services/economicDispatchCoordinator.js';
import { createServiceReview } from '../services/serviceReviewService.js';

const router=Router();
const phone=(req:AuthRequest)=>String(req.user?.phone||'').trim();

router.post('/economic-requests/:id/dispatch/broadcast',authenticateUser,async(req:AuthRequest,res)=>{try{const owner=phone(req);const result=await broadcastDispatch({requestId:String(req.params.id),ownerPhone:owner,skill:String(req.body?.skill||'ride_request'),vehicleType:req.body?.vehicleType?String(req.body.vehicleType):undefined,location:req.body?.location?String(req.body.location):undefined,latitude:req.body?.latitude!==undefined?Number(req.body.latitude):undefined,longitude:req.body?.longitude!==undefined?Number(req.body.longitude):undefined,maxProviders:req.body?.maxProviders!==undefined?Number(req.body.maxProviders):undefined});res.json({success:true,...result});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to broadcast dispatch request.'});}});
router.post('/dispatch-leads/:id/accept',authenticateUser,async(req:AuthRequest,res)=>{try{const result=await acceptDispatchLead({leadId:String(req.params.id),providerPhone:phone(req)});res.json({success:true,lead:result});}catch(error){res.status(409).json({success:false,error:error instanceof Error?error.message:'Unable to accept dispatch lead.'});}});
router.post('/dispatch-leads/:id/arrived',authenticateUser,async(req:AuthRequest,res)=>{try{const result=await markDispatchArrived({leadId:String(req.params.id),providerPhone:phone(req)});res.json({success:true,lead:result,callReady:Boolean(result.communicationSessionId)});}catch(error){res.status(409).json({success:false,error:error instanceof Error?error.message:'Unable to mark arrival.'});}});
router.post('/dispatch-leads/:id/completed',authenticateUser,async(req:AuthRequest,res)=>{try{const result=await completeDispatch({leadId:String(req.params.id),providerPhone:phone(req),evidence:typeof req.body?.evidence==='object'&&!Array.isArray(req.body.evidence)?req.body.evidence:undefined});res.json({success:true,lead:result,awaitingOwnerConfirmation:result.status==='completion_reported',reviewAvailable:result.status==='completed'});}catch(error){res.status(409).json({success:false,error:error instanceof Error?error.message:'Unable to report dispatch completion.'});}});
router.post('/dispatch-leads/:id/confirm-completion',authenticateUser,async(req:AuthRequest,res)=>{try{const result=await confirmDispatchCompletion({leadId:String(req.params.id),ownerPhone:phone(req)});res.json({success:true,lead:result,reviewAvailable:true});}catch(error){res.status(409).json({success:false,error:error instanceof Error?error.message:'Unable to confirm dispatch completion.'});}});
router.post('/economic-requests/:id/review',authenticateUser,async(req:AuthRequest,res)=>{try{const requestId=String(req.params.id);const result=await createServiceReview({requestId,reviewerPhone:phone(req),providerPhone:String(req.body?.providerPhone||''),rating:Number(req.body?.rating),feedback:req.body?.feedback?String(req.body.feedback):undefined});res.status(201).json({success:true,review:result});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to submit review.'});}});

export default router;
