import { Router } from 'express';
import crypto from 'crypto';
import { authenticateAdmin, authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { getDb } from '../database.js';
import { assertIdentityAllows } from '../services/progressiveIdentityService.js';
import {
  ECONOMIC_CATEGORIES,
  getEconomicCategory,
  getDefaultCapabilities,
  getSkillFlow,
  getSkillRequirements,
  createEconomicRequest,
  getEconomicRequest,
  transitionEconomicRequest,
  type EconomicRequestStatus,
} from '../services/skillFlows.js';
import { runOrchestrationPass, lockEscrowForEconomicRequest, completeEconomicRequest } from '../services/tradeEngine.js';
import { runDailyMemoryDecay, runWeeklyMemoryPrune, runMemoryCrystallize, getWorkingContextInspector, ensureLivingMemorySchema } from '../services/livingMemoryEngine.js';
import { startStorefrontSession, advanceStorefront } from '../services/agenticStorefront.js';
import { appendChatMessage } from '../services/chatConversationService.js';
import { getAiQuotaStatus } from '../services/aiQuotaService.js';
import { getMemoryFacts, revokeMemoryFact } from '../services/memoryProfile.js';
import { addEconomicParticipant, attachEconomicOffer, getEconomicRequestCoordination, getEconomicParticipants, updateEconomicParticipant, searchKnownEconomicOffers, startKnownOfferEconomicRequest, getDeliveryCandidates, selectDeliveryCandidate, type EconomicParticipantRole, type EconomicParticipantStatus } from '../services/economicParticipants.js';
import { createExecutionRequest, dispatchExecutionRequest, getExecutionRequestsForRequest } from '../services/executionConnector.js';

const router = Router();
const ALLOWED_STATUSES = new Set<EconomicRequestStatus>(['requested', 'awaiting_match', 'partially_matched', 'matched', 'quoting', 'quoted', 'awaiting_confirmation', 'reserved', 'payment_pending', 'paid', 'in_fulfillment', 'fulfilled', 'completed', 'cancelled', 'disputed', 'failed', 'abandoned']);
function phoneFrom(req: AuthRequest): string | null { return req.user?.phone ? String(req.user.phone) : null; }
async function requireEconomicIdentity(phone: string) { const gate = await assertIdentityAllows(phone, 'economic_request'); return gate; }
function cleanRequirements(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) return {}; const input = value as Record<string, unknown>; return Object.fromEntries(Object.entries(input).filter(([key]) => /^[a-zA-Z][a-zA-Z0-9_]{0,63}$/.test(key))); }
function requiredRequirementKeys(skill: string): string[] { return getSkillRequirements(skill).filter((requirement) => requirement.required).map((requirement) => requirement.key); }
function validateRequirements(skill: string, requirements: Record<string, unknown>, allowPartial: boolean): string[] { if (allowPartial) return []; return requiredRequirementKeys(skill).filter((key) => { const value = requirements[key]; return value === undefined || value === null || (typeof value === 'string' && !value.trim()); }); }

router.get('/categories', async (_req: AuthRequest, res) => res.json({ success: true, categories: ECONOMIC_CATEGORIES.map((category) => ({ id: category, capabilities: getDefaultCapabilities(category) })) }));
router.get('/skills/:skill/flow', async (req: AuthRequest, res) => { const skill = String(req.params.skill || '').trim().toLowerCase(); const category = getEconomicCategory(skill); if (!category) return res.status(404).json({ success: false, error: 'Unknown economic skill' }); const flow = await getSkillFlow(skill); res.json({ success: true, skill, category, flow, requiredRequirements: getSkillRequirements(skill).filter((requirement) => requirement.required), requirements: getSkillRequirements(skill), capabilities: flow?.capabilities || getDefaultCapabilities(category) }); });

router.post('/storefront/start', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); const gate = await requireEconomicIdentity(phone); if (!gate.allowed) return res.status(403).json({ success: false, error: gate.reason, identity: gate.snapshot.cardData }); const skill = typeof req.body?.skill === 'string' ? req.body.skill.trim().toLowerCase() : 'find_worker'; const requirements = cleanRequirements(req.body?.requirements); try { const card = await startStorefrontSession(phone, skill, requirements); res.status(201).json({ success: true, card }); } catch (error) { console.error('[Storefront] start failed:', error); res.status(500).json({ success: false, error: 'Unable to start storefront session' }); } });
router.post('/storefront/:id/advance', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); const gate = await requireEconomicIdentity(phone); if (!gate.allowed) return res.status(403).json({ success: false, error: gate.reason, identity: gate.snapshot.cardData }); const requestId = String(req.params.id || ''); const action = typeof req.body?.action === 'string' ? req.body.action : undefined; const patch = cleanRequirements(req.body?.requirements || req.body?.fields); const conversationId = typeof req.body?.conversationId === 'string' ? req.body.conversationId.trim() : undefined; const idempotencyKey = typeof req.body?.idempotencyKey === 'string' ? req.body.idempotencyKey.trim().slice(0, 180) : undefined; try { const card = await advanceStorefront(phone, requestId, patch, action, idempotencyKey); await appendChatMessage({ phone, sender: 'assistant', content: card.message || 'Request state updated.', channel: 'web', conversationId, cardData: card, metadata: { source: 'storefront_advance', requestId } }); res.json({ success: true, card }); } catch (error) { console.error('[Storefront] advance failed:', error); res.status(500).json({ success: false, error: 'Unable to advance storefront' }); } });
router.get('/ai-quota', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); try { const status = await getAiQuotaStatus(phone); res.json({ success: true, quota: status }); } catch { res.status(500).json({ success: false, error: 'Unable to load AI quota' }); } });
router.post('/', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); const skill = typeof req.body?.skill === 'string' ? req.body.skill.trim().toLowerCase() : ''; const category = getEconomicCategory(skill); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); if (!skill || !category) return res.status(400).json({ success: false, error: 'A supported economic skill is required' }); const gate = await requireEconomicIdentity(phone); if (!gate.allowed) return res.status(403).json({ success: false, error: gate.reason, identity: gate.snapshot.cardData }); const requirements = cleanRequirements(req.body?.requirements); const missing = validateRequirements(skill, requirements, req.body?.allowPartial === true); if (missing.length) return res.status(422).json({ success: false, error: 'More information is required', missing }); try { const request = await createEconomicRequest({ id: crypto.randomUUID(), phone, skill, requirements, amount: typeof req.body?.amount === 'number' && Number.isFinite(req.body.amount) ? req.body.amount : undefined }); res.status(201).json({ success: true, request }); } catch (error) { console.error('[EconomicRequest] create failed:', error); res.status(500).json({ success: false, error: 'Unable to create economic request' }); } });
router.get('/offers/search', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); try { const offers = await searchKnownEconomicOffers(String(req.query.q || ''), Number(req.query.limit) || 5); res.json({ success: true, offers }); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to search known offers'; res.status(422).json({ success: false, error: message }); } });
router.post('/offers/:offerId/start', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); const gate = await requireEconomicIdentity(phone); if (!gate.allowed) return res.status(403).json({ success: false, error: gate.reason, identity: gate.snapshot.cardData }); try { const result = await startKnownOfferEconomicRequest({ buyerPhone: phone, offerId: String(req.params.offerId || ''), deliveryRequired: typeof req.body?.deliveryRequired === 'boolean' ? req.body.deliveryRequired : undefined, deliveryLocation: typeof req.body?.deliveryLocation === 'string' ? req.body.deliveryLocation : undefined, quantity: typeof req.body?.quantity === 'string' ? req.body.quantity : undefined }); const card = await advanceStorefront(phone, result.request.id, {}, 'view_offer'); res.status(201).json({ success: true, request: result.request, card }); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to start a request from this offer'; res.status(/not found/.test(message) ? 404 : 422).json({ success: false, error: message }); } });

router.post('/:id/offer', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); try { const offer = await attachEconomicOffer({ requestId: String(req.params.id || ''), ownerPhone: phone, id: typeof req.body?.id === 'string' ? req.body.id : crypto.randomUUID(), sellerPhone: req.body?.sellerPhone, description: req.body?.description, priceMinor: req.body?.priceMinor, currency: req.body?.currency, source: req.body?.source, availabilityNote: req.body?.availabilityNote, externalSource: req.body?.externalSource, status: req.body?.status, provenance: req.body?.provenance, mediaReference: req.body?.mediaReference, externalUrl: req.body?.externalUrl, originOfferId: req.body?.originOfferId }); res.status(201).json({ success: true, offer }); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to attach offer'; const status = /ownership|not found/.test(message) ? 404 : 422; res.status(status).json({ success: false, error: message }); } });
router.post('/:id/participants', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); try { const participant = await addEconomicParticipant({ requestId: String(req.params.id || ''), ownerPhone: phone, role: req.body?.role as EconomicParticipantRole, providerPhone: req.body?.providerPhone, capability: req.body?.capability, status: req.body?.status as EconomicParticipantStatus | undefined, evidence: req.body?.evidence }); res.status(201).json({ success: true, participant }); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to add economic participant'; res.status(422).json({ success: false, error: message }); } });
router.patch('/:id/participants/:participantId', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); try { const participant = await updateEconomicParticipant({ requestId: String(req.params.id), ownerPhone: phone, participantId: String(req.params.participantId), status: req.body?.status as EconomicParticipantStatus | undefined, providerPhone: req.body?.providerPhone, capability: req.body?.capability, evidence: req.body?.evidence }); res.json({ success: true, participant }); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to update participant'; res.status(422).json({ success: false, error: message }); } });
router.get('/:id', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); const request = await getEconomicRequest(String(req.params.id)); if (!request || request.phone !== phone) return res.status(404).json({ success: false, error: 'Request not found' }); res.json({ success: true, request }); });
router.get('/:id/coordination', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); try { res.json({ success: true, coordination: await getEconomicRequestCoordination(String(req.params.id), phone) }); } catch (error) { res.status(404).json({ success: false, error: error instanceof Error ? error.message : 'Unable to load coordination' }); } });
router.get('/:id/participants', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); try { res.json({ success: true, participants: await getEconomicParticipants(String(req.params.id), phone) }); } catch (error) { res.status(404).json({ success: false, error: error instanceof Error ? error.message : 'Unable to load participants' }); } });
router.post('/:id/transition', authenticateUser, async (req: AuthRequest, res) => { const phone = phoneFrom(req); if (!phone) return res.status(401).json({ success: false, error: 'Authenticated phone is required' }); const nextStatus=String(req.body?.status||'') as EconomicRequestStatus; if(!ALLOWED_STATUSES.has(nextStatus)) return res.status(400).json({success:false,error:'Unsupported status'}); try { const request=await getEconomicRequest(String(req.params.id)); if(!request||request.phone!==phone)return res.status(404).json({success:false,error:'Request not found'}); const updated=await transitionEconomicRequest(String(req.params.id),nextStatus,req.body?.evidence); res.json({success:true,request:updated}); } catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to transition request'});} });

// Remaining legacy economic/admin routes intentionally continue below through the existing service owners.
router.post('/:id/offer/search', authenticateUser, async (req: AuthRequest, res) => { const phone=phoneFrom(req); if(!phone)return res.status(401).json({success:false,error:'Authenticated phone is required'}); try{res.json({success:true,offers:await searchKnownEconomicOffers(String(req.body?.query||''),Number(req.body?.limit)||5)});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to search offers'});} });
router.get('/:id/delivery/candidates', authenticateUser, async (req: AuthRequest,res)=>{const phone=phoneFrom(req);if(!phone)return res.status(401).json({success:false,error:'Authenticated phone is required'});try{res.json({success:true,candidates:await getDeliveryCandidates(String(req.params.id),phone)});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to load delivery candidates'});}});
router.post('/:id/delivery/select',authenticateUser,async(req:AuthRequest,res)=>{const phone=phoneFrom(req);if(!phone)return res.status(401).json({success:false,error:'Authenticated phone is required'});try{res.json({success:true,candidate:await selectDeliveryCandidate(String(req.params.id),phone,String(req.body?.candidateId||''))});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to select delivery candidate'});}});
router.post('/:id/execution/create',authenticateUser,async(req:AuthRequest,res)=>{const phone=phoneFrom(req);if(!phone)return res.status(401).json({success:false,error:'Authenticated phone is required'});try{res.status(201).json({success:true,request:await createExecutionRequest({economicRequestId:String(req.params.id),ownerPhone:phone,requirements:req.body?.requirements,providerPhone:req.body?.providerPhone})});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to create execution request'});}});
router.post('/:id/execution/dispatch',authenticateUser,async(req:AuthRequest,res)=>{const phone=phoneFrom(req);if(!phone)return res.status(401).json({success:false,error:'Authenticated phone is required'});try{res.json({success:true,request:await dispatchExecutionRequest({economicRequestId:String(req.params.id),ownerPhone:phone,executionId:String(req.body?.executionId||'')})});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to dispatch execution request'});}});
router.get('/:id/execution',authenticateUser,async(req:AuthRequest,res)=>{const phone=phoneFrom(req);if(!phone)return res.status(401).json({success:false,error:'Authenticated phone is required'});try{res.json({success:true,requests:await getExecutionRequestsForRequest(String(req.params.id),phone)});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to load execution requests'});}});

export default router;
