import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Compass, MapPin, Search, Sparkles, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "@/components/app-shell";
import { AskKurukoo } from "@/components/kurukoo/ask-kurukoo";
import { CapabilityPills, DirectoryEmpty } from "@/components/kurukoo/surface-directory";
import { CommerceOutcomes } from "@/components/kurukoo/commerce-outcomes";
import { fetchCanonicalTopics, fetchDiscoveryEntities, fetchProactiveFeed, type CanonicalTopic, type DiscoveryEntity, type ProactiveOpportunity } from "@/lib/kurukoo-api";
import { exploreGoalGroups } from "@/lib/explore-goals";

export const Route = createFileRoute("/explore")({ head: () => ({ meta: [{ title: "Explore — Kurukoo" }, { name: "description", content: "Ideas, nearby context and useful things Kurukoo can help you move forward." }] }), component: ExplorePage });
const destination: Record<string, string> = { food: "/explore/food", groceries: "/explore/groceries", ride: "/explore/mobility", travel: "/explore/mobility", repair: "/explore/repairs", cleaning: "/explore/home", solar: "/explore/home", "money-circle": "/explore/money-circle", work: "/explore/work", business: "/explore/work", sell: "/explore/selling", health: "/explore/health", education: "/explore/learning", events: "/explore/events", spiritual: "/explore/prayer", connect: "/explore/community", emergency: "/explore/safety", security: "/explore/safety" };

function ExplorePage() {
  const [q, setQ] = useState(""); const [entities, setEntities] = useState<DiscoveryEntity[]>([]); const [topics, setTopics] = useState<CanonicalTopic[]>([]); const [opportunities, setOpportunities] = useState<ProactiveOpportunity[]>([]); const [loading, setLoading] = useState(true); const [searching, setSearching] = useState(false); const term = q.trim().toLowerCase();
  useEffect(() => { let cancelled = false; Promise.allSettled([fetchDiscoveryEntities({ radius: 5000 }), fetchCanonicalTopics(6), fetchProactiveFeed()]).then(([d, t, o]) => { if (cancelled) return; if (d.status === "fulfilled") setEntities(d.value); if (t.status === "fulfilled") setTopics(t.value); if (o.status === "fulfilled") setOpportunities(o.value); setLoading(false); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!term) return; let cancelled = false; const timer = window.setTimeout(() => { setSearching(true); fetchDiscoveryEntities({ radius: 5000, q: term }).then((value) => { if (!cancelled) setEntities(value); }).catch(() => { if (!cancelled) setEntities([]); }).finally(() => { if (!cancelled) setSearching(false); }); }, 250); return () => { cancelled = true; window.clearTimeout(timer); }; }, [term]);
  const matches = useMemo(() => entities.slice(0, 6), [entities]); const featuredGroups = exploreGoalGroups.slice(0, 4);
  return <div className="mx-auto w-full max-w-6xl space-y-10 pb-10">
    <PageHeader eyebrow="Explore" title="Ideas for what to do next." subtitle="You do not need to know which service, provider or tool you need. Start with the outcome and Kurukoo can help you work out the route." />

    <section className="border-y border-border py-6 md:py-7">
      <div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center bg-brand-tint text-brand-ink"><Compass className="size-4.5" /></span><div><p className="text-[10.5px] font-bold uppercase tracking-[0.14em] text-primary">Need a starting point?</p><h2 className="mt-1.5 text-[28px] font-semibold tracking-[-0.04em]">Tell Kurukoo what you are trying to change.</h2><p className="mt-2 max-w-xl text-[12.5px] leading-6 text-muted-foreground">Search when you already have something specific in mind. Otherwise, describe the result you want and let Kurukoo take it from there.</p></div></div>
      <div className="mt-5 flex flex-col gap-2 sm:flex-row"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input aria-label="Search Explore" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Try “I need a plumber” or “find dinner nearby”…" className="min-h-12 w-full border border-border bg-background pl-10 pr-3 text-[13px] outline-none focus-visible:ring-2 focus-visible:ring-ring" /></div><AskKurukoo prompt={q.trim() ? `Help me with ${q.trim()}.` : "Help me choose what to do next."} /></div>
    </section>

    {opportunities.length ? <section><div className="mb-3 flex items-end justify-between"><div><p className="text-[10.5px] font-bold uppercase tracking-[0.14em] text-primary">Worth knowing</p><h2 className="mt-1 text-[17px] font-semibold">Things Kurukoo found</h2></div><Link to="/opportunities" className="text-[10.5px] font-medium">See all <ArrowRight className="ml-1 inline size-3.5" /></Link></div><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-3">{opportunities.slice(0, 3).map((item) => <Link key={item.id} to={item.ctaLink as never} className="bg-surface p-5 transition-colors hover:bg-elevated/45"><p className="text-[9.5px] font-bold uppercase tracking-[0.12em] text-primary">{item.type}</p><h3 className="mt-2 text-[13.5px] font-semibold">{item.title}</h3><p className="mt-1.5 line-clamp-2 text-[11px] leading-relaxed text-muted-foreground">{item.subtitle}</p><span className="mt-4 inline-flex items-center gap-1 text-[10.5px] font-medium">{item.ctaText}<ArrowRight className="size-3.5" /></span></Link>)}</div></section> : null}

    <section><div className="mb-3"><p className="text-[10.5px] font-bold uppercase tracking-[0.14em] text-primary">Ideas</p><h2 className="mt-1 text-[17px] font-semibold">You might want to…</h2><p className="mt-1 text-[10.5px] text-muted-foreground">Examples of outcomes Kurukoo can help you move forward.</p></div><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2">{featuredGroups.map((group) => { const Icon = group.icon; return <div key={group.id} className="bg-surface p-5"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center bg-elevated"><Icon className="size-4" /></span><h3 className="text-[13.5px] font-semibold">{group.label}</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{group.goals.slice(0, 4).map((goal) => <Link key={goal.id} to={(destination[goal.id] ?? "/chat") as never} search={destination[goal.id] ? undefined : ({ query: goal.prompt } as never)} className="border border-border bg-background p-3 transition-colors hover:bg-elevated"><p className="text-[12px] font-medium">{goal.label}</p><div className="mt-2"><CapabilityPills items={goal.capabilityIds} limit={2} /></div></Link>)}</div></div>; })}</div></section>
    <CommerceOutcomes />

    <section className="border-t border-border pt-7"><div className="mb-3"><p className="text-[10.5px] font-bold uppercase tracking-[0.14em] text-primary">Context</p><h2 className="mt-1 text-[17px] font-semibold">What could help right now?</h2><p className="mt-1 text-[10.5px] text-muted-foreground">Nearby places and community context are supporting information. The goal is still to help you decide what to do next.</p></div><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2"><Link to="/discover" className="bg-surface p-5 hover:bg-elevated"><MapPin className="size-5 text-primary" /><h3 className="mt-3 text-[14px] font-semibold">Nearby context</h3><p className="mt-1 text-[11.5px] leading-relaxed text-muted-foreground">People, places, businesses, offers and events Kurukoo can help you act on.</p><span className="mt-3 inline-flex items-center gap-1 text-[10.5px] font-medium">See what is nearby <ArrowRight className="size-3.5" /></span></Link><Link to="/topics" className="bg-surface p-5 hover:bg-elevated"><Users className="size-5" /><h3 className="mt-3 text-[14px] font-semibold">Community context</h3><p className="mt-1 text-[11.5px] leading-relaxed text-muted-foreground">Questions and local context that can help you decide what to do next.</p><span className="mt-3 inline-flex items-center gap-1 text-[10.5px] font-medium">See Topics <ArrowRight className="size-3.5" /></span></Link></div></section>

    {term ? <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-[17px] font-semibold">Nearby matches</h2><p className="text-[10.5px] text-muted-foreground">{searching ? "Searching…" : loading ? "Loading…" : `${matches.length} result${matches.length === 1 ? "" : "s"}`}</p></div></div>{matches.length ? <div className="grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{matches.map((item) => <article key={item.id} className="bg-surface p-5"><p className="text-[13.5px] font-semibold">{item.name}</p><p className="mt-1 text-[10.5px] text-muted-foreground">{item.category ?? item.kind}{item.location ? ` · ${item.location}` : ""}</p>{item.description ? <p className="mt-2 line-clamp-2 text-[11px] leading-relaxed text-muted-foreground">{item.description}</p> : null}<Link to="/chat" search={{ query: `Help me with ${item.name}` } as never} className="mt-3 inline-flex items-center gap-1 text-[10.5px] font-medium">Ask Kurukoo <ArrowRight className="size-3.5" /></Link></article>)}</div> : <DirectoryEmpty title="Nothing matched nearby" body="Describe the outcome to Kurukoo and it can try another route." action={<AskKurukoo prompt={`I searched for ${q} and need another way to approach it.`} />} />}</section> : null}
    {topics.length ? <section><div className="mb-3"><h2 className="text-[17px] font-semibold">Community context</h2><p className="text-[10.5px] text-muted-foreground">Recent conversations related to what people are doing.</p></div><div className="grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{topics.map((topic) => <Link key={topic.id} to="/topics/$slug" params={{ slug: topic.slug }} className="bg-surface p-5 hover:bg-elevated/45"><p className="text-[9.5px] font-bold uppercase tracking-[0.12em] text-primary">Topic</p><h3 className="mt-2 text-[13px] font-semibold leading-snug">{topic.title}</h3><p className="mt-1.5 line-clamp-2 text-[11px] leading-relaxed text-muted-foreground">{topic.body}</p></Link>)}</div></section> : null}
  </div>;
}
