import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Bell, ShoppingCart, Wallet, CirclePlay, Gift, MessageCircle, Mic2, Plus, Sparkles, Users, SunMedium, Building2, Phone, Focus, PackageCheck, Utensils, Palette, PhoneCall } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Composer } from "@/components/kurukoo/composer";
import { Panel, ContextIconTile, StatusPill, FlowEvent, ActiveRequestRow } from "@/components/kurukoo/ui";
import { useKurukoo } from "@/lib/kurukoo-store";
import { cn } from "@/lib/utils";
import { useProfileName } from "@/components/app-shell";

const description = "Your personal workspace for getting useful things done with Kurukoo.";
export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "Home — Kurukoo" }, { name: "description", content: description }, { property: "og:title", content: "Home — Kurukoo" }, { property: "og:description", content: description }] }), component: HomePage });
function SectionAction({ to, children }: { to: string; children: ReactNode }) { return <Link to={to as never} className="inline-flex items-center gap-1 text-[12px] font-medium text-primary hover:opacity-80">{children}<ArrowUpRight className="size-3.5" /></Link>; }
function CardHeader({ title, count, to, action }: { title: string; count?: number; to?: string; action?: string }) { return <div className="flex items-center justify-between gap-3 px-4 pb-3 pt-4"><h2 className="min-w-0 text-[14px] font-semibold tracking-tight">{title}</h2>{typeof count === "number" ? <span className="grid min-w-6 place-items-center rounded-full bg-elevated px-1.5 py-1 text-[10.5px] text-muted-foreground">{count}</span> : to && action ? <SectionAction to={to}>{action}</SectionAction> : null}</div>; }
function IconTile({ children, className }: { children: ReactNode; className?: string }) { return <ContextIconTile className={className}>{children}</ContextIconTile>; }
function HomeHorizonIllustration() { return <div aria-hidden className="pointer-events-none absolute inset-x-0 bottom-0 h-40 overflow-hidden opacity-35"><div className="absolute right-[13%] top-2 size-11 rounded-full bg-[#d99764]/60 blur-[1px]" /><div className="absolute bottom-3 left-[47%] h-16 w-40 rounded-[50%] border border-[#bca99b]/40" /><div className="absolute bottom-1 left-[58%] h-24 w-28 rounded-t-full border-l border-r border-t border-[#bca99b]/35" /><Building2 className="absolute bottom-4 right-[32%] size-9 text-muted-foreground/40" /><Building2 className="absolute bottom-7 right-[29%] size-6 text-muted-foreground/35" /><SunMedium className="absolute right-[17%] top-4 size-7 text-[#c58d62]/70" /></div>; }
function TrustedPerson({ name, status, tone, icon: Icon }: { name: string; status: string; tone: string; icon: typeof Users }) { return <div className="flex min-w-[64px] flex-col items-center gap-0.5"><span className={cn("relative grid size-11 place-items-center rounded-full", tone)}><Icon className="size-5" /><span className="absolute bottom-0 right-0 size-2.5 rounded-full border-2 border-surface bg-[var(--color-success)]" /></span><span className="text-[12px] font-medium">{name}</span><span className="text-[10.5px] text-muted-foreground">{status}</span></div>; }
function detectPlaceFromTimezone(timeZone: string) { const known: Record<string, string> = { "Africa/Accra": "Accra", "Africa/Lagos": "Lagos", "Africa/Abidjan": "Abidjan", "Africa/Nairobi": "Nairobi", "Africa/Cairo": "Cairo", "Europe/London": "London", "Europe/Dublin": "Dublin", "Europe/Paris": "Paris", "Europe/Berlin": "Berlin", "America/New_York": "New York", "America/Los_Angeles": "Los Angeles", "America/Chicago": "Chicago", "Asia/Dubai": "Dubai", "Asia/Singapore": "Singapore", "Asia/Tokyo": "Tokyo" }; return known[timeZone] ?? timeZone.split("/").pop()?.replaceAll("_", " ") ?? "Your location"; }
function useLocalWeather() { const [weather, setWeather] = useState({ temperature: "23", place: "Accra" }); useEffect(() => { let cancelled = false; const timezonePlace = () => detectPlaceFromTimezone(Intl.DateTimeFormat().resolvedOptions().timeZone); const cached = localStorage.getItem("kurukoo-location-weather"); if (cached) { try { const parsed = JSON.parse(cached) as { at: number; temperature: string; place: string }; if (Date.now() - parsed.at < 6 * 60 * 60 * 1000) setWeather({ temperature: parsed.temperature, place: parsed.place }); } catch { /* ignore malformed cache */ } } const fallbackPlace = timezonePlace(); if (!navigator.geolocation) { setWeather((v) => ({ ...v, place: fallbackPlace })); return () => { cancelled = true; }; } navigator.geolocation.getCurrentPosition(async ({ coords }) => { try { const response = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${coords.latitude}&longitude=${coords.longitude}&current=temperature_2m&timezone=auto`); if (!response.ok) throw new Error("Weather unavailable"); const data = await response.json() as { current?: { temperature_2m?: number }; timezone?: string }; if (cancelled) return; const temperature = typeof data.current?.temperature_2m === "number" ? String(Math.round(data.current.temperature_2m)) : "23"; const place = detectPlaceFromTimezone(data.timezone ?? fallbackPlace); setWeather({ temperature, place }); localStorage.setItem("kurukoo-location-weather", JSON.stringify({ at: Date.now(), temperature, place })); } catch { if (!cancelled) setWeather((v) => ({ ...v, place: fallbackPlace })); } }, () => { if (!cancelled) setWeather((v) => ({ ...v, place: fallbackPlace })); }, { maximumAge: 6 * 60 * 60 * 1000, timeout: 8000 }); return () => { cancelled = true; }; }, []); return weather; }
function getGreeting(hour: number) { if (hour >= 5 && hour < 12) return "Good morning"; if (hour >= 12 && hour < 18) return "Good afternoon"; if (hour >= 18 && hour < 22) return "Good evening"; return "Good night"; }
function useLocalDateTime() { const [now, setNow] = useState(() => new Date()); useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 60_000); return () => window.clearInterval(timer); }, []); const locale = Intl.DateTimeFormat().resolvedOptions().locale || "en-GB"; const date = new Intl.DateTimeFormat(locale, { weekday: "short", day: "numeric", month: "short", year: "numeric" }).format(now); return { greeting: getGreeting(now.getHours()), date }; }

function HomePage() {
  const { work, send, notifications } = useKurukoo();
  const weather = useLocalWeather();
  const { greeting, date } = useLocalDateTime();
  const profileName = useProfileName();
  const [showAllFlow, setShowAllFlow] = useState(false);
  const liveActive = work.filter((w) => w.stage !== "done").slice(0, 3);
  const active = liveActive.length ? liveActive : [
    { id: "demo-request-1", title: "Delivery to Osu", detail: "Kurukoo is coordinating the next step", updated: "11:00", stage: "active" as const },
    { id: "demo-request-2", title: "Client call preparation", detail: "Brief and key points ready for review", updated: "15:00", stage: "needs_you" as const },
  ];
  const unread = notifications.filter((item) => !item.read).length;
  const flow = [
    { time: "09:00", title: "Focus time", detail: "Design system review", kind: "Focus", icon: Focus },
    { time: "11:00", title: "Delivery window", detail: "Market items to Osu", kind: "Request", icon: PackageCheck },
    { time: "13:00", title: "Lunch break", detail: "Keep the afternoon light", kind: "Personal", icon: Utensils },
    { time: "15:00", title: "Design review", detail: "Share updated mockups", kind: "Work", icon: Palette },
    { time: "18:30", title: "Call Mum", detail: "Check in and catch up", kind: "People", icon: PhoneCall },
  ];
  const visibleFlow = flow.slice(0, showAllFlow ? 5 : 4);
  return <div className="space-y-5 min-w-0">
    <header className="flex min-h-12 items-center justify-between gap-4 border-b border-border/70 pb-3">
      <div className="flex min-w-0 items-center gap-2 text-[12px] text-muted-foreground"><p className="shrink-0 font-medium text-foreground">{greeting}, {profileName}</p><span aria-hidden className="h-4 w-px shrink-0 bg-border" /><span className="inline-flex min-w-0 items-center gap-1.5 truncate"><SunMedium className="size-4 shrink-0 text-[#c58d62]" />{weather.temperature}°C · {weather.place}</span></div>
      <div className="flex shrink-0 items-center gap-1"><span className="hidden text-[12px] text-muted-foreground sm:inline">{date}</span><Link to="/wallet" aria-label="Open wallet" title="Wallet" className="grid size-9 place-items-center rounded-full hover:bg-elevated"><Wallet className="size-[17px] text-muted-foreground" /></Link><Link to="/cart" aria-label="Open cart" title="Cart" className="grid size-9 place-items-center rounded-full hover:bg-elevated"><ShoppingCart className="size-[17px] text-muted-foreground" /></Link><Link to="/activity" aria-label="Open activity" className="relative grid size-9 place-items-center rounded-full hover:bg-elevated"><Bell className="size-[17px] text-muted-foreground" />{unread > 0 ? <span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-primary ring-2 ring-background" /> : null}</Link></div>
    </header>
    <section aria-labelledby="home-hero-title" className="relative overflow-hidden pb-2 pt-4 md:pt-6">
      <HomeHorizonIllustration />
      <div className="relative z-10 max-w-4xl"><h1 id="home-hero-title" className="font-serif text-[42px] leading-[1.02] tracking-[-0.045em] md:text-[58px]">Wake up. Get going.</h1><p className="mt-2 max-w-2xl text-[14px] leading-relaxed text-muted-foreground">Ask plainly and Kurukoo will help carry the next useful step.</p><div className="mt-5 max-w-[920px]"><Composer onSend={send} placeholder="What needs your attention?" /></div></div>
    </section>
    <div className="grid min-w-0 gap-4 lg:grid-cols-2 xl:grid-cols-[minmax(0,.65fr)_minmax(0,.9fr)_minmax(0,1.08fr)]">
      <section className="min-w-0"><Panel className="overflow-hidden p-0"><CardHeader title="Active requests" count={active.length} /><div>{active.map((item, index) => <ActiveRequestRow key={item.id} title={item.title} detail={item.detail} timing={item.updated} status={<StatusPill tone={item.stage === "needs_you" ? "peach" : "green"}>{item.stage === "needs_you" ? "Needs you" : index === 0 ? "On the way" : "Scheduled"}</StatusPill>} />)}</div><div className="border-t border-border px-4 py-3"><SectionAction to="/work">View all requests</SectionAction></div></Panel></section>
      <section className="min-w-0"><Panel className="overflow-hidden p-0"><CardHeader title="Today’s flow" /><div>{visibleFlow.map((item, index) => <FlowEvent key={item.time} time={item.time} title={item.title} detail={item.detail} kind={item.kind} icon={item.icon} isLast={index === visibleFlow.length - 1} />)}</div><div className="flex items-center justify-between border-t border-border px-4 py-3"><button type="button" onClick={() => setShowAllFlow(v => !v)} className="text-[12px] text-muted-foreground hover:text-foreground">{showAllFlow ? "Show less" : "Show later"}</button><SectionAction to="/activity">View full day</SectionAction></div></Panel></section>
      <div className="min-w-0 space-y-4 lg:col-span-2 xl:col-span-1">
        <section className="min-w-0"><Panel className="overflow-hidden p-0"><CardHeader title="Suggested next steps" count={2} /><div>{[{ icon: Sparkles, title: "Prepare for client call", detail: "Brief ready, 3 key points", action: "Open" }, { icon: Gift, title: "Grocery top-up", detail: "Based on your list", action: "Review" }].map(({ icon: ItemIcon, title, detail, action }) => <div key={title} className="flex items-center gap-3 border-b border-border p-4 last:border-b-0"><IconTile className={title.startsWith("Prepare") ? "bg-[#eee9f7] text-[#75619b]" : "bg-[#eaf1e9] text-[#55705a]"}><ItemIcon className="size-4" /></IconTile><div className="min-w-0 flex-1"><p className="text-[13.5px] font-medium">{title}</p><p className="mt-0.5 text-[11.5px] text-muted-foreground">{detail}</p></div><button type="button" className="rounded-full border border-border px-3 py-1.5 text-[11.5px] hover:bg-elevated">{action}</button></div>)}</div><div className="border-t border-border px-4 py-3"><SectionAction to="/chat">See suggestions</SectionAction></div></Panel></section>
        <section className="min-w-0"><Panel className="p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-semibold tracking-tight">Trusted people</h2><SectionAction to="/contacts">See people</SectionAction></div><div className="flex items-start justify-between gap-3"><TrustedPerson name="Ama" status="Online" tone="bg-[#edf2e9] text-[#55705a]" icon={Users} /><TrustedPerson name="Mum" status="Online" tone="bg-[#f4e6dc] text-[#765443]" icon={Phone} /><TrustedPerson name="Kojo" status="Busy" tone="bg-[#e8eef3] text-[#526b80]" icon={Users} /><button type="button" className="flex min-w-[64px] flex-col items-center gap-0.5 text-muted-foreground hover:text-foreground" aria-label="Add trusted person"><span className="grid size-11 place-items-center rounded-full border border-border"><Plus className="size-5" /></span><span className="text-[12px]">Add</span></button></div></Panel></section>
      </div>
    </div>
    <div className="grid min-w-0 gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Panel className="min-w-0 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-semibold tracking-tight">Tasks & reminders</h2><SectionAction to="/activity">View all</SectionAction></div><div className="space-y-1"><div className="flex items-center gap-3 py-2"><span className="grid size-5 place-items-center rounded-full border border-border" /><span className="min-w-0 flex-1 text-[13px]">Share updated mockups</span><span className="text-[11px] text-muted-foreground">15:00</span></div><div className="flex items-center gap-3 py-2"><span className="grid size-5 place-items-center rounded-full border border-border" /><span className="min-w-0 flex-1 text-[13px]">Reply to Kojo</span><span className="text-[11px] text-muted-foreground">17:00</span></div></div><button type="button" className="mt-2 inline-flex items-center gap-1.5 text-[12px] text-muted-foreground hover:text-foreground"><Plus className="size-3.5" />Add reminder</button></Panel>
      <Panel className="min-w-0 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-semibold tracking-tight">Opportunity radar</h2><SectionAction to="/explore">Explore</SectionAction></div><IconTile className="bg-[#eaf1f5] text-[#58758b]"><Gift className="size-4" /></IconTile><p className="mt-3 text-[13.5px] font-medium">Local design meetup</p><p className="mt-1 text-[12px] leading-relaxed text-muted-foreground">A new opportunity near Osu matches your interests.</p><SectionAction to="/explore">Review</SectionAction></Panel>
      <Panel className="min-w-0 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-semibold tracking-tight">Points</h2><SectionAction to="/wallet">View points</SectionAction></div><p className="text-[30px] font-semibold tracking-tight">1,240</p><p className="mt-0.5 text-[12px] text-muted-foreground">points · +80 this week</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-elevated"><div className="h-full w-[68%] rounded-full bg-primary" /></div><p className="mt-2 text-[11px] text-muted-foreground">260 to next level</p></Panel>
      <Panel className="min-w-0 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-semibold tracking-tight">Topics for you</h2><SectionAction to="/topics">Explore topics</SectionAction></div><div className="flex flex-wrap gap-1.5"><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">Design</span><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">Accra</span><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">AI</span><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">Mobility</span></div></Panel>
    </div>
    <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,.8fr)]"><Panel className="min-w-0 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-semibold tracking-tight">Guide videos</h2><SectionAction to="/explore">View all</SectionAction></div><div className="grid gap-3 sm:grid-cols-2"><div><div className="relative flex aspect-[16/8] items-center justify-center overflow-hidden rounded-xl bg-elevated"><CirclePlay className="size-8 text-muted-foreground" /><span className="absolute bottom-2 right-2 rounded bg-background/80 px-1.5 py-0.5 text-[10px]">3:45</span></div><p className="mt-2 text-[12.5px] font-medium">Get more from Kurukoo</p></div><div><div className="relative flex aspect-[16/8] items-center justify-center overflow-hidden rounded-xl bg-elevated"><CirclePlay className="size-8 text-muted-foreground" /><span className="absolute bottom-2 right-2 rounded bg-background/80 px-1.5 py-0.5 text-[10px]">4:12</span></div><p className="mt-2 text-[12.5px] font-medium">Staying safe online</p></div></div></Panel><Panel className="min-w-0 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-semibold tracking-tight">Connected channels</h2><SectionAction to="/connect">Manage</SectionAction></div><div className="space-y-1"><div className="flex items-center gap-3 py-2"><IconTile><MessageCircle className="size-4" /></IconTile><span className="flex-1 text-[13px]">Web chat</span><StatusPill tone="green">Active</StatusPill></div><div className="flex items-center gap-3 py-2"><IconTile><Mic2 className="size-4" /></IconTile><span className="flex-1 text-[13px]">WhatsApp</span><StatusPill>Setup available</StatusPill></div><div className="flex items-center gap-3 py-2"><IconTile><Users className="size-4" /></IconTile><span className="flex-1 text-[13px]">Telegram</span><StatusPill>Setup available</StatusPill></div></div></Panel></div>
    <p className="pb-4 text-center text-[11px] text-muted-foreground">Kurukoo keeps you in control. Nothing is committed without your approval.</p>
  </div>;
}
