import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Check, CirclePlay, Gift, MessageCircle, Mic2, Plus, Sparkles, Users, SunMedium, Building2, Phone, CarFront, Package, MoreHorizontal } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Composer } from "@/components/kurukoo/composer";
import { Panel, ContextIconTile, StatusPill, FlowEvent, ActiveRequestRow } from "@/components/kurukoo/ui";
import { useKurukoo } from "@/lib/kurukoo-store";
import { cn } from "@/lib/utils";

const description = "Your personal workspace for getting useful things done with Kurukoo.";
export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "Home — Kurukoo" }, { name: "description", content: description }, { property: "og:title", content: "Home — Kurukoo" }, { property: "og:description", content: description }] }), component: HomePage });

function SectionAction({ to, children }: { to: string; children: ReactNode }) { return <Link to={to as never} className="inline-flex items-center gap-1 text-[12px] font-medium text-primary hover:opacity-80">{children}<ArrowUpRight className="size-3.5" /></Link>; }
function SectionTitle({ title, to, action }: { title: string; to?: string; action?: string }) { return <div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-[14px] font-semibold tracking-tight">{title}</h2>{to && action ? <SectionAction to={to}>{action}</SectionAction> : null}</div>; }
function IconTile({ children, className }: { children: ReactNode; className?: string }) { return <ContextIconTile className={className}>{children}</ContextIconTile>; }
function HomeHorizonIllustration() { return <div aria-hidden className="pointer-events-none absolute inset-x-0 bottom-0 h-40 overflow-hidden opacity-35"><div className="absolute right-[13%] top-2 size-11 rounded-full bg-[#d99764]/60 blur-[1px]" /><div className="absolute bottom-3 left-[47%] h-16 w-40 rounded-[50%] border border-[#bca99b]/40" /><div className="absolute bottom-1 left-[58%] h-24 w-28 rounded-t-full border-l border-r border-t border-[#bca99b]/35" /><Building2 className="absolute bottom-4 right-[32%] size-9 text-muted-foreground/40" /><Building2 className="absolute bottom-7 right-[29%] size-6 text-muted-foreground/35" /><SunMedium className="absolute right-[17%] top-4 size-7 text-[#c58d62]/70" /></div>; }
function TrustedPerson({ name, status, tone, icon: Icon }: { name: string; status: string; tone: string; icon: typeof Users }) { return <div className="flex min-w-[64px] flex-col items-center gap-1.5"><span className={cn("relative grid size-11 place-items-center rounded-full", tone)}><Icon className="size-5" /><span className="absolute bottom-0 right-0 size-2.5 rounded-full border-2 border-surface bg-[var(--color-success)]" /></span><span className="text-[12px] font-medium">{name}</span><span className="text-[10.5px] text-muted-foreground">{status}</span></div>; }

function HomePage() {
  const { messages, work, send } = useKurukoo();
  const [showAllFlow, setShowAllFlow] = useState(false);
  const active = work.filter((w) => w.stage !== "done").slice(0, 3);
  const recentMessage = messages.filter((m) => m.role === "kurukoo").at(-1);
  return <div className="space-y-5">
    <header className="flex min-h-12 items-center justify-between gap-4 border-b border-border/70 pb-3">
      <div><p className="text-[12px] font-medium text-muted-foreground">Good afternoon, Ada</p><p className="mt-0.5 text-[11.5px] text-muted-foreground">Your useful part of the day</p></div>
      <div className="hidden items-center gap-3 sm:flex"><span className="inline-flex items-center gap-1.5 text-[12px] text-muted-foreground"><SunMedium className="size-4 text-[#c58d62]" />23°C · Accra</span><span className="text-[12px] text-muted-foreground">Tue, 27 May 2030</span><Link to="/activity" aria-label="Open activity" className="relative grid size-9 place-items-center rounded-full hover:bg-elevated"><span className="size-2 rounded-full bg-primary" /></Link></div>
    </header>

    <section aria-labelledby="home-hero-title" className="relative overflow-hidden pb-2 pt-4 md:pt-6">
      <HomeHorizonIllustration />
      <div className="relative z-10 max-w-4xl">
        <p className="text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">Home</p>
        <h1 id="home-hero-title" className="mt-2 font-serif text-[42px] leading-[1.02] tracking-[-0.045em] md:text-[58px]">Wake up. Get going.</h1>
        <p className="mt-3 max-w-xl text-[15px] leading-relaxed text-muted-foreground">What needs your attention? Ask plainly and Kurukoo will help carry the next useful step.</p>
        <div className="mt-6 max-w-[920px]"><Composer onSend={send} placeholder="What needs your attention?" /></div>
      </div>
    </section>

    <div className="grid gap-4 lg:grid-cols-[1.12fr_.9fr_1.08fr]">
      <section><SectionTitle title="Active requests" to="/work" action="View all requests" /><Panel className="overflow-hidden p-0"><div className="divide-y divide-border">{active.length ? active.map((item, index) => <ActiveRequestRow key={item.id} title={item.title} detail={item.detail} timing={item.updated} status={<StatusPill tone={item.stage === "needs_you" ? "peach" : "green"}>{item.stage === "needs_you" ? "Needs you" : index === 0 ? "On the way" : "Scheduled"}</StatusPill>} />) : <div className="px-4 py-6 text-[13px] text-muted-foreground">Nothing is in progress. Start with a request above.</div>}</div><div className="border-t border-border px-4 py-3"><SectionAction to="/work">View all requests</SectionAction></div></Panel></section>

      <section><SectionTitle title="Today’s flow" to="/activity" action="View full day" /><Panel className="overflow-hidden p-0"><div className="divide-y divide-border">{[['09:00','Focus time','Design system review','Focus'],['11:00','Delivery window','Market items to Osu','Request'],['13:00','Lunch break','Keep the afternoon light','Personal'],['15:00','Design review','Share updated mockups','Work'],['18:30','Call Mum','Check in and catch up','People']].slice(0, showAllFlow ? 5 : 4).map(([time,title,detail,kind]) => <FlowEvent key={time} time={time} title={title} detail={detail} kind={kind} />)}</div><button type="button" onClick={() => setShowAllFlow(v => !v)} className="flex w-full items-center justify-between border-t border-border px-4 py-3 text-[12px] text-muted-foreground hover:bg-elevated/50"><span>{showAllFlow ? "Show less" : "Show later"}</span><ArrowUpRight className="size-3.5" /></button></Panel></section>

      <div className="space-y-4">
        <section><SectionTitle title="Agent-assisted next steps" to="/chat" action="See all suggestions" /><Panel className="p-0"><div className="divide-y divide-border"><div className="flex items-center gap-3 p-4"><IconTile className="bg-[#eee9f7] text-[#75619b]"><Sparkles className="size-4" /></IconTile><div className="min-w-0 flex-1"><p className="text-[13.5px] font-medium">Prepare for client call</p><p className="mt-0.5 text-[11.5px] text-muted-foreground">Brief ready, 3 key points</p></div><button type="button" className="rounded-full border border-border px-3 py-1.5 text-[11.5px] hover:bg-elevated">Open</button></div><div className="flex items-center gap-3 p-4"><IconTile className="bg-[#eaf1e9] text-[#55705a]"><Gift className="size-4" /></IconTile><div className="min-w-0 flex-1"><p className="text-[13.5px] font-medium">Grocery top-up</p><p className="mt-0.5 text-[11.5px] text-muted-foreground">Based on your list</p></div><button type="button" className="rounded-full border border-border px-3 py-1.5 text-[11.5px] hover:bg-elevated">Review</button></div></div><div className="border-t border-border px-4 py-3"><SectionAction to="/chat">See all suggestions</SectionAction></div></Panel></section>
        <section><SectionTitle title="Trusted people" to="/contacts" action="See people" /><Panel className="p-4"><div className="flex items-start justify-between gap-3"><TrustedPerson name="Ama" status="Online" tone="bg-[#edf2e9] text-[#55705a]" icon={Users} /><TrustedPerson name="Mum" status="Online" tone="bg-[#f4e6dc] text-[#765443]" icon={Phone} /><TrustedPerson name="Kojo" status="Busy" tone="bg-[#e8eef3] text-[#526b80]" icon={Users} /><button type="button" className="flex min-w-[64px] flex-col items-center gap-1.5 text-muted-foreground hover:text-foreground" aria-label="Add trusted person"><span className="grid size-11 place-items-center rounded-full border border-border"><Plus className="size-5" /></span><span className="text-[12px]">Add</span></button></div></Panel></section>
      </div>
    </div>

    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Panel className="p-4"><SectionTitle title="Tasks & reminders" to="/activity" action="View all" /><div className="space-y-1"><div className="flex items-center gap-3 py-2"><span className="grid size-5 place-items-center rounded-full border border-border" /><span className="min-w-0 flex-1 text-[13px]">Share updated mockups</span><span className="text-[11px] text-muted-foreground">15:00</span></div><div className="flex items-center gap-3 py-2"><span className="grid size-5 place-items-center rounded-full border border-border" /><span className="min-w-0 flex-1 text-[13px]">Reply to Kojo</span><span className="text-[11px] text-muted-foreground">17:00</span></div></div><button type="button" className="mt-2 inline-flex items-center gap-1.5 text-[12px] text-muted-foreground hover:text-foreground"><Plus className="size-3.5" />Add reminder</button></Panel>
      <Panel className="p-4"><SectionTitle title="Opportunity radar" to="/explore" action="Explore" /><IconTile className="bg-[#eaf1f5] text-[#58758b]"><Gift className="size-4" /></IconTile><p className="mt-3 text-[13.5px] font-medium">Local design meetup</p><p className="mt-1 text-[12px] leading-relaxed text-muted-foreground">A new opportunity near Osu matches your interests.</p><SectionAction to="/explore">Review</SectionAction></Panel>
      <Panel className="p-4"><SectionTitle title="Points" to="/wallet" action="View points" /><p className="text-[30px] font-semibold tracking-tight">1,240</p><p className="mt-0.5 text-[12px] text-muted-foreground">points · +80 this week</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-elevated"><div className="h-full w-[68%] rounded-full bg-primary" /></div><p className="mt-2 text-[11px] text-muted-foreground">260 to next level</p></Panel>
      <Panel className="p-4"><SectionTitle title="Topics for you" to="/topics" action="Explore topics" /><div className="flex flex-wrap gap-1.5"><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">Design</span><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">Accra</span><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">AI</span><span className="rounded-full bg-elevated px-2.5 py-1 text-[11px]">Mobility</span></div><SectionAction to="/topics">Explore topics</SectionAction></Panel>
    </div>

    <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Panel className="p-4"><SectionTitle title="Guide videos" to="/explore" action="View all" /><div className="grid gap-3 sm:grid-cols-2"><div><div className="relative flex aspect-[16/8] items-center justify-center overflow-hidden rounded-xl bg-elevated"><CirclePlay className="size-8 text-muted-foreground" /><span className="absolute bottom-2 right-2 rounded bg-background/80 px-1.5 py-0.5 text-[10px]">3:45</span></div><p className="mt-2 text-[12.5px] font-medium">Get more from Kurukoo</p></div><div><div className="relative flex aspect-[16/8] items-center justify-center overflow-hidden rounded-xl bg-elevated"><CirclePlay className="size-8 text-muted-foreground" /><span className="absolute bottom-2 right-2 rounded bg-background/80 px-1.5 py-0.5 text-[10px]">4:12</span></div><p className="mt-2 text-[12.5px] font-medium">Staying safe online</p></div></div></Panel><Panel className="p-4"><SectionTitle title="Connected channels" to="/connect" action="Manage" /><div className="space-y-1"><div className="flex items-center gap-3 py-2"><IconTile><MessageCircle className="size-4" /></IconTile><span className="flex-1 text-[13px]">Web chat</span><StatusPill tone="green">Active</StatusPill></div><div className="flex items-center gap-3 py-2"><IconTile><Mic2 className="size-4" /></IconTile><span className="flex-1 text-[13px]">WhatsApp</span><StatusPill>Setup available</StatusPill></div><div className="flex items-center gap-3 py-2"><IconTile><Users className="size-4" /></IconTile><span className="flex-1 text-[13px]">Telegram</span><StatusPill>Setup available</StatusPill></div></div></Panel></div>
    <p className="pb-4 text-center text-[11px] text-muted-foreground">Kurukoo keeps you in control. Nothing is committed without your approval.</p>
  </div>;
}
