import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BriefcaseBusiness, HandCoins, Package, Sparkles, Store, Users, Zap } from "lucide-react";
import { userJobs } from "@/lib/skill-catalog";

export const Route = createFileRoute("/opportunities")({ component: Opportunities });

const earningPaths = [
  ["Find Work", "Discover paid work, gigs and useful opportunities.", BriefcaseBusiness, "/chat"],
  ["Offer Delivery", "Make your delivery capability discoverable and receive relevant requests.", Package, "/providers"],
  ["Sell an Item", "Put something useful in front of people looking for it.", Store, "/businesses"],
  ["Offer a Service", "Turn a capability into a trusted provider offer.", HandCoins, "/providers"],
  ["Become a Creator", "Publish useful ideas and build an audience around topics.", Sparkles, "/creators"],
  ["Promote an Item", "Use clearly labelled advertising to reach relevant discovery.", Zap, "/advertising"],
] as const;

function Opportunities() { return <div className="w-full pb-12"><header className="mb-8 border-b border-border/70 pb-5"><p className="text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">Work, earn and participate</p><h1 className="mt-1 text-[34px] font-semibold tracking-[-0.035em]">Opportunities</h1><p className="mt-2 max-w-2xl text-[14px] leading-relaxed text-muted-foreground">Kurukoo is for the people asking for help and the people, businesses and creators able to provide it.</p></header><section><div className="flex items-end justify-between gap-4"><div><h2 className="text-[20px] font-semibold tracking-tight">Ways to participate</h2><p className="mt-1 text-[12px] text-muted-foreground">The same conversation-first system can lead to demand, supply, work and earnings.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{earningPaths.map(([title,body,Icon,to])=><Link key={title} to={to as never} className="rounded-2xl border border-border bg-surface p-5 hover:bg-elevated"><span className="grid size-9 place-items-center rounded-full bg-[#f4e6dc] text-[#765443]"><Icon className="size-4" /></span><h2 className="mt-4 text-[15px] font-semibold">{title}</h2><p className="mt-2 text-[12px] leading-relaxed text-muted-foreground">{body}</p><span className="mt-4 inline-flex items-center gap-1 text-[11.5px] font-medium">Open path <ArrowRight className="size-3.5" /></span></Link>)}</div></section><section className="mt-8 rounded-2xl bg-elevated/60 p-5"><div className="flex items-start gap-3"><Users className="mt-0.5 size-5 shrink-0 text-muted-foreground"/><div><p className="text-[13px] font-semibold">A useful job should stay a job, not a skill name.</p><p className="mt-1.5 text-[11.5px] leading-relaxed text-muted-foreground">People can ask for things naturally. Kurukoo can connect that request to the right provider, business, creator or opportunity underneath.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{userJobs.filter((job) => ["Find Work", "Offer Delivery", "Sell an Item", "Promote Items"].includes(job)).map((job) => <Link key={job} to="/chat" className="rounded-full border border-border bg-background px-3 py-1.5 text-[11px] hover:bg-surface">{job}</Link>)}</div></section><div className="mt-8 rounded-2xl border border-border bg-surface p-5"><div className="flex items-center gap-3"><Sparkles className="size-5 text-muted-foreground"/><div><p className="text-[13px] font-semibold">Have something in mind?</p><p className="mt-1 text-[11.5px] text-muted-foreground">Tell Kurukoo what you want to make happen and let the conversation find the next step.</p></div></div><Link to="/chat" className="mt-4 inline-flex rounded-full bg-foreground px-4 py-2 text-[11.5px] font-medium text-background">Start a conversation</Link></div></div>; }
