/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
/**
 * Payment-related mutations — points, wallet and verified external payment boundaries.
 * Identity comes from the authenticated session. Client-supplied payment
 * references are never treated as proof of payment.
 */
import { Router } from 'express';
import { authenticateUser, AuthRequest } from '../middleware/auth.js';
import { paymentRateLimit } from '../middleware/rateLimit.js';
import { addPoints, getPointsBalance, addCredits } from '../services/pointsEngine.js';
import { getProfile } from '../services/memoryProfile.js';
import { getEconomicRequest, transitionEconomicRequest } from '../services/skillFlows.js';
import { lockEscrowForEconomicRequest } from '../services/tradeEngine.js';
import { createStripePaymentIntent, stripeStatus, verifyStripeWebhook } from '../services/stripePayment.js';
import { createPaystackTransaction, paystackStatus, verifyPaystackTransaction, verifyPaystackWebhook } from '../services/paystackPayment.js';
import { moveEconomicPaymentToPending, recordVerifiedEconomicPayment } from '../services/economicPaymentEvidence.js';
import { settleCommercialEventByKey } from '../services/commercialSettlement.js';
import { recordCommercialEvent } from '../services/commercialLedger.js';
import { getDb, saveDb } from '../database.js';
import { persistCoordinatorEvent } from '../services/coordinatorStore.js';

const router = Router();
function configuredPaymentProvider(): string | null { const configured=String(process.env.KURUKOO_PAY_PROVIDER||'').trim().toLowerCase(); if(configured)return configured; return process.env.NODE_ENV==='production'?null:'sandbox'; }

router.get('/points/balance', authenticateUser, async (req:AuthRequest,res)=>{const phone=req.user?.phone?String(req.user.phone):null;if(!phone)return res.status(401).json({error:'Authenticated phone is required'});if(req.query.phone&&String(req.query.phone)!==phone)return res.status(403).json({error:'You can only view your own balance'});try{const balance=await getPointsBalance(phone);const profile=await getProfile(phone,'points_query');res.json({success:true,points:balance,tier:profile?.subscription_tier||'Base',currency:'NGN'});}catch(e:any){res.status(500).json({error:e.message||'Failed to fetch points balance'});}});
router.get('/payments/stripe/status', authenticateUser, (_req:AuthRequest,res)=>res.json(stripeStatus()));
router.post('/payments/stripe/intents', authenticateUser, paymentRateLimit, async (req:AuthRequest,res)=>{const phone=req.user?.phone?String(req.user.phone):null;const requestId=typeof req.body?.economicRequestId==='string'?req.body.economicRequestId.trim():'';if(!phone||!requestId)return res.status(400).json({error:'An authenticated owner and Economic Request are required.'});const request=await getEconomicRequest(requestId);if(!request||request.phone!==phone)return res.status(404).json({error:'That Economic Request is unavailable.'});const quote=request.quote as Record<string,unknown>|undefined;const amountMinor=typeof quote?.amount_minor==='number'?quote.amount_minor:0;const currency=typeof quote?.currency==='string'?quote.currency:'GBP';if(!['quoted','awaiting_confirmation','payment_pending'].includes(request.status)||!Number.isSafeInteger(amountMinor)||amountMinor<=0)return res.status(409).json({error:'A current confirmed quote is required before payment can begin.'});try{const intent=await createStripePaymentIntent({amountMinor,currency,economicRequestId:request.id,idempotencyKey:`kurukoo:stripe:${request.id}:${amountMinor}:${currency}`});if(request.status!=='payment_pending')await transitionEconomicRequest(request.id,'payment_pending',{fulfillment:{...(request.fulfillment||{}),payment_provider:'stripe',payment_intent_id:intent.id,payment_started_at:new Date().toISOString()}});res.json({provider:'stripe',paymentIntentId:intent.id,clientSecret:intent.clientSecret,amountMinor:intent.amountMinor,currency:intent.currency,status:intent.status});}catch(error){res.status(503).json({error:error instanceof Error?error.message:'Payment provider is unavailable.',payment_required:true});}});
router.get('/payments/paystack/status', authenticateUser, (_req:AuthRequest,res)=>res.json(paystackStatus()));
router.post('/payments/paystack/transactions', authenticateUser, paymentRateLimit, async (req:AuthRequest,res)=>{const phone=req.user?.phone?String(req.user.phone):'';const requestId=typeof req.body?.economicRequestId==='string'?req.body.economicRequestId.trim():'';if(!phone||!requestId)return res.status(400).json({error:'An authenticated owner and Economic Request are required.'});const request=await getEconomicRequest(requestId);if(!request||request.phone!==phone)return res.status(404).json({error:'That Economic Request is unavailable.'});const quote=request.quote&&typeof request.quote==='object'?request.quote as Record<string,unknown>:{};const amountMinor=Number(quote.amount_minor||0),currency=String(quote.currency||'NGN');if(!['quoted','awaiting_confirmation','reserved','payment_pending'].includes(request.status)||!Number.isSafeInteger(amountMinor)||amountMinor<=0)return res.status(409).json({error:'A current confirmed quote is required before payment can begin.'});const profile=await getProfile(phone,'paystack_payment_preparation');const email=String((profile as any)?.email||req.body?.email||'').trim();try{const transaction=await createPaystackTransaction({amountMinor,currency,email,economicRequestId:request.id,idempotencyKey:`kurukoo:paystack:${request.id}:${amountMinor}:${currency}`});await moveEconomicPaymentToPending(request.id);await transitionEconomicRequest(request.id,'payment_pending',{fulfillment:{...(request.fulfillment||{}),payment_provider:'paystack',payment_reference:transaction.reference,payment_started_at:new Date().toISOString(),payment_status:'authorization_pending'}}).catch(()=>undefined);return res.status(201).json({success:true,provider:'paystack',paymentReference:transaction.reference,authorizationUrl:transaction.authorizationUrl,accessCode:transaction.accessCode,amountMinor:transaction.amountMinor,currency:transaction.currency,status:transaction.status,settlement:'verify_or_signed_webhook_required'});}catch(error){return res.status(503).json({success:false,error:error instanceof Error?error.message:'Paystack payment preparation is unavailable.',payment_required:true});}});
router.post('/payments/paystack/verify', authenticateUser, paymentRateLimit, async (req:AuthRequest,res)=>{const phone=req.user?.phone?String(req.user.phone):'';const requestId=typeof req.body?.economicRequestId==='string'?req.body.economicRequestId.trim():'';const reference=typeof req.body?.reference==='string'?req.body.reference.trim():'';if(!phone||!requestId||!reference)return res.status(400).json({error:'An authenticated owner, Economic Request, and Paystack reference are required.'});const request=await getEconomicRequest(requestId);if(!request||request.phone!==phone)return res.status(404).json({error:'That Economic Request is unavailable.'});try{const verified=await verifyPaystackTransaction(reference);if(verified.status!=='success')return res.status(202).json({success:false,settled:false,paymentStatus:verified.status,message:'Paystack has not verified this payment as successful. No value has been delivered.'});const recorded=await recordVerifiedEconomicPayment({requestId,provider:'paystack',paymentReference:verified.reference,evidenceId:`verify:${verified.providerTransactionId||verified.reference}`,amountMinor:verified.amountMinor,currency:verified.currency,evidenceSource:'provider_verify',metadata:{paystack_channel:verified.channel||null,paystack_gateway_response:verified.gatewayResponse||null,paystack_paid_at:verified.paidAt||null}});return res.json({success:true,settled:true,payment:recorded,receipt:{requestId,paymentReference:verified.reference,amountMinor:verified.amountMinor,currency:verified.currency,provider:'paystack',paidAt:verified.paidAt||null}});}catch(error){return res.status(422).json({success:false,error:error instanceof Error?error.message:'Paystack verification could not be completed.'});}});
router.get('/payments/economic/:requestId/receipt', authenticateUser, async (req:AuthRequest,res)=>{const phone=String(req.user?.phone||'');const request=await getEconomicRequest(String(req.params.requestId||''));if(!phone||!request||request.phone!==phone)return res.status(404).json({error:'That Economic Request is unavailable.'});const fulfilment=request.fulfillment&&typeof request.fulfillment==='object'?request.fulfillment as Record<string,unknown>:{};if(fulfilment.payment_verified!==true)return res.status(409).json({error:'A verified payment receipt is not available for this request.'});return res.json({success:true,receipt:{requestId:request.id,provider:fulfilment.payment_provider,paymentReference:fulfilment.payment_reference,evidenceId:fulfilment.payment_evidence_id||fulfilment.payment_event_id||null,amountMinor:fulfilment.payment_amount_minor||((request.quote as any)?.amount_minor)||null,currency:fulfilment.payment_currency||((request.quote as any)?.currency)||null,verifiedAt:fulfilment.payment_verified_at,settlement:'escrow_or_existing-settlement-policy'}});});
router.post('/payments/points/intents', authenticateUser, paymentRateLimit, async (req:AuthRequest,res)=>{const phone=String(req.user?.phone||'');const points=Math.floor(Number(req.body?.amountPoints||0));const pricePerPoint=Math.floor(Number(process.env.KURUKOO_POINTS_PRICE_MINOR||0));const currency=String(process.env.KURUKOO_POINTS_CURRENCY||'NGN').toUpperCase();if(!phone||!Number.isSafeInteger(points)||points<=0)return res.status(400).json({error:'A positive amountPoints is required.'});if(pricePerPoint<=0)return res.status(503).json({error:'Points purchase pricing is not configured for this deployment.',payment_required:true});const amountMinor=points*pricePerPoint;if(!Number.isSafeInteger(amountMinor)||amountMinor<=0)return res.status(400).json({error:'Points purchase amount is invalid.'});try{const idempotencyKey=`points:${phone}:${points}:${Date.now()}`;await recordCommercialEvent({eventType:'points_purchase',direction:'inbound',status:'authorized',currency,grossMinor:amountMinor,platformFeeMinor:amountMinor,providerAmountMinor:0,payer:phone,payee:'KURUKOO',representedParty:phone,idempotencyKey,metadata:{points,pricePerPoint,currency}});const intent=await createStripePaymentIntent({amountMinor,currency,economicRequestId:`commercial:points:${points}:${idempotencyKey}`,idempotencyKey:`kurukoo:${idempotencyKey}`});res.json({success:true,provider:'stripe',paymentIntentId:intent.id,clientSecret:intent.clientSecret,amountMinor,currency,points});}catch(error){res.status(503).json({error:error instanceof Error?error.message:'Points payment provider unavailable.',payment_required:true});}});

router.post('/webhooks/stripe', async (req,res)=>{
  const event=verifyStripeWebhook((req as any).rawBody as Buffer,req.header('stripe-signature'));if(!event)return res.status(400).json({error:'Invalid Stripe webhook signature.'});const db=await getDb();db.run(`CREATE TABLE IF NOT EXISTS payment_webhook_events(provider TEXT NOT NULL,event_id TEXT NOT NULL,received_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(provider,event_id))`);const exists=db.prepare(`SELECT event_id FROM payment_webhook_events WHERE provider='stripe' AND event_id=?`);exists.bind([event.id]);const duplicate=exists.step();exists.free();if(duplicate)return res.status(200).json({received:true,duplicate:true});db.run(`INSERT INTO payment_webhook_events(provider,event_id) VALUES ('stripe',?)`,[event.id]);saveDb();const payment=event.data?.object;if(!payment?.id)return res.status(200).json({received:true,ignored:true});const requestId=String(payment?.metadata?.economic_request_id||'');
  if(event.type==='payment_intent.succeeded'&&payment.status==='succeeded'&&requestId.startsWith('commercial:points:')){
    const match=requestId.match(/^commercial:points:(\d+):(.+)$/);if(!match){db.run(`DELETE FROM payment_webhook_events WHERE provider='stripe' AND event_id=?`,[event.id]);saveDb();return res.status(400).json({error:'Malformed commercial Points payment reference.'});}const points=Number(match[1]);const key=match[2];
    try{const settled=await settleCommercialEventByKey(key,String(payment.id),{stripeEventId:event.id,points});if(!settled)return res.status(200).json({received:true,ignored:true});const ledgerStmt=db.prepare(`SELECT payer,metadata FROM commercial_ledger WHERE idempotency_key=?`);ledgerStmt.bind([key]);if(ledgerStmt.step()){const row=ledgerStmt.getAsObject() as any;let meta:any={};try{meta=JSON.parse(String(row.metadata||'{}'));}catch{}if(!meta.pointsCredited){await addPoints(String(row.payer),points,'Verified Points purchase');meta.pointsCredited=true;meta.stripeEventId=event.id;db.run(`UPDATE commercial_ledger SET metadata=? WHERE idempotency_key=?`,[JSON.stringify(meta),key]);saveDb();}}ledgerStmt.free();return res.status(200).json({received:true,pointsCredited:true});}
    catch(error){db.run(`DELETE FROM payment_webhook_events WHERE provider='stripe' AND event_id=?`,[event.id]);saveDb();return res.status(500).json({error:error instanceof Error?error.message:'Points payment reconciliation failed; retry is safe.'});}
  }
  if(event.type==='payment_intent.succeeded'&&payment.status==='succeeded'&&requestId.startsWith('commercial:')){
    const key=requestId.slice('commercial:'.length);try{const settled=await settleCommercialEventByKey(key,String(payment.id),{stripeEventId:event.id});return res.status(200).json({received:true,commercialSettled:settled});}catch(error){db.run(`DELETE FROM payment_webhook_events WHERE provider='stripe' AND event_id=?`,[event.id]);saveDb();return res.status(500).json({error:error instanceof Error?error.message:'Commercial payment reconciliation failed; retry is safe.'});}}
  if(!requestId)return res.status(200).json({received:true,ignored:true});const request=await getEconomicRequest(requestId);if(!request)return res.status(200).json({received:true,ignored:true});const quote=request.quote as Record<string,unknown>|undefined;
  if(event.type==='payment_intent.succeeded'&&payment.status==='succeeded'&&Number(payment.amount)===Number(quote?.amount_minor)&&String(payment.currency||'').toLowerCase()===String(quote?.currency||'').toLowerCase()){
    try{await transitionEconomicRequest(request.id,'paid',{fulfillment:{...(request.fulfillment||{}),payment_verified:true,payment_provider:'stripe',payment_reference:payment.id,payment_event_id:event.id,payment_verified_at:new Date().toISOString()}});const escrow=await lockEscrowForEconomicRequest(request.id,Number(payment.amount));if(!escrow.success)throw new Error('Verified payment was received but escrow could not be locked safely.');await persistCoordinatorEvent({id:`payment:${event.id}:verified`,type:'payment.webhook.verified',occurredAt:new Date().toISOString(),producer:'paymentRoutes',correlationId:`economic_request:${request.id}`,ownerPhone:request.phone.startsWith('anon_')?undefined:request.phone,economicRequestId:request.id,payload:{provider:'stripe',eventId:event.id,paymentReference:String(payment.id),amountMinor:Number(payment.amount),currency:String(payment.currency||'').toLowerCase(),escrowLocked:true},sensitivity:request.phone.startsWith('anon_')?'public':'personal',provenance:{source:'provider',sourceId:String(event.id),evidenceLevel:'verified_external'},policy:{autonomousAllowed:false,confirmationRequired:'external_evidence'},schemaVersion:1});}
    catch(error){db.run(`DELETE FROM payment_webhook_events WHERE provider='stripe' AND event_id=?`,[event.id]);saveDb();console.error('[Stripe] verified payment transition failed',{eventId:event.id,requestId,message:error instanceof Error?error.message:'unknown'});return res.status(500).json({error:'Payment reconciliation failed; retry is safe.'});}
  }
  res.status(200).json({received:true});
});
router.post('/webhooks/paystack', async (req,res)=>{const event=verifyPaystackWebhook((req as any).rawBody as Buffer,req.header('x-paystack-signature'));if(!event)return res.status(400).json({error:'Invalid Paystack webhook signature.'});const data=event.data as Record<string,any>;if(event.event!=='charge.success')return res.status(200).json({received:true,ignored:true});const requestId=String(data?.metadata?.economic_request_id||'').trim(),reference=String(data?.reference||'').trim();if(!requestId||!reference)return res.status(200).json({received:true,ignored:true});const db=await getDb();db.run(`CREATE TABLE IF NOT EXISTS payment_webhook_events(provider TEXT NOT NULL,event_id TEXT NOT NULL,received_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(provider,event_id))`);const eventId=String(data.id||reference);const exists=db.prepare(`SELECT event_id FROM payment_webhook_events WHERE provider='paystack' AND event_id=?`);exists.bind([eventId]);const duplicate=exists.step();exists.free();if(duplicate)return res.status(200).json({received:true,duplicate:true});db.run(`INSERT INTO payment_webhook_events(provider,event_id) VALUES ('paystack',?)`,[eventId]);saveDb();try{const recorded=await recordVerifiedEconomicPayment({requestId,provider:'paystack',paymentReference:reference,evidenceId:`webhook:${eventId}`,amountMinor:Number(data.amount||0),currency:String(data.currency||''),evidenceSource:'provider_webhook',metadata:{paystack_channel:data.channel||null,paystack_paid_at:data.paid_at||data.paidAt||null}});return res.status(200).json({received:true,settled:recorded.success,duplicate:recorded.idempotent});}catch(error){db.run(`DELETE FROM payment_webhook_events WHERE provider='paystack' AND event_id=?`,[eventId]);saveDb();return res.status(500).json({error:error instanceof Error?error.message:'Paystack payment reconciliation failed; retry is safe.'});}});
router.post('/points/topup', authenticateUser, paymentRateLimit, async (req:AuthRequest,res)=>{const phone=req.user?.phone?String(req.user.phone):null;if(!phone)return res.status(401).json({error:'Authenticated phone is required'});if(req.body?.phone&&String(req.body.phone)!==phone)return res.status(403).json({error:'Top-up must use authenticated identity'});const points=Number(req.body?.amount_points);if(!Number.isInteger(points)||points<=0)return res.status(400).json({error:'amount_points must be a positive integer'});const provider=configuredPaymentProvider();if(process.env.NODE_ENV==='production'||provider!=='sandbox')return res.status(503).json({error:'Verified payment provider integration is required before production top-ups are enabled',payment_required:true});try{await addPoints(phone,points,'Sandbox top-up');const newBalance=await getPointsBalance(phone);res.json({success:true,message:`Credited ${points} sandbox Points.`,balance:newBalance});}catch(e:any){res.status(500).json({error:e.message||'Failed to top up points'});}});
router.post('/credits/topup', authenticateUser, paymentRateLimit, async (req:AuthRequest,res)=>{const phone=req.user?.phone?String(req.user.phone):null;if(!phone)return res.status(401).json({error:'Authenticated phone is required'});if(req.body?.phone&&String(req.body.phone)!==phone)return res.status(403).json({error:'Credit top-up must use authenticated identity'});const amount=Number(req.body?.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Valid positive amount is required'});const provider=configuredPaymentProvider();if(process.env.NODE_ENV==='production'||provider!=='sandbox')return res.status(503).json({success:false,error:'Verified payment provider integration is required before production credit top-ups are enabled',payment_required:true});try{const profile=await getProfile(phone,'credit_topup');const fcmToken=req.body?.fcmToken||req.headers['x-fcm-token'];if(profile?.fcm_token&&(!fcmToken||fcmToken!==profile.fcm_token))return res.status(403).json({success:false,error:'Device session token mismatch or missing.'});await addCredits(phone,amount,'Sandbox credit top-up');res.json({success:true});}catch(e:any){res.status(500).json({success:false,error:e.message||'Failed to top up credits'});}});
export default router;
