/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import { Router } from 'express';
import { authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { createRateLimiter } from '../middleware/rateLimit.js';
import { generatePrayer, createPrayerRoutine, listPrayerRoutines, type PrayerTradition } from '../services/prayerAgentService.js';
import { ensurePrayerCapability } from '../services/prayerCapability.js';
import { synthesizeSpeech } from '../services/serverTtsService.js';
ensurePrayerCapability();
const router=Router();
const limiter=createRateLimiter({windowMs:60_000,max:12,keyPrefix:'prayer',message:'Prayer requests are temporarily limited — try again shortly'});
const owner=(req:AuthRequest)=>req.user?.phone?String(req.user.phone):null;
const tradition=(value:unknown):PrayerTradition=>['christian','muslim','jewish','spiritual','general'].includes(String(value))?String(value) as PrayerTradition:'general';
router.get('/status',authenticateUser,async(req:AuthRequest,res)=>{const phone=owner(req);if(!phone)return res.status(401).json({error:'Authentication required'});res.json({success:true,agent:'agent_prayer_companion',capability:'skill.prayer',modes:['text','audio','live'],traditions:['christian','muslim','jewish','spiritual','general'],routines:await listPrayerRoutines(phone)});});
router.post('/generate',authenticateUser,limiter,async(req:AuthRequest,res)=>{const phone=owner(req);if(!phone)return res.status(401).json({error:'Authentication required'});const result=await generatePrayer({phone,topic:typeof req.body?.topic==='string'?req.body.topic:undefined,name:typeof req.body?.name==='string'?req.body.name:undefined,tradition:tradition(req.body?.tradition),tone:typeof req.body?.tone==='string'?req.body.tone:undefined,length:['short','medium','long'].includes(req.body?.length)?req.body.length:'medium',conversationId:typeof req.body?.conversationId==='string'?req.body.conversationId:undefined});res.json({success:true,...result});});
router.post('/audio',authenticateUser,limiter,async(req:AuthRequest,res)=>{const phone=owner(req);if(!phone)return res.status(401).json({error:'Authentication required'});const text=typeof req.body?.text==='string'?req.body.text.replace(/[\u0000-\u001f]/g,' ').trim().slice(0,6000):'';if(!text)return res.status(400).json({error:'text is required'});try{const result=await synthesizeSpeech(text);res.set({'Content-Type':result.mime,'Content-Length':String(result.data.length),'Cache-Control':'private, max-age=300','X-Kurukoo-Voice-Agent':'agent_prayer_companion'});res.send(result.data);}catch(error:any){res.status(503).json({error:error?.message||'Prayer audio is unavailable right now.',code:error?.code||'PRAYER_AUDIO_FAILED'});}});
router.post('/routine',authenticateUser,limiter,async(req:AuthRequest,res)=>{const phone=owner(req);if(!phone)return res.status(401).json({error:'Authentication required'});const dueAt=typeof req.body?.dueAt==='string'?req.body.dueAt:'';const topic=typeof req.body?.topic==='string'?req.body.topic.trim():'';const recurrence=req.body?.recurrence==='weekly'?'weekly':'daily';if(!topic||!dueAt)return res.status(400).json({error:'topic and dueAt are required'});try{const reminder=await createPrayerRoutine({phone,topic,dueAt,recurrence,tradition:tradition(req.body?.tradition),name:typeof req.body?.name==='string'?req.body.name:undefined,conversationId:typeof req.body?.conversationId==='string'?req.body.conversationId:undefined});res.json({success:true,reminder,agentId:'agent_prayer_companion'});}catch(error:any){res.status(400).json({error:error?.message||'Prayer routine could not be scheduled.'});}});
router.get('/routines',authenticateUser,async(req:AuthRequest,res)=>{const phone=owner(req);if(!phone)return res.status(401).json({error:'Authentication required'});res.json({success:true,routines:await listPrayerRoutines(phone)});});
export default router;
