/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import { Router } from 'express';
import { authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { appendChatMessage, listChatMessages } from '../services/chatConversationService.js';
import { createProviderCommunicationSession, endProviderCommunicationSession, ensureProviderCommunicationConversation, getProviderCommunicationSession, getProviderCommunicationStatus, recordProviderLocation, startMaskedProviderCall, updateProviderCommunicationState } from '../services/providerCommunicationService.js';

const router=Router();
const participantRole=(session:{customerPhone:string;providerPhone:string},phone:string)=>session.customerPhone===phone?'customer':session.providerPhone===phone?'provider':null;
const messageClosed=(state:string)=>new Set(['completed','ended','failed']).has(state);
router.get('/status',authenticateUser,(_req:AuthRequest,res)=>{const gpsIntervalMs=Math.max(5000,Math.min(120000,Number(process.env.KURUKOO_PROVIDER_GPS_INTERVAL_MS)||15000));res.json({success:true,gpsIntervalMs,...getProviderCommunicationStatus()});});
router.post('/sessions',authenticateUser,async(req:AuthRequest,res)=>{try{const customerPhone=String(req.user?.phone||'');const providerPhone=String(req.body?.providerPhone||'').trim();if(!providerPhone)return res.status(400).json({success:false,error:'providerPhone is required.'});const session=await createProviderCommunicationSession({customerPhone,providerPhone,economicRequestId:req.body?.economicRequestId,mode:req.body?.mode});res.status(201).json({success:true,session,communication:{maskedCall:Boolean(session.proxyPhone),realTimeSession:Boolean(session.roomId),preferredTransport:'webrtc'}});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to create provider communication session.'});}});
router.post('/sessions/:id/call',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||current.customerPhone!==phone)return res.status(403).json({success:false,error:'Only the customer can start this masked provider call.'});const session=await startMaskedProviderCall(String(req.params.id));res.status(202).json({success:true,session,masked:true,provider:'twilio'});}catch(error){res.status(503).json({success:false,error:error instanceof Error?error.message:'Unable to start masked provider call.'});}});
router.get('/sessions/:id',authenticateUser,async(req:AuthRequest,res)=>{const session=await getProviderCommunicationSession(String(req.params.id));if(!session)return res.status(404).json({success:false,error:'Communication session not found.'});const phone=String(req.user?.phone||'');const role=participantRole(session,phone);if(!role)return res.status(403).json({success:false,error:'Not a communication participant.'});const ready=await ensureProviderCommunicationConversation(session.id);const gpsIntervalMs=Math.max(5000,Math.min(120000,Number(process.env.KURUKOO_PROVIDER_GPS_INTERVAL_MS)||15000));res.json({success:true,session:ready,role,gpsIntervalMs,transport:{webRtc:Boolean(ready.roomId),data:true,audio:true,video:true,maskedCallFallback:Boolean(ready.proxyPhone||getProviderCommunicationStatus().maskedCall.twilio?.configured)}});});
router.get('/sessions/:id/messages',authenticateUser,async(req:AuthRequest,res)=>{try{const session=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');const role=session?participantRole(session,phone):null;if(!session||!role)return res.status(403).json({success:false,error:'Not a communication participant.'});const ready=await ensureProviderCommunicationConversation(session.id);const messages=await listChatMessages(ready.customerPhone,{conversationId:ready.conversationId,limit:Number(req.query.limit)||50,beforeId:Number(req.query.beforeId)||undefined});res.json({success:true,sessionId:ready.id,conversationId:ready.conversationId,messages});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to retrieve provider-session messages.'});}});
router.post('/sessions/:id/messages',authenticateUser,async(req:AuthRequest,res)=>{try{const session=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');const role=session?participantRole(session,phone):null;if(!session||!role)return res.status(403).json({success:false,error:'Not a communication participant.'});if(messageClosed(session.state))return res.status(409).json({success:false,error:'Communication session is no longer active.'});const content=typeof req.body?.content==='string'?req.body.content.replace(/[\u0000-\u001f]/g,' ').trim().slice(0,4000):'';if(!content)return res.status(400).json({success:false,error:'Message content is required.'});if(!session.economicRequestId)return res.status(409).json({success:false,error:'Communication session has no canonical request context.'});const ready=await ensureProviderCommunicationConversation(session.id);const message=await appendChatMessage({phone:ready.customerPhone,sender:'user',content,channel:'provider_session',conversationId:ready.conversationId,metadata:{providerCommunicationSessionId:ready.id,participantRole:role,authorPhone:phone,transport:'webrtc_data_or_channel_fallback'}});res.status(201).json({success:true,message,conversationId:ready.conversationId});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to persist provider-session message.'});}});
router.post('/sessions/:id/state',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||(current.customerPhone!==phone&&current.providerPhone!==phone))return res.status(403).json({success:false,error:'Not a communication participant.'});const session=await updateProviderCommunicationState(String(req.params.id),req.body?.state);res.json({success:true,session});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to update communication state.'});}});
router.post('/sessions/:id/location',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||current.providerPhone!==phone)return res.status(403).json({success:false,error:'Only the provider can publish live location.'});const session=await recordProviderLocation(String(req.params.id),Number(req.body?.latitude),Number(req.body?.longitude));res.json({success:true,session});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to record provider location.'});}});
router.post('/sessions/:id/end',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||(current.customerPhone!==phone&&current.providerPhone!==phone))return res.status(403).json({success:false,error:'Not a communication participant.'});res.json({success:true,session:await endProviderCommunicationSession(String(req.params.id))});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to end communication session.'});}});
export default router;
