/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import { Router } from 'express';
import { authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { appendChatMessage, listChatMessages } from '../services/chatConversationService.js';
import { createProviderCommunicationSession, endProviderCommunicationSession, ensureProviderCommunicationConversation, getProviderCommunicationSession, getProviderCommunicationStatus, recordProviderLocation, startMaskedProviderCall, updateProviderCommunicationState } from '../services/providerCommunicationService.js';
import { getCanonicalStore } from '../services/canonicalStore.js';
import { getEconomicRequest, transitionEconomicRequest } from '../services/skillFlows.js';
import { getEconomicParticipants, updateEconomicParticipant, type EconomicParticipantRole, type EconomicParticipantStatus } from '../services/economicParticipants.js';
import { assertIdentityAllows } from '../services/progressiveIdentityService.js';

const router=Router();
const participantRole=(session:{customerPhone:string;providerPhone:string},phone:string)=>session.customerPhone===phone?'customer':session.providerPhone===phone?'provider':null;
const messageClosed=(state:string)=>new Set(['completed','ended','failed']).has(state);
const providerRoles=new Set<string>(['service_provider','seller','delivery_provider','provider']);
const providerStatuses=new Set<EconomicParticipantStatus>(['invited','offered','selected','confirmed','handover_pending','handed_over','collected','in_progress','completion_reported','delivered','declined','withdrawn']);
function parseJson(value:unknown,fallback:any={}){if(value&&typeof value==='object')return value;if(typeof value!=='string'||!value.trim())return fallback;try{return JSON.parse(value)}catch{return fallback}}
async function requireProvider(phone:string){const gate=await assertIdentityAllows(phone,'provider_action');return gate.allowed?gate:null}
async function providerParticipant(requestId:string,phone:string){const participants=await getEconomicParticipants(requestId);return participants.find((item)=>item.providerPhone===phone&&providerRoles.has(String(item.role)))||null}

router.get('/status',authenticateUser,(_req:AuthRequest,res)=>{const gpsIntervalMs=Math.max(5000,Math.min(120000,Number(process.env.KURUKOO_PROVIDER_GPS_INTERVAL_MS)||15000));res.json({success:true,gpsIntervalMs,...getProviderCommunicationStatus()});});
router.post('/sessions',authenticateUser,async(req:AuthRequest,res)=>{try{const customerPhone=String(req.user?.phone||'');const providerPhone=String(req.body?.providerPhone||'').trim();if(!providerPhone)return res.status(400).json({success:false,error:'providerPhone is required.'});const session=await createProviderCommunicationSession({customerPhone,providerPhone,economicRequestId:req.body?.economicRequestId,mode:req.body?.mode});res.status(201).json({success:true,session,communication:{maskedCall:Boolean(session.proxyPhone),realTimeSession:Boolean(session.roomId),preferredTransport:'webrtc'}});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to create provider communication session.'});}});
router.post('/sessions/:id/call',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||current.customerPhone!==phone)return res.status(403).json({success:false,error:'Only the customer can start this masked provider call.'});const session=await startMaskedProviderCall(String(req.params.id));res.status(202).json({success:true,session,masked:true,provider:'twilio'});}catch(error){res.status(503).json({success:false,error:error instanceof Error?error.message:'Unable to start masked provider call.'});}});
router.get('/sessions/:id',authenticateUser,async(req:AuthRequest,res)=>{const session=await getProviderCommunicationSession(String(req.params.id));if(!session)return res.status(404).json({success:false,error:'Communication session not found.'});const phone=String(req.user?.phone||'');const role=participantRole(session,phone);if(!role)return res.status(403).json({success:false,error:'Not a communication participant.'});const ready=await ensureProviderCommunicationConversation(session.id);const gpsIntervalMs=Math.max(5000,Math.min(120000,Number(process.env.KURUKOO_PROVIDER_GPS_INTERVAL_MS)||15000));res.json({success:true,session:ready,role,gpsIntervalMs,transport:{webRtc:Boolean(ready.roomId),data:true,audio:true,video:true,maskedCallFallback:Boolean(ready.proxyPhone||getProviderCommunicationStatus().maskedCall.twilio?.configured)}});});
router.get('/sessions/:id/messages',authenticateUser,async(req:AuthRequest,res)=>{try{const session=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');const role=session?participantRole(session,phone):null;if(!session||!role)return res.status(403).json({success:false,error:'Not a communication participant.'});const ready=await ensureProviderCommunicationConversation(session.id);const messages=await listChatMessages(ready.customerPhone,{conversationId:ready.conversationId,limit:Number(req.query.limit)||50,beforeId:Number(req.query.beforeId)||undefined});res.json({success:true,sessionId:ready.id,conversationId:ready.conversationId,messages});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to retrieve provider-session messages.'});}});
router.post('/sessions/:id/messages',authenticateUser,async(req:AuthRequest,res)=>{try{const session=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');const role=session?participantRole(session,phone):null;if(!session||!role)return res.status(403).json({success:false,error:'Not a communication participant.'});if(messageClosed(session.state))return res.status(409).json({success:false,error:'Communication session is no longer active.'});const content=typeof req.body?.content==='string'?req.body.content.replace(/[\u0000-\u001f]/g,' ').trim().slice(0,4000):'';if(!content)return res.status(400).json({success:false,error:'Message content is required.'});if(!session.economicRequestId)return res.status(409).json({success:false,error:'Communication session has no canonical request context.'});const ready=await ensureProviderCommunicationConversation(session.id);const message=await appendChatMessage({phone:ready.customerPhone,sender:'user',content,channel:'provider_session',conversationId:ready.conversationId,metadata:{providerCommunicationSessionId:ready.id,participantRole:role,authorPhone:phone,transport:'webrtc_data_or_channel_fallback'}});res.status(201).json({success:true,message,conversationId:ready.conversationId});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to persist provider-session message.'});}});
router.post('/sessions/:id/state',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||(current.customerPhone!==phone&&current.providerPhone!==phone))return res.status(403).json({success:false,error:'Not a communication participant.'});const session=await updateProviderCommunicationState(String(req.params.id),req.body?.state);res.json({success:true,session});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to update communication state.'});}});
router.post('/sessions/:id/location',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||current.providerPhone!==phone)return res.status(403).json({success:false,error:'Only the provider can publish live location.'});const session=await recordProviderLocation(String(req.params.id),Number(req.body?.latitude),Number(req.body?.longitude));res.json({success:true,session});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to record provider location.'});}});
router.post('/sessions/:id/end',authenticateUser,async(req:AuthRequest,res)=>{try{const current=await getProviderCommunicationSession(String(req.params.id));const phone=String(req.user?.phone||'');if(!current||(current.customerPhone!==phone&&current.providerPhone!==phone))return res.status(403).json({success:false,error:'Not a communication participant.'});res.json({success:true,session:await endProviderCommunicationSession(String(req.params.id))});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to end communication session.'});}});

router.get('/requests',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'').trim();const gate=await requireProvider(phone);if(!gate)return res.status(403).json({success:false,error:'Provider verification is required before provider work can be accepted.'});const limit=Math.max(1,Math.min(50,Number(req.query.limit)||20));const store=await getCanonicalStore();const rows=await store.all<any>(`SELECT er.id,er.phone,er.skill,er.category,er.status,er.requirements_json,er.quote_json,er.fulfillment_json,er.created_at,er.updated_at,ep.role,ep.capability,ep.status AS participant_status,ep.evidence_json FROM economic_participants ep JOIN economic_requests er ON er.id=ep.request_id WHERE ep.provider_phone=? ORDER BY CASE WHEN er.status IN ('awaiting_confirmation','reserved','paid','in_fulfillment') THEN 0 WHEN er.status IN ('matched','quoting','quoted') THEN 1 ELSE 2 END, er.updated_at DESC LIMIT ?`,[phone,limit]);const requests=rows.map((row)=>({id:String(row.id),customerPhone:String(row.phone),skill:String(row.skill),category:String(row.category||''),status:String(row.status),requirements:parseJson(row.requirements_json,{}),quote:parseJson(row.quote_json,null),fulfillment:parseJson(row.fulfillment_json,null),createdAt:String(row.created_at||''),updatedAt:String(row.updated_at||''),participant:{role:String(row.role),capability:String(row.capability||''),status:String(row.participant_status),evidence:parseJson(row.evidence_json,{})}}));res.json({success:true,requests});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to load provider requests.'});}});
router.get('/requests/:id',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'').trim();const gate=await requireProvider(phone);if(!gate)return res.status(403).json({success:false,error:'Provider verification is required.'});const request=await getEconomicRequest(String(req.params.id));const participant=request?await providerParticipant(String(req.params.id),phone):null;if(!request||!participant)return res.status(404).json({success:false,error:'Provider request not found.'});res.json({success:true,request,participant,communicationSessionId:null});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to load provider request.'});}});
router.post('/requests/:id/quote',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'').trim();const gate=await requireProvider(phone);if(!gate)return res.status(403).json({success:false,error:'Provider verification is required.'});const request=await getEconomicRequest(String(req.params.id));const participant=request?await providerParticipant(String(req.params.id),phone):null;if(!request||!participant)return res.status(404).json({success:false,error:'Provider request not found.'});const amountMinor=Number(req.body?.amountMinor);const currency=String(req.body?.currency||'NGN').trim().toUpperCase();if(!Number.isInteger(amountMinor)||amountMinor<=0)return res.status(422).json({success:false,error:'A positive integer amountMinor is required.'});if(!/^[A-Z]{3}$/.test(currency))return res.status(422).json({success:false,error:'Currency must be a three-letter code.'});const quote={amount_minor:amountMinor,currency,provider_phone:phone,provider_name:req.body?.providerName?String(req.body.providerName).slice(0,160):undefined,note:req.body?.note?String(req.body.note).slice(0,1000):undefined,valid_until:req.body?.validUntil?String(req.body.validUntil).slice(0,80):undefined,submitted_at:new Date().toISOString(),revision:Number(req.body?.revision)||1};let updated=request;if(request.status==='partially_matched')updated=await transitionEconomicRequest(request.id,'quoting',{providerPhone:phone});if(['matched','quoting'].includes(updated.status))updated=await transitionEconomicRequest(request.id,'quoted',{providerPhone:phone,quote});else if(updated.status!=='quoted')return res.status(409).json({success:false,error:`A quote cannot be submitted while the request is ${updated.status}.`});const participantUpdated=await updateEconomicParticipant({requestId:request.id,actorPhone:phone,role:participant.role as EconomicParticipantRole,providerPhone:phone,status:'offered' as EconomicParticipantStatus,evidence:{...participant.evidence,quote}});res.json({success:true,request:updated,participant:participantUpdated,quote});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to submit provider quote.'});}});
router.post('/requests/:id/accept',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'').trim();const gate=await requireProvider(phone);if(!gate)return res.status(403).json({success:false,error:'Provider verification is required.'});const request=await getEconomicRequest(String(req.params.id));const participant=request?await providerParticipant(String(req.params.id),phone):null;if(!request||!participant)return res.status(404).json({success:false,error:'Provider request not found.'});const participantUpdated=await updateEconomicParticipant({requestId:request.id,actorPhone:phone,role:participant.role as EconomicParticipantRole,providerPhone:phone,status:'confirmed' as EconomicParticipantStatus,evidence:{...participant.evidence,accepted_at:new Date().toISOString()}});let updated=request;if(['reserved','paid'].includes(request.status))updated=await transitionEconomicRequest(request.id,'in_fulfillment',{providerPhone:phone});res.json({success:true,request:updated,participant:participantUpdated,started:['reserved','paid'].includes(request.status)});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to accept provider request.'});}});
router.post('/requests/:id/decline',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'').trim();const gate=await requireProvider(phone);if(!gate)return res.status(403).json({success:false,error:'Provider verification is required.'});const request=await getEconomicRequest(String(req.params.id));const participant=request?await providerParticipant(String(req.params.id),phone):null;if(!request||!participant)return res.status(404).json({success:false,error:'Provider request not found.'});const updated=await updateEconomicParticipant({requestId:request.id,actorPhone:phone,role:participant.role as EconomicParticipantRole,providerPhone:phone,status:'declined' as EconomicParticipantStatus,evidence:{...participant.evidence,declined_at:new Date().toISOString(),reason:req.body?.reason?String(req.body.reason).slice(0,500):undefined}});res.json({success:true,request,participant:updated});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to decline provider request.'});}});
router.post('/requests/:id/evidence',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'').trim();const gate=await requireProvider(phone);if(!gate)return res.status(403).json({success:false,error:'Provider verification is required.'});const request=await getEconomicRequest(String(req.params.id));const participant=request?await providerParticipant(String(req.params.id),phone):null;if(!request||!participant)return res.status(404).json({success:false,error:'Provider request not found.'});const status=String(req.body?.status||'completion_reported') as EconomicParticipantStatus;if(!providerStatuses.has(status))return res.status(422).json({success:false,error:'Unsupported provider evidence status.'});const evidence=req.body?.evidence&&typeof req.body.evidence==='object'&&!Array.isArray(req.body.evidence)?req.body.evidence:{};const updated=await updateEconomicParticipant({requestId:request.id,actorPhone:phone,role:participant.role as EconomicParticipantRole,providerPhone:phone,status,evidence:{...participant.evidence,...evidence,submitted_at:new Date().toISOString()}});res.json({success:true,request,participant:updated,awaitingCustomerConfirmation:status==='completion_reported'});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to submit provider evidence.'});}});
router.post('/requests/:id/communication',authenticateUser,async(req:AuthRequest,res)=>{try{const phone=String(req.user?.phone||'').trim();const gate=await requireProvider(phone);if(!gate)return res.status(403).json({success:false,error:'Provider verification is required.'});const request=await getEconomicRequest(String(req.params.id));const participant=request?await providerParticipant(String(req.params.id),phone):null;if(!request||!participant)return res.status(404).json({success:false,error:'Provider request not found.'});const session=await createProviderCommunicationSession({customerPhone:request.phone,providerPhone:phone,economicRequestId:request.id,mode:req.body?.mode||'both'});res.status(201).json({success:true,session});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to start provider communication.'});}});
export default router;
