import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { PageHeader } from "@/components/app-shell";
import { PlanCard } from "@/components/kurukoo/cards";
import { Action } from "@/components/kurukoo/primitives";
import { Panel, Tabs } from "@/components/kurukoo/ui";
import { plans } from "@/lib/kurukoo-demo";
export const Route=createFileRoute("/subscriptions")({head:()=>({meta:[{title:"Subscriptions — Kurukoo"},{name:"description",content:"Manage Kurukoo plans for people, providers, businesses and creators, with access, points and billing kept clear."}]}),component:SubscriptionsPage});
const tabs=["You","Providers","Businesses","Creators"] as const;
function SubscriptionsPage(){const [tab,setTab]=useState<string>(tabs[0]);const audience=tab==="You"?"user":tab==="Providers"?"provider":tab==="Businesses"?"business":"creator";return <><PageHeader title="Subscriptions" subtitle="Plans give you access. Points and paid transactions are kept separate."/><Tabs items={tabs} value={tab} onChange={setTab}/><div className="mt-4 grid gap-3 sm:grid-cols-2">{plans.filter(p=>p.audience===audience).map(p=><PlanCard key={p.id} plan={p}/>)}</div><Panel className="mt-6 p-4"><p className="text-[15px] font-medium">Billing</p><p className="mt-1 text-[13.5px] text-muted-foreground">Choose, change or cancel a plan. Billing status, invoices and renewal details appear when the payment connection is enabled.</p><div className="mt-3 flex flex-wrap gap-2"><Action variant="primary">Change plan</Action><Action>Cancel subscription</Action></div></Panel><div className="mt-6 grid gap-3 sm:grid-cols-3"><Panel className="p-4"><p className="text-[13px] font-semibold">Access</p><p className="mt-1.5 text-[11.5px] leading-relaxed text-muted-foreground">Your plan controls access to the relevant Kurukoo experience.</p></Panel><Panel className="p-4"><p className="text-[13px] font-semibold">Points</p><p className="mt-1.5 text-[11.5px] leading-relaxed text-muted-foreground">Points support coordination work and are separate from subscription charges.</p></Panel><Panel className="p-4"><p className="text-[13px] font-semibold">Services and purchases</p><p className="mt-1.5 text-[11.5px] leading-relaxed text-muted-foreground">Approved services and purchases remain visible as separate transactions.</p></Panel></div><p className="mt-5 rounded-2xl border border-border bg-elevated/50 px-4 py-3 text-[12px] leading-relaxed text-muted-foreground">Live billing and plan changes become active when the payment connection is enabled.</p></>}
