import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, ArrowRight, Download, KeyRound, LockKeyhole, RefreshCw, ShieldCheck, Square, CreditCard } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/app-shell";
import { actionClass } from "@/components/kurukoo/primitives";
import { Badge, Panel } from "@/components/kurukoo/ui";
import { cancelTrustCard, exportTrustAudit, fetchTrustOverview, freezeTrustCard, stopExecutionSession, type AuditEntry, type Credential, type ExecutionSession, type VirtualCard } from "@/lib/trust-api";

export const Route = createFileRoute("/trust")({
  head: () => ({ meta: [{ title: "Trust — Kurukoo" }, { name: "description", content: "Control credentials, protected payments, secure execution and your execution audit." }] }),
  component: TrustPage,
});

function TrustPage() {
  const [credentials, setCredentials] = useState<Credential[]>([]);
  const [cards, setCards] = useState<VirtualCard[]>([]);
  const [sessions, setSessions] = useState<ExecutionSession[]>([]);
  const [audit, setAudit] = useState<AuditEntry[]>([]);
  const [availability, setAvailability] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  async function load() {
    setLoading(true); setError("");
    try { const data = await fetchTrustOverview(); setCredentials(data.credentials.credentials ?? []); setCards(data.cards.cards ?? []); setSessions(data.sessions.sessions ?? []); setAudit(data.audit.timeline ?? []); setAvailability(data.availability); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Trust controls could not be loaded."); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  async function action(id: string, run: () => Promise<unknown>, after = load) { setBusy(id); try { await run(); await after(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The action could not be completed."); } finally { setBusy(null); } }
  async function downloadAudit() { setBusy("audit"); try { const blob = await exportTrustAudit(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "kurukoo-audit-export.json"; anchor.click(); URL.revokeObjectURL(url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Audit export is not available."); } finally { setBusy(null); } }
  return <div className="space-y-8 pb-12">
    <PageHeader title="Trust" subtitle="The controls around what Kurukoo may use, spend and do on your behalf. Important actions stay bounded, reviewable and reversible where the underlying service supports it." />
    <div className="flex flex-wrap items-center gap-2 border-y border-border py-3"><span className="inline-flex items-center gap-2 text-[11px] font-medium"><span className="size-2 rounded-full bg-[var(--color-success)]" /> Your account controls are active</span><span className="text-[10.5px] text-muted-foreground">Availability depends on the connected service and your market.</span><button type="button" disabled={loading} onClick={() => void load()} className={`${actionClass()} ml-auto`}><RefreshCw className="size-3.5" />{loading ? "Checking…" : "Refresh"}</button></div>
    {error ? <div role="alert" className="border border-destructive/30 bg-destructive/5 px-4 py-3 text-[11.5px] text-destructive">{error}</div> : null}
    <section className="grid gap-3 md:grid-cols-3"><Panel className="p-5"><KeyRound className="size-5 text-primary" /><p className="mt-4 text-[11px] uppercase tracking-[0.12em] text-muted-foreground">Credentials</p><p className="mt-1 text-2xl font-semibold">{credentials.length}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Stored as protected metadata; the agent does not receive plaintext secrets.</p></Panel><Panel className="p-5"><CreditCard className="size-5 text-primary" /><p className="mt-4 text-[11px] uppercase tracking-[0.12em] text-muted-foreground">Protected payment</p><p className="mt-1 text-2xl font-semibold">{cards.length}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">One-time or bounded cards when the supported payment provider is actually available.</p></Panel><Panel className="p-5"><Activity className="size-5 text-primary" /><p className="mt-4 text-[11px] uppercase tracking-[0.12em] text-muted-foreground">Secure work</p><p className="mt-1 text-2xl font-semibold">{sessions.length}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Bounded execution sessions with explicit expiry and provider requirements.</p></Panel></section>
    <section className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
      <div><div className="mb-3"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Protected access</p><h2 className="mt-1.5 text-[22px] font-semibold tracking-[-0.03em]">Credentials</h2><p className="mt-1 text-[11px] text-muted-foreground">Kurukoo can know that a credential exists without exposing its secret in the conversational layer.</p></div><Panel className="overflow-hidden p-0"><div className="divide-y divide-border">{credentials.length ? credentials.map((item) => <div key={item.id} className="flex items-center gap-3 px-4 py-4"><span className="grid size-9 place-items-center bg-elevated"><KeyRound className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-[12.5px] font-medium">{item.label}</p><p className="mt-1 text-[10.5px] text-muted-foreground">{item.domain || "Protected service"}{item.credentialType ? ` · ${item.credentialType}` : ""}</p></div><Badge tone="success">Protected</Badge></div>) : <div className="px-5 py-10 text-center text-[11.5px] text-muted-foreground">No protected credentials are available to this account or deployment.</div>}</div></Panel></div>
      <div><div className="mb-3"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Bounded payment</p><h2 className="mt-1.5 text-[22px] font-semibold tracking-[-0.03em]">Payment protection</h2></div><Panel className="overflow-hidden p-0"><div className="divide-y divide-border">{cards.length ? cards.map((card) => <div key={card.id} className="px-4 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center bg-elevated"><CreditCard className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-[12.5px] font-medium">{card.brand} ···· {card.last4}</p><p className="mt-1 text-[10.5px] text-muted-foreground">{card.currency} {card.spendLimitMinor / 100} · {card.status}</p></div><Badge tone={card.status === "active" ? "success" : "quiet"}>{card.status}</Badge></div>{card.status === "active" ? <div className="mt-3 flex gap-2"><button type="button" disabled={busy === card.id} onClick={() => void action(card.id, () => freezeTrustCard(card.id))} className={actionClass()}>{busy === card.id ? "Freezing…" : "Freeze"}</button><button type="button" disabled={busy === card.id} onClick={() => void action(`${card.id}:cancel`, () => cancelTrustCard(card.id))} className={actionClass()}>{busy === `${card.id}:cancel` ? "Cancelling…" : "Cancel"}</button></div> : null}</div>) : <div className="px-5 py-10 text-center text-[11.5px] text-muted-foreground">No protected payment instruments are available.</div>}</div></Panel></div>
    </section>
    <section><div className="mb-3"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Secure execution</p><h2 className="mt-1.5 text-[22px] font-semibold tracking-[-0.03em]">Work Kurukoo can control</h2><p className="mt-1 text-[11px] text-muted-foreground">Sessions expire and can be stopped. A missing execution provider remains an honest unavailable state.</p></div><Panel className="overflow-hidden p-0"><div className="divide-y divide-border">{sessions.length ? sessions.map((session) => <div key={session.id} className="flex flex-wrap items-center gap-3 px-4 py-4"><span className="grid size-9 place-items-center bg-elevated"><LockKeyhole className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-[12.5px] font-medium">Secure session</p><p className="mt-1 text-[10.5px] text-muted-foreground">{session.status}{session.expiresAt ? ` · expires ${new Date(session.expiresAt).toLocaleString()}` : ""}</p></div><button type="button" disabled={busy === session.id} onClick={() => void action(session.id, () => stopExecutionSession(session.id))} className={actionClass()}><Square className="size-3.5" />{busy === session.id ? "Stopping…" : "Stop"}</button></div>) : <div className="px-5 py-10 text-center text-[11.5px] text-muted-foreground">No secure execution sessions are active.</div>}</div></Panel></section>
    <section><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Evidence trail</p><h2 className="mt-1.5 text-[22px] font-semibold tracking-[-0.03em]">Execution audit</h2><p className="mt-1 text-[11px] text-muted-foreground">A read-only view of execution events from canonical services.</p></div><button type="button" disabled={busy === "audit"} onClick={() => void downloadAudit()} className={actionClass()}><Download className="size-3.5" />{busy === "audit" ? "Preparing…" : "Export"}</button></div><Panel className="overflow-hidden p-0"><div className="divide-y divide-border">{audit.length ? audit.slice(0, 20).map((entry) => <div key={entry.id} className="flex items-start gap-3 px-4 py-4"><span className="mt-0.5 size-2 shrink-0 rounded-full bg-primary" /><div className="min-w-0 flex-1"><p className="text-[12px] font-medium">{entry.summary || entry.action || entry.type || "Execution event"}</p><p className="mt-1 text-[10.5px] text-muted-foreground">{entry.status || "Recorded"}{entry.createdAt || entry.timestamp ? ` · ${new Date(entry.createdAt || entry.timestamp || "").toLocaleString()}` : ""}{entry.requestId ? ` · Request ${entry.requestId}` : ""}</p></div></div>) : <div className="px-5 py-10 text-center text-[11.5px] text-muted-foreground">No audit events are available to show for this account.</div>}</div></Panel></section>
    <section className="border-t border-border pt-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 text-primary" /><div><p className="text-[13px] font-medium">Trust is part of the product, not an admin afterthought.</p><p className="mt-1 max-w-2xl text-[11px] leading-relaxed text-muted-foreground">Memory does not grant permission. A provider claim does not prove fulfilment. A queued action does not prove completion. Kurukoo keeps those boundaries visible.</p><div className="mt-3 flex flex-wrap gap-2"><Link to="/memory" className={actionClass()}>Manage Memory <ArrowRight className="size-3.5" /></Link><Link to="/connect" className={actionClass()}>Manage Connections <ArrowRight className="size-3.5" /></Link></div></div></div></section>
  </div>;
}
