import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, CreditCard, Coins, WalletCards } from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { TransactionRow } from "@/components/kurukoo/cards";
import { Action } from "@/components/kurukoo/primitives";
import { Panel, Rows, SectionHeader } from "@/components/kurukoo/ui";
import { transactions } from "@/lib/kurukoo-demo";
export const Route=createFileRoute("/wallet")({head:()=>({meta:[{title:"Wallet and points — Kurukoo"},{name:"description",content:"Keep Kurukoo points for coordination separate from money used for approved services, purchases and payouts."}]}),component:WalletPage});
function Metric({icon:Icon,label,value,note}:{icon:typeof Coins;label:string;value:string;note:string}){return <Panel className="p-4"><span className="grid size-9 place-items-center rounded-xl bg-elevated text-muted-foreground"><Icon className="size-4"/></span><p className="mt-4 text-[11.5px] text-muted-foreground">{label}</p><p className="mt-1 text-[25px] font-semibold tracking-[-0.03em]">{value}</p><p className="mt-1 text-[11.5px] text-muted-foreground">{note}</p></Panel>}
function WalletPage(){return <><PageHeader title="Wallet" subtitle="Points support Kurukoo's coordination work. Money covers approved services and purchases."/><div className="grid gap-3 sm:grid-cols-3"><Metric icon={Coins} label="Kurukoo points" value="480 pts" note="Available for coordination"/><Metric icon={WalletCards} label="Wallet balance" value="£0.00" note="Payment method when connected"/><Metric icon={CreditCard} label="Provider earnings" value="—" note="Payouts when connected"/></div><Panel className="mt-4 p-5"><p className="text-[15px] font-medium">Value at a glance</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-elevated/60 p-4"><p className="text-[11px] font-medium uppercase tracking-[0.12em] text-muted-foreground">Points</p><p className="mt-2 text-[13px] leading-relaxed">Used for Kurukoo's coordination work.</p></div><div className="rounded-xl bg-elevated/60 p-4"><p className="text-[11px] font-medium uppercase tracking-[0.12em] text-muted-foreground">Money</p><p className="mt-2 text-[13px] leading-relaxed">Used after an approved provider, business or paid transaction step.</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Action variant="primary">Top up points</Action><Action>Add payment method</Action><Link to="/subscriptions"><Action>Manage subscription</Action></Link></div></Panel><section className="mt-8"><SectionHeader title="History" subtitle="Points and money remain visible as separate transaction types."/><Rows>{transactions.map(t=><TransactionRow key={t.id} tx={t}/>)}</Rows></section><div className="mt-4 flex justify-end"><Link to="/activity" className="inline-flex items-center gap-1 text-[12.5px] font-medium text-muted-foreground">See request activity <ArrowUpRight className="size-3.5"/></Link></div><p className="mt-5 rounded-2xl border border-border bg-elevated/50 px-4 py-3 text-[12px] leading-relaxed text-muted-foreground">Top-ups, refunds, live balances and provider payouts become active when the payment connection is enabled.</p></>}
