import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, CircleDot, Compass, FileCheck2, LockKeyhole, MessageCircle, Sparkles, Workflow } from "lucide-react";
import { useEffect, useState } from "react";
import { fetchExecutionOverview, type ExecutionMode, type ExecutionOverview, type ExecutionSurface } from "@/lib/execution-api";
import { useKurukoo } from "@/lib/kurukoo-store";
import { Panel } from "@/components/kurukoo/ui";

export const Route = createFileRoute("/work")({
  head: () => ({ meta: [{ title: "Work — Kurukoo" }, { name: "description", content: "See what Kurukoo is doing, what needs you, and what is actually done." }] }),
  component: WorkPage,
});

const loopLabels: Record<string, string> = { tell: "Tell", understand: "Understand", find_or_plan: "Find / plan", choose: "Choose", approve: "Approve", do: "Do", show_proof: "Show proof", done: "Done" };
const fallbackModes: ExecutionMode[] = [
  { id: "digital", title: "Digital", description: "Websites, apps, forms, research, documents and supported digital services.", prompt: "Handle this digitally if you can." },
  { id: "physical", title: "Physical", description: "People, providers, businesses, deliveries, repairs and local services.", prompt: "Find the right real-world help for this." },
  { id: "hybrid", title: "Hybrid", description: "Combine digital actions with people, products, logistics or physical fulfilment.", prompt: "Work out the best digital and physical route." },
  { id: "assisted", title: "User-assisted", description: "Prepare the work and tell me exactly what you need from me before continuing.", prompt: "Prepare everything and tell me what you need from me." },
];
const fallbackSurfaces: ExecutionSurface[] = [
  { id: "assist", title: "Assist", path: "/chat", description: "Tell Kurukoo what needs doing." },
  { id: "discover", title: "Discover", path: "/explore", description: "Find people, places, products, services and opportunities." },
  { id: "work", title: "Work", path: "/work", description: "See everything Kurukoo is doing, waiting on or has completed." },
  { id: "memory", title: "Memory", path: "/memory", description: "Control the context Kurukoo remembers and uses." },
  { id: "trust", title: "Trust", path: "/trust", description: "Credentials, protected payment, secure execution and evidence." },
  { id: "connect", title: "Connect", path: "/connect", description: "Connect channels, tools, devices and external resources." },
];

function WorkPage() {
  const { work } = useKurukoo();
  const [overview, setOverview] = useState<ExecutionOverview | null>(null);
  useEffect(() => { void fetchExecutionOverview().then(setOverview).catch(() => setOverview(null)); }, []);
  const active = work.filter(item => item.stage !== "done");
  const completed = work.filter(item => item.stage === "done");
  const needsYou = active.filter(item => item.stage === "needs_you");
  const modes = overview?.modes?.length ? overview.modes : fallbackModes;
  const surfaces = overview?.surfaceGroups?.length ? overview.surfaceGroups : fallbackSurfaces;
  const latest = active.slice(0, 4);

  return <div className="min-w-0 pb-12">
    <header className="max-w-3xl border-b border-border pb-8 pt-4 md:pt-7">
      <div className="flex items-center gap-2 text-[11px] font-medium text-muted-foreground"><span className="size-1.5 rounded-full bg-[var(--color-success)]" />{active.length ? `${active.length} ${active.length === 1 ? "request" : "requests"} in motion` : "Ready when you are"}</div>
      <h1 className="mt-3 text-[42px] font-semibold leading-[1] tracking-[-0.055em]">Work that moves.</h1>
      <p className="mt-4 max-w-2xl text-[14px] leading-6 text-muted-foreground">Kurukoo handles the work behind your requests. Come here when you want to see what is moving, what needs a decision, and what actually happened.</p>
    </header>
    {needsYou.length ? <section className="border-b border-border py-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[13px] font-semibold"><LockKeyhole className="size-4 text-primary" />A decision is waiting for you</div><p className="mt-1 text-[12px] text-muted-foreground">Kurukoo will not take this consequential step without your approval.</p></div><Link to={(`/work/${needsYou[0].id}`) as never} className="inline-flex items-center gap-2 bg-primary px-4 py-2.5 text-[12px] font-medium text-primary-foreground">Review <ArrowRight className="size-3.5" /></Link></div><div className="mt-5 divide-y divide-border border-y border-border">{needsYou.slice(0, 3).map(item => <Link key={item.id} to={(`/work/${item.id}`) as never} className="flex items-center gap-3 py-3 hover:bg-elevated"><LockKeyhole className="size-4 text-primary" /><span className="min-w-0 flex-1 truncate text-[12.5px] font-medium">{item.title}</span><span className="text-[11px] text-muted-foreground">Needs you</span><ArrowRight className="size-3.5 text-muted-foreground" /></Link>)}</div></section> : null}
    <section className="grid grid-cols-3 border-b border-border"><div className="py-5 pr-4"><p className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground">In motion</p><p className="mt-1 text-3xl font-semibold tracking-[-0.04em]">{active.length}</p></div><div className="border-l border-border px-4 py-5"><p className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground">Your decisions</p><p className="mt-1 text-3xl font-semibold tracking-[-0.04em]">{needsYou.length}</p></div><div className="border-l border-border pl-4 py-5"><p className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground">Outcomes</p><p className="mt-1 text-3xl font-semibold tracking-[-0.04em]">{completed.length}</p></div></section>
    {active.length ? <section className="py-8"><div className="mb-4 flex items-end justify-between"><div><h2 className="text-[17px] font-semibold tracking-tight">In motion</h2><p className="mt-1 text-[12px] text-muted-foreground">Open a request to follow its live state, next step and evidence.</p></div><Link to="/chat" search={{ prompt: "Show me everything Kurukoo is working on" } as never} className="text-[12px] font-medium text-primary">Ask Kurukoo</Link></div><div className="divide-y divide-border border-y border-border">{latest.map((item, index) => <Link key={item.id} to={(`/work/${item.id}`) as never} className="group flex gap-4 py-5 hover:bg-elevated/50"><div className="flex w-8 shrink-0 flex-col items-center"><span className="grid size-7 place-items-center border border-border bg-surface">{item.stage === "needs_you" ? <LockKeyhole className="size-3.5 text-primary" /> : <CircleDot className="size-3.5" />}</span>{index < latest.length - 1 ? <span className="mt-2 h-full w-px bg-border" /> : null}</div><div className="min-w-0 flex-1"><div className="flex items-start gap-4"><div className="min-w-0 flex-1"><h3 className="text-[14px] font-semibold">{item.title}</h3><p className="mt-1.5 max-w-2xl text-[12px] leading-5 text-muted-foreground">{item.detail}</p></div><ArrowRight className="mt-1 size-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5" /></div><div className="mt-3 flex items-center gap-3 text-[10.5px] text-muted-foreground"><span>{item.stage === "needs_you" ? "Needs you" : item.stage === "understanding" ? "Understanding" : "Working"}</span><span>·</span><span>{item.updated}</span></div></div></Link>)}</div></section> : <section className="border-y border-border py-14 text-center"><Sparkles className="mx-auto size-6 text-muted-foreground" /><h2 className="mt-3 text-[16px] font-semibold">Nothing is moving yet.</h2><p className="mx-auto mt-1 max-w-md text-[12px] leading-5 text-muted-foreground">Tell Kurukoo the outcome you want. It will work out the route with you.</p><Link to="/chat" className="mt-5 inline-flex items-center gap-2 bg-primary px-4 py-2.5 text-[12px] font-medium text-primary-foreground">Tell Kurukoo what needs doing <ArrowRight className="size-3.5" /></Link></section>}
    <section className="grid gap-8 border-t border-border py-8 lg:grid-cols-[1.2fr_.8fr]"><div><div className="flex items-center gap-2"><Workflow className="size-4" /><h2 className="text-[16px] font-semibold">One simple loop</h2></div><p className="mt-1 text-[12px] text-muted-foreground">The same experience whether Kurukoo works digitally, physically or both.</p><div className="mt-5 grid grid-cols-2 border-l border-t border-border sm:grid-cols-4">{(overview?.executionLoop ?? Object.keys(loopLabels)).map((step, index, list) => <div key={step} className="border-b border-r border-border p-3"><span className="text-[10px] text-muted-foreground">0{index + 1}</span><p className="mt-1 text-[12px] font-medium">{loopLabels[step] ?? step}</p><p className="mt-1 text-[10px] text-muted-foreground">{index < list.length - 1 ? "next" : "outcome"}</p></div>)}</div></div><div className="border-l border-border pl-6"><div className="flex items-center gap-2"><FileCheck2 className="size-4" /><h2 className="text-[16px] font-semibold">Proof, not promises</h2></div><p className="mt-2 text-[12px] leading-5 text-muted-foreground">A request is only shown as complete when available evidence supports that state. Conversation, consent and evidence stay attached to the work.</p><div className="mt-5 space-y-3 text-[11.5px]"><div className="flex gap-2"><CheckCircle2 className="size-3.5 shrink-0" />Evidence stays with the request</div><div className="flex gap-2"><LockKeyhole className="size-3.5 shrink-0" />Consequential actions require consent</div><div className="flex gap-2"><MessageCircle className="size-3.5 shrink-0" />Context follows the work</div></div></div></section>
    <section className="border-t border-border py-8"><div className="mb-5"><h2 className="text-[16px] font-semibold">You choose the outcome. Kurukoo chooses the route.</h2><p className="mt-1 text-[12px] text-muted-foreground">You do not need to know which machinery is required.</p></div><div className="grid gap-px border border-border bg-border md:grid-cols-2 xl:grid-cols-4">{modes.map(mode => <Link key={mode.id} to="/chat" search={{ prompt: mode.prompt } as never} className="group bg-surface p-4 hover:bg-elevated"><div className="flex items-center justify-between"><span className="grid size-8 place-items-center border border-border"><Compass className="size-3.5" /></span><ArrowRight className="size-3.5 text-muted-foreground transition-transform group-hover:translate-x-0.5" /></div><h3 className="mt-4 text-[13px] font-semibold">{mode.title}</h3><p className="mt-1.5 text-[11.5px] leading-5 text-muted-foreground">{mode.description}</p></Link>)}</div></section>
    <section className="border-t border-border pt-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground">Everything around the work</p><h2 className="mt-1 text-[17px] font-semibold">Stay in control without managing the machinery.</h2></div><Link to="/chat" className="inline-flex items-center gap-2 bg-primary px-4 py-2.5 text-[12px] font-medium text-primary-foreground">Start something <ArrowRight className="size-3.5" /></Link></div><div className="mt-5 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{surfaces.map(surface => <Link key={surface.id} to={surface.path as never} className="bg-surface p-3.5 hover:bg-elevated"><p className="text-[12px] font-semibold">{surface.title}</p><p className="mt-1 text-[10.5px] leading-5 text-muted-foreground">{surface.description}</p></Link>)}</div></section>
  </div>;
}
