import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, CircleDot, Compass, FileCheck2, LockKeyhole, MessageCircle, Sparkles, Workflow } from "lucide-react";
import { useEffect, useState } from "react";
import { fetchExecutionOverview, type ExecutionMode, type ExecutionOverview, type ExecutionSurface } from "@/lib/execution-api";
import { useKurukoo } from "@/lib/kurukoo-store";
import { Panel } from "@/components/kurukoo/ui";

export const Route = createFileRoute("/work")({
  head: () => ({ meta: [{ title: "Work — Kurukoo" }, { name: "description", content: "Everything Kurukoo is doing, waiting on, and has completed." }] }),
  component: WorkPage,
});

const loopLabels: Record<string, string> = { tell: "Tell", understand: "Understand", find_or_plan: "Find / plan", choose: "Choose", approve: "Approve", do: "Do", show_proof: "Show proof", done: "Done" };
const fallbackModes: ExecutionMode[] = [
  { id: "digital", title: "Digital", description: "Websites, apps, forms, research, documents and supported digital services.", prompt: "Handle this digitally if you can." },
  { id: "physical", title: "Physical", description: "People, providers, businesses, deliveries, repairs and local services.", prompt: "Find the right real-world help for this." },
  { id: "hybrid", title: "Hybrid", description: "Combine digital actions with people, products, logistics or physical fulfilment.", prompt: "Work out the best digital and physical route." },
  { id: "assisted", title: "User-assisted", description: "Prepare the work and tell me exactly what you need from me before continuing.", prompt: "Prepare everything and tell me what you need from me." },
];
const fallbackSurfaces: ExecutionSurface[] = [
  { id: "assist", title: "Assist", path: "/chat", description: "Tell Kurukoo what needs doing." },
  { id: "discover", title: "Discover", path: "/explore", description: "Find people, places, products, services and opportunities." },
  { id: "work", title: "Work", path: "/work", description: "See everything Kurukoo is doing, waiting on or has completed." },
  { id: "memory", title: "Memory", path: "/memory", description: "Control the context Kurukoo remembers and uses." },
  { id: "trust", title: "Trust", path: "/safety", description: "Permissions, safety, verification, evidence and truthful outcomes." },
  { id: "connect", title: "Connect", path: "/connect", description: "Connect channels, tools, devices and external resources." },
];

function WorkPage() {
  const { work } = useKurukoo();
  const [overview, setOverview] = useState<ExecutionOverview | null>(null);
  useEffect(() => { void fetchExecutionOverview().then(setOverview); }, []);
  const active = work.filter(item => item.stage !== "done");
  const completed = work.filter(item => item.stage === "done");
  const needsYou = active.filter(item => item.stage === "needs_you");
  const modes = overview?.modes?.length ? overview.modes : fallbackModes;
  const surfaces = overview?.surfaceGroups?.length ? overview.surfaceGroups : fallbackSurfaces;

  return <div className="min-w-0 space-y-7 pb-10">
    <header className="max-w-4xl pt-3 md:pt-6"><div className="flex items-center gap-2 text-[10.5px] font-medium text-muted-foreground"><span className="grid size-2 rounded-full bg-[var(--color-success)]" /><span>{active.length ? `${active.length} ${active.length === 1 ? "piece" : "pieces"} of work in motion` : "Ready when you are"}</span></div><h1 className="mt-2 font-serif text-[40px] leading-[1.02] tracking-[-0.045em]">Work that moves.</h1><p className="mt-3 max-w-2xl text-[13px] leading-relaxed text-muted-foreground">This is where you see what Kurukoo is doing, what needs your decision, and what has actually happened. The mechanics stay out of your way.</p></header>

    {needsYou.length ? <section className="rounded-[20px] border border-primary/20 bg-brand-tint/10 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><LockKeyhole className="size-4 text-primary" /><p className="text-[13px] font-semibold">A decision is waiting for you</p></div><p className="mt-1 text-[11.5px] text-muted-foreground">Kurukoo has reached a consequential step. Review the request before anything moves forward.</p></div><Link to={(`/work/${needsYou[0].id}`) as never} className="inline-flex items-center gap-1.5 rounded-xl bg-primary px-3.5 py-2 text-[11.5px] font-medium text-primary-foreground">Review now <ArrowRight className="size-3.5" /></Link></div><div className="mt-4 grid gap-2">{needsYou.slice(0, 3).map(item => <Link key={item.id} to={(`/work/${item.id}`) as never} className="flex items-center gap-3 rounded-xl border border-primary/10 bg-surface/70 px-3 py-2.5 hover:bg-surface"><span className="grid size-7 place-items-center rounded-lg bg-elevated"><LockKeyhole className="size-3.5 text-primary" /></span><span className="min-w-0 flex-1 truncate text-[12px] font-medium">{item.title}</span><span className="text-[10px] text-muted-foreground">Needs you</span><ArrowRight className="size-3.5 text-muted-foreground" /></Link>)}</div></section> : null}

    <section className="grid gap-3 sm:grid-cols-3"><Panel className="p-4"><p className="text-[10.5px] text-muted-foreground">In motion</p><p className="mt-1 text-2xl font-semibold tracking-tight">{active.length}</p><p className="mt-1 text-[10.5px] text-muted-foreground">Work currently moving.</p></Panel><Panel className="p-4"><p className="text-[10.5px] text-muted-foreground">Your decisions</p><p className="mt-1 text-2xl font-semibold tracking-tight">{needsYou.length}</p><p className="mt-1 text-[10.5px] text-muted-foreground">Only the things that need you.</p></Panel><Panel className="p-4"><p className="text-[10.5px] text-muted-foreground">Outcomes</p><p className="mt-1 text-2xl font-semibold tracking-tight">{completed.length}</p><p className="mt-1 text-[10.5px] text-muted-foreground">Requests recorded as done.</p></Panel></section>

    {active.length ? <section className="space-y-3"><div className="flex items-end justify-between"><div><h2 className="text-[15px] font-semibold">In motion</h2><p className="mt-0.5 text-[11px] text-muted-foreground">Open any request for its live state, next step and evidence.</p></div><Link to="/chat" search={{ prompt: "Show me everything Kurukoo is working on" } as never} className="text-[11.5px] font-medium text-primary">Ask Kurukoo</Link></div><div className="grid gap-3 lg:grid-cols-2">{active.map(item => <Link key={item.id} to={(`/work/${item.id}`) as never} className="group rounded-[18px] border border-border bg-surface p-4 transition-[transform,background-color,border-color] hover:-translate-y-px hover:bg-elevated"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-brand-tint text-brand-ink">{item.stage === "needs_you" ? <LockKeyhole className="size-4" /> : <CircleDot className="size-4" />}</span><div className="min-w-0 flex-1"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><h3 className="text-[13.5px] font-semibold">{item.title}</h3><p className="mt-1 text-[11.5px] leading-relaxed text-muted-foreground">{item.detail}</p></div><ArrowRight className="size-4 shrink-0 text-muted-foreground transition group-hover:translate-x-0.5" /></div><div className="mt-3 flex items-center gap-2 text-[10.5px] text-muted-foreground"><span className="rounded-full bg-elevated px-2 py-1">{item.stage === "needs_you" ? "Needs you" : item.stage === "understanding" ? "Understanding" : "Working"}</span><span>{item.updated}</span></div></div></div></Link>)}</div></section> : <Panel className="p-10 text-center"><Sparkles className="mx-auto size-7 text-muted-foreground" /><h2 className="mt-3 text-[15px] font-semibold">Nothing needs your attention.</h2><p className="mx-auto mt-1 max-w-md text-[12px] text-muted-foreground">Start with an outcome and Kurukoo will work out the route.</p><Link to="/chat" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-[12px] font-medium text-primary-foreground">Tell Kurukoo what needs doing <ArrowRight className="size-3.5" /></Link></Panel>}

    <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><Panel className="overflow-hidden p-0"><div className="border-b border-border px-4 py-4"><div className="flex items-center gap-2"><Workflow className="size-4 text-muted-foreground" /><h2 className="text-[14px] font-semibold">One execution loop</h2></div><p className="mt-1 text-[11.5px] text-muted-foreground">One mental model, whether Kurukoo is working digitally, physically or both.</p></div><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4">{(overview?.executionLoop ?? Object.keys(loopLabels)).map((step, index, list) => <div key={step} className="bg-surface p-3"><span className="text-[10px] text-muted-foreground">0{index + 1}</span><p className="mt-1 text-[12px] font-medium">{loopLabels[step] ?? step}</p>{index < list.length - 1 ? <p className="mt-1 text-[10px] text-muted-foreground">→ next</p> : <p className="mt-1 text-[10px] text-muted-foreground">outcome</p>}</div>)}</div></Panel><Panel className="p-4"><div className="flex items-center gap-2"><FileCheck2 className="size-4 text-muted-foreground" /><h2 className="text-[14px] font-semibold">Proof, not promises</h2></div><p className="mt-2 text-[12px] leading-relaxed text-muted-foreground">A request is only shown as complete when the available evidence supports that state. A provider claim, indicative result or database row is never silently turned into a finished outcome.</p><div className="mt-4 grid gap-2 text-[11px]"><div className="flex items-center gap-2"><CheckCircle2 className="size-3.5" />Evidence stays attached to the work</div><div className="flex items-center gap-2"><LockKeyhole className="size-3.5" />Consent stays with consequential actions</div><div className="flex items-center gap-2"><MessageCircle className="size-3.5" />Conversation context follows the request</div></div></Panel></section>

    <section><div className="mb-3"><h2 className="text-[15px] font-semibold">How Kurukoo can act</h2><p className="text-[11.5px] text-muted-foreground">The route changes with the outcome. You don't have to choose the machinery.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{modes.map(mode => <Link key={mode.id} to="/chat" search={{ prompt: mode.prompt } as never} className="group rounded-[18px] border border-border bg-surface p-4 hover:bg-elevated"><div className="flex items-center justify-between"><span className="rounded-xl bg-elevated p-2"><Compass className="size-4" /></span><ArrowRight className="size-4 text-muted-foreground transition group-hover:translate-x-0.5" /></div><h3 className="mt-4 text-[13.5px] font-semibold">{mode.title}</h3><p className="mt-1 text-[11.5px] leading-relaxed text-muted-foreground">{mode.description}</p></Link>)}</div></section>

    <section className="rounded-[20px] border border-border bg-elevated/45 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Your control surface</p><h2 className="mt-1 text-[16px] font-semibold">Move from intention to outcome.</h2></div><Link to="/chat" className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-[12px] font-medium text-primary-foreground">Start something <ArrowRight className="size-3.5" /></Link></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{surfaces.map(surface => <Link key={surface.id} to={surface.path as never} className="rounded-xl border border-border bg-surface p-3 hover:bg-elevated"><p className="text-[12px] font-semibold">{surface.title}</p><p className="mt-1 text-[10.5px] leading-relaxed text-muted-foreground">{surface.description}</p></Link>)}</div></section>
  </div>;
}
