import { getCanonicalStore } from './canonicalStore.js';

export type AgentTraceKind =
  | 'goal_started'
  | 'plan_selected'
  | 'budget_checked'
  | 'budget_exhausted'
  | 'model_decision'
  | 'tool_requested'
  | 'tool_started'
  | 'tool_call'
  | 'tool_succeeded'
  | 'tool_failed'
  | 'policy_decision'
  | 'authorization'
  | 'capability_execution'
  | 'evidence'
  | 'quality_evaluated'
  | 'outcome'
  | 'notification'
  | 'continuation'
  | 'needs_user'
  | 'execution_stopped'
  | 'goal_completed'
  | 'goal_failed'
  | 'goal_cancelled';

export interface AgentExecutionTraceEvent {
  id?: number;
  ownerPhone: string;
  goalId?: string;
  conversationId?: string;
  kind: AgentTraceKind;
  actor?: string;
  status?: string;
  tool?: string;
  capability?: string;
  action?: string;
  canonicalObjectId?: string;
  reason?: string;
  evidence?: string;
  metadata?: Record<string, unknown>;
  /** Optional caller-supplied idempotency key. Duplicate keys are ignored. */
  idempotencyKey?: string;
  createdAt?: string;
}

export async function ensureAgentExecutionTraceSchema(): Promise<void> {
  const store = await getCanonicalStore();
  if (store.mode === 'postgres') {
    await store.run(`CREATE TABLE IF NOT EXISTS agent_execution_trace (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      owner_phone TEXT NOT NULL,
      goal_id TEXT,
      conversation_id TEXT,
      kind TEXT NOT NULL,
      actor TEXT,
      status TEXT,
      tool TEXT,
      capability TEXT,
      action TEXT,
      canonical_object_id TEXT,
      reason TEXT,
      evidence TEXT,
      metadata_json TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`);
  } else {
    await store.run(`CREATE TABLE IF NOT EXISTS agent_execution_trace (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      owner_phone TEXT NOT NULL,
      goal_id TEXT,
      conversation_id TEXT,
      kind TEXT NOT NULL,
      actor TEXT,
      status TEXT,
      tool TEXT,
      capability TEXT,
      action TEXT,
      canonical_object_id TEXT,
      reason TEXT,
      evidence TEXT,
      metadata_json TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`);
  }
  await store.run(`CREATE INDEX IF NOT EXISTS idx_agent_trace_owner_goal ON agent_execution_trace(owner_phone, goal_id, created_at DESC)`);
  await store.run(`CREATE INDEX IF NOT EXISTS idx_agent_trace_conversation ON agent_execution_trace(owner_phone, conversation_id, created_at DESC)`);
  try {
    await store.run(`ALTER TABLE agent_execution_trace ADD COLUMN idempotency_key TEXT`);
  } catch {
    /* column already exists */
  }
  await store.run(`CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_trace_idempotency ON agent_execution_trace(idempotency_key) WHERE idempotency_key IS NOT NULL`);
}

export async function recordAgentExecutionTrace(event: AgentExecutionTraceEvent): Promise<void> {
  if (!event.ownerPhone) throw new Error('ownerPhone is required');
  await ensureAgentExecutionTraceSchema();
  const store = await getCanonicalStore();
  await store.run(
    `INSERT INTO agent_execution_trace(
      owner_phone, goal_id, conversation_id, kind, actor, status, tool,
      capability, action, canonical_object_id, reason, evidence, metadata_json, idempotency_key, created_at
    ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT DO NOTHING`,
    [
      event.ownerPhone,
      event.goalId || null,
      event.conversationId || null,
      event.kind,
      event.actor || null,
      event.status || null,
      event.tool || null,
      event.capability || null,
      event.action || null,
      event.canonicalObjectId || null,
      event.reason || null,
      event.evidence || null,
      event.metadata ? JSON.stringify(event.metadata) : null,
      event.idempotencyKey || null,
      event.createdAt || new Date().toISOString(),
    ],
  );
}

export async function listAgentExecutionTrace(
  ownerPhone: string,
  goalId?: string,
  limit = 100,
): Promise<AgentExecutionTraceEvent[]> {
  if (!ownerPhone) return [];
  await ensureAgentExecutionTraceSchema();
  const store = await getCanonicalStore();
  const boundedLimit = Math.max(1, Math.min(500, Math.floor(limit)));
  const rows = goalId
    ? await store.all<any>(
        `SELECT * FROM agent_execution_trace WHERE owner_phone=? AND goal_id=? ORDER BY id ASC LIMIT ?`,
        [ownerPhone, goalId, boundedLimit],
      )
    : await store.all<any>(
        `SELECT * FROM agent_execution_trace WHERE owner_phone=? ORDER BY id DESC LIMIT ?`,
        [ownerPhone, boundedLimit],
      );
  return rows.map((row) => {
    let metadata: Record<string, unknown> | undefined;
    if (row.metadata_json) {
      try {
        const parsed = JSON.parse(String(row.metadata_json));
        if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) metadata = parsed;
      } catch {
        metadata = undefined;
      }
    }
    return {
      id: Number(row.id),
      ownerPhone: String(row.owner_phone),
      goalId: row.goal_id ? String(row.goal_id) : undefined,
      conversationId: row.conversation_id ? String(row.conversation_id) : undefined,
      kind: String(row.kind) as AgentTraceKind,
      actor: row.actor ? String(row.actor) : undefined,
      status: row.status ? String(row.status) : undefined,
      tool: row.tool ? String(row.tool) : undefined,
      capability: row.capability ? String(row.capability) : undefined,
      action: row.action ? String(row.action) : undefined,
      canonicalObjectId: row.canonical_object_id ? String(row.canonical_object_id) : undefined,
      reason: row.reason ? String(row.reason) : undefined,
      evidence: row.evidence ? String(row.evidence) : undefined,
      metadata,
      createdAt: row.created_at ? String(row.created_at) : undefined,
    };
  });
}
