/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
export const CANONICAL_URLS = {
  public: {
    home: '/',
    features: '/features',
    explore: '/explore',
    discover: '/discover',
    network: '/network',
    channels: '/channels',
    topics: '/topics',
    resources: '/resources',
    howItWorks: '/how-it-works',
    about: '/about',
    help: '/help',
    contact: '/contact',
    pricing: '/pricing',
    partners: '/partners',
    advertise: '/advertise',
    careers: '/careers',
    blog: '/blog',
    developers: '/developers',
    legal: '/legal',
    cookies: '/cookies',
  },
  auth: {
    login: '/login',
    signup: '/signup',
  },
  conversation: {
    agent: '/chat',
    conversation: (conversationId: string) => `/chat/${encodeURIComponent(conversationId)}`,
    share: (shareId: string) => `/share/${encodeURIComponent(shareId)}`,
  },
  desk: {
    home: '/home',
    discover: '/explore',
    topics: '/topics',
    requests: '/activity',
    request: (requestId: string) => `/activity/${encodeURIComponent(requestId)}`,
    reminders: '/reminders',
    reminder: (reminderId: string) => `/reminders/${encodeURIComponent(reminderId)}`,
    saved: '/saved',
    cart: '/cart',
    tasks: '/work',
    task: (taskId: string) => `/tasks/${encodeURIComponent(taskId)}`,
    connect: '/connect',
    connection: (connectionId: string) => `/connections/${encodeURIComponent(connectionId)}`,
    agents: '/agents',
    agent: (agentId: string) => `/agents/${encodeURIComponent(agentId)}`,
    capabilities: '/capabilities',
    opportunities: '/opportunities',
    opportunity: (opportunityId: string) => `/opportunities/${encodeURIComponent(opportunityId)}`,
    wallet: '/wallet',
    points: '/points',
    topUp: '/top-up',
    subscriptions: '/subscriptions',
    checkout: '/checkout',
    confirmations: '/confirmations',
    memory: '/memory',
    memoryItem: (memoryId: string) => `/memory/${encodeURIComponent(memoryId)}`,
    artifacts: '/artifacts',
    artifact: (artifactId: string) => `/artifacts/${encodeURIComponent(artifactId)}`,
    notifications: '/notifications',
    safety: '/safety',
    call: '/call',
    prayer: '/prayer',
    settings: '/settings',
  },
  admin: {
    home: '/admin',
    conversations: '/admin/conversations',
    providers: '/admin/providers',
    requests: '/admin/requests',
    orders: '/admin/orders',
    moderation: '/admin/moderation',
    compliance: '/admin/compliance',
    notifications: '/admin/notifications',
    integrations: '/admin/integrations',
    agents: '/admin/agents',
    users: '/admin/users',
    pricing: '/admin/pricing',
    referrals: '/admin/referrals',
    commissions: '/admin/commissions',
    partnerships: '/admin/partnerships',
    trust: '/admin/trust',
    social: '/admin/social',
    creators: '/admin/creators',
    celebrity: '/admin/celebrity',
    analytics: '/admin/analytics',
    revenue: '/admin/revenue',
    marketing: '/admin/marketing',
    advertising: '/admin/advertising',
    content: '/admin/content',
    curation: '/admin/curation',
    settings: '/admin/settings',
    seo: '/admin/seo',
    roadmap: '/admin/roadmap',
    user: (userId: string) => `/admin/users/${encodeURIComponent(userId)}`,
    provider: (providerId: string) => `/admin/providers/${encodeURIComponent(providerId)}`,
    request: (requestId: string) => `/admin/requests/${encodeURIComponent(requestId)}`,
    conversation: (conversationId: string) => `/admin/conversations/${encodeURIComponent(conversationId)}`,
    agent: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}`,
  },
  api: {
    root: '/api/v1',
  },
  infrastructure: {
    health: '/health',
    ready: '/ready',
    live: '/live',
  },
} as const;
