export const CANONICAL_URLS = {
  public: {
    home: '/',
    features: '/features',
    explore: '/explore',
    discover: '/discover',
    network: '/network',
    channels: '/channels',
    topics: '/topics',
    resources: '/resources',
    howItWorks: '/how-it-works',
    about: '/about',
    help: '/help',
    contact: '/contact',
    pricing: '/pricing',
    partners: '/partners',
    advertise: '/advertise',
    careers: '/careers',
    blog: '/blog',
    developers: '/developers',
    legal: '/legal',
    cookies: '/cookies',
  },
  auth: {
    login: '/login',
    signup: '/signup',
  },
  conversation: {
    agent: '/chat',
    conversation: (conversationId: string) => `/chat/${encodeURIComponent(conversationId)}`,
    share: (shareId: string) => `/share/${encodeURIComponent(shareId)}`,
  },
  desk: {
    home: '/desk',
    discover: '/discover',
    topics: '/topics',
    requests: '/requests',
    request: (requestId: string) => `/requests/${encodeURIComponent(requestId)}`,
    reminders: '/reminders',
    reminder: (reminderId: string) => `/reminders/${encodeURIComponent(reminderId)}`,
    saved: '/saved',
    cart: '/cart',
    tasks: '/tasks',
    task: (taskId: string) => `/tasks/${encodeURIComponent(taskId)}`,
    connect: '/connect',
    connection: (connectionId: string) => `/connections/${encodeURIComponent(connectionId)}`,
    agents: '/agents',
    agent: (agentId: string) => `/agents/${encodeURIComponent(agentId)}`,
    capabilities: '/capabilities',
    opportunities: '/opportunities',
    opportunity: (opportunityId: string) => `/opportunities/${encodeURIComponent(opportunityId)}`,
    wallet: '/wallet',
    points: '/points',
    topUp: '/top-up',
    subscriptions: '/subscriptions',
    checkout: '/checkout',
    confirmations: '/confirmations',
    memory: '/memory',
    memoryItem: (memoryId: string) => `/memory/${encodeURIComponent(memoryId)}`,
    artifacts: '/artifacts',
    artifact: (artifactId: string) => `/artifacts/${encodeURIComponent(artifactId)}`,
    notifications: '/notifications',
    safety: '/safety',
    call: '/call',
    prayer: '/prayer',
    settings: '/settings',
  },
  admin: {
    home: '/admin',
    conversations: '/admin/conversations',
    providers: '/admin/providers',
    requests: '/admin/requests',
    orders: '/admin/orders',
    moderation: '/admin/moderation',
    compliance: '/admin/compliance',
    notifications: '/admin/notifications',
    integrations: '/admin/integrations',
    agents: '/admin/agents',
    users: '/admin/users',
    pricing: '/admin/pricing',
    referrals: '/admin/referrals',
    commissions: '/admin/commissions',
    partnerships: '/admin/partnerships',
    trust: '/admin/trust',
    social: '/admin/social',
    creators: '/admin/creators',
    celebrity: '/admin/celebrity',
    analytics: '/admin/analytics',
    revenue: '/admin/revenue',
    marketing: '/admin/marketing',
    advertising: '/admin/advertising',
    content: '/admin/content',
    curation: '/admin/curation',
    settings: '/admin/settings',
    seo: '/admin/seo',
    roadmap: '/admin/roadmap',
    user: (userId: string) => `/admin/users/${encodeURIComponent(userId)}`,
    provider: (providerId: string) => `/admin/providers/${encodeURIComponent(providerId)}`,
    request: (requestId: string) => `/admin/requests/${encodeURIComponent(requestId)}`,
    conversation: (conversationId: string) => `/admin/conversations/${encodeURIComponent(conversationId)}`,
    agent: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}`,
  },
  api: {
    root: '/api/v1',
  },
  infrastructure: {
    health: '/health',
    ready: '/ready',
    live: '/live',
  },
} as const;

export const LEGACY_URL_ALIASES = {
  '/app': CANONICAL_URLS.desk.home,
  '/app/agent': CANONICAL_URLS.conversation.agent,
  '/app/discover': CANONICAL_URLS.desk.discover,
  '/app/topics': CANONICAL_URLS.desk.topics,
  '/app/requests': CANONICAL_URLS.desk.requests,
  '/app/reminders': CANONICAL_URLS.desk.reminders,
  '/app/saved': CANONICAL_URLS.desk.saved,
  '/app/cart': CANONICAL_URLS.desk.cart,
  '/app/tasks': CANONICAL_URLS.desk.tasks,
  '/app/connect': CANONICAL_URLS.desk.connect,
  '/app/agents': CANONICAL_URLS.desk.agents,
  '/app/capabilities': CANONICAL_URLS.desk.capabilities,
  '/app/opportunities': CANONICAL_URLS.desk.opportunities,
  '/app/wallet': CANONICAL_URLS.desk.wallet,
  '/app/points': CANONICAL_URLS.desk.points,
  '/app/top-up': CANONICAL_URLS.desk.topUp,
  '/app/subscriptions': CANONICAL_URLS.desk.subscriptions,
  '/app/checkout': CANONICAL_URLS.desk.checkout,
  '/app/confirmations': CANONICAL_URLS.desk.confirmations,
  '/app/memory': CANONICAL_URLS.desk.memory,
  '/app/artifacts': CANONICAL_URLS.desk.artifacts,
  '/app/prayer': CANONICAL_URLS.desk.prayer,
  '/app/call': CANONICAL_URLS.desk.call,
  '/app/notifications': CANONICAL_URLS.desk.notifications,
  '/app/safety': CANONICAL_URLS.desk.safety,
  '/web': CANONICAL_URLS.desk.home,
  '/workspace': CANONICAL_URLS.desk.home,
  '/subscription': CANONICAL_URLS.desk.subscriptions,
  '/confirmation': CANONICAL_URLS.desk.confirmations,
} as const;

export function canonicalizeUrl(pathname: string): string {
  return LEGACY_URL_ALIASES[pathname as keyof typeof LEGACY_URL_ALIASES] ?? pathname;
}
