import { createRequire } from 'node:module';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { getDb, saveDb } from '../database.js';
import { createPostgresPersistence, type PostgresPersistence } from './postgresPersistence.js';
const require = createRequire(import.meta.url); let postgresOwner: PostgresPersistence | null = null;
type S={bind:(p?:unknown[])=>void;step:()=>boolean;getAsObject:()=>Record<string,unknown>;free:()=>void}; type D={prepare:(s:string)=>S;run:(s:string,p?:unknown[])=>void;exec:(s:string)=>Array<{columns:string[];values:unknown[][]}>};
export interface CanonicalStore{readonly mode:'sqljs'|'postgres';all<T=Record<string,unknown>>(sql:string,p?:unknown[]):Promise<T[]>;one<T=Record<string,unknown>>(sql:string,p?:unknown[]):Promise<T|undefined>;run(sql:string,p?:unknown[]):Promise<{rowCount:number}>;insert<T=Record<string,unknown>>(sql:string,p?:unknown[]):Promise<T|undefined>;transaction<T>(fn:(tx:CanonicalStore)=>Promise<T>):Promise<T>;close():Promise<void>}
function pgSql(s:string){let o='',n=0,q:string|null=null;for(let i=0;i<s.length;i++){const c=s[i];if(q){o+=c;if(c===q){if(s[i+1]===c&&q!== '`')o+=s[++i];else q=null}continue}if(c==="'"){q="'";o+=c}else if(c==='"'){q='"';o+=c}else if(c==='`'){q='`';o+=c}else if(c==='?')o+=`$${++n}`;else o+=c}return o}
function sqljs(db:D):CanonicalStore{return{mode:'sqljs',async all<T=Record<string,unknown>>(s:string,p:unknown[]=[]){const st=db.prepare(s);try{st.bind(p);const r:T[]=[];while(st.step())r.push(st.getAsObject() as T);return r}finally{st.free()}},async one<T=Record<string,unknown>>(s:string,p:unknown[]=[]){return(await this.all<T>(s,p))[0]},async run(s:string,p:unknown[]=[]){db.run(s,p);let c=0;try{c=Number(db.exec('SELECT changes() AS count')?.[0]?.values?.[0]?.[0]||0)}catch{}saveDb();return{rowCount:c}},async insert<T=Record<string,unknown>>(s:string,p:unknown[]=[]){const st=db.prepare(s);try{st.bind(p);if(!st.step())return;return st.getAsObject() as T}finally{st.free();saveDb()}},async transaction<T>(fn:(tx:CanonicalStore)=>Promise<T>){db.run('BEGIN');try{const r=await fn(sqljs(db));db.run('COMMIT');saveDb(true);return r}catch(e){try{db.run('ROLLBACK')}catch{}throw e}},async close(){saveDb(true)}}}
function postgres(sql:any):CanonicalStore{return{mode:'postgres',async all<T=Record<string,unknown>>(s:string,p:unknown[]=[]){return sql.unsafe(pgSql(s),p) as Promise<T[]>},async one<T=Record<string,unknown>>(s:string,p:unknown[]=[]){const r:any=await sql.unsafe(pgSql(s),p);return r[0] as T|undefined},async run(s:string,p:unknown[]=[]){const r:any=await sql.unsafe(pgSql(s),p);return{rowCount:Number(r?.count??r?.length??0)}},async insert<T=Record<string,unknown>>(s:string,p:unknown[]=[]){const r:any=await sql.unsafe(pgSql(s),p);return r[0] as T|undefined},async transaction<T>(fn:(tx:CanonicalStore)=>Promise<T>){return sql.begin((tx:any)=>fn(postgres(tx)))},async close(){await closeCanonicalStore()}}}
function owner(env:NodeJS.ProcessEnv){if(!postgresOwner)postgresOwner=createPostgresPersistence(env);return postgresOwner}
export async function getCanonicalStore(env:NodeJS.ProcessEnv=process.env){return getCanonicalPersistenceMode(env)==='postgres'?postgres(owner(env).sql):sqljs(await getDb() as D)}
export async function closeCanonicalStore(){if(!postgresOwner)return;const p=postgresOwner;postgresOwner=null;await p.close()}
export function canonicalStoreUsesPostgres(env:NodeJS.ProcessEnv=process.env){return getCanonicalPersistenceMode(env)==='postgres'}
export function assertPostgresSql(s:string){if(/\bINSERT\s+OR\s+(REPLACE|IGNORE)\b/i.test(s)||/\bAUTOINCREMENT\b/i.test(s))throw new Error(`PostgreSQL canonical persistence rejected SQLite-only SQL: ${s}`)}
export function normalizeCanonicalSql(s:string){assertPostgresSql(s);return s}
export function isCanonicalStoreAvailable(env:NodeJS.ProcessEnv=process.env){if(getCanonicalPersistenceMode(env)==='sqljs')return true;try{require('postgres');return Boolean(String(env.DATABASE_URL||env.POSTGRES_URL||'').trim())}catch{return false}}
