import crypto from 'node:crypto';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { getCanonicalStore } from './canonicalStore.js';

export type DurableJobStatus = 'queued' | 'running' | 'completed' | 'failed' | 'dead_letter' | 'cancelled';
export interface DurableJob { id:string; kind:string; payload:Record<string,unknown>; status:DurableJobStatus; attempts:number; maxAttempts:number; availableAt:string; lockedUntil?:string; lockedBy?:string; lastError?:string; createdAt:string; updatedAt:string; completedAt?:string; }
let schemaPromise:Promise<void>|null=null;
async function ensureSchema(){if(schemaPromise)return schemaPromise;schemaPromise=(async()=>{const store=await getCanonicalStore();await store.run(`CREATE TABLE IF NOT EXISTS durable_jobs (id TEXT PRIMARY KEY, kind TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'queued', attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 5, available_at TEXT NOT NULL, locked_until TEXT, locked_by TEXT, last_error TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TEXT)`);await store.run(`CREATE INDEX IF NOT EXISTS idx_durable_jobs_claim ON durable_jobs(status, available_at, locked_until)`);await store.run(`CREATE INDEX IF NOT EXISTS idx_durable_jobs_kind ON durable_jobs(kind, created_at DESC)`);})().catch(e=>{schemaPromise=null;throw e});return schemaPromise;}
function json(v:unknown){const raw=JSON.stringify(v??{});return raw.length>32000?`${raw.slice(0,32000)}...`:raw;}
function isoAfterMs(ms:number){return new Date(Date.now()+Math.max(0,ms)).toISOString();}
function parseJson(v:unknown){try{const p=JSON.parse(String(v||'{}'));return p&&typeof p==='object'&&!Array.isArray(p)?p as Record<string,unknown>:{};}catch{return {};}}
function mapRow(r:any):DurableJob{return{id:String(r.id),kind:String(r.kind),payload:parseJson(r.payload_json),status:String(r.status) as DurableJobStatus,attempts:Number(r.attempts||0),maxAttempts:Number(r.max_attempts||5),availableAt:String(r.available_at),lockedUntil:r.locked_until?String(r.locked_until):undefined,lockedBy:r.locked_by?String(r.locked_by):undefined,lastError:r.last_error?String(r.last_error):undefined,createdAt:String(r.created_at),updatedAt:String(r.updated_at),completedAt:r.completed_at?String(r.completed_at):undefined};}

export async function enqueueDurableJob(input:{kind:string;payload?:Record<string,unknown>;delayMs?:number;maxAttempts?:number;id?:string}):Promise<string>{await ensureSchema();const id=input.id||crypto.randomUUID();const kind=String(input.kind||'').trim().slice(0,120);if(!kind)throw new Error('durable job kind is required');const store=await getCanonicalStore();const sql=getCanonicalPersistenceMode()==='postgres'?`INSERT INTO durable_jobs(id,kind,payload_json,status,attempts,max_attempts,available_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`:`INSERT OR IGNORE INTO durable_jobs(id,kind,payload_json,status,attempts,max_attempts,available_at) VALUES(?,?,?,?,?,?,?)`;await store.run(sql,[id,kind,json(input.payload),'queued',0,Math.max(1,Math.min(50,Math.floor(Number(input.maxAttempts)||5))),isoAfterMs(Number(input.delayMs)||0)]);return id;}
export async function claimDurableJob(workerId:string,kinds?:string[],leaseMs=120000):Promise<DurableJob|null>{await ensureSchema();const store=await getCanonicalStore();const now=new Date().toISOString();const safeLease=Math.max(5000,Math.min(15*60*1000,Math.floor(Number(leaseMs)||120000)));const kindList=(kinds||[]).map(String).map(v=>v.trim()).filter(Boolean).slice(0,20);return store.transaction(async tx=>{const where=kindList.length?` AND kind IN (${kindList.map(()=>'?').join(',')})`:'';const row=await tx.one<any>(`SELECT * FROM durable_jobs WHERE status='queued' AND available_at<=? AND (locked_until IS NULL OR locked_until<=?)${where} ORDER BY available_at ASC, created_at ASC LIMIT 1`,[now,now,...kindList]);if(!row)return null;const id=String(row.id);const updated=await tx.run(`UPDATE durable_jobs SET status='running',attempts=attempts+1,locked_until=?,locked_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='queued' AND (locked_until IS NULL OR locked_until<=?)`,[isoAfterMs(safeLease),String(workerId).slice(0,160),id,now]);if(updated.rowCount!==1)return null;const record=await tx.one<any>(`SELECT * FROM durable_jobs WHERE id=? LIMIT 1`,[id]);return record?mapRow(record):null;});}
async function mutateLocked(jobId:string,workerId:string,sql:string,params:unknown[]){await ensureSchema();const store=await getCanonicalStore();return (await store.run(sql,[...params,jobId,workerId])).rowCount===1;}
export async function completeDurableJob(jobId:string,workerId:string){return mutateLocked(jobId,workerId,`UPDATE durable_jobs SET status='completed',locked_until=NULL,locked_by=NULL,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND locked_by=? AND status='running'`,[]);}
export async function failDurableJob(job:Pick<DurableJob,'id'|'attempts'|'maxAttempts'>,workerId:string,error:unknown,retryDelayMs?:number):Promise<DurableJobStatus>{await ensureSchema();const store=await getCanonicalStore();const message=String(error instanceof Error?error.message:error).slice(0,1000)||'job failed';const terminal=job.attempts>=job.maxAttempts;const status:DurableJobStatus=terminal?'dead_letter':'queued';const availableAt=terminal?new Date().toISOString():isoAfterMs(retryDelayMs??Math.min(60*60*1000,5000*(2**Math.min(Math.max(job.attempts-1,0),7))));const updated=await store.run(`UPDATE durable_jobs SET status=?,available_at=?,locked_until=NULL,locked_by=NULL,last_error=?,updated_at=CURRENT_TIMESTAMP,completed_at=CASE WHEN ?='dead_letter' THEN COALESCE(completed_at,CURRENT_TIMESTAMP) ELSE completed_at END WHERE id=? AND locked_by=? AND status='running'`,[status,availableAt,message,status,job.id,workerId]);return updated.rowCount===1?status:'failed';}
export async function cancelDurableJob(jobId:string){await ensureSchema();const store=await getCanonicalStore();return (await store.run(`UPDATE durable_jobs SET status='cancelled',locked_until=NULL,locked_by=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status IN ('queued','running')`,[jobId])).rowCount===1;}
export async function releaseExpiredDurableJobLeases(){await ensureSchema();const store=await getCanonicalStore();const sql=getCanonicalPersistenceMode()==='postgres'?`UPDATE durable_jobs SET status='queued',locked_until=NULL,locked_by=NULL,available_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE status='running' AND locked_until IS NOT NULL AND locked_until<=CURRENT_TIMESTAMP`:`UPDATE durable_jobs SET status='queued',locked_until=NULL,locked_by=NULL,available_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE status='running' AND locked_until IS NOT NULL AND julianday(locked_until)<=julianday('now')`;return (await store.run(sql)).rowCount;}
export async function getDurableJobStats(){await ensureSchema();const store=await getCanonicalStore();const stats:Record<DurableJobStatus,number>={queued:0,running:0,completed:0,failed:0,dead_letter:0,cancelled:0};for(const row of await store.all<any>('SELECT status, COUNT(*) AS count FROM durable_jobs GROUP BY status')){const status=String(row.status) as DurableJobStatus;if(status in stats)stats[status]=Number(row.count||0);}return stats;}
export async function getDurableJob(jobId:string){await ensureSchema();const store=await getCanonicalStore();const row=await store.one<any>('SELECT * FROM durable_jobs WHERE id=? LIMIT 1',[String(jobId)]);return row?mapRow(row):null;}
