import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import { getDb, saveDb } from '../database.js';
import { requestPhoneOtp, verifyPhoneOtp, normalizeOtpPhone } from './otpAuthService.js';
import { listUniversalCapabilities } from './universalCapabilityProtocol.js';
import { executeCanonicalCapabilityProposal } from './canonicalCapabilityExecutor.js';
import { getAgentGoal } from './agentRuntime.js';
import { getEconomicRequest } from './skillFlows.js';
import { getInternalNotificationById } from './pushNotifications.js';

export const MCP_SCOPES = ['kurukoo.read', 'kurukoo.act', 'kurukoo.write', 'kurukoo.execute'] as const;
export type McpScope = typeof MCP_SCOPES[number];

const AUTH_CODE_TTL_MS = 5 * 60 * 1000;
const ACCESS_TTL_MS = Math.max(300, Number(process.env.KURUKOO_MCP_ACCESS_TOKEN_TTL_SECONDS || 3600)) * 1000;
const REFRESH_TTL_MS = Math.max(3600, Number(process.env.KURUKOO_MCP_REFRESH_TOKEN_TTL_SECONDS || 7_776_000)) * 1000;

function issuer(): string {
  const configured = String(process.env.KURUKOO_MCP_ISSUER || '').trim().replace(/\/$/, '');
  if (!configured) throw new Error('KURUKOO_MCP_ISSUER must be configured for the remote MCP integration');
  if (process.env.NODE_ENV === 'production' && !configured.startsWith('https://')) throw new Error('KURUKOO_MCP_ISSUER must use HTTPS in production');
  return configured;
}
function oauthSecret(): string {
  const configured = String(process.env.KURUKOO_MCP_OAUTH_SECRET || process.env.JWT_SECRET || '').trim();
  if (configured.length < 32) throw new Error('KURUKOO_MCP_OAUTH_SECRET or JWT_SECRET must be at least 32 characters');
  return configured;
}
function hash(value: string): string { return crypto.createHash('sha256').update(value).digest('hex'); }
function randomToken(prefix: string): string { return `${prefix}_${crypto.randomBytes(36).toString('base64url')}`; }
function ensureString(value: unknown, fallback = ''): string { return String(value ?? fallback).trim(); }

async function ensureMcpSchema(): Promise<void> {
  const db = await getDb();
  db.run(`CREATE TABLE IF NOT EXISTS mcp_oauth_transactions(id TEXT PRIMARY KEY,client_id TEXT NOT NULL,redirect_uri TEXT NOT NULL,response_type TEXT NOT NULL,scope TEXT NOT NULL,state TEXT,code_challenge TEXT,code_challenge_method TEXT,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,user_phone TEXT,consented INTEGER NOT NULL DEFAULT 0,consumed_at TEXT);
  CREATE INDEX IF NOT EXISTS idx_mcp_oauth_tx_expires ON mcp_oauth_transactions(expires_at);
  CREATE TABLE IF NOT EXISTS mcp_authorization_codes(code_hash TEXT PRIMARY KEY,client_id TEXT NOT NULL,redirect_uri TEXT NOT NULL,scope TEXT NOT NULL,user_phone TEXT NOT NULL,code_challenge TEXT,code_challenge_method TEXT,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,consumed_at TEXT);
  CREATE INDEX IF NOT EXISTS idx_mcp_auth_codes_expiry ON mcp_authorization_codes(expires_at);
  CREATE TABLE IF NOT EXISTS mcp_refresh_tokens(token_hash TEXT PRIMARY KEY,family_id TEXT NOT NULL,client_id TEXT NOT NULL,scope TEXT NOT NULL,user_phone TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,revoked_at TEXT);
  CREATE INDEX IF NOT EXISTS idx_mcp_refresh_family ON mcp_refresh_tokens(family_id,revoked_at,expires_at);
  CREATE TABLE IF NOT EXISTS mcp_access_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,user_phone TEXT NOT NULL,client_id TEXT NOT NULL,tool_name TEXT,action TEXT,scope TEXT,outcome TEXT,metadata_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
  saveDb();
}
function configuredClientOk(clientId: string, clientSecret?: string): boolean {
  const expectedId = String(process.env.KURUKOO_MCP_CLIENT_ID || '');
  if (!expectedId) return true;
  if (clientId !== expectedId) return false;
  const expectedSecret = String(process.env.KURUKOO_MCP_CLIENT_SECRET || '');
  if (!expectedSecret) return true;
  const presented = String(clientSecret || '');
  if (presented.length !== expectedSecret.length) return false;
  return crypto.timingSafeEqual(Buffer.from(expectedSecret), Buffer.from(presented));
}
function validateRedirectUri(clientId: string, redirectUri: string): boolean {
  const configured = String(process.env.KURUKOO_MCP_REDIRECT_URIS || '').split(',').map(v => v.trim()).filter(Boolean);
  if (configured.length) return configured.includes(redirectUri);
  if (String(process.env.KURUKOO_MCP_CLIENT_ID || '')) return clientId === String(process.env.KURUKOO_MCP_CLIENT_ID || '') && /^https:\/\//i.test(redirectUri);
  return /^https:\/\//i.test(redirectUri);
}
function validateScope(scope: string): string[] {
  const requested = scope.split(/[\s,]+/).map(v => v.trim()).filter(Boolean);
  const invalid = requested.filter(v => !(MCP_SCOPES as readonly string[]).includes(v));
  if (invalid.length) throw new Error(`Unsupported scope: ${invalid.join(', ')}`);
  return [...new Set(requested.length ? requested : ['kurukoo.read'])];
}
function scopeAllows(scopes: string[], required: McpScope): boolean { return scopes.includes(required) || (required === 'kurukoo.act' && scopes.includes('kurukoo.write')) || (required === 'kurukoo.write' && scopes.includes('kurukoo.act')); }
export function mcpEnabled(): boolean { return process.env.KURUKOO_MCP_ENABLED === 'true' || (process.env.NODE_ENV !== 'production' && process.env.KURUKOO_MCP_ENABLED !== 'false'); }
export function getMcpMetadata() { const base = issuer(); return { issuer:base, authorization_endpoint:`${base}/oauth/authorize`, token_endpoint:`${base}/oauth/token`, revocation_endpoint:`${base}/oauth/revoke`, response_types_supported:['code'], grant_types_supported:['authorization_code','refresh_token'], code_challenge_methods_supported:['S256'], token_endpoint_auth_methods_supported:['none','client_secret_post'], scopes_supported:[...MCP_SCOPES], service_documentation:`${base}/docs/CHATGPT_KURUKOO_APP.md`, client_id_metadata_document_supported:true }; }
export function getProtectedResourceMetadata() { const base = issuer(); return { resource:`${base}/mcp`, authorization_servers:[base], scopes_supported:[...MCP_SCOPES], bearer_methods_supported:['header'] }; }
export function beginAuthorization(params:{clientId:string;redirectUri:string;responseType:string;scope:string;state?:string;codeChallenge?:string;codeChallengeMethod?:string}):{transactionId:string;scopes:string[]} {
  if (!configuredClientOk(params.clientId)) throw new Error('Unknown OAuth client');
  if (params.responseType !== 'code') throw new Error('Only response_type=code is supported');
  if (!validateRedirectUri(params.clientId, params.redirectUri)) throw new Error('Unregistered redirect_uri');
  const scopes = validateScope(params.scope);
  if (params.codeChallengeMethod && params.codeChallengeMethod !== 'S256') throw new Error('Only PKCE S256 is supported');
  if (params.codeChallengeMethod === 'S256' && !params.codeChallenge) throw new Error('code_challenge is required when using S256');
  const transactionId = `mcp_tx_${crypto.randomUUID()}`; const createdAt = new Date().toISOString(); const expiresAt = new Date(Date.now()+AUTH_CODE_TTL_MS).toISOString();
  void getDb().then(db => { db.run('INSERT INTO mcp_oauth_transactions(id,client_id,redirect_uri,response_type,scope,state,code_challenge,code_challenge_method,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?)',[transactionId,params.clientId,params.redirectUri,params.responseType,scopes.join(' '),params.state||null,params.codeChallenge||null,params.codeChallengeMethod||null,createdAt,expiresAt]); saveDb(); });
  return { transactionId, scopes };
}
export async function getAuthorizationTransaction(id:string):Promise<any|null>{ await ensureMcpSchema(); const db=await getDb(); const row=db.exec('SELECT * FROM mcp_oauth_transactions WHERE id=? LIMIT 1',[id])[0]?.values?.[0] as any[]|undefined; if(!row)return null; const tx={id:String(row[0]),clientId:String(row[1]),redirectUri:String(row[2]),responseType:String(row[3]),scope:String(row[4]),state:row[5]?String(row[5]):undefined,codeChallenge:row[6]?String(row[6]):undefined,codeChallengeMethod:row[7]?String(row[7]):undefined,createdAt:String(row[8]),expiresAt:String(row[9]),userPhone:row[10]?String(row[10]):undefined,consented:Boolean(Number(row[11])),consumedAt:row[12]?String(row[12]):undefined}; if(new Date(tx.expiresAt).getTime()<=Date.now()||tx.consumedAt)return null; return tx; }
export async function attachAuthorizationUser(transactionId:string,phoneInput:string):Promise<void>{ await ensureMcpSchema(); const phone=normalizeOtpPhone(phoneInput); const db=await getDb(); db.run('UPDATE mcp_oauth_transactions SET user_phone=?, consented=1 WHERE id=? AND expires_at>CURRENT_TIMESTAMP AND consumed_at IS NULL',[phone,transactionId]); saveDb(); }
export async function requestAuthorizationOtp(transactionId:string,phoneInput:string):Promise<any>{ const tx=await getAuthorizationTransaction(transactionId); if(!tx)throw new Error('Authorization request expired or not found'); const phone=normalizeOtpPhone(phoneInput); const result=await requestPhoneOtp(phone); return {...result,phone}; }
export async function verifyAuthorizationOtp(transactionId:string,phoneInput:string,code:string):Promise<{redirectUri:string;state?:string;code:string;scopes:string[]}>{ const tx=await getAuthorizationTransaction(transactionId); if(!tx)throw new Error('Authorization request expired or not found'); const verification=await verifyPhoneOtp(phoneInput,code); if(!verification.success||!verification.phone)throw new Error(verification.message); const phone=verification.phone; await attachAuthorizationUser(transactionId,phone); return finalizeAuthorization(tx.id,phone); }
export async function approveAuthorization(transactionId:string,phone:string):Promise<{redirectUri:string;state?:string;code:string;scopes:string[]}>{ const tx=await getAuthorizationTransaction(transactionId); if(!tx)throw new Error('Authorization request expired or not found'); await attachAuthorizationUser(transactionId,phone); return finalizeAuthorization(transactionId,normalizeOtpPhone(phone)); }
async function finalizeAuthorization(transactionId:string,phone:string):Promise<{redirectUri:string;state?:string;code:string;scopes:string[]}>{ const tx=await getAuthorizationTransaction(transactionId); if(!tx||tx.userPhone!==phone||!tx.consented)throw new Error('Authorization has not been completed'); await ensureMcpSchema(); const rawCode=randomToken('mcpcode'); const db=await getDb(); db.run('INSERT INTO mcp_authorization_codes(code_hash,client_id,redirect_uri,scope,user_phone,code_challenge,code_challenge_method,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?)',[hash(rawCode),tx.clientId,tx.redirectUri,tx.scope,phone,tx.codeChallenge||null,tx.codeChallengeMethod||null,new Date().toISOString(),new Date(Date.now()+AUTH_CODE_TTL_MS).toISOString()]); db.run('UPDATE mcp_oauth_transactions SET consumed_at=CURRENT_TIMESTAMP WHERE id=?',[transactionId]); saveDb(); return {redirectUri:tx.redirectUri,state:tx.state,code:rawCode,scopes:tx.scope.split(' ')}; }
export async function exchangeAuthorizationCode(input:{clientId:string;clientSecret?:string;code:string;redirectUri:string;codeVerifier?:string}):Promise<Record<string,any>>{ if(!configuredClientOk(input.clientId,input.clientSecret))throw new Error('Invalid client authentication'); await ensureMcpSchema(); const db=await getDb(); const row=db.exec('SELECT code_hash,client_id,redirect_uri,scope,user_phone,code_challenge,code_challenge_method,expires_at,consumed_at FROM mcp_authorization_codes WHERE code_hash=? LIMIT 1',[hash(input.code)])[0]?.values?.[0] as any[]|undefined; if(!row)throw new Error('Invalid authorization code'); const expiresAt=new Date(String(row[7])).getTime(); if(String(row[8]||'')||expiresAt<=Date.now())throw new Error('Authorization code expired or already used'); if(String(row[1])!==input.clientId||String(row[2])!==input.redirectUri)throw new Error('Authorization code client binding mismatch'); if(String(row[6]||'')==='S256'){if(!input.codeVerifier)throw new Error('code_verifier is required'); const digest=crypto.createHash('sha256').update(input.codeVerifier).digest('base64url'); if(digest!==String(row[5]))throw new Error('PKCE verification failed');} db.run('UPDATE mcp_authorization_codes SET consumed_at=CURRENT_TIMESTAMP WHERE code_hash=? AND consumed_at IS NULL',[hash(input.code)]); if(db.getRowsModified()!==1)throw new Error('Authorization code already consumed'); const scope=String(row[3]); const userPhone=String(row[4]); const accessToken=await issueAccessToken(userPhone,input.clientId,scope.split(' ')); const refreshToken=await issueRefreshToken(userPhone,input.clientId,scope.split(' ')); saveDb(); return {access_token:accessToken,token_type:'Bearer',expires_in:Math.floor(ACCESS_TTL_MS/1000),refresh_token:refreshToken,scope}; }
export async function refreshAccessToken(input:{clientId:string;clientSecret?:string;refreshToken:string}):Promise<Record<string,any>>{ if(!configuredClientOk(input.clientId,input.clientSecret))throw new Error('Invalid client authentication'); await ensureMcpSchema(); const db=await getDb(); const row=db.exec('SELECT token_hash,family_id,client_id,scope,user_phone,expires_at,revoked_at FROM mcp_refresh_tokens WHERE token_hash=? LIMIT 1',[hash(input.refreshToken)])[0]?.values?.[0] as any[]|undefined; if(!row||String(row[2])!==input.clientId)throw new Error('Invalid refresh token'); if(row[6]||new Date(String(row[5])).getTime()<=Date.now())throw new Error('Refresh token expired or revoked'); const scopes=String(row[3]).split(' ').filter(Boolean) as McpScope[]; db.run('UPDATE mcp_refresh_tokens SET revoked_at=CURRENT_TIMESTAMP WHERE token_hash=? AND revoked_at IS NULL',[hash(input.refreshToken)]); const accessToken=await issueAccessToken(String(row[4]),input.clientId,scopes); const refreshToken=await issueRefreshToken(String(row[4]),input.clientId,scopes,String(row[1])); saveDb(); return {access_token:accessToken,token_type:'Bearer',expires_in:Math.floor(ACCESS_TTL_MS/1000),refresh_token:refreshToken,scope:scopes.join(' ')}; }
async function issueAccessToken(phone:string,clientId:string,scopes:McpScope[]):Promise<string>{ return jwt.sign({typ:'mcp',sub:phone,phone,client_id:clientId,scope:scopes.join(' '),aud:issuer()},oauthSecret(),{algorithm:'HS256',expiresIn:Math.floor(ACCESS_TTL_MS/1000)}); }
async function issueRefreshToken(phone:string,clientId:string,scopes:McpScope[],familyId=crypto.randomUUID()):Promise<string>{ const token=randomToken('mcprf'); const db=await getDb(); db.run('INSERT INTO mcp_refresh_tokens(token_hash,family_id,client_id,scope,user_phone,created_at,expires_at) VALUES(?,?,?,?,?,?,?)',[hash(token),familyId,clientId,scopes.join(' '),phone,new Date().toISOString(),new Date(Date.now()+REFRESH_TTL_MS).toISOString()]); return token; }
export async function verifyAccessToken(token:string):Promise<{phone:string;clientId:string;scopes:McpScope[]}>{ const payload=jwt.verify(token,oauthSecret(),{algorithms:['HS256'],audience:issuer()}) as any; if(payload?.typ!=='mcp'||!payload?.phone||!payload?.client_id)throw new Error('Invalid MCP access token'); const scopes=String(payload.scope||'').split(' ').filter(Boolean) as McpScope[]; validateScope(scopes.join(' ')); return {phone:String(payload.phone),clientId:String(payload.client_id),scopes}; }
export async function revokeToken(token:string):Promise<void>{ await ensureMcpSchema(); const db=await getDb(); db.run('UPDATE mcp_refresh_tokens SET revoked_at=CURRENT_TIMESTAMP WHERE token_hash=? AND revoked_at IS NULL',[hash(token)]); saveDb(); }
async function audit(phone:string,clientId:string,toolName:string,action:string,scopes:string[],outcome:string,metadata:Record<string,unknown>={}):Promise<void>{ const db=await getDb(); db.run('INSERT INTO mcp_access_audit(user_phone,client_id,tool_name,action,scope,outcome,metadata_json) VALUES(?,?,?,?,?,?,?)',[phone,clientId,toolName,action,scopes.join(' '),outcome,JSON.stringify(metadata)]); saveDb(); }
export const MCP_TOOLS=[
{name:'kurukoo.get_context',description:'Read the authenticated user\'s current Kurukoo relationship context. Use this before acting when the request depends on active or paused work.',inputSchema:{type:'object',properties:{},additionalProperties:false},requiredScope:'kurukoo.read' as McpScope},
{name:'kurukoo.list_capabilities',description:'List Kurukoo\'s canonical capability catalog with actions, risk, activation and evidence semantics.',inputSchema:{type:'object',properties:{family:{type:'string'}},additionalProperties:false},requiredScope:'kurukoo.read' as McpScope},
{name:'kurukoo.inspect',description:'Inspect an exact user-owned Kurukoo object without guessing or substituting a different object.',inputSchema:{type:'object',required:['capability','canonicalObjectId'],properties:{capability:{type:'string'},canonicalObjectId:{type:'string'},action:{type:'string',default:'open'}},additionalProperties:false},requiredScope:'kurukoo.read' as McpScope},
{name:'kurukoo.find',description:'Discover relevant Kurukoo capabilities without changing user state. Use this before requesting an action when the capability is not yet known.',inputSchema:{type:'object',required:['request'],properties:{request:{type:'string'},contextId:{type:'string'},location:{type:'string'}},additionalProperties:false},requiredScope:'kurukoo.read' as McpScope},
{name:'kurukoo.execute',description:'Execute a canonical Kurukoo capability action. Kurukoo remains authoritative for ownership, authorization, confirmation, idempotency, evidence and external activation.',inputSchema:{type:'object',required:['capability','action'],properties:{capability:{type:'string'},action:{type:'string'},contextId:{type:'string'},canonicalObjectId:{type:'string'},arguments:{type:'object'},confirmationGranted:{type:'boolean'},idempotencyKey:{type:'string'},confidence:{type:'number'}},additionalProperties:false},requiredScope:'kurukoo.act' as McpScope}
] as const;
export function mcpToolList(_filterFamily?:string){ return MCP_TOOLS.map(({requiredScope:_requiredScope,...tool})=>({...tool,annotations:{readOnlyHint:tool.name.endsWith('get_context')||tool.name.endsWith('list_capabilities')||tool.name.endsWith('inspect')||tool.name.endsWith('find')?true:false}})); }
async function inspectObject(phone:string,capability:string,objectId:string):Promise<Record<string,unknown>>{ if(capability==='agent'){const goal=await getAgentGoal(phone,objectId);return goal?{capability,canonicalObjectId:objectId,object:goal}:{capability,canonicalObjectId:objectId,found:false};} if(['economic_request','order','product','payment'].includes(capability)){const request=await getEconomicRequest(objectId);return request?.phone===phone?{capability,canonicalObjectId:objectId,object:request}:{capability,canonicalObjectId:objectId,found:false};} if(capability==='notification'){const id=Number(objectId);const notification=Number.isSafeInteger(id)?await getInternalNotificationById(id,phone):null;return notification?{capability,canonicalObjectId:objectId,object:notification}:{capability,canonicalObjectId:objectId,found:false};} return {capability,canonicalObjectId:objectId,found:false,message:'No exact read projection is registered for this capability yet. Kurukoo did not substitute another object.'}; }
function scoreDiscovery(query:string,cap:any):number{ const qTokens=new Set(query.toLowerCase().split(/[^a-z0-9]+/).filter(t=>t.length>=3)); const values=[String(cap.capability||''),String(cap.family||''),...(Array.isArray(cap.actions)?cap.actions:[])].join(' ').toLowerCase().split(/[^a-z0-9]+/).filter(t=>t.length>=3); let score=0; for(const token of values) if(qTokens.has(token)) score+=2; const searchable=[String(cap.capability||''),String(cap.family||'')].join(' ').toLowerCase(); if(searchable.includes(query.toLowerCase().trim()))score+=5; return score; }
export async function callMcpTool(auth:{phone:string;clientId:string;scopes:McpScope[]},name:string,args:any):Promise<Record<string,unknown>>{
  const definition=MCP_TOOLS.find(tool=>tool.name===name); if(!definition)throw new Error(`Unknown MCP tool: ${name}`); if(!scopeAllows(auth.scopes,definition.requiredScope))throw new Error(`OAuth scope ${definition.requiredScope} is required for ${name}`);
  if(name==='kurukoo.get_context'){const capabilities=await listUniversalCapabilities();const response={user:{phone:auth.phone},externalController:{clientId:auth.clientId,channel:'external-ai-mcp'},continuity:{ownerScope:auth.phone,instruction:'Use exact canonical object/context IDs returned by Kurukoo. Do not infer a replacement object if one becomes stale.'},availableCapabilityFamilies:[...new Set(capabilities.map(cap=>cap.family))].slice(0,80),connection:{status:'connected',scopes:auth.scopes,provider:'External AI / remote MCP'}};await audit(auth.phone,auth.clientId,name,'read',auth.scopes,'completed');return response;}
  if(name==='kurukoo.list_capabilities'){const capabilities=await listUniversalCapabilities();const family=ensureString(args?.family).toLowerCase();const filtered=family?capabilities.filter(cap=>cap.family.toLowerCase()===family):capabilities;const response={count:filtered.length,capabilities:filtered.map(cap=>({capability:cap.capability,kind:cap.kind,family:cap.family,mode:cap.mode,actions:cap.actions,risk:cap.risk,confirmationRequired:cap.confirmationRequired,activationState:cap.activationState,evidenceStatus:cap.evidenceStatus,continuationContext:cap.continuationContext}))};await audit(auth.phone,auth.clientId,name,'read',auth.scopes,'completed',{count:filtered.length});return response;}
  if(name==='kurukoo.inspect'){const response=await inspectObject(auth.phone,ensureString(args?.capability),ensureString(args?.canonicalObjectId));await audit(auth.phone,auth.clientId,name,'read',auth.scopes,'completed',{capability:args?.capability,canonicalObjectId:args?.canonicalObjectId,found:response.found!==false});return response;}
  if(name==='kurukoo.find'){const request=ensureString(args?.request);if(!request)throw new Error('request is required');const capabilities=await listUniversalCapabilities();const ranked=capabilities.map(cap=>({cap,score:scoreDiscovery(request,cap)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||String(a.cap.capability).localeCompare(String(b.cap.capability))).slice(0,12);const response={request,location:args?.location?ensureString(args.location):undefined,matchedCapabilities:ranked.map(item=>({capability:item.cap.capability,kind:item.cap.kind,family:item.cap.family,actions:item.cap.actions,risk:item.cap.risk,activationState:item.cap.activationState,confidence:Math.min(0.99,0.35+item.score/20)})),next:'Use kurukoo.execute with an exact capability/action only after Kurukoo has established the relevant context or object.'};await audit(auth.phone,auth.clientId,name,'find',auth.scopes,'completed',{candidateCount:ranked.length});return response;}
  const capability=ensureString(args?.capability).toLowerCase();const action=ensureString(args?.action).toLowerCase();if(!capability||!action)throw new Error('capability and action are required');if(!args?.confirmationGranted&&['pay','confirm','execute','refund','dispute','emergency_dispatch','dispatch'].includes(action)&&!scopeAllows(auth.scopes,'kurukoo.execute')){const blocked={status:'confirmation_required',capability,action,message:'Kurukoo requires the explicit execution scope and/or canonical confirmation policy before this action can proceed.'};await audit(auth.phone,auth.clientId,name,action,auth.scopes,'blocked',{reason:'execution_scope_or_confirmation'});return blocked;}
  const idempotencyKey=ensureString(args?.idempotencyKey)||`mcp:${auth.clientId}:${auth.phone}:${crypto.randomUUID()}`;const result=await executeCanonicalCapabilityProposal({phone:auth.phone,capability,action,contextId:args?.contextId?ensureString(args.contextId):undefined,canonicalObjectId:args?.canonicalObjectId?ensureString(args.canonicalObjectId):undefined,arguments:args?.arguments&&typeof args.arguments==='object'?args.arguments:{},confirmationGranted:args?.confirmationGranted===true,idempotencyKey,channel:'external-ai-mcp',confidence:typeof args?.confidence==='number'?args.confidence:undefined});await audit(auth.phone,auth.clientId,name,action,auth.scopes,String(result.status),{capability,canonicalObjectId:result.canonicalObjectId,evidenceLevel:result.evidenceLevel,externalActivation:result.externalActivation});return result as unknown as Record<string,unknown>;
}
export function renderAuthorizationPage(input:{transactionId:string;clientName?:string;scopes:string[];message?:string;phone?:string;codeSent?:boolean;error?:string}):string{const scopeLabels=input.scopes.map(scope=>`<li>${scope}</li>`).join('');const action=`/oauth/authorize/consent/${encodeURIComponent(input.transactionId)}`;const otpAction=`/oauth/authorize/otp/${encodeURIComponent(input.transactionId)}`;const safe=(value:string)=>value.replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]!));const clientName=safe(input.clientName||'AI assistant');const heading=`Connect ${clientName} to your Kurukoo`;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${heading}</title><link rel="stylesheet" href="/css/site.css"><link rel="stylesheet" href="/css/kurukoo-home.css"></head><body class="page-shell"><main class="container"><section class="card"><p class="eyebrow">Kurukoo connection</p><h1>${heading}</h1><p>${clientName} is asking to access your Kurukoo account.</p><ul>${scopeLabels}</ul>${input.error?`<p role="alert">${safe(input.error)}</p>`:''}${input.message?`<p>${safe(input.message)}</p>`:''}<form method="post" action="${otpAction}"><label>Phone number<input name="phone" autocomplete="tel" required value="${safe(input.phone||'')}"></label><button class="btn" type="submit">Send Kurukoo code</button></form>${input.codeSent?`<form method="post" action="${otpAction}/verify"><input type="hidden" name="phone" value="${safe(input.phone||'')}"><label>Verification code<input name="code" inputmode="numeric" autocomplete="one-time-code" required></label><button class="btn" type="submit">Verify and connect</button></form>`:''}<form method="post" action="${action}"><button class="btn" type="submit">Approve using current Kurukoo session</button></form><p class="muted">Kurukoo does not receive or store credentials belonging to your external AI provider. You are authorizing this AI client to call Kurukoo's canonical tools for this account.</p></section></main></body></html>`;}
export async function currentSessionPhoneFromBearer(authHeader?:string):Promise<string|null>{const raw=ensureString(authHeader);if(!raw.startsWith('Bearer '))return null;try{const decoded=jwt.verify(raw.slice(7).trim(),String(process.env.JWT_SECRET||''),{algorithms:['HS256']}) as any;return decoded?.phone?String(decoded.phone):null;}catch{return null;}}
