import crypto from 'crypto';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { getCanonicalStore } from './canonicalStore.js';

const ALGORITHM = 'aes-256-cbc';

function parseProfileJson(value: string, field: string): any {
    try { return JSON.parse(value); }
    catch (error) { throw new Error(`[Kurukoo Security] Invalid encrypted ${field} profile data.`, { cause: error }); }
}
export type MemoryProvenance = 'user_declared' | 'verified' | 'inferred' | 'observed' | 'system_generated' | 'expired';

async function ensureMemoryFactsSchema(): Promise<void> {
    const store = await getCanonicalStore();
    if (getCanonicalPersistenceMode() === 'postgres') {
        await store.run(`CREATE TABLE IF NOT EXISTS memory_facts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            phone TEXT NOT NULL,
            field TEXT NOT NULL,
            value TEXT NOT NULL,
            provenance TEXT NOT NULL,
            confidence REAL,
            source_ref TEXT,
            observed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(phone, field, value, provenance)
        )`);
    } else {
        await store.run(`CREATE TABLE IF NOT EXISTS memory_facts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            phone TEXT NOT NULL,
            field TEXT NOT NULL,
            value TEXT NOT NULL,
            provenance TEXT NOT NULL,
            confidence REAL,
            source_ref TEXT,
            observed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(phone, field, value, provenance)
        )`);
    }
    await store.run(`CREATE INDEX IF NOT EXISTS idx_memory_facts_owner ON memory_facts(phone, status, field)`);
}

export async function recordMemoryFact(phone: string, field: string, value: unknown, provenance: MemoryProvenance, options: { confidence?: number; sourceRef?: string; expiresAt?: string } = {}): Promise<void> {
    const normalized = String(value ?? '').trim();
    if (!phone || !field || !normalized || provenance === 'expired') return;
    await ensureMemoryFactsSchema();
    const store = await getCanonicalStore();
    await store.run(`INSERT INTO memory_facts (phone, field, value, provenance, confidence, source_ref, expires_at, status, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, 'active', CURRENT_TIMESTAMP)
            ON CONFLICT(phone, field, value, provenance) DO UPDATE SET confidence = excluded.confidence, source_ref = excluded.source_ref, expires_at = excluded.expires_at, status = 'active', updated_at = CURRENT_TIMESTAMP`,
        [phone, field, normalized, provenance, options.confidence ?? null, options.sourceRef ?? null, options.expiresAt ?? null]);
}

export async function getMemoryFacts(phone: string, fields?: string[]): Promise<Array<{ id: number; field: string; value: string; provenance: MemoryProvenance; confidence: number | null; sourceRef: string | null; observedAt: string; expiresAt: string | null }>> {
    await ensureMemoryFactsSchema();
    const store = await getCanonicalStore();
    const params: unknown[] = [phone];
    let where = `phone = ? AND status = 'active' AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)`;
    if (fields?.length) { where += ` AND field IN (${fields.map(() => '?').join(',')})`; params.push(...fields); }
    const rows = await store.all<any>(`SELECT id, field, value, provenance, confidence, source_ref, observed_at, expires_at FROM memory_facts WHERE ${where} ORDER BY updated_at DESC`, params);
    return rows.map(row => ({ id: Number(row.id), field: String(row.field), value: String(row.value), provenance: String(row.provenance) as MemoryProvenance, confidence: row.confidence == null ? null : Number(row.confidence), sourceRef: row.source_ref == null ? null : String(row.source_ref), observedAt: String(row.observed_at), expiresAt: row.expires_at == null ? null : String(row.expires_at) }));
}

export async function revokeMemoryFact(phone: string, factId: number): Promise<{ revoked: boolean; reason?: 'not_found' | 'already_revoked' }> {
    if (!phone || !Number.isInteger(factId) || factId <= 0) return { revoked: false, reason: 'not_found' };
    await ensureMemoryFactsSchema();
    const store = await getCanonicalStore();
    const row = await store.one<any>(`SELECT id, status FROM memory_facts WHERE id = ? AND phone = ? LIMIT 1`, [factId, phone]);
    if (!row) return { revoked: false, reason: 'not_found' };
    if (String(row.status) !== 'active') return { revoked: false, reason: 'already_revoked' };
    await store.run(`UPDATE memory_facts SET status = 'revoked', updated_at = CURRENT_TIMESTAMP WHERE id = ? AND phone = ? AND status = 'active'`, [factId, phone]);
    await logProfileAccess(phone, 'memory_self_service', 'write');
    return { revoked: true };
}

const getSecretKey = () => {
    const raw = String(process.env.MEMORY_ENCRYPTION_KEY || '').trim();
    if (!raw && process.env.NODE_ENV === 'production') throw new Error('[Kurukoo Security] MEMORY_ENCRYPTION_KEY must be configured in production.');
    return crypto.createHash('sha256').update(raw || 'development-only-memory-key').digest();
};

export function encryptData(text: string): string {
    if (!text) return text;
    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv(ALGORITHM, getSecretKey(), iv);
    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    return iv.toString('hex') + ':' + encrypted;
}

export function decryptData(encryptedText: string): string {
    if (!encryptedText || !encryptedText.includes(':')) return encryptedText;
    const parts = encryptedText.split(':');
    const looksEncrypted = /^[a-f0-9]{32}$/i.test(parts[0] || '');
    if (!looksEncrypted) return encryptedText;
    if (parts.length !== 2 || !/^[a-f0-9]+$/i.test(parts[1])) throw new Error('[Kurukoo Security] Invalid encrypted profile payload.');
    const iv = Buffer.from(parts[0], 'hex');
    const decipher = crypto.createDecipheriv(ALGORITHM, getSecretKey(), iv);
    let decrypted = decipher.update(parts[1], 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    return decrypted;
}

export async function logProfileAccess(phone: string, serviceName: string, action: 'read' | 'write') {
    try {
        const store = await getCanonicalStore();
        await store.run(`INSERT INTO profile_access_log (phone, service_name, action) VALUES (?, ?, ?)`, [phone, serviceName, action]);
    } catch (e) {
        console.error('Failed to log profile access:', e);
    }
}

function decodeProfileField(value: unknown, field: 'preferences' | 'behavior_patterns'): Record<string, unknown> {
    if (!value) return {};
    try {
        const decrypted = decryptData(String(value));
        const parsed = parseProfileJson(decrypted, field);
        return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
    } catch (error) {
        console.warn(`[Kurukoo Security] ${field} profile context unavailable; field omitted.`, error instanceof Error ? error.message : 'decrypt failure');
        return {};
    }
}

export async function getProfile(phone: string, serviceName: string = 'system') {
    await logProfileAccess(phone, serviceName, 'read');
    const store = await getCanonicalStore();
    const profile = await store.one<any>(`SELECT * FROM memory_profiles WHERE phone = ?`, [phone]);
    if (profile) {
        profile.preferences = decodeProfileField(profile.preferences, 'preferences');
        profile.behavior_patterns = decodeProfileField(profile.behavior_patterns, 'behavior_patterns');
    }
    return profile || null;
}

export async function updateProfile(phone: string, serviceName: string = 'system', updates: {
    name?: string;
    location?: string;
    country?: string;
    subscription_tier?: string;
    wallet_balance_minor?: number;
    preferences?: any;
    behavior_patterns?: any;
    fcm_token?: string;
    is_available?: number;
    provenance?: MemoryProvenance;
    source_ref?: string;
}) {
    await logProfileAccess(phone, serviceName, 'write');
    const store = await getCanonicalStore();
    const existing = await getProfile(phone, serviceName);

    const name = updates.name !== undefined ? updates.name : (existing ? existing.name : null);
    const location = updates.location !== undefined ? updates.location : (existing ? existing.location : null);
    const country = updates.country !== undefined ? updates.country : (existing ? existing.country : null);
    const subscription_tier = updates.subscription_tier !== undefined ? updates.subscription_tier : (existing ? existing.subscription_tier : null);
    const wallet_balance_minor = updates.wallet_balance_minor !== undefined ? updates.wallet_balance_minor : (existing ? existing.wallet_balance_minor : null);

    const prefsObj = updates.preferences !== undefined ? updates.preferences : (existing ? existing.preferences : {});
    if (!prefsObj.referral_code) {
        const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        let code = '';
        for (let i = 0; i < 8; i++) code += chars.charAt(Math.floor(Math.random() * chars.length));
        prefsObj.referral_code = code;
    }
    if (!prefsObj.badges) prefsObj.badges = [];
    const prefsStr = encryptData(JSON.stringify(prefsObj));
    const patternsObj = updates.behavior_patterns !== undefined ? updates.behavior_patterns : (existing ? existing.behavior_patterns : {});
    const patternsStr = encryptData(JSON.stringify(patternsObj));
    const fcm_token = updates.fcm_token !== undefined ? updates.fcm_token : (existing ? existing.fcm_token : null);
    const is_available = updates.is_available !== undefined ? updates.is_available : (existing ? existing.is_available : 0);

    if (!existing) {
        await store.run(`INSERT INTO memory_profiles (phone, name, location, country, subscription_tier, wallet_balance_minor, preferences, behavior_patterns, fcm_token, is_available) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [phone, name, location, country, subscription_tier, wallet_balance_minor, prefsStr, patternsStr, fcm_token, is_available]);
    } else {
        await store.run(`UPDATE memory_profiles SET name = ?, location = ?, country = ?, subscription_tier = ?, wallet_balance_minor = ?, preferences = ?, behavior_patterns = ?, fcm_token = ?, is_available = ?, updated_at = CURRENT_TIMESTAMP WHERE phone = ?`, [name, location, country, subscription_tier, wallet_balance_minor, prefsStr, patternsStr, fcm_token, is_available, phone]);
    }
    const provenance = updates.provenance || 'user_declared';
    if (updates.name !== undefined) await recordMemoryFact(phone, 'name', updates.name, provenance, { sourceRef: updates.source_ref || serviceName });
    if (updates.location !== undefined) await recordMemoryFact(phone, 'location', updates.location, provenance, { sourceRef: updates.source_ref || serviceName });
    if (updates.country !== undefined) await recordMemoryFact(phone, 'country', updates.country, provenance, { sourceRef: updates.source_ref || serviceName });
    return await getProfile(phone, serviceName);
}

export interface CanonicalIdentityContext {
    hasProfile: boolean;
    hasName: boolean;
    name?: string;
    nameProvenance?: MemoryProvenance | 'profile';
    location?: string;
    country?: string;
    stableFacts: Array<{ field: string; value: string; provenance: MemoryProvenance; confidence: number | null }>;
    preferences: Record<string, unknown>;
}

function projectSafePreferences(value: unknown): Record<string, unknown> {
    if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
    const source = value as Record<string, unknown>;
    const allowed = ['language', 'locale', 'timezone', 'communication_style', 'preferred_channel', 'accessibility', 'travel_preferences', 'service_preferences'];
    const projected: Record<string, unknown> = {};
    for (const key of allowed) {
        const current = source[key];
        if (typeof current === 'string' || typeof current === 'number' || typeof current === 'boolean') projected[key] = current;
    }
    return projected;
}

export async function getCanonicalIdentityContext(phone: string, serviceName = 'system'): Promise<CanonicalIdentityContext> {
    const [profile, facts] = await Promise.all([
        getProfile(phone, serviceName),
        getMemoryFacts(phone, ['name', 'location', 'country', 'language', 'locale', 'timezone', 'communication_style', 'preferred_channel']),
    ]);
    const nameFact = facts.find(fact => fact.field === 'name');
    const locationFact = facts.find(fact => fact.field === 'location');
    const countryFact = facts.find(fact => fact.field === 'country');
    return {
        hasProfile: Boolean(profile),
        hasName: Boolean(profile?.name || nameFact?.value),
        name: profile?.name ? String(profile.name) : nameFact?.value,
        nameProvenance: nameFact?.provenance || (profile?.name ? 'profile' : undefined),
        location: profile?.location ? String(profile.location) : locationFact?.value,
        country: profile?.country ? String(profile.country) : countryFact?.value,
        stableFacts: facts.slice(0, 8).map(fact => ({ field: fact.field, value: fact.value, provenance: fact.provenance, confidence: fact.confidence })),
        preferences: projectSafePreferences(profile?.preferences),
    };
}
