import crypto from 'node:crypto';
import { getDb, saveDb } from '../database.js';
import { decryptStorageCredential, encryptStorageCredential, ensureStorageConnectionSchema } from './artifactService.js';
import { getFeatureFlagStatus } from './featureFlags.js';

type SourceKind = 'outlook' | 'onedrive';
type Connection = { accessToken: string; refreshToken: string | null; expiresAt: number };
type MicrosoftItem = { id: string; title: string; detail?: string; url?: string; kind: string };

const GRAPH_BASE = 'https://graph.microsoft.com/v1.0';
const MAX_ITEMS = 25;
const MAX_QUERY_CHARS = 80;
const SCOPES: Record<SourceKind, string[]> = { outlook: ['openid', 'offline_access', 'Mail.ReadBasic'], onedrive: ['openid', 'offline_access', 'Files.Read'] };
function problem(code: string, message: string): Error & { code: string } { return Object.assign(new Error(message), { code }); }
function sha(value: string) { return crypto.createHash('sha256').update(value).digest('hex'); }
function owner(value: string) { const phone = String(value || '').trim(); if (!phone || phone.startsWith('anon_')) throw problem('MICROSOFT_OWNER_REQUIRED', 'Microsoft sources require an authenticated owner.'); return phone; }
function kindOf(value: unknown): SourceKind { if (value === 'outlook' || value === 'onedrive') return value; throw problem('MICROSOFT_SOURCE_INVALID', 'Choose Outlook or OneDrive.'); }
function clean(value: unknown, max: number) { return String(value || '').replace(/[\u0000-\u001F]/g, ' ').trim().slice(0, max); }
function settings(kind: SourceKind) {
  const clientId = clean(process.env.KURUKOO_MICROSOFT_CLIENT_ID, 300); const clientSecret = clean(process.env.KURUKOO_MICROSOFT_CLIENT_SECRET, 600); const redirectUri = clean(process.env.KURUKOO_MICROSOFT_REDIRECT_URI, 2000); const tenant = clean(process.env.KURUKOO_MICROSOFT_TENANT || 'common', 200);
  const feature = getFeatureFlagStatus(process.env.KURUKOO_DEFAULT_COUNTRY || 'ng', kind);
  return { clientId, clientSecret, redirectUri, tenant, configured: Boolean(clientId && clientSecret && redirectUri), enabled: feature.enabled, featureFlagState: feature.status };
}
function authBase(current: ReturnType<typeof settings>) { return `https://login.microsoftonline.com/${encodeURIComponent(current.tenant)}/oauth2/v2.0`; }
async function schema() { const db = await ensureStorageConnectionSchema(); db.run(`CREATE TABLE IF NOT EXISTS external_source_reads (id TEXT PRIMARY KEY, phone TEXT NOT NULL, provider TEXT NOT NULL, source_hash TEXT NOT NULL, range_hash TEXT NOT NULL, status TEXT NOT NULL, row_count INTEGER NOT NULL DEFAULT 0, column_count INTEGER NOT NULL DEFAULT 0, error_code TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)`); db.run('CREATE INDEX IF NOT EXISTS idx_external_source_reads_owner ON external_source_reads(phone, provider, created_at DESC)'); saveDb(); return db; }
async function audit(phone: string, kind: SourceKind, selector: string, status: 'read' | 'failed', count = 0, errorCode?: string) { const db = await schema(); db.run('INSERT INTO external_source_reads (id, phone, provider, source_hash, range_hash, status, row_count, column_count, error_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), phone, `microsoft_${kind}`, sha(kind), sha(selector || '*'), status, count, 0, errorCode || null]); saveDb(); }
async function connection(phone: string, kind: SourceKind): Promise<Connection | null> { const db = await schema(); const provider = `microsoft_${kind}`; const statement = db.prepare('SELECT access_token_encrypted, refresh_token_encrypted, expires_at, status FROM artifact_storage_connections WHERE phone=? AND provider=? LIMIT 1'); statement.bind([phone, provider]); const row = statement.step() ? statement.getAsObject() as Record<string, unknown> : null; statement.free(); if (!row || String(row.status) !== 'active' || !row.access_token_encrypted) return null; try { return { accessToken: decryptStorageCredential(String(row.access_token_encrypted)), refreshToken: row.refresh_token_encrypted ? decryptStorageCredential(String(row.refresh_token_encrypted)) : null, expiresAt: Number(row.expires_at || 0) }; } catch { db.run('UPDATE artifact_storage_connections SET status=?, updated_at=CURRENT_TIMESTAMP WHERE phone=? AND provider=?', ['reauthorization_required', phone, provider]); saveDb(); return null; } }
async function store(phone: string, kind: SourceKind, token: { access_token: string; refresh_token?: string; expires_in?: number }) { const db = await schema(); const provider = `microsoft_${kind}`; const expiresAt = Date.now() + Math.max(60, Number(token.expires_in) || 3_600) * 1000; db.run(`INSERT INTO artifact_storage_connections (phone, provider, access_token_encrypted, refresh_token_encrypted, expires_at, status, updated_at) VALUES (?, ?, ?, ?, ?, 'active', CURRENT_TIMESTAMP) ON CONFLICT(phone, provider) DO UPDATE SET access_token_encrypted=excluded.access_token_encrypted, refresh_token_encrypted=excluded.refresh_token_encrypted, expires_at=excluded.expires_at, status='active', updated_at=CURRENT_TIMESTAMP`, [phone, provider, encryptStorageCredential(token.access_token), token.refresh_token ? encryptStorageCredential(token.refresh_token) : null, expiresAt]); saveDb(); }
async function reauthorize(phone: string, kind: SourceKind) { const db = await schema(); db.run('UPDATE artifact_storage_connections SET status=?, updated_at=CURRENT_TIMESTAMP WHERE phone=? AND provider=?', ['reauthorization_required', phone, `microsoft_${kind}`]); saveDb(); }
async function refresh(phone: string, kind: SourceKind, current: Connection): Promise<Connection> { if (current.expiresAt > Date.now() + 30_000) return current; if (!current.refreshToken) { await reauthorize(phone, kind); throw problem('MICROSOFT_REAUTHORIZATION_REQUIRED', 'Microsoft access expired and no refresh token is available. Reconnect this source.'); } const cfg = settings(kind); const body = new URLSearchParams({ client_id: cfg.clientId, client_secret: cfg.clientSecret, grant_type: 'refresh_token', refresh_token: current.refreshToken, scope: SCOPES[kind].join(' ') }); const response = await fetch(`${authBase(cfg)}/token`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const token = await response.json().catch(() => ({})) as any; if (!response.ok || !token.access_token) { await reauthorize(phone, kind); throw problem('MICROSOFT_REAUTHORIZATION_REQUIRED', 'Microsoft token refresh failed. Reconnect this source.'); } await store(phone, kind, token); return { accessToken: token.access_token, refreshToken: token.refresh_token || current.refreshToken, expiresAt: Date.now() + Math.max(60, Number(token.expires_in) || 3600) * 1000 }; }

export async function getMicrosoftSourceStatus(phoneValue: string, kindValue: unknown) { const phone = owner(phoneValue); const kind = kindOf(kindValue); const cfg = settings(kind); const connected = cfg.configured && cfg.enabled ? await connection(phone, kind) : null; const reason = !cfg.configured ? 'Microsoft OAuth deployment credentials are not configured.' : !cfg.enabled ? `${kind === 'outlook' ? 'Outlook' : 'OneDrive'} is configured but disabled by feature flag.` : connected ? undefined : 'No active Microsoft connection exists for this owner.'; return { provider: kind, configured: cfg.configured, enabled: cfg.enabled, connected: Boolean(connected), featureFlagState: cfg.featureFlagState, ...(reason ? { reason } : {}) }; }
export async function startMicrosoftConnection(phoneValue: string, kindValue: unknown) { const phone = owner(phoneValue); const kind = kindOf(kindValue); const cfg = settings(kind); if (!cfg.configured) throw problem('MICROSOFT_OAUTH_NOT_CONFIGURED', 'Microsoft source connection requires a registered client, secret, and exact callback URI.'); if (!cfg.enabled) throw problem('MICROSOFT_FEATURE_DISABLED', 'Microsoft source is disabled by feature flag.'); const state = crypto.randomBytes(32).toString('base64url'); const verifier = crypto.randomBytes(48).toString('base64url'); const challenge = crypto.createHash('sha256').update(verifier).digest('base64url'); const expiresAt = Date.now() + 10 * 60_000; const db = await schema(); db.run('DELETE FROM artifact_oauth_states WHERE expires_at < ?', [Date.now()]); db.run('INSERT INTO artifact_oauth_states (state_hash, phone, provider, code_verifier_encrypted, expires_at) VALUES (?, ?, ?, ?, ?)', [sha(state), phone, `microsoft_${kind}`, encryptStorageCredential(verifier), expiresAt]); saveDb(); const url = new URL(`${authBase(cfg)}/authorize`); url.searchParams.set('client_id', cfg.clientId); url.searchParams.set('response_type', 'code'); url.searchParams.set('redirect_uri', cfg.redirectUri); url.searchParams.set('response_mode', 'query'); url.searchParams.set('scope', SCOPES[kind].join(' ')); url.searchParams.set('state', state); url.searchParams.set('code_challenge', challenge); url.searchParams.set('code_challenge_method', 'S256'); return { authorizationUrl: url.toString(), expiresAt: new Date(expiresAt).toISOString() }; }
export async function completeMicrosoftConnection(phoneValue: string, kindValue: unknown, state: string, code: string) { const phone = owner(phoneValue); const kind = kindOf(kindValue); const cfg = settings(kind); if (!cfg.configured || !cfg.enabled) throw problem(!cfg.configured ? 'MICROSOFT_OAUTH_NOT_CONFIGURED' : 'MICROSOFT_FEATURE_DISABLED', 'Microsoft source cannot complete authorization in its current state.'); const db = await schema(); const statement = db.prepare('SELECT phone, code_verifier_encrypted, expires_at FROM artifact_oauth_states WHERE state_hash=? AND provider=? LIMIT 1'); statement.bind([sha(String(state || '')), `microsoft_${kind}`]); const row = statement.step() ? statement.getAsObject() as Record<string, unknown> : null; statement.free(); if (!row || String(row.phone) !== phone || Number(row.expires_at || 0) < Date.now() || !row.code_verifier_encrypted) throw problem('MICROSOFT_OAUTH_STATE_INVALID', 'Microsoft authorization state is invalid or expired.'); const verifier = decryptStorageCredential(String(row.code_verifier_encrypted)); db.run('DELETE FROM artifact_oauth_states WHERE state_hash=?', [sha(String(state || ''))]); saveDb(); const body = new URLSearchParams({ client_id: cfg.clientId, client_secret: cfg.clientSecret, grant_type: 'authorization_code', code: clean(code, 4_000), redirect_uri: cfg.redirectUri, code_verifier: verifier, scope: SCOPES[kind].join(' ') }); const response = await fetch(`${authBase(cfg)}/token`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const token = await response.json().catch(() => ({})) as any; if (!response.ok || !token.access_token) throw problem('MICROSOFT_OAUTH_EXCHANGE_FAILED', 'Microsoft authorization code exchange failed.'); await store(phone, kind, token); return { connected: true, provider: kind }; }
export async function listMicrosoftSource(phoneValue: string, kindValue: unknown, queryValue?: unknown): Promise<{ provider: SourceKind; items: MicrosoftItem[]; hasMore: boolean }> { const phone = owner(phoneValue); const kind = kindOf(kindValue); const query = clean(queryValue, MAX_QUERY_CHARS); try { const current = await connection(phone, kind); if (!current) throw problem('MICROSOFT_NOT_CONNECTED', 'No active Microsoft connection exists for this owner.'); const token = await refresh(phone, kind, current); const url = kind === 'outlook' ? new URL(`${GRAPH_BASE}/me/messages`) : new URL(`${GRAPH_BASE}/me/drive/root/children`); url.searchParams.set('$top', String(MAX_ITEMS)); url.searchParams.set('$select', kind === 'outlook' ? 'id,subject,receivedDateTime,sender,webLink' : 'id,name,size,lastModifiedDateTime,folder,webUrl'); if (kind === 'outlook' && query) url.searchParams.set('$search', `"${query.replace(/"/g, '')}"`); const response = await fetch(url, { headers: { Authorization: `Bearer ${token.accessToken}`, ...(kind === 'outlook' && query ? { ConsistencyLevel: 'eventual' } : {}) } }); const payload = await response.json().catch(() => ({})) as any; if (!response.ok) { if (response.status === 401 || response.status === 403) await reauthorize(phone, kind); throw problem(response.status === 401 || response.status === 403 ? 'MICROSOFT_REAUTHORIZATION_REQUIRED' : 'MICROSOFT_LIST_FAILED', `Microsoft Graph did not confirm source access (HTTP ${response.status}).`); } const items = (Array.isArray(payload.value) ? payload.value : []).slice(0, MAX_ITEMS).map((item: any) => kind === 'outlook' ? ({ id: clean(item.id, 300), kind: 'message', title: clean(item.subject || 'No subject', 500), detail: clean(item.sender?.emailAddress?.name || item.receivedDateTime || '', 500) || undefined, url: clean(item.webLink, 2_000) || undefined }) : ({ id: clean(item.id, 300), kind: item.folder ? 'folder' : 'file', title: clean(item.name || 'Unnamed item', 500), detail: item.lastModifiedDateTime ? `Modified ${clean(item.lastModifiedDateTime, 100)}` : undefined, url: clean(item.webUrl, 2_000) || undefined })).filter((item: MicrosoftItem) => Boolean(item.id)); await audit(phone, kind, query, 'read', items.length); return { provider: kind, items, hasMore: Boolean(payload['@odata.nextLink']) }; } catch (cause) { await audit(phone, kind, query, 'failed', 0, String((cause as any)?.code || 'MICROSOFT_LIST_FAILED')).catch(() => undefined); throw cause; } }
export async function revokeMicrosoftConnection(phoneValue: string, kindValue: unknown) { const phone = owner(phoneValue); const kind = kindOf(kindValue); const db = await schema(); const statement = db.prepare('SELECT status FROM artifact_storage_connections WHERE phone=? AND provider=? LIMIT 1'); statement.bind([phone, `microsoft_${kind}`]); const exists = statement.step(); statement.free(); if (!exists) return { revoked: false, providerRevocationConfirmed: false }; db.run('UPDATE artifact_storage_connections SET status=?, access_token_encrypted=NULL, refresh_token_encrypted=NULL, updated_at=CURRENT_TIMESTAMP WHERE phone=? AND provider=?', ['revoked', phone, `microsoft_${kind}`]); saveDb(); return { revoked: true, providerRevocationConfirmed: false }; }
export const __microsoftGraphInternal = { scopes: SCOPES, maxItems: MAX_ITEMS };
