import { getDb, saveDb } from '../database.js';
import { getCommission } from './commissionService.js';
import { processDirectPayment } from './directWallet.js';
import { createEconomicRequest, getEconomicCategory } from './skillFlows.js';
import { chargeProviderLead } from './agentNetworkCommerce.js';
import { buildSkillExecutionContract } from './skillExecutionContract.js';
import { broadcastDispatch } from './economicDispatchCoordinator.js';

export async function getLeadCharge(orderType:string):Promise<number>{const ot=orderType.toLowerCase();if(ot.includes('okada')||ot.includes('keke')||ot.includes('car')||ot.includes('taxi')||ot.includes('ride'))return getCommission('provider_lead_ride');if(ot.includes('bicycle')||ot.includes('delivery'))return getCommission('provider_lead_delivery');if(ot.includes('hawker')||ot.includes('food'))return getCommission('provider_lead_food');if(ot.includes('barrow')||ot.includes('truck'))return getCommission('provider_lead_truck');return getCommission('provider_lead_professional');}

export async function finalizeOrder(buyerPhone:string,arg2:string='',arg3:Record<string,unknown>={},arg4?:any):Promise<{success:boolean;message:string;orderId?:string}>{
 let providerPhone=''; let orderType=''; let details:Record<string,unknown>={}; const db=await getDb(); const creditEconomyEnabled=process.env.CREDIT_ECONOMY_ENABLED!=='false';
 if(arg4!==undefined){providerPhone=arg2;orderType=arg3 as unknown as string;details=arg4||{};}else{details=arg3||{};orderType=String(details.skill||arg2||'general_service');
  if(orderType==='universal_vendor_order'){const idempotencyKey=String(details.idempotencyKey||`vendor:${buyerPhone}:${Date.now()}`);const existing=db.prepare('SELECT id,status FROM orders WHERE idempotency_key=?');existing.bind([idempotencyKey]);if(existing.step()){const row=existing.getAsObject();existing.free();return{success:true,message:`Vendor order is already awaiting confirmation. Status: ${row.status}`,orderId:String(row.id)};}existing.free();const orderId=`ord_${Date.now()}_${Math.floor(Math.random()*10000)}`;db.run(`INSERT INTO orders (id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES (?,?,?,?,?,?,?)`,[orderId,buyerPhone,orderType,null,0,'awaiting_confirmation',idempotencyKey]);db.run(`INSERT INTO audit_logs (action,details) VALUES (?,?)`,['vendor_order_started',JSON.stringify({orderId,buyerPhone,next:'confirm_item_quantity_location'})]);saveDb();return{success:true,message:'Vendor order started. Confirm the item, quantity and delivery location before escrow is locked.',orderId};}
  const economicCategory=getEconomicCategory(orderType); if(!economicCategory)return{success:true,message:''};
  const interaction=buildSkillExecutionContract(orderType).interaction; const hasExplicitExecution=Boolean(details.bookingMode)||(typeof details.amount==='number'&&Number.isFinite(details.amount)&&Number(details.amount)>0)||arg4!==undefined;
  if(!hasExplicitExecution){const idempotencyKey=String(details.idempotencyKey||`request:${buyerPhone}:${orderType}`);const existing=db.prepare('SELECT id,status FROM orders WHERE idempotency_key=? LIMIT 1');existing.bind([idempotencyKey]);if(existing.step()){const row=existing.getAsObject();existing.free();return{success:true,message:`Your ${orderType.replace(/_/g,' ')} request is already awaiting confirmation.`,orderId:String(row.id)};}existing.free();const orderId=`req_${Date.now()}_${Math.floor(Math.random()*10000)}`;db.run(`INSERT INTO orders (id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES (?,?,?,?,?,?,?)`,[orderId,buyerPhone,orderType,null,0,'awaiting_confirmation',idempotencyKey]);await createEconomicRequest({id:orderId,phone:buyerPhone,skill:orderType,requirements:details as Record<string,unknown>});db.run(`INSERT INTO audit_logs (action,details) VALUES (?,?)`,['economic_request_started',JSON.stringify({orderId,buyerPhone,orderType,category:economicCategory,next:'capture_requirements_and_confirm'})]);saveDb();return{success:true,message:'Request started. I’ll collect the missing details and show you the provider, price and terms before anything is committed.',orderId};}
  if(interaction.pattern==='dispatch'){
    const idempotencyKey=details.idempotencyKey?String(details.idempotencyKey):null;
    if(idempotencyKey){const existing=db.prepare('SELECT id,status FROM orders WHERE idempotency_key=? LIMIT 1');existing.bind([idempotencyKey]);if(existing.step()){const row=existing.getAsObject();existing.free();return{success:true,message:`Dispatch request already exists. Status: ${row.status}`,orderId:String(row.id)};}existing.free();}
    const orderId=`ord_${Date.now()}_${Math.floor(Math.random()*10000)}`;
    await createEconomicRequest({id:orderId,phone:buyerPhone,skill:orderType,requirements:details as Record<string,unknown>,status:'requested'});
    db.run(`INSERT INTO orders (id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES (?,?,?,?,?,?,?)`,[orderId,buyerPhone,orderType,null,Number(details.amount||0),'awaiting_match',idempotencyKey]);
    const vehicleType=details.vehicleType?String(details.vehicleType):details.vehicle_type?String(details.vehicle_type):details.vehicle?String(details.vehicle):undefined;
    const origin=details.origin?String(details.origin):details.location?String(details.location):undefined;
    const broadcast=await broadcastDispatch({requestId:orderId,ownerPhone:buyerPhone,skill:orderType,vehicleType,location:origin,latitude:details.latitude!==undefined?Number(details.latitude):undefined,longitude:details.longitude!==undefined?Number(details.longitude):undefined,maxProviders:details.maxProviders!==undefined?Number(details.maxProviders):undefined});
    db.run(`INSERT INTO audit_logs (action,details) VALUES (?,?)`,['dispatch_broadcast_started',JSON.stringify({orderId,buyerPhone,orderType,vehicleType,offerCount:broadcast.offers.length})]);saveDb();
    return{success:true,message:broadcast.offers.length?`Request broadcast to ${broadcast.offers.length} eligible provider${broadcast.offers.length===1?'':'s'}. The lead is charged only when a provider accepts.`:'No eligible provider is currently available; the request remains available for re-matching.',orderId};
  }
  const idempotencyKey=details.idempotencyKey?String(details.idempotencyKey):null;
  if(idempotencyKey){const existing=db.prepare('SELECT id,status FROM orders WHERE idempotency_key=?');existing.bind([idempotencyKey]);if(existing.step()){const row=existing.getAsObject();existing.free();return{success:true,message:`Order is already in progress. Status: ${row.status}`,orderId:String(row.id)};}existing.free();}
  const stmt=db.prepare(`SELECT s.phone,ps.status,ps.leads_this_month,ps.tier FROM skills s JOIN memory_profiles m ON s.phone=m.phone LEFT JOIN provider_subscriptions ps ON s.phone=ps.phone WHERE s.skill=? AND s.is_available=1 AND ps.status='active' LIMIT 1`);stmt.bind([orderType]);if(stmt.step()){const row=stmt.getAsObject();const limit=row.tier==='Plus'?100:(row.tier==='Business'?1000:30);if(Number(row.leads_this_month)<limit)providerPhone=String(row.phone);}stmt.free();
  if(!providerPhone){const fallbackStmt=db.prepare(`SELECT s.phone FROM skills s LEFT JOIN provider_subscriptions ps ON s.phone=ps.phone WHERE s.is_available=1 AND ps.status='active' LIMIT 1`);if(fallbackStmt.step())providerPhone=String(fallbackStmt.getAsObject().phone);fallbackStmt.free();}
 }
 const idempotencyKey=details.idempotencyKey?String(details.idempotencyKey):null;if(idempotencyKey){const checkStmt=db.prepare('SELECT id,status FROM orders WHERE idempotency_key=?');checkStmt.bind([idempotencyKey]);if(checkStmt.step()){const existing=checkStmt.getAsObject();checkStmt.free();return{success:true,message:`Order retrieved from cache (idempotent). Status: ${existing.status}`,orderId:String(existing.id)};}checkStmt.free();}
 const clientStmt=db.prepare('SELECT subscription_tier FROM memory_profiles WHERE phone=?');clientStmt.bind([buyerPhone]);let clientTier='Base';if(clientStmt.step())clientTier=String(clientStmt.getAsObject().subscription_tier||'Base');clientStmt.free();if(!providerPhone)return{success:false,message:'No verified provider is currently available. Your request can remain deferred for re-matching.'};
 if(arg4!==undefined){const provSubStmt=db.prepare('SELECT tier,status,leads_this_month FROM provider_subscriptions WHERE phone=?');provSubStmt.bind([providerPhone]);if(provSubStmt.step()){const row=provSubStmt.getAsObject();const limit=row.tier==='Plus'?100:(row.tier==='Business'?1000:30);if(row.status!=='active'||Number(row.leads_this_month)>=limit){provSubStmt.free();return{success:false,message:'Provider subscription inactive or leads exhausted.'};}}else{provSubStmt.free();return{success:false,message:'Provider subscription inactive.'};}provSubStmt.free();}
 const isInstant=details.bookingMode==='instant'||!details.bookingMode;const orderId=`ord_${Math.floor(Math.random()*1000000)}`;const jobAmount=Number(details.amount||0);
 const leadCharge=await chargeProviderLead({providerPhone,category:getEconomicCategory(orderType)||undefined,skill:orderType,requestId:orderId});if(!leadCharge.success)return{success:false,message:`Provider lead requires ${await getLeadCharge(orderType)} Points before this lead can be accepted.`};db.run(`UPDATE provider_subscriptions SET leads_this_month=leads_this_month+1 WHERE phone=?`,[providerPhone]);
 if(!creditEconomyEnabled){if(jobAmount>0){const paid=await processDirectPayment(buyerPhone,providerPhone,jobAmount);if(!paid){db.run(`UPDATE provider_subscriptions SET leads_this_month=leads_this_month-1 WHERE phone=?`,[providerPhone]);return{success:false,message:'Fulfillment failed due to direct payment error.'};}}}else if(!isInstant&&jobAmount>0){const escrowDeducted=await processDirectPayment(buyerPhone,'ESCROW',jobAmount);db.run(`UPDATE provider_subscriptions SET leads_this_month=leads_this_month-1 WHERE phone=?`,[providerPhone]);if(!escrowDeducted)return{success:false,message:`Verified payment is required before escrow can be created. Required: ₦${jobAmount}.`};return{success:false,message:'Payment reference verification must complete through the Economic Request flow before escrow can be created.'};}
 db.run(`INSERT INTO orders (id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES (?,?,?,?,?,?,?)`,[orderId,buyerPhone,orderType,providerPhone,jobAmount,isInstant?'completed':'escrow_held',idempotencyKey]);db.run(`INSERT INTO audit_logs (action,details) VALUES (?,?)`,['order_finalized',JSON.stringify({orderId,buyerPhone,providerPhone,orderType,isInstant,clientTier,leadCharge})]);saveDb();return{success:true,message:`Matched successfully with verified provider.${isInstant?' Match complete.':' Escrow payment secured.'}`,orderId};
}
