export type PageState = 'loading' | 'ready' | 'empty' | 'pending' | 'needs_input' | 'success' | 'failure' | 'unavailable' | 'cancelled' | 'recovery';

export type PageContentContract = {
  purpose: string;
  audience: 'public' | 'authenticated' | 'admin' | 'shared';
  jobs: string[];
  sections: string[];
  actions: string[];
  states: PageState[];
  dataAuthority: string;
  truthBoundary?: string;
  seo: 'indexable' | 'noindex' | 'shared';
};

const c = (purpose: string, jobs: string[], sections: string[], actions: string[], states: PageState[], dataAuthority: string, truthBoundary?: string, audience: PageContentContract['audience'] = 'authenticated'): PageContentContract => ({ purpose, audience, jobs, sections, actions, states, dataAuthority, truthBoundary, seo: audience === 'authenticated' || audience === 'admin' ? 'noindex' : 'indexable' });

export const PAGE_CONTENT_CONTRACTS: Record<string, PageContentContract> = {
  desk: c('Personal operating home for knowing what matters and continuing work.', ['see what needs attention', 'resume conversations/goals', 'review active work', 'start something new'], ['welcome', 'attention queue', 'active goals', 'request summary', 'tasks/reminders summary', 'notifications summary', 'recent continuity', 'agent status', 'quick actions', 'context/recovery'], ['open chat', 'resume', 'inspect', 'create/continue', 'search'], ['loading','ready','empty','failure','recovery'], 'conversation + goal + request + reminder + notification authorities'),
  discover: c('Discover useful people, services, products, Topics and opportunities without overstating availability.', ['find something useful', 'compare options', 'inspect provenance', 'continue in Agent'], ['search/filter', 'results', 'source/provenance', 'availability truth', 'Topics', 'Opportunities', 'saved/follow state', 'location context', 'Agent handoff'], ['search', 'filter', 'inspect', 'save', 'continue in Agent'], ['loading','ready','empty','unavailable','failure'], 'discovery/presence/provider/opportunity authorities', 'Availability is never implied without current canonical evidence.', 'shared'),
  topics: c('Community knowledge and discussion separate from fulfilment claims.', ['browse', 'search', 'open discussion', 'reply/report', 'save'], ['categories', 'search', 'topic list', 'author/context', 'moderation/reporting', 'replies', 'related content', 'Agent continuation'], ['open', 'reply', 'report', 'save', 'continue in Agent'], ['loading','ready','empty','failure','recovery'], 'topic/content/moderation authorities', 'Community content is not provider/payment/fulfilment evidence.', 'shared'),
  requests: c('Manage canonical Economic Requests and their lifecycle.', ['see active/waiting/completed work', 'supply missing information', 'review evidence/quote', 'recover/cancel'], ['attention queue', 'active', 'waiting/deferred', 'needs input', 'completed', 'cancelled', 'detail', 'originating conversation', 'provider/evidence', 'quote/payment state', 'next action'], ['open detail', 'continue in Agent', 'supply information', 'cancel', 'retry/recover', 'dispute where supported'], ['loading','ready','empty','pending','needs_input','success','failure','cancelled','recovery'], 'economic request + quote + payment + provider evidence authorities', 'No payment or fulfilment success without canonical evidence.'),
  reminders: c('Keep scheduled help connected to conversations and notifications.', ['see due work', 'create', 'edit', 'pause', 'resume', 'cancel'], ['today', 'upcoming', 'overdue', 'completed', 'detail', 'originating context', 'notification state', 'recurrence'], ['create', 'edit', 'pause', 'resume', 'cancel', 'continue in Agent'], ['loading','ready','empty','pending','success','failure','cancelled'], 'reminder + notification authorities'),
  saved: c('Retain useful owner-scoped context for later.', ['find saved items', 'inspect source', 'reuse', 'remove stale content'], ['saved items', 'source/provenance', 'date', 'follow/watch', 'originating context', 'stale/unavailable treatment'], ['open', 'continue', 'remove', 'move to request/cart where permitted'], ['loading','ready','empty','unavailable','failure'], 'saved-items + memory/context authorities'),
  cart: c('Prepare sourced economic actions without implying payment success.', ['review items', 'compare provenance', 'edit/remove', 'connect to request', 'proceed to verified checkout'], ['cart groups', 'offer provenance', 'availability', 'quantity/options', 'request transition', 'price/summary', 'payment boundary', 'empty/error'], ['review', 'edit', 'remove', 'request/checkout', 'return to Agent'], ['loading','ready','empty','pending','needs_input','failure','recovery'], 'cart + economic offer + payment authorities', 'Cart presence is not payment success.'),
  tasks: c('Manage work and contribution tasks with evidence.', ['see work due', 'complete', 'pause/reschedule', 'attach evidence', 'return to source'], ['today', 'upcoming', 'overdue', 'completed', 'source', 'reminder relationship', 'agent relationship', 'evidence/artifact', 'detail'], ['complete', 'pause', 'reschedule', 'attach evidence', 'open originating context'], ['loading','ready','empty','pending','success','failure','recovery'], 'task + artifact + reminder authorities'),
  connect: c('Manage connected resources, channels and device/session readiness.', ['see connection health', 'connect', 'authorize', 'pair', 'revoke', 'recover'], ['storage', 'channels', 'linked devices', 'permissions', 'readiness', 'connection health', 'last sync', 'unsupported/unconfigured'], ['connect', 'pair', 'authorize', 'revoke', 'retry'], ['loading','ready','empty','pending','success','failure','unavailable','recovery'], 'connection + channel + integration authorities', 'Connection readiness is distinct from verified external activation.'),
  agents: c('Manage bounded autonomous workers and their goals.', ['inspect agent identity', 'see goals/runtime', 'control execution', 'review risk/evidence'], ['agent identity', 'goals', 'runtime state', 'tools/capabilities', 'risk/approval', 'usage/budget', 'pause/resume/cancel', 'retry/failure', 'evidence'], ['create goal', 'pause', 'resume', 'cancel', 'inspect'], ['loading','ready','empty','pending','success','failure','cancelled','recovery'], 'agent runtime + goal + policy authorities'),
  capabilities: c('Manage the roles and capabilities available under one identity.', ['see capability coverage', 'add/update', 'verify', 'manage availability'], ['roles', 'capabilities', 'evidence', 'availability', 'skill coverage', 'profile completeness', 'verification state'], ['add/update', 'verify', 'manage availability'], ['loading','ready','empty','pending','success','failure'], 'capability registry + profile + verification authorities'),
  opportunities: c('Review relevant ways to participate in the Kurukoo network.', ['inspect fit', 'see evidence', 'accept/decline/claim', 'continue in Agent'], ['source', 'fit/relevance', 'eligibility', 'evidence', 'invitation/claim state', 'related capability', 'expiration'], ['inspect', 'accept', 'decline', 'claim', 'continue in Agent'], ['loading','ready','empty','pending','success','failure','cancelled'], 'opportunity + discovery + capability authorities'),
  wallet: c('Show economic account state with clear boundaries between wallet, Points and external payment.', ['see balance', 'inspect ledger', 'review pending/failed', 'navigate to top-up/points/subscription'], ['balance', 'ledger', 'pending', 'failed', 'payment readiness', 'Points separation', 'subscription relationship'], ['inspect', 'top up', 'open Points', 'open subscriptions', 'recover'], ['loading','ready','empty','pending','failure','recovery'], 'wallet + payment + Points + subscription authorities', 'Wallet balance is not payment settlement evidence.'),
  points: c('Show the closed-loop Kurukoo Points economy.', ['see balance', 'inspect earn/spend history', 'understand qualifying actions'], ['balance', 'history', 'earn/spend', 'rewards', 'non-cash disclosure', 'reversal/dispute where applicable'], ['inspect', 'earn/spend where supported', 'view history'], ['loading','ready','empty','pending','failure'], 'Points + credit transaction authorities', 'Points are distinct from cash payment rails.'),
  'top-up': c('Prepare adding funds while accurately representing payment readiness.', ['choose amount', 'review readiness', 'authorize when supported', 'recover failure'], ['amount', 'payment method readiness', 'fees where canonical', 'review', 'confirmation', 'failure/retry', 'sandbox/unconfigured'], ['review', 'authorize', 'retry', 'return to Agent'], ['loading','ready','pending','success','failure','unavailable','recovery'], 'payment adapter + wallet authorities', 'Never claim successful charge without provider evidence.'),
  subscriptions: c('Manage plans and entitlements without implying billing success when rails are not active.', ['compare plans', 'inspect entitlements', 'change/cancel', 'recover billing issues'], ['current plan', 'features', 'renew/cancel/change', 'billing readiness', 'trial/expiry', 'payment evidence'], ['compare', 'subscribe/change', 'cancel', 'recover'], ['loading','ready','empty','pending','success','failure','unavailable','recovery'], 'pricing + subscription + payment authorities'),
  checkout: c('Review one canonical economic action before payment/confirmation.', ['verify request/offer', 'review quote', 'inspect evidence', 'confirm or recover'], ['request identity', 'offer/item', 'quantity', 'provider/evidence', 'price/quote', 'payment state', 'confirmation boundary', 'cancellation/recovery'], ['confirm', 'pay when available', 'edit/cancel', 'return to Agent'], ['loading','ready','pending','needs_input','success','failure','cancelled','recovery'], 'economic request + offer + payment authorities', 'Checkout must not manufacture external payment success.'),
  confirmations: c('Explain what actually happened and what can happen next.', ['understand outcome', 'inspect evidence', 'continue', 'repeat', 'dispute/recover'], ['request identity', 'lifecycle', 'evidence', 'payment', 'provider coordination', 'completion/cancellation', 'recovery', 'originating conversation'], ['continue', 'cancel', 'dispute', 'repeat', 'continue in Agent'], ['loading','ready','pending','success','failure','cancelled','recovery'], 'economic request + evidence + payment + notification authorities'),
  memory: c('Manage owner-scoped memory and its privacy/provenance boundary.', ['inspect memory', 'understand source/scope', 'revoke/delete', 'review proposed memory'], ['active facts', 'categories', 'provenance', 'scope', 'confidence', 'proposed/suggested', 'privacy/retention', 'empty/error'], ['inspect', 'revoke', 'delete', 'manage', 'continue in Agent'], ['loading','ready','empty','pending','success','failure','recovery'], 'memory profile + provenance authorities'),
  artifacts: c('Manage files, recordings and other owner-scoped artifacts.', ['browse', 'open/download', 'connect storage', 'delete/revoke'], ['files', 'recordings', 'transcripts', 'source', 'owner scope', 'storage readiness', 'retention'], ['open', 'download', 'delete', 'connect storage', 'continue in Agent'], ['loading','ready','empty','pending','success','failure','unavailable','recovery'], 'artifact + storage integration authorities'),
  prayer: c('Provide a continuity-aware prayer capability without creating a parallel identity or memory system.', ['start prayer', 'save', 'set reminder', 'use voice when supported'], ['current context', 'prayer content', 'routine/history', 'reminders', 'artifacts', 'voice boundary', 'privacy'], ['start', 'save', 'remind', 'voice'], ['loading','ready','empty','pending','success','failure','unavailable'], 'conversation + memory + reminder + artifact authorities'),
  call: c('Provide truthful realtime communication readiness and session state.', ['check readiness', 'start/end', 'recover connection', 'understand recording/artifact boundary'], ['AI voice readiness', 'peer-call readiness', 'consent', 'participant identity', 'session state', 'recovery', 'recording/artifact disclosure'], ['start', 'end', 'retry', 'inspect'], ['loading','ready','pending','success','failure','unavailable','recovery'], 'voice + WebRTC/channel readiness authorities'),
  notifications: c('Provide actionable notification continuity without fragmenting the user journey.', ['see urgent/action items', 'mark read', 'continue to object', 'manage permissions'], ['attention queue', 'requests', 'reminders', 'agent activity', 'network', 'read/unread', 'originating object', 'delivery/device permission'], ['open', 'mark read', 'continue', 'settings'], ['loading','ready','empty','pending','failure','unavailable','recovery'], 'notification queue + delivery/device authorities'),
  safety: c('Manage consent-bound safety/check-in context without implying emergency-service fulfilment.', ['see check-in state', 'manage trusted contacts', 'resolve overdue checks'], ['check-in status', 'trusted contacts', 'consent', 'overdue', 'resolution', 'emergency boundary', 'incident continuity'], ['start/update/end check-in', 'manage contacts', 'use emergency path'], ['loading','ready','empty','pending','success','failure','unavailable','recovery'], 'safety coordinator + trusted contact authorities', 'Safety UI must never imply emergency-service dispatch unless externally verified.'),
  settings: c('Centralize account, privacy, notification, connection and product preferences.', ['manage account', 'manage privacy', 'manage notifications', 'manage connected services', 'review product settings'], ['profile', 'authentication/security', 'privacy/memory', 'notifications', 'connections', 'preferences', 'accessibility', 'data/export/delete', 'danger zone'], ['edit', 'save', 'revoke', 'sign out', 'export/delete where supported'], ['loading','ready','empty','pending','success','failure','recovery'], 'identity + privacy + notification + connection authorities'),
};

export function getPageContentContract(section: string): PageContentContract {
  return PAGE_CONTENT_CONTRACTS[section] || c('Kurukoo product surface.', [], ['purpose-specific content', 'primary actions', 'states', 'navigation', 'recovery'], ['open', 'continue in Agent'], ['loading','ready','empty','failure','recovery'], 'canonical surface authority');
}
