/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import { CLIENT_SURFACES } from './clientSurfaceRegistry.js';

export type FeatureAudience = 'consumer' | 'provider' | 'business' | 'agent' | 'admin' | 'public';
export type VisualRepresentation = 'primary_nav' | 'secondary_nav' | 'icon_tooltip' | 'chat_card' | 'discover_card' | 'contextual_action' | 'modal_action' | 'status_chip' | 'admin_panel' | 'public_section';

export interface PlatformFeatureVisualContract {
  id: string;
  label: string;
  tooltip: string;
  icon: string;
  audience: FeatureAudience[];
  representations: VisualRepresentation[];
  webSurface: string;
  mobileSurface: string | null;
  action: string;
  canonicalOwner: string;
  discoverable: boolean;
}

const feature = (input: PlatformFeatureVisualContract) => input;

export const PLATFORM_FEATURE_VISUAL_CONTRACTS: readonly PlatformFeatureVisualContract[] = [
  feature({id:'chat',label:'Chat',tooltip:'Talk to Kurukoo and get help, coordination or action.',icon:'message-circle',audience:['consumer','provider','business'],representations:['primary_nav','chat_card'],webSurface:'/chat',mobileSurface:'/(tabs)/',action:'open_chat',canonicalOwner:'canonicalChatTurnService',discoverable:true}),
  feature({id:'discover',label:'Discover',tooltip:'Find useful things, people, products, offers and opportunities around you.',icon:'compass',audience:['consumer','provider','business'],representations:['primary_nav','discover_card'],webSurface:'/discover',mobileSurface:'/(tabs)/discover',action:'open_discover',canonicalOwner:'discoverExperience',discoverable:true}),
  feature({id:'daily_picks',label:'Daily Picks',tooltip:'See fresh things happening or available today.',icon:'sparkles',audience:['consumer','provider','business'],representations:['discover_card'],webSurface:'/discover',mobileSurface:'/(tabs)/discover',action:'open_daily_picks',canonicalOwner:'discoverCommercialComposition',discoverable:true}),
  feature({id:'nearby',label:'Nearby',tooltip:'See relevant people, businesses, services and opportunities near you.',icon:'map-pin',audience:['consumer'],representations:['discover_card','contextual_action'],webSurface:'/discover',mobileSurface:'/(tabs)/discover',action:'open_nearby',canonicalOwner:'discoveryNetwork',discoverable:true}),
  feature({id:'topics',label:'Topics',tooltip:'Follow, discuss and ask questions about things that matter.',icon:'messages-square',audience:['consumer','provider','business','public'],representations:['secondary_nav','discover_card','chat_card'],webSurface:'/topics',mobileSurface:null,action:'open_topics',canonicalOwner:'topicService',discoverable:true}),
  feature({id:'opportunities',label:'Opportunities',tooltip:'Discover jobs, requests, offers, gigs and ways to participate.',icon:'lightbulb',audience:['consumer','provider','business','agent'],representations:['secondary_nav','discover_card'],webSurface:'/opportunities',mobileSurface:null,action:'open_opportunities',canonicalOwner:'opportunityEngine',discoverable:true}),
  feature({id:'products',label:'Products',tooltip:'Find products from Kurukoo sellers, connected stores and affiliate sources.',icon:'shopping-bag',audience:['consumer','provider','business'],representations:['chat_card','discover_card','contextual_action'],webSurface:'/discover',mobileSurface:null,action:'open_product',canonicalOwner:'catalogueSourceRegistry',discoverable:true}),
  feature({id:'seller_offers',label:'Seller Offers',tooltip:'View products, prices and current seller availability.',icon:'store',audience:['consumer','provider','business'],representations:['chat_card','discover_card'],webSurface:'/discover',mobileSurface:null,action:'open_offer',canonicalOwner:'commercialCatalogService',discoverable:true}),
  feature({id:'ride_request',label:'Ride',tooltip:'Request a nearby vehicle, choose a vehicle type and track the trip.',icon:'car-front',audience:['consumer'],representations:['chat_card','contextual_action','status_chip'],webSurface:'/requests',mobileSurface:'/(tabs)/requests',action:'request_ride',canonicalOwner:'SkillExecutionContract:dispatch',discoverable:true}),
  feature({id:'delivery',label:'Delivery',tooltip:'Send or receive something with a matched delivery provider.',icon:'package',audience:['consumer','provider','business'],representations:['chat_card','contextual_action','status_chip'],webSurface:'/requests',mobileSurface:'/(tabs)/requests',action:'request_delivery',canonicalOwner:'SkillExecutionContract:dispatch',discoverable:true}),
  feature({id:'repairs',label:'Repairs',tooltip:'Find and coordinate repair services for devices, vehicles, appliances and more.',icon:'wrench',audience:['consumer'],representations:['chat_card','discover_card'],webSurface:'/chat',mobileSurface:'/(tabs)/',action:'request_repair',canonicalOwner:'skillBehaviourConvergence',discoverable:true}),
  feature({id:'bookings',label:'Bookings',tooltip:'Reserve providers, accommodation, events or other services.',icon:'calendar-check',audience:['consumer','business'],representations:['chat_card','status_chip'],webSurface:'/requests',mobileSurface:'/(tabs)/requests',action:'create_booking',canonicalOwner:'skillExecutionContract:booking',discoverable:true}),
  feature({id:'reminders',label:'Reminders',tooltip:'Remember something and let Kurukoo notify you at the right time.',icon:'bell-ring',audience:['consumer'],representations:['secondary_nav','icon_tooltip','status_chip'],webSurface:'/reminders',mobileSurface:null,action:'create_reminder',canonicalOwner:'reminderService',discoverable:true}),
  feature({id:'notifications',label:'Notifications',tooltip:'See important updates and actions that need your attention.',icon:'bell',audience:['consumer','provider','business'],representations:['secondary_nav','icon_tooltip'],webSurface:'/notifications',mobileSurface:null,action:'open_notifications',canonicalOwner:'pushNotifications',discoverable:true}),
  feature({id:'tasks',label:'Tasks',tooltip:'Track ongoing work, reminders and agent-driven tasks.',icon:'check-square',audience:['consumer','provider','business'],representations:['primary_nav','status_chip'],webSurface:'/work',mobileSurface:'/(tabs)/tasks',action:'open_tasks',canonicalOwner:'taskRoutes',discoverable:true}),
  feature({id:'agents',label:'AI Agents',tooltip:'Create and control agents that can represent you or your business within defined boundaries.',icon:'bot',audience:['consumer','provider','business'],representations:['primary_nav','secondary_nav','chat_card'],webSurface:'/agents',mobileSurface:null,action:'open_agents',canonicalOwner:'agentRuntime',discoverable:true}),
  feature({id:'agent_network',label:'Agent Network',tooltip:'Use or join Kurukoo agents who provide local services such as Points top-ups.',icon:'users-round',audience:['consumer','agent','provider'],representations:['discover_card','contextual_action','icon_tooltip'],webSurface:'/discover',mobileSurface:null,action:'open_agent_network',canonicalOwner:'agentNetworkCommerce',discoverable:true}),
  feature({id:'points',label:'Points',tooltip:'Use Kurukoo Points for eligible platform actions, boosts and provider lead access.',icon:'coins',audience:['consumer','provider','business','agent'],representations:['secondary_nav','status_chip','icon_tooltip'],webSurface:'/points',mobileSurface:null,action:'open_points',canonicalOwner:'pointsEngine',discoverable:true}),
  feature({id:'top_up',label:'Top Up',tooltip:'Add Kurukoo Points through an authorised payment or local Kurukoo agent.',icon:'wallet-cards',audience:['consumer','provider','business'],representations:['secondary_nav','contextual_action'],webSurface:'/top-up',mobileSurface:null,action:'top_up_points',canonicalOwner:'agentNetworkCommerce + payment',discoverable:true}),
  feature({id:'provider_leads',label:'Provider Leads',tooltip:'Receive eligible customer opportunities and pay the configured lead cost.',icon:'target',audience:['provider','business'],representations:['status_chip','icon_tooltip','admin_panel'],webSurface:'/requests',mobileSurface:'/(tabs)/requests',action:'open_provider_leads',canonicalOwner:'commercialLedger + pointsEngine',discoverable:true}),
  feature({id:'provider_communication',label:'Provider Communication',tooltip:'Message or speak with the matched provider inside the active request.',icon:'phone-call',audience:['consumer','provider'],representations:['chat_card','contextual_action','status_chip'],webSurface:'/call',mobileSurface:null,action:'open_provider_session',canonicalOwner:'providerCommunicationService',discoverable:true}),
  feature({id:'webrtc_call',label:'WebRTC Call',tooltip:'Use an in-app voice/video/data connection when the provider session is active.',icon:'video',audience:['consumer','provider'],representations:['contextual_action','icon_tooltip'],webSurface:'/call',mobileSurface:null,action:'start_webrtc_call',canonicalOwner:'webrtcSignalling',discoverable:true}),
  feature({id:'provider_tracking',label:'Provider Tracking',tooltip:'See provider movement and arrival state during supported trips or deliveries.',icon:'navigation',audience:['consumer','provider'],representations:['status_chip','contextual_action'],webSurface:'/call',mobileSurface:null,action:'open_tracking',canonicalOwner:'providerCommunicationSession + Trickbridge',discoverable:true}),
  feature({id:'masked_call_fallback',label:'Private Call Fallback',tooltip:'Use a protected external voice route when direct WebRTC communication is unavailable.',icon:'shield-phone',audience:['consumer','provider'],representations:['contextual_action','icon_tooltip'],webSurface:'/call',mobileSurface:null,action:'start_private_call',canonicalOwner:'providerCommunicationService + telephony adapter',discoverable:false}),
  feature({id:'reviews',label:'Reviews',tooltip:'Rate a completed provider interaction and leave feedback.',icon:'star',audience:['consumer','provider','business'],representations:['contextual_action','status_chip'],webSurface:'/requests',mobileSurface:'/(tabs)/requests',action:'leave_review',canonicalOwner:'trust/review lifecycle',discoverable:true}),
  feature({id:'checkout',label:'Checkout',tooltip:'Review and confirm an order, booking or economic commitment before payment.',icon:'credit-card',audience:['consumer'],representations:['secondary_nav','contextual_action'],webSurface:'/checkout',mobileSurface:null,action:'open_checkout',canonicalOwner:'checkout + economicRequest',discoverable:true}),
  feature({id:'subscriptions',label:'Subscriptions',tooltip:'Manage provider, business or agent service plans.',icon:'badge-dollar-sign',audience:['provider','business','consumer'],representations:['secondary_nav'],webSurface:'/subscriptions',mobileSurface:null,action:'open_subscriptions',canonicalOwner:'subscription',discoverable:true}),
  feature({id:'wallet',label:'Wallet',tooltip:'View eligible balances and payment/account activity.',icon:'wallet',audience:['consumer','provider','business'],representations:['secondary_nav','status_chip'],webSurface:'/wallet',mobileSurface:null,action:'open_wallet',canonicalOwner:'directWallet + payment',discoverable:true}),
  feature({id:'memory',label:'Memory',tooltip:'Review and manage the personal context Kurukoo can use to help you.',icon:'brain',audience:['consumer'],representations:['secondary_nav','icon_tooltip'],webSurface:'/memory',mobileSurface:null,action:'open_memory',canonicalOwner:'memoryProfile',discoverable:true}),
  feature({id:'safety',label:'Safety',tooltip:'Access safety tools, check-ins and trusted-contact controls.',icon:'shield',audience:['consumer'],representations:['secondary_nav','icon_tooltip','contextual_action'],webSurface:'/safety',mobileSurface:null,action:'open_safety',canonicalOwner:'safetyService',discoverable:true}),
  feature({id:'prayer',label:'Prayer Companion',tooltip:'Use Kurukoo’s in-house prayer/support agent and its conversation flow.',icon:'heart-handshake',audience:['consumer'],representations:['chat_card','secondary_nav'],webSurface:'/prayer',mobileSurface:null,action:'open_prayer',canonicalOwner:'prayerAgent',discoverable:true}),
  feature({id:'explore_capabilities',label:'Explore Kurukoo',tooltip:'See what Kurukoo can help you find, book, buy, remember or coordinate.',icon:'grid-2x2',audience:['public','consumer'],representations:['primary_nav','public_section','chat_card'],webSurface:'/explore',mobileSurface:'/(tabs)/',action:'open_explore',canonicalOwner:'capabilityRegistry + CLIENT_FEATURE_ENTRYPOINTS',discoverable:true}),
  feature({id:'help',label:'Help Centre',tooltip:'Get help with using Kurukoo and find guides for common tasks.',icon:'circle-help',audience:['public','consumer','provider','business'],representations:['secondary_nav','icon_tooltip','public_section'],webSurface:'/help',mobileSurface:null,action:'open_help',canonicalOwner:'contentRoutes + support',discoverable:true}),
  feature({id:'resources',label:'Resources',tooltip:'Read guides, how-to material and useful Kurukoo resources.',icon:'book-open',audience:['public','consumer','provider','business'],representations:['secondary_nav','public_section'],webSurface:'/resources',mobileSurface:null,action:'open_resources',canonicalOwner:'contentRoutes',discoverable:true}),
  feature({id:'blog',label:'Kuru Media',tooltip:'Read product updates, stories, guides and ecosystem content.',icon:'newspaper',audience:['public'],representations:['public_section'],webSurface:'/blog',mobileSurface:null,action:'open_blog',canonicalOwner:'contentRoutes',discoverable:true}),
  feature({id:'legal',label:'Legal & Privacy',tooltip:'Read Kurukoo’s terms, privacy, safety and legal information.',icon:'scale',audience:['public'],representations:['public_section','icon_tooltip'],webSurface:'/legal',mobileSurface:null,action:'open_legal',canonicalOwner:'publicRoutes',discoverable:true}),
  feature({id:'careers',label:'Careers',tooltip:'See roles and opportunities to work with Kurukoo.',icon:'briefcase-business',audience:['public'],representations:['public_section'],webSurface:'/careers',mobileSurface:null,action:'open_careers',canonicalOwner:'publicRoutes',discoverable:true}),
  feature({id:'partners',label:'Partners',tooltip:'Connect businesses, providers, technology partners and ecosystem participants.',icon:'handshake',audience:['public','provider','business'],representations:['public_section'],webSurface:'/partners',mobileSurface:null,action:'open_partners',canonicalOwner:'partnerRoutes',discoverable:true}),
  feature({id:'advertise',label:'Advertise on Kurukoo',tooltip:'Promote a product, offer or service in relevant Kurukoo discovery surfaces.',icon:'megaphone',audience:['provider','business'],representations:['public_section','contextual_action'],webSurface:'/advertise',mobileSurface:null,action:'create_promotion',canonicalOwner:'adManager',discoverable:true}),
  feature({id:'channels',label:'Channels',tooltip:'Connect to Kurukoo through web, mobile and supported external channels.',icon:'radio-tower',audience:['public','consumer','provider'],representations:['public_section','secondary_nav'],webSurface:'/channels',mobileSurface:'/(tabs)/connect',action:'open_channels',canonicalOwner:'channelRoutes + externalActivationService',discoverable:true}),
  feature({id:'qr_context',label:'QR Context',tooltip:'Open a specific Kurukoo context, provider, offer or conversation by scanning a QR code.',icon:'qr-code',audience:['consumer','provider','business'],representations:['icon_tooltip','contextual_action'],webSurface:'/start',mobileSurface:null,action:'scan_qr',canonicalOwner:'qrRouter',discoverable:true}),
  feature({id:'connect',label:'Connect',tooltip:'Connect devices, channels and approved external services to Kurukoo.',icon:'link-2',audience:['consumer','provider','business'],representations:['primary_nav','secondary_nav'],webSurface:'/connect',mobileSurface:'/(tabs)/connect',action:'open_connect',canonicalOwner:'connectionRoutes',discoverable:true}),
  feature({id:'admin_ai',label:'AI Operations',tooltip:'Monitor AI provider health, routing, telemetry and inference budgets.',icon:'activity',audience:['admin'],representations:['admin_panel'],webSurface:'/admin',mobileSurface:null,action:'open_admin_ai',canonicalOwner:'adminPlatformRoutes + AI telemetry',discoverable:false}),
  feature({id:'admin_credentials',label:'Provider Credentials',tooltip:'Securely rotate and test approved provider credentials.',icon:'key-round',audience:['admin'],representations:['admin_panel'],webSurface:'/admin',mobileSurface:null,action:'open_admin_credentials',canonicalOwner:'providerCredentialService',discoverable:false}),
  feature({id:'admin_unknown_intents',label:'AI Routing Review',tooltip:'Review privacy-safe unknown/ambiguous requests for routing improvement.',icon:'list-checks',audience:['admin'],representations:['admin_panel'],webSurface:'/admin',mobileSurface:null,action:'open_admin_routing_review',canonicalOwner:'unknownIntentReview + FastText',discoverable:false}),
] as const;

export function getPlatformFeatureVisualContract(id:string){ return PLATFORM_FEATURE_VISUAL_CONTRACTS.find(feature => feature.id === id); }
export function getDiscoverablePlatformFeatures(){ return PLATFORM_FEATURE_VISUAL_CONTRACTS.filter(feature => feature.discoverable); }
export function assertVisualFeatureSurfaces(){
  const known = new Set(CLIENT_SURFACES.map(surface => surface.route));
  const missing = PLATFORM_FEATURE_VISUAL_CONTRACTS.filter(feature => feature.webSurface && !known.has(feature.webSurface) && !feature.webSurface.startsWith('/admin/?'));
  if(missing.length) throw new Error(`Visual feature registry references unknown web surfaces: ${missing.map(f=>`${f.id}:${f.webSurface}`).join(', ')}`);
  return true;
}
