import crypto from 'node:crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { generateProxyNumber, releaseProxyNumber, getPrivacyBridgeStatus } from './privacyBridge.js';
import { createWebRTCRoom, destroyWebRTCRoom, getWebRTCStatus } from './webrtcSignalling.js';
import { placeTwilioMaskedCall, twilioVoiceStatus, type MaskedCallResult } from './twilioVoiceAdapter.js';
import { createTrickbridgeSession, endTrickbridgeSession, publishTrickbridgeLocation, trickbridgeStatus } from './trickbridgeTrackingAdapter.js';
import { ensureConversation } from './chatConversationService.js';

export type ProviderCommunicationState='created'|'ringing'|'connected'|'provider_en_route'|'arrived'|'in_progress'|'completed'|'ended'|'failed';
export type ProviderCommunicationMode='webrtc_tracking'|'masked_call'|'both';
export interface ProviderCommunicationSession {id:string;economicRequestId?:string;conversationId?:string;customerPhone:string;providerPhone:string;proxyPhone?:string;mode:ProviderCommunicationMode;state:ProviderCommunicationState;roomId?:string;callId?:string;callProvider?:string;trackingBridgeId?:string;lastLatitude?:number;lastLongitude?:number;lastLocationAt?:string;createdAt:string;updatedAt:string;}
async function ensureSchema():Promise<void>{const store=await getCanonicalStore();await store.run(`CREATE TABLE IF NOT EXISTS provider_communication_sessions (id TEXT PRIMARY KEY,economic_request_id TEXT,conversation_id TEXT,customer_phone TEXT NOT NULL,provider_phone TEXT NOT NULL,proxy_phone TEXT,mode TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'created',room_id TEXT,call_id TEXT,call_provider TEXT,tracking_bridge_id TEXT,last_latitude REAL,last_longitude REAL,last_location_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`);for(const sql of ['ALTER TABLE provider_communication_sessions ADD COLUMN conversation_id TEXT','ALTER TABLE provider_communication_sessions ADD COLUMN call_id TEXT','ALTER TABLE provider_communication_sessions ADD COLUMN call_provider TEXT','ALTER TABLE provider_communication_sessions ADD COLUMN tracking_bridge_id TEXT']){try{await store.run(sql);}catch{}}await store.run(`CREATE INDEX IF NOT EXISTS idx_provider_communication_request ON provider_communication_sessions(economic_request_id,updated_at DESC)`);await store.run(`CREATE INDEX IF NOT EXISTS idx_provider_communication_parties ON provider_communication_sessions(customer_phone,provider_phone,state)`);}
function rowToSession(row:Record<string,unknown>):ProviderCommunicationSession{return{id:String(row.id),economicRequestId:row.economic_request_id?String(row.economic_request_id):undefined,conversationId:row.conversation_id?String(row.conversation_id):undefined,customerPhone:String(row.customer_phone),providerPhone:String(row.provider_phone),proxyPhone:row.proxy_phone?String(row.proxy_phone):undefined,mode:String(row.mode) as ProviderCommunicationMode,state:String(row.state) as ProviderCommunicationState,roomId:row.room_id?String(row.room_id):undefined,callId:row.call_id?String(row.call_id):undefined,callProvider:row.call_provider?String(row.call_provider):undefined,trackingBridgeId:row.tracking_bridge_id?String(row.tracking_bridge_id):undefined,lastLatitude:row.last_latitude!==null&&row.last_latitude!==undefined?Number(row.last_latitude):undefined,lastLongitude:row.last_longitude!==null&&row.last_longitude!==undefined?Number(row.last_longitude):undefined,lastLocationAt:row.last_location_at?String(row.last_location_at):undefined,createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
function normalizedMode(mode:ProviderCommunicationMode|undefined):ProviderCommunicationMode{return mode||'webrtc_tracking';}
export async function createProviderCommunicationSession(input:{customerPhone:string;providerPhone:string;economicRequestId?:string;mode?:ProviderCommunicationMode}):Promise<ProviderCommunicationSession>{await ensureSchema();const customerPhone=String(input.customerPhone||'').trim(),providerPhone=String(input.providerPhone||'').trim();if(!customerPhone||!providerPhone||customerPhone.startsWith('anon_'))throw new Error('Authenticated customer and provider phones are required.');const mode=normalizedMode(input.mode);if((mode==='masked_call'||mode==='both')&&!twilioVoiceStatus().configured)throw new Error('Masked provider calling is not activated. Configure the approved telephony adapter before explicitly requesting it.');const id=`pcs_${crypto.randomUUID()}`;let proxyPhone:string|undefined,roomId:string|undefined,trackingBridgeId:string|undefined;if(mode==='masked_call'||mode==='both')proxyPhone=await generateProxyNumber(providerPhone,`provider:${input.economicRequestId||id}`);if(mode==='webrtc_tracking'||mode==='both'){if(getWebRTCStatus().enabled){roomId=`provider-session:${id}`;createWebRTCRoom(roomId,customerPhone);}const tracking=await createTrickbridgeSession({providerSessionId:id,providerPhone});trackingBridgeId=tracking.id;}const conversationId=await ensureConversation(customerPhone,undefined,'provider_session',undefined,true);await(await getCanonicalStore()).run(`INSERT INTO provider_communication_sessions (id,economic_request_id,conversation_id,customer_phone,provider_phone,proxy_phone,mode,state,room_id,tracking_bridge_id) VALUES (?, ?, ?, ?, ?, ?, ?, 'created', ?, ?)` ,[id,input.economicRequestId||null,conversationId,customerPhone,providerPhone,proxyPhone||null,mode,roomId||null,trackingBridgeId||null]);return{id,economicRequestId:input.economicRequestId,conversationId,customerPhone,providerPhone,proxyPhone,mode,state:'created',roomId,trackingBridgeId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
export async function getProviderCommunicationSession(id:string):Promise<ProviderCommunicationSession|null>{await ensureSchema();const row=await(await getCanonicalStore()).one<Record<string,unknown>>('SELECT * FROM provider_communication_sessions WHERE id=? LIMIT 1',[String(id||'')]);return row?rowToSession(row):null;}
export async function ensureProviderCommunicationConversation(id:string):Promise<ProviderCommunicationSession>{const current=await getProviderCommunicationSession(id);if(!current)throw new Error('Provider communication session not found.');if(current.conversationId)return current;const conversationId=await ensureConversation(current.customerPhone,undefined,'provider_session',undefined,true);await(await getCanonicalStore()).run(`UPDATE provider_communication_sessions SET conversation_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND (conversation_id IS NULL OR conversation_id='')`,[conversationId,current.id]);const next=await getProviderCommunicationSession(id);if(!next?.conversationId)throw new Error('Provider communication conversation could not be established.');return next;}
export async function updateProviderCommunicationState(id:string,state:ProviderCommunicationState):Promise<ProviderCommunicationSession>{await ensureSchema();if(!new Set<ProviderCommunicationState>(['created','ringing','connected','provider_en_route','arrived','in_progress','completed','ended','failed']).has(state))throw new Error('Unsupported provider communication state.');await(await getCanonicalStore()).run('UPDATE provider_communication_sessions SET state=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[state,id]);const session=await getProviderCommunicationSession(id);if(!session)throw new Error('Provider communication session not found.');return session;}
export async function startMaskedProviderCall(id:string):Promise<ProviderCommunicationSession>{await ensureSchema();const session=await getProviderCommunicationSession(id);if(!session)throw new Error('Provider communication session not found.');if(session.mode==='webrtc_tracking')throw new Error('This session does not permit masked calling.');const call:MaskedCallResult=await placeTwilioMaskedCall({customerPhone:session.customerPhone,providerPhone:session.providerPhone});await(await getCanonicalStore()).run(`UPDATE provider_communication_sessions SET call_id=?,call_provider=?,state='ringing',updated_at=CURRENT_TIMESTAMP WHERE id=?`,[call.callId,call.provider,id]);const next=await getProviderCommunicationSession(id);if(!next)throw new Error('Provider communication session not found after call start.');return next;}
export async function recordProviderLocation(id:string,latitude:number,longitude:number):Promise<ProviderCommunicationSession>{await ensureSchema();if(!Number.isFinite(latitude)||latitude<-90||latitude>90||!Number.isFinite(longitude)||longitude<-180||longitude>180)throw new Error('Valid coordinates are required.');const session=await getProviderCommunicationSession(id);if(!session)throw new Error('Provider communication session not found.');await(await getCanonicalStore()).run(`UPDATE provider_communication_sessions SET last_latitude=?,last_longitude=?,last_location_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,state=CASE WHEN state IN ('created','ringing','connected','provider_en_route') THEN 'provider_en_route' ELSE state END WHERE id=?`,[latitude,longitude,id]);try{if(session.trackingBridgeId)await publishTrickbridgeLocation({bridgeSessionId:session.trackingBridgeId,latitude,longitude});}catch(error){console.warn('[Trickbridge] Provider location update failed; canonical local state retained:',error instanceof Error?error.message:'unknown');}const next=await getProviderCommunicationSession(id);if(!next)throw new Error('Provider communication session not found.');return next;}
export async function endProviderCommunicationSession(id:string):Promise<ProviderCommunicationSession>{await ensureSchema();const session=await getProviderCommunicationSession(id);if(!session)throw new Error('Provider communication session not found.');if(session.roomId)destroyWebRTCRoom(session.roomId);if(session.trackingBridgeId)await endTrickbridgeSession(session.trackingBridgeId);if(session.proxyPhone)await releaseProxyNumber(session.proxyPhone).catch(()=>false);return updateProviderCommunicationState(id,'ended');}
export function getProviderCommunicationStatus():{maskedCall:ReturnType<typeof getPrivacyBridgeStatus>&{twilio?:ReturnType<typeof twilioVoiceStatus>};webrtc:ReturnType<typeof getWebRTCStatus>;trickbridge:ReturnType<typeof trickbridgeStatus>}{return{maskedCall:{...getPrivacyBridgeStatus(),twilio:twilioVoiceStatus()},webrtc:getWebRTCStatus(),trickbridge:trickbridgeStatus()};}
