import { getDb, saveDb } from '../database.js';
import { getEconomicRequest } from './skillFlows.js';
import { recalculateTrustScore } from './trustScore.js';

export interface ServiceReview { id:number; requestId:string; reviewerPhone:string; providerPhone:string; rating:number; feedback?:string; createdAt:string; }

async function ensureSchema(){const db=await getDb();db.run(`CREATE TABLE IF NOT EXISTS service_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT,request_id TEXT NOT NULL,reviewer_phone TEXT NOT NULL,provider_phone TEXT NOT NULL,rating INTEGER NOT NULL,feedback TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(request_id,reviewer_phone,provider_phone))`);db.run(`CREATE INDEX IF NOT EXISTS idx_service_reviews_provider ON service_reviews(provider_phone,created_at DESC)`);}

export async function createServiceReview(input:{requestId:string;reviewerPhone:string;providerPhone:string;rating:number;feedback?:string}):Promise<ServiceReview>{await ensureSchema();const request=await getEconomicRequest(input.requestId);if(!request)throw new Error('Economic request not found.');if(request.phone!==input.reviewerPhone)throw new Error('Only the request owner can submit the review.');if(String(request.status)!=='completed')throw new Error('Review is available after canonical completion.');const rating=Number(input.rating);if(!Number.isInteger(rating)||rating<1||rating>5)throw new Error('Rating must be an integer from 1 to 5.');const provider=String(input.providerPhone||'').trim();if(!provider)throw new Error('Provider is required.');const db=await getDb();const existing=db.exec('SELECT * FROM service_reviews WHERE request_id=? AND reviewer_phone=? AND provider_phone=? LIMIT 1',[input.requestId,input.reviewerPhone,provider]);if(existing[0]?.values?.length){const row=existing[0].values[0];return {id:Number(row[0]),requestId:String(row[1]),reviewerPhone:String(row[2]),providerPhone:String(row[3]),rating:Number(row[4]),feedback:row[5]?String(row[5]):undefined,createdAt:String(row[6])};}
db.run('INSERT INTO service_reviews (request_id,reviewer_phone,provider_phone,rating,feedback) VALUES (?,?,?,?,?)',[input.requestId,input.reviewerPhone,provider,rating,input.feedback?String(input.feedback).trim().slice(0,2000):null]);
const skill=String(request.skill||'');db.run(`UPDATE skills SET rating=CASE WHEN COALESCE(jobs_completed,0)>0 THEN ROUND(((COALESCE(rating,3)*MAX(COALESCE(jobs_completed,0)-1,0))+?)/MAX(COALESCE(jobs_completed,0),1),2) ELSE ? END WHERE phone=? AND skill=?`,[rating,rating,provider,skill]);
const row=db.exec('SELECT * FROM service_reviews WHERE request_id=? AND reviewer_phone=? AND provider_phone=? LIMIT 1',[input.requestId,input.reviewerPhone,provider])[0]?.values?.[0];const columns=db.exec('PRAGMA table_info(service_reviews)')[0]?.values||[];const object=columns.length&&row?Object.fromEntries(columns.map((column:any[],i:number)=>[String(column[1]),row[i]])):{};await recalculateTrustScore(provider,'service_review');return{id:Number(object.id||0),requestId:String(object.request_id||input.requestId),reviewerPhone:String(object.reviewer_phone||input.reviewerPhone),providerPhone:String(object.provider_phone||provider),rating:Number(object.rating||rating),feedback:object.feedback?String(object.feedback):undefined,createdAt:String(object.created_at||new Date().toISOString())};}
