import { getEconomicCategory, getKnownSkills } from './skillFlows.js';

export type SkillMarket = 'uk' | 'ng' | 'ca' | 'global';
export type SkillMode = 'economic' | 'information' | 'coordination' | 'safety';

export interface SkillExtension {
  skill: string;
  aliases: string[];
  baseSkill?: string;
  category: string;
  mode: SkillMode;
  markets: SkillMarket[];
  requirements: string[];
  optional: string[];
  subtypes?: string[];
  memoryKeys: string[];
  capabilities: string[];
  evidence: string[];
  failureModes: string[];
  notifications?: string[];
  commercial?: 'free' | 'quote' | 'transaction' | 'subscription' | 'mixed';
}

// Local-market additions are intentionally data-only. They reuse existing canonical
// capabilities/skills instead of creating another execution architecture.
export const LOCAL_SKILL_EXTENSIONS: SkillExtension[] = [
  { skill:'gp_appointment', aliases:['gp appointment','doctor appointment','nhs gp','book my gp'], baseSkill:'doctor_appointment', category:'health-medical', mode:'coordination', markets:['uk'], requirements:['practice or area','reason for appointment','preferred time'], optional:['patient preference','accessibility'], memoryKeys:['location','preferred_channel','accessibility'], capabilities:['discovery','availability','reservation','cancellation','completion'], evidence:['appointment confirmation'], failureModes:['practice unavailable','no appointment slot'], notifications:['appointment reminder'], commercial:'free' },
  { skill:'dentist_appointment', aliases:['dentist','dentist appointment','book dentist'], baseSkill:'doctor_appointment', category:'health-medical', mode:'coordination', markets:['uk','ng','ca'], requirements:['location','appointment need','preferred time'], optional:['new patient','insurance'], memoryKeys:['location','accessibility'], capabilities:['discovery','availability','reservation','cancellation','completion'], evidence:['appointment confirmation'], failureModes:['no accepting practice','no appointment slot'], notifications:['appointment reminder'], commercial:'mixed' },
  { skill:'mot_booking', aliases:['mot','mot test','mot booking'], baseSkill:'automotive-mechanics', category:'automotive-mechanics', mode:'coordination', markets:['uk'], requirements:['vehicle registration','preferred area','preferred date'], optional:['collection','repairs after test'], memoryKeys:['location','vehicle'], capabilities:['discovery','availability','reservation','payment','cancellation','completion'], evidence:['booking reference','test outcome where available'], failureModes:['no slot','vehicle details invalid'], notifications:['booking reminder'], commercial:'transaction' },
  { skill:'driving_test_booking', aliases:['driving test','driving test booking','book my driving test'], baseSkill:'government-civic', category:'government-civic', mode:'coordination', markets:['uk'], requirements:['test type','licence details','preferred area','earliest acceptable date'], optional:['automatic/manual','test-centre radius'], memoryKeys:['location','preferences'], capabilities:['discovery','availability','reservation','cancellation','completion'], evidence:['official booking reference'], failureModes:['no slot','eligibility issue'], notifications:['test reminder'], commercial:'free' },
  { skill:'school_admissions', aliases:['school place','school admissions','school application'], baseSkill:'government-civic', category:'government-civic', mode:'information', markets:['uk','ca','ng'], requirements:['child age/year','local area','school preference'], optional:['special educational needs','siblings'], memoryKeys:['location','family'], capabilities:['discovery','verification','evidence','completion'], evidence:['application guidance/source','submission confirmation where integrated'], failureModes:['no authoritative source','deadline passed'], notifications:['deadline reminder'], commercial:'free' },
  { skill:'snow_removal', aliases:['snow removal','snow plowing','clear my driveway'], baseSkill:'house_cleaner', category:'cleaning-sanitation', mode:'economic', markets:['ca'], requirements:['location','surface type','required clearance time'], optional:['depth','recurring service','salt/grit'], memoryKeys:['location','service_preferences','accessibility'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['service completion','before/after evidence where appropriate'], failureModes:['weather prevents service','no provider','access blocked'], notifications:['service window reminder'], commercial:'transaction' },
  { skill:'winter_tire_service', aliases:['winter tires','winter tyre change','tire change','tyre change'], baseSkill:'mechanic', category:'automotive-mechanics', mode:'economic', markets:['ca'], requirements:['vehicle make/model/year','location','service timing'], optional:['tire storage','mobile service','wheel balance'], memoryKeys:['vehicle','location'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','dispute','completion'], evidence:['service record','vehicle handover/return confirmation'], failureModes:['wrong fit','no appointment','parts/tires unavailable'], notifications:['appointment reminder'], commercial:'transaction' },
  { skill:'hydro_outage', aliases:['hydro outage','power outage','electricity outage canada'], baseSkill:'energy_tariff', category:'government-civic', mode:'information', markets:['ca'], requirements:['location or utility territory'], optional:['outage address','safety concern'], memoryKeys:['location'], capabilities:['discovery','verification','evidence','completion'], evidence:['utility status/source'], failureModes:['utility unknown','status unavailable'], notifications:['status update where supported'], commercial:'free' },
  { skill:'pos_agent', aliases:['pos agent','pos withdrawal','cashpoint agent','cash out'], baseSkill:'bill_payment_runner', category:'finance-tax', mode:'economic', markets:['ng'], requirements:['service needed','location','amount'], optional:['bank/network preference'], memoryKeys:['location','preferred_channel'], capabilities:['discovery','availability','quote','verification','payment','fulfillment','evidence','completion'], evidence:['transaction receipt'], failureModes:['agent unavailable','network failure','cash unavailable'], notifications:['transaction receipt'], commercial:'transaction' },
  { skill:'generator_fuel_delivery', aliases:['generator fuel','fuel delivery','diesel delivery','petrol delivery'], baseSkill:'delivery', category:'water-beverage', mode:'economic', markets:['ng'], requirements:['fuel type','quantity','location','needed time'], optional:['container/safety notes','generator type'], memoryKeys:['location','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['delivery confirmation'], failureModes:['fuel unavailable','delivery delay','unsafe location'], notifications:['delivery status'], commercial:'transaction' },
  { skill:'borehole_water', aliases:['borehole water','water tanker','water delivery','water supplier'], baseSkill:'tanker_water_supplier', category:'water-beverage', mode:'economic', markets:['ng','ca','uk'], requirements:['location','quantity','required time'], optional:['water use','tank capacity'], memoryKeys:['location','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['delivery confirmation','supplier evidence where available'], failureModes:['supplier unavailable','access issue','delay'], notifications:['delivery update'], commercial:'transaction' },
  { skill:'gas_refill', aliases:['gas refill','cooking gas','lpg refill'], baseSkill:'product_sourcing', category:'water-beverage', mode:'economic', markets:['ng'], requirements:['gas type','quantity/cylinder size','location'], optional:['pickup/delivery','urgency'], memoryKeys:['location'], capabilities:['discovery','availability','quote','verification','payment','fulfillment','tracking','evidence','cancellation','completion'], evidence:['delivery/pickup confirmation'], failureModes:['stock unavailable','unsafe handling'], notifications:['delivery update'], commercial:'transaction' },
  { skill:'parcel_pickup', aliases:['parcel pickup','collect my parcel','parcel dropoff'], baseSkill:'document_courier', category:'errands-delivery', mode:'economic', markets:['uk','ng','ca'], requirements:['pickup location','destination or carrier','parcel size','time'], optional:['tracking number','signature'], memoryKeys:['location','preferred_channel'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','tracking','evidence','cancellation','completion'], evidence:['handover','tracking','delivery confirmation'], failureModes:['parcel unavailable','identity mismatch','carrier restriction'], notifications:['pickup/dropoff updates'], commercial:'transaction' },
  { skill:'locksmith', aliases:['locksmith','locked out','door lock repair'], baseSkill:'find_worker', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca'], requirements:['location','lock problem','urgency'], optional:['property type','proof of occupancy','lock type'], memoryKeys:['location','property'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','dispute','completion'], evidence:['arrival','service record','customer completion'], failureModes:['no provider','ownership/occupancy cannot be established','security concern'], notifications:['arrival estimate'], commercial:'transaction' },
  { skill:'boiler_repairer', aliases:['boiler repair','boiler engineer','heating repair'], baseSkill:'boiler_service', category:'repairs-maintenance', mode:'economic', markets:['uk'], requirements:['location','boiler make/model if known','fault/symptoms','urgency'], optional:['heating/hot water impact','lease/landlord status'], memoryKeys:['location','property','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','dispute','completion'], evidence:['service record','safety status','completion'], failureModes:['no qualified provider','parts unavailable','unsafe installation state'], notifications:['appointment reminder'], commercial:'transaction' },
  { skill:'rubbish_removal', aliases:['rubbish removal','junk removal','waste removal','take this away'], baseSkill:'waste_collector', category:'cleaning-sanitation', mode:'economic', markets:['uk','ng','ca'], requirements:['location','waste type','estimated volume','time'], optional:['stairs/access','hazardous material'], memoryKeys:['location','property'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','completion'], evidence:['collection confirmation','waste receipt where applicable'], failureModes:['restricted waste','no vehicle','access issue'], notifications:['collection reminder'], commercial:'transaction' },
  { skill:'window_cleaner', aliases:['window cleaner','window cleaning'], baseSkill:'house_cleaner', category:'cleaning-sanitation', mode:'economic', markets:['uk','ng','ca'], requirements:['location','building type','windows/scope','timing'], optional:['height/access','inside/outside'], memoryKeys:['location','property','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','completion'], evidence:['service completion'], failureModes:['access unsafe','weather','no provider'], notifications:['service reminder'], commercial:'transaction' },
  { skill:'key_cutter', aliases:['key cutting','copy a key','duplicate key'], baseSkill:'find_worker', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca'], requirements:['location','key type','quantity'], optional:['restricted key evidence'], memoryKeys:['location'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','completion'], evidence:['handover'], failureModes:['restricted key','blank unavailable'], commercial:'transaction' },
  { skill:'laundry_pickup', aliases:['laundry pickup','wash and fold','laundry service'], baseSkill:'laundry_man', category:'personal-care', mode:'economic', markets:['uk','ng','ca'], requirements:['location','laundry volume/type','pickup time'], optional:['detergent preference','special fabrics','delivery time'], memoryKeys:['location','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','tracking','evidence','cancellation','completion'], evidence:['pickup','return','service receipt'], failureModes:['fabric restriction','lost item dispute','delay'], notifications:['pickup/return updates'], commercial:'transaction' },
  { skill:'market_shopper', aliases:['market shopper','market run','buy from market'], baseSkill:'grocery_shopper', category:'agriculture-produce', mode:'economic', markets:['ng','ca','uk'], requirements:['shopping list','location','budget','needed time'], optional:['brand preferences','substitutions'], memoryKeys:['location','service_preferences','shopping_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['purchase receipt','delivery/pickup confirmation'], failureModes:['item unavailable','price changes','substitution issue'], notifications:['shopping updates'], commercial:'transaction' },
  { skill:'school_run_uk', aliases:['school run','school pickup','school drop off'], baseSkill:'school_run', category:'transport-mobility', mode:'coordination', markets:['uk'], requirements:['pickup/dropoff locations','child age','schedule','authorized adults'], optional:['car seat needs','school contact details'], memoryKeys:['location','family','accessibility'], capabilities:['discovery','availability','verification','reservation','tracking','evidence','cancellation','completion'], evidence:['authorized driver verification','pickup/dropoff confirmation'], failureModes:['no verified driver','school schedule change','guardian authorization issue'], notifications:['pickup/dropoff notification'], commercial:'transaction' },
  { skill:'laptop_repairer', aliases:['laptop repair','macbook repair','computer repair'], baseSkill:'phone_repairer', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca','global'], requirements:['brand','model','issue','location'], optional:['operating system','power state','liquid/drop history','data sensitivity','pickup_required','deadline'], subtypes:['MacBook','Dell','Lenovo','HP','Acer','Asus','Microsoft Surface'], memoryKeys:['location','device_inventory','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','escrow','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['intake condition','diagnosis','repair record','functional test','return confirmation'], failureModes:['no compatible part','data risk','repair uneconomic','same-day unavailable'], notifications:['repair status'], commercial:'transaction' },
  { skill:'tablet_repairer', aliases:['tablet repair','ipad repair','galaxy tab repair'], baseSkill:'phone_repairer', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca','global'], requirements:['brand','model','issue','location'], optional:['pickup_required','return_required','deadline','parts_preference'], subtypes:['iPad','Samsung Galaxy Tab','Lenovo Tab','Microsoft Surface Go'], memoryKeys:['location','device_inventory'], capabilities:['discovery','availability','quote','verification','reservation','payment','escrow','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['intake','repair','functional test','return'], failureModes:['part unavailable','model mismatch','no provider'], notifications:['repair status'], commercial:'transaction' },
  { skill:'console_repairer', aliases:['console repair','playstation repair','ps5 repair','xbox repair','switch repair'], baseSkill:'phone_repairer', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca','global'], requirements:['console brand/model','fault','location'], optional:['disc/digital','controller issue','pickup_required'], subtypes:['PS5','PS4','Xbox Series','Xbox One','Nintendo Switch'], memoryKeys:['location','device_inventory'], capabilities:['discovery','availability','quote','verification','reservation','payment','escrow','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['intake','diagnosis','repair/test','return'], failureModes:['board-level fault','part unavailable','data/account concern'], notifications:['repair status'], commercial:'transaction' },
  { skill:'tv_repairer', aliases:['tv repair','television repair','smart tv repair'], baseSkill:'phone_repairer', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca','global'], requirements:['brand','model/size','fault','location'], optional:['wall mounted','collection/on-site','smart-tv/network issue'], subtypes:['Samsung','LG','Sony','TCL','Hisense','Panasonic'], memoryKeys:['location','property','device_inventory'], capabilities:['discovery','availability','quote','verification','reservation','payment','escrow','fulfillment','evidence','cancellation','dispute','completion'], evidence:['diagnosis','repair','functional test'], failureModes:['panel damage','parts unavailable','safe access issue'], notifications:['repair status'], commercial:'transaction' },
  { skill:'smartwatch_repairer', aliases:['smartwatch repair','apple watch repair','galaxy watch repair'], baseSkill:'phone_repairer', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca','global'], requirements:['brand','model','fault','location'], optional:['paired phone','water exposure','battery concern'], subtypes:['Apple Watch','Samsung Galaxy Watch','Garmin','Fitbit'], memoryKeys:['location','device_inventory'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','completion'], evidence:['diagnosis','repair/test'], failureModes:['water damage','part unavailable','pairing/data issue'], notifications:['repair status'], commercial:'transaction' },
  { skill:'earbuds_repairer', aliases:['earbuds repair','airpods repair','wireless earbuds repair'], baseSkill:'phone_repairer', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca','global'], requirements:['brand/model','left/right/both','fault','location'], optional:['case included','battery issue','pairing issue'], subtypes:['AirPods','Galaxy Buds','Sony','Bose'], memoryKeys:['location','device_inventory'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','completion'], evidence:['diagnosis','test'], failureModes:['sealed component','battery safety','parts unavailable'], notifications:['repair status'], commercial:'transaction' },
  { skill:'speaker_repairer', aliases:['speaker repair','bluetooth speaker repair','wireless speaker repair'], baseSkill:'phone_repairer', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca','global'], requirements:['brand/model','fault','location'], optional:['battery issue','water exposure','pickup'], subtypes:['JBL','Bose','Sonos','Sony'], memoryKeys:['location','device_inventory'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','completion'], evidence:['diagnosis','functional test'], failureModes:['battery safety','water damage','parts unavailable'], notifications:['repair status'], commercial:'transaction' },
  { skill:'appliance_repairer', aliases:['appliance repair','washing machine repair','fridge repair','oven repair','dishwasher repair'], baseSkill:'repair', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca'], requirements:['appliance type','brand/model if known','fault','location'], optional:['built-in/free-standing','power/gas/water','warranty','urgency'], subtypes:['washing machine','fridge','freezer','oven','dishwasher','dryer','microwave','air conditioner'], memoryKeys:['location','property','appliance_inventory','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','dispute','completion'], evidence:['diagnosis','repair record','safety test'], failureModes:['unsafe state','parts unavailable','warranty constraint'], notifications:['appointment reminder'], commercial:'transaction' },
  { skill:'bicycle_repairer', aliases:['bike repair','bicycle repair','cycle repair'], baseSkill:'repair', category:'automotive-mechanics', mode:'economic', markets:['uk','ng','ca'], requirements:['bike type','fault','location'], optional:['pickup','deadline','parts preference'], subtypes:['road bike','mountain bike','e-bike','cargo bike','city bike'], memoryKeys:['location','vehicle'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','completion'], evidence:['service record','test ride/functional check'], failureModes:['parts unavailable','unsafe frame damage'], notifications:['repair update'], commercial:'transaction' },
  { skill:'motorbike_repairer', aliases:['motorbike repair','motorcycle repair','bike mechanic'], baseSkill:'mechanic', category:'automotive-mechanics', mode:'economic', markets:['uk','ng','ca'], requirements:['make/model','fault','location','urgency'], optional:['recovery','registration','parts preference'], memoryKeys:['location','vehicle'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','tracking','evidence','cancellation','dispute','completion'], evidence:['diagnosis','repair record','test/return'], failureModes:['unsafe to ride','parts unavailable','recovery unavailable'], notifications:['repair status'], commercial:'transaction' },
  { skill:'vehicle_recovery', aliases:['vehicle recovery','breakdown recovery','tow truck','towing'], baseSkill:'towing_service', category:'emergency-dispatch', mode:'economic', markets:['uk','ng','ca'], requirements:['current location','vehicle type','problem','safe destination'], optional:['registration','insurance/provider membership'], memoryKeys:['location','vehicle','preferred_channel'], capabilities:['discovery','availability','verification','reservation','payment','tracking','fulfillment','evidence','cancellation','completion'], evidence:['arrival','handover','destination confirmation'], failureModes:['dangerous location','wrong vehicle type','no recovery unit'], notifications:['ETA/update'], commercial:'transaction' },
  { skill:'property_manager', aliases:['property manager','manage my rental','letting manager'], baseSkill:'house_agent', category:'property-real-estate', mode:'coordination', markets:['uk','ng','ca'], requirements:['property location','role/authority','service needed'], optional:['tenant details','contract/reference'], memoryKeys:['location','property','household'], capabilities:['discovery','verification','coordination','evidence','completion'], evidence:['provider/job record','communication log'], failureModes:['authority unclear','tenant/privacy issue'], notifications:['maintenance updates'], commercial:'mixed' },
  { skill:'childcare_search', aliases:['childcare','childminder','find childcare','daycare search'], baseSkill:'babysitter', category:'childcare-nanny', mode:'economic', markets:['uk','ng','ca'], requirements:['child age','location','schedule','care need'], optional:['special needs','food/allergy','transport','provider preferences'], memoryKeys:['location','family','accessibility'], capabilities:['discovery','availability','verification','quote','reservation','payment','cancellation','dispute','completion'], evidence:['provider verification','booking/attendance confirmation'], failureModes:['no suitable provider','verification incomplete','availability mismatch'], notifications:['care reminder'], commercial:'transaction' },
  { skill:'local_courier', aliases:['courier','local courier','same day courier'], baseSkill:'document_courier', category:'errands-delivery', mode:'economic', markets:['uk','ng','ca'], requirements:['pickup','destination','item','deadline'], optional:['size/weight','fragility','signature'], memoryKeys:['location','preferred_channel'], capabilities:['discovery','availability','quote','verification','reservation','payment','tracking','fulfillment','evidence','cancellation','dispute','completion'], evidence:['pickup','tracking','delivery proof'], failureModes:['route unavailable','size/weight issue','recipient unavailable'], notifications:['pickup/delivery updates'], commercial:'transaction' },
  { skill:'neighbourhood_handyman', aliases:['handyman','odd jobs','small repairs','general handyman'], baseSkill:'find_worker', category:'repairs-maintenance', mode:'economic', markets:['uk','ng','ca'], requirements:['job description','location','preferred time'], optional:['photos','materials','budget','access instructions'], memoryKeys:['location','property','service_preferences'], capabilities:['discovery','availability','quote','verification','reservation','payment','fulfillment','evidence','cancellation','dispute','completion'], evidence:['before/after where useful','completion confirmation'], failureModes:['job exceeds scope','materials unavailable','no provider'], notifications:['appointment reminder'], commercial:'transaction' },
];

export function getLocalSkillExtensions(): SkillExtension[] { return LOCAL_SKILL_EXTENSIONS; }
export function getSkillExtension(skill: string): SkillExtension | null { const key = skill.trim().toLowerCase(); return LOCAL_SKILL_EXTENSIONS.find(x => x.skill === key || x.aliases.some(a => a === key)) || null; }
export function getAllCatalogueSkillNames(): string[] { return [...new Set([...getKnownSkills(), ...LOCAL_SKILL_EXTENSIONS.map(x => x.skill)])]; }
export function getSkillCategoryConverged(skill: string): string | null { return getSkillExtension(skill)?.category || getEconomicCategory(skill); }
