/** Transaction orchestration for the shared Economic OS. */
import { getDb, saveDb } from '../database.js';
import { addPoints } from './pointsEngine.js';
import { ensureEscrowSchema, createEscrow, releaseEscrow } from './escrow.js';
import { find_worker } from './find-worker.js';
import { getEconomicRequest, transitionEconomicRequest, type EconomicRequest, type EconomicRequestStatus } from './skillFlows.js';
const MATCH_BATCH=25;
export interface OrchestrationResult{scanned:number;matched:number;quoted:number;escrowed:number;released:number;failed:number;errors:string[];}
async function listEconomicByStatus(statuses:EconomicRequestStatus[],limit=MATCH_BATCH):Promise<EconomicRequest[]>{const db=await getDb();db.run(`CREATE TABLE IF NOT EXISTS economic_requests (id TEXT PRIMARY KEY, phone TEXT NOT NULL, skill TEXT NOT NULL, category TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'requested', requirements_json TEXT NOT NULL DEFAULT '{}', capabilities_json TEXT NOT NULL DEFAULT '[]', provider_phone TEXT, quote_json TEXT, fulfillment_json TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);const placeholders=statuses.map(()=>'?').join(',');const stmt=db.prepare(`SELECT id FROM economic_requests WHERE status IN (${placeholders}) ORDER BY updated_at ASC LIMIT ?`);stmt.bind([...statuses,limit]);const ids:string[]=[];while(stmt.step())ids.push(String(stmt.getAsObject().id));stmt.free();const out:EconomicRequest[]=[];for(const id of ids){const req=await getEconomicRequest(id);if(req)out.push(req);}return out;}
async function orchestrateMatching(req:EconomicRequest):Promise<'matched'|'partial'|'none'>{const location=typeof req.requirements?.location==='string'?req.requirements.location:typeof req.requirements?.origin==='string'?String(req.requirements.origin):undefined;const result=await find_worker({skill:req.skill,location,max:5});if(result.count===0){if(req.status==='requested')await transitionEconomicRequest(req.id,'awaiting_match');return'none';}const top=result.providers[0];if(result.count===1){await transitionEconomicRequest(req.id,'matched',{providerPhone:top.phone});return'matched';}await transitionEconomicRequest(req.id,'partially_matched',{providerPhone:top.phone,fulfillment:{candidates:result.providers.map(p=>({phone:p.phone,name:p.name,rating:p.rating,hourly_rate:p.hourly_rate,verified:p.verified}))}});await transitionEconomicRequest(req.id,'matched',{providerPhone:top.phone});return'matched';}
async function orchestrateQuote(req:EconomicRequest):Promise<boolean>{let amountMinor:number|null=null;if(req.providerPhone){const db=await getDb();const stmt=db.prepare(`SELECT hourly_rate FROM skills WHERE phone=? AND lower(skill)=lower(?) LIMIT 1`);stmt.bind([req.providerPhone,req.skill]);if(stmt.step()){const rate=Number(stmt.getAsObject().hourly_rate||0);if(Number.isInteger(rate)&&rate>0)amountMinor=Math.round(rate);}stmt.free();}if(amountMinor===null)return false;const confirmedAmount=amountMinor;await transitionEconomicRequest(req.id,'quoting');await transitionEconomicRequest(req.id,'quoted',{quote:{amount_minor:confirmedAmount,currency:'NGN',skill:req.skill,provider_phone:req.providerPhone,source:'provider_listed_rate',indicative:true,generated_at:new Date().toISOString(),valid_for_hours:24}});return true;}
/** Creates the internal escrow ledger only after a trusted payment adapter has already marked the request paid and attached a verified payment reference. */
export async function lockEscrowForEconomicRequest(requestId:string,amountMinor?:number):Promise<{success:boolean;orderId?:string;escrowId?:number;message:string}>{const req=await getEconomicRequest(requestId);if(!req)return{success:false,message:'Economic request not found'};if(!req.providerPhone)return{success:false,message:'No provider matched yet'};if(req.status!=='paid')return{success:false,message:'Verified payment must be completed before escrow can be created'};const fulfillment=(req.fulfillment||{}) as Record<string,unknown>;if(fulfillment.payment_verified!==true||typeof fulfillment.payment_reference!=='string'||!String(fulfillment.payment_reference).trim())return{success:false,message:'No verified payment authorization is attached to this request'};const quoteAmount=amountMinor??(req.quote&&typeof(req.quote as any).amount_minor==='number'?Number((req.quote as any).amount_minor):null);if(!Number.isInteger(quoteAmount)||Number(quoteAmount)<=0)return{success:false,message:'A confirmed positive quote is required'};const confirmedAmount=Number(quoteAmount);const orderId=`eco_${requestId.slice(0,8)}_${Date.now()}`;const db=await getDb();db.run(`INSERT OR IGNORE INTO orders (id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES (?,?,?,?,?,?,?)`,[orderId,req.phone,req.skill,req.providerPhone,confirmedAmount,'escrow_held',`eco:${requestId}`]);const escrowId=await createEscrow(orderId,req.phone,req.providerPhone,confirmedAmount,`Escrow for economic request ${requestId} (${req.skill})`,{verified:true,paymentReference:String(fulfillment.payment_reference).trim()});try{await transitionEconomicRequest(requestId,'in_fulfillment',{fulfillment:{...fulfillment,order_id:orderId,escrow_id:escrowId,locked_at:new Date().toISOString()}});}catch{}saveDb();return{success:true,orderId,escrowId,message:'Verified payment received; escrow ledger created and request moved to fulfillment'};}
export async function completeEconomicRequest(requestId:string,evidence?:Record<string,unknown>):Promise<{success:boolean;message:string}>{const req=await getEconomicRequest(requestId);if(!req)return{success:false,message:'Economic request not found'};try{if(req.status==='in_fulfillment'||req.status==='paid')await transitionEconomicRequest(requestId,'fulfilled',{fulfillment:{...(req.fulfillment||{}),...(evidence||{}),fulfilled_at:new Date().toISOString()}});await transitionEconomicRequest(requestId,'completed');}catch(e){return{success:false,message:e instanceof Error?e.message:'Transition failed'};}const orderId=(req.fulfillment as any)?.order_id;if(orderId){const db=await getDb();db.run(`UPDATE orders SET status='delivered' WHERE id=? AND status IN ('escrow_held','paid','in_fulfillment','delivered')`,[orderId]);saveDb();}return{success:true,message:'Economic request completed; verified escrow release remains subject to the cooling-off policy'};}
export async function runEscrowPass():Promise<number>{const db=await getDb();await ensureEscrowSchema(db);let released=0;const stmt=db.prepare(`SELECT o.id AS order_id,e.id AS escrow_id,e.provider_phone,e.amount_minor FROM orders o JOIN escrow e ON o.id=e.order_id WHERE o.status IN ('delivered','completed') AND e.status='held' AND (e.cooling_off_until IS NULL OR datetime(e.cooling_off_until)<=datetime('now'))`);while(stmt.step()){const row=stmt.getAsObject() as any;try{if(!await releaseEscrow(Number(row.escrow_id)))continue;const marker=`escrow_release:${row.escrow_id}`;const tx=db.prepare(`SELECT id FROM credit_transactions WHERE description=? LIMIT 1`);tx.bind([marker]);const already=tx.step();tx.free();if(!already)await addPoints(String(row.provider_phone),Number(row.amount_minor),marker);db.run(`UPDATE orders SET status='completed' WHERE id=? AND status IN ('delivered','completed')`,[String(row.order_id)]);db.run(`UPDATE escrow SET completed_at=COALESCE(completed_at,CURRENT_TIMESTAMP) WHERE id=?`,[Number(row.escrow_id)]);released++;}catch(error){console.error(`[Transaction Engine] Failed escrow ${row.escrow_id}:`,error);}}stmt.free();saveDb();return released;}
export async function runOrchestrationPass():Promise<OrchestrationResult>{const result:OrchestrationResult={scanned:0,matched:0,quoted:0,escrowed:0,released:0,failed:0,errors:[]};try{const rows=await listEconomicByStatus(['requested','awaiting_match','partially_matched']);result.scanned+=rows.length;for(const req of rows){try{if(await orchestrateMatching(req)==='matched')result.matched++;}catch(e){result.failed++;result.errors.push(`match:${req.id}:${e instanceof Error?e.message:String(e)}`);}}}catch(e){result.errors.push(`match_batch:${e instanceof Error?e.message:String(e)}`);}try{const rows=await listEconomicByStatus(['matched']);result.scanned+=rows.length;for(const req of rows){try{if(await orchestrateQuote(req))result.quoted++;}catch(e){result.failed++;result.errors.push(`quote:${req.id}:${e instanceof Error?e.message:String(e)}`);}}}catch(e){result.errors.push(`quote_batch:${e instanceof Error?e.message:String(e)}`);}try{result.released=await runEscrowPass();}catch(e){result.errors.push(`escrow:${e instanceof Error?e.message:String(e)}`);}return result;}
export async function runEscrowPassLegacy():Promise<void>{await runOrchestrationPass();}
