import { getEconomicCategory, getKnownSkills, getSkillCapabilities, getSkillFlow, getSkillRequirements, type EconomicCapability, type SkillFlow } from './skillFlows.js';
import { listAgentTools } from './agentToolRegistry.js';
import { ensureCapabilityFoundation } from './capabilityFoundation.js';
import { listCapabilityRegistrations, getCapabilityRegistration } from './capabilityRegistry.js';

export type CapabilityMode = 'read_only' | 'conversation' | 'structured_action' | 'state_change' | 'external_execution';
export type UniversalCapabilityKind = 'skill' | 'operation' | 'agent_tool';
export type CapabilityRisk = 'read_only' | 'low_risk' | 'confirmation_required' | 'high_risk';
export type CapabilityResultStatus = 'accepted' | 'waiting' | 'needs_user' | 'confirmation_required' | 'blocked' | 'failed' | 'completed' | 'externally_pending' | 'unavailable_external_dependency';
export type CapabilityActivationState = 'locally_available' | 'repository_ready_external_activation' | 'unavailable_external_dependency' | 'intentionally_unsupported';

export interface UniversalCapabilityDescriptor {
  kind: UniversalCapabilityKind; capability: string; family: string; mode: CapabilityMode; actions: string[];
  context: { requiredInputs: Array<{ key: string; label: string; required: boolean }>; optionalInputs: Array<{ key: string; label: string; required: boolean }> };
  permissions: string[]; owner: string[]; risk: CapabilityRisk; consentRequired: boolean; confirmationRequired: boolean;
  lifecycle: string[]; canonicalFactsAvailable: string[]; executionStatus: string[]; evidenceStatus: string[]; nextAllowedActions: string[];
  failureStates: string[]; retryPolicy: string[]; recoveryActions: string[]; continuationContext: string[]; externalDependencyState: string[]; activationState: CapabilityActivationState;
}
export interface CapabilityActionProposal { capability: string; action: string; contextId?: string; canonicalObjectId?: string; arguments?: Record<string, unknown>; confidence?: number; reason?: string; confirmationRequired?: boolean; }
export interface CapabilityValidationResult { valid: boolean; code?: 'missing_capability' | 'unsupported_action' | 'invalid_confidence' | 'foreign_context' | 'stale_context' | 'missing_confirmation' | 'invalid_arguments'; message?: string; }
export interface UniversalCapabilityResult {
  status: CapabilityResultStatus;
  capability?: string;
  action?: string;
  contextId?: string;
  canonicalObjectId?: string;
  canonicalFacts: Record<string, unknown>;
  evidenceLevel: 'none' | 'internal_record' | 'canonical_service' | 'provider_evidence' | 'verified_external_evidence';
  externalActivation: CapabilityActivationState;
  nextActions: Array<{ action: string; label: string; confirmationRequired?: boolean }>;
  retryRecovery: Array<{ action: string; label: string }>;
  continuationContext?: Record<string, unknown>;
  message: string;
  executablePlan?: {
    skill: string;
    registeredSkill: string;
    composition: string[];
    executableCandidates: Array<{ capability: string; actions: string[]; owner: string[]; risk: string; activationState: string }>;
    unresolved: string[];
    cycle?: string[];
  };
}

const ACTIONS_BY_MODE: Record<CapabilityMode, string[]> = { read_only: ['read', 'open'], conversation: ['answer', 'clarify', 'continue'], structured_action: ['start', 'review', 'select', 'update', 'cancel', 'resume'], state_change: ['create', 'update', 'pause', 'resume', 'cancel', 'confirm'], external_execution: ['discover', 'quote', 'select', 'confirm', 'pay', 'execute', 'track', 'dispute', 'recover'] };
export const CANONICAL_CONTEXT_ACTIONS = new Set(['agent_goal:agent.goal.resume','agent_goal:agent.goal.review','agent_goal:agent.goal.pause','agent_goal:agent.goal.cancel','economic_request:economic_request.review_match','economic_request:economic_request.select_provider','economic_request:economic_request.update','economic_request:economic_request.cancel','notification:notification.open','notification:notification.dismiss','discovery_entity:discovery.context.open','memory_context:memory.context.forget','reminder:reminder.open','points:points.balance.open']);
export function isSupportedCanonicalContextAction(objectType: string | undefined, canonicalAction: string | undefined): boolean { return Boolean(objectType && canonicalAction && CANONICAL_CONTEXT_ACTIONS.has(`${objectType}:${canonicalAction}`)); }
const FAILURE_STATES = ['blocked', 'failed', 'unavailable_external_dependency', 'stale_context', 'foreign_context', 'confirmation_required'];
const LIFECYCLE_FOR_MODE: Record<CapabilityMode, string[]> = { read_only: ['requested', 'answered', 'completed', 'failed'], conversation: ['requested', 'clarifying', 'answered', 'follow_up', 'completed', 'failed'], structured_action: ['requested', 'clarifying', 'ready', 'completed', 'cancelled', 'failed'], state_change: ['requested', 'awaiting_confirmation', 'accepted', 'completed', 'cancelled', 'failed'], external_execution: ['requested', 'awaiting_match', 'quoted', 'awaiting_confirmation', 'payment_pending', 'executing', 'evidence_pending', 'completed', 'disputed', 'failed'] };
function modeFor(flow: SkillFlow | null, capabilities: EconomicCapability[]): CapabilityMode { if (flow?.mode === 'information') return 'read_only'; if (flow?.mode === 'safety') return 'conversation'; if (flow?.mode === 'coordination') return 'state_change'; if (capabilities.some(capability => ['payment','escrow','fulfillment','tracking','completion'].includes(capability))) return 'external_execution'; if (flow?.mode === 'economic' || capabilities.length) return 'structured_action'; return 'conversation'; }
function riskFor(mode: CapabilityMode, capabilities: EconomicCapability[]): CapabilityRisk { if (mode === 'read_only' || mode === 'conversation') return 'read_only'; if (capabilities.some(capability => ['payment','escrow','fulfillment','completion','dispute'].includes(capability))) return 'confirmation_required'; if (mode === 'external_execution') return 'confirmation_required'; return 'low_risk'; }
function activationFor(capabilities: EconomicCapability[], mode: CapabilityMode): CapabilityActivationState { if (mode === 'read_only' || mode === 'conversation') return 'locally_available'; if (capabilities.some(capability => ['discovery','payment','escrow','fulfillment','tracking','evidence'].includes(capability))) return 'repository_ready_external_activation'; return 'locally_available'; }
function ownersFor(flow: SkillFlow | null, capabilities: EconomicCapability[]): string[] { const owners = ['canonicalChatTurnService','intentRouter','skillFlows']; if (flow?.mode === 'economic' || capabilities.length) owners.push('economicRequestService','agenticStorefront'); if (capabilities.includes('discovery')) owners.push('discoveryNetwork','providerDiscovery'); if (capabilities.includes('payment') || capabilities.includes('escrow')) owners.push('paymentRoutes','escrow'); if (capabilities.includes('fulfillment') || capabilities.includes('tracking')) owners.push('executionConnector','notificationQueue'); if (flow?.mode === 'safety') owners.push('safetyService'); if (flow?.mode === 'coordination') owners.push('agentRuntime','notificationQueue'); return [...new Set(owners)]; }
function descriptorForSkill(skill: string, flow: SkillFlow | null): UniversalCapabilityDescriptor { const category = getEconomicCategory(skill) || 'uncategorized'; const declaredCapabilities = getSkillCapabilities(skill); const mode = modeFor(flow, declaredCapabilities); const capabilities = flow?.mode === 'information' ? [] : declaredCapabilities; const risk = riskFor(mode, capabilities); const requirements = getSkillRequirements(skill); const requiredInputs = requirements.filter(requirement => requirement.required).map(requirement => ({ key: requirement.key, label: requirement.label, required: true })); const optionalInputs = requirements.filter(requirement => !requirement.required).map(requirement => ({ key: requirement.key, label: requirement.label, required: false })); const capabilityActions: Record<string, string> = { discovery:'discover', availability:'check_availability', quote:'quote', verification:'verify', reservation:'reserve', payment:'pay', escrow:'authorize_escrow', contract:'review_contract', fulfillment:'fulfill', tracking:'track', evidence:'submit_evidence', cancellation:'cancel', dispute:'dispute', completion:'confirm_completion' }; const actions = [...new Set([...ACTIONS_BY_MODE[mode], ...capabilities.map(capability => capabilityActions[capability]).filter(Boolean)])]; const external = activationFor(capabilities, mode) === 'repository_ready_external_activation' ? ['External provider/payment/dispatch/evidence activation is not proven in this environment.'] : []; return { kind:'skill', capability:skill, family:category, mode, actions, context:{ requiredInputs, optionalInputs }, permissions:['authenticated_owner', ...(risk === 'read_only' ? [] : ['canonical_service_authorization'])], owner:ownersFor(flow, capabilities), risk, consentRequired:risk === 'confirmation_required', confirmationRequired:risk === 'confirmation_required', lifecycle:flow ? LIFECYCLE_FOR_MODE[mode] : ['requested','clarifying','failed'], canonicalFactsAvailable:['intent','requirements','canonical_object_identity','lifecycle','evidence','external_activation'], executionStatus:['not_started','accepted','waiting','needs_user','executing','completed','failed'], evidenceStatus:['none','internal_record','canonical_service','provider_evidence','verified_external_evidence'], nextAllowedActions:actions, failureStates:FAILURE_STATES, retryPolicy:['retry only through the canonical service','preserve the existing object and idempotency key','do not duplicate a request or payment'], recoveryActions:['clarify missing requirements','retry','resume','cancel','wait for external activation','escalate to an authorized operator'], continuationContext:['conversationId','contextId','canonicalObjectId','ownerScope','lifecycle','nextAllowedActions'], externalDependencyState:external, activationState:activationFor(capabilities, mode) }; }
const CANONICAL_OPERATION_DEFINITIONS: Array<{ capability:string; family:string; actions:string[]; owner:string[]; risk:CapabilityRisk; activationState:CapabilityActivationState }> = [
 { capability:'economic_request', family:'network-fulfilment', actions:['create','update','review_match','select_provider','cancel'], owner:['economicRequestService','canonicalChatTurnService'], risk:'low_risk', activationState:'locally_available' },
 { capability:'provider', family:'network-fulfilment', actions:['discover','select','quote'], owner:['discoveryNetwork','providerEntity','economicRequestService'], risk:'low_risk', activationState:'repository_ready_external_activation' },
 { capability:'payment', family:'economic-execution', actions:['authorize','confirm','refund'], owner:['stripePayment','paymentRoutes','escrow'], risk:'confirmation_required', activationState:'repository_ready_external_activation' },
 { capability:'reminder', family:'native-assistance', actions:['create','update','cancel','open'], owner:['reminderService','notificationQueue'], risk:'low_risk', activationState:'locally_available' },
 { capability:'subscription', family:'account', actions:['inspect','change'], owner:['subscriptionService','pricingService'], risk:'confirmation_required', activationState:'repository_ready_external_activation' },
 { capability:'agent', family:'agent-runtime', actions:['create','pause','resume','cancel'], owner:['agentRuntime'], risk:'confirmation_required', activationState:'locally_available' },
 { capability:'notification', family:'native-assistance', actions:['open','dismiss'], owner:['pushNotifications'], risk:'low_risk', activationState:'locally_available' },
 { capability:'memory', family:'native-assistance', actions:['store','forget'], owner:['memoryProfile','livingMemoryEngine'], risk:'confirmation_required', activationState:'locally_available' },
 { capability:'points', family:'economy', actions:['balance','claim','use'], owner:['pointsEngine'], risk:'confirmation_required', activationState:'locally_available' },
 { capability:'referral', family:'network-growth', actions:['invite','claim'], owner:['referralService'], risk:'low_risk', activationState:'locally_available' },
 { capability:'qr', family:'context', actions:['context'], owner:['qrContextService'], risk:'read_only', activationState:'locally_available' },
 { capability:'order', family:'commerce', actions:['create'], owner:['orderRoutes','orderFinalizer','economicRequestService'], risk:'confirmation_required', activationState:'repository_ready_external_activation' },
 { capability:'product', family:'commerce', actions:['select'], owner:['productSourcing','agenticStorefront'], risk:'low_risk', activationState:'repository_ready_external_activation' },
 { capability:'topic', family:'community', actions:['create','reply'], owner:['topicService'], risk:'low_risk', activationState:'locally_available' },
 { capability:'content', family:'public-content', actions:['open'], owner:['contentManager'], risk:'read_only', activationState:'locally_available' },
 { capability:'channel', family:'communications', actions:['send','continue'], owner:['channelRegistry','channelUsageService'], risk:'confirmation_required', activationState:'repository_ready_external_activation' },
 { capability:'execution', family:'external-execution', actions:['dispatch','view'], owner:['executionConnector','connectedResourceService'], risk:'confirmation_required', activationState:'repository_ready_external_activation' },
 { capability:'emergency', family:'emergency-dispatch', actions:['assess','location','dial','connect','end','followup'], owner:['emergencyService','canonicalChatTurnService','voiceBoundary','webrtcSignalling'], risk:'high_risk', activationState:'repository_ready_external_activation' },
];
function operationDescriptor(definition: typeof CANONICAL_OPERATION_DEFINITIONS[number]): UniversalCapabilityDescriptor { const confirmationRequired = definition.risk === 'confirmation_required'; const readOnlyActions = new Set(['view','inspect','open','context']); const allReadOnly = definition.actions.every(action => readOnlyActions.has(action)); const risk = allReadOnly ? 'read_only' : definition.risk; return { kind:'operation', capability:definition.capability, family:definition.family, mode:risk === 'read_only' ? 'read_only' : definition.activationState === 'repository_ready_external_activation' ? 'external_execution' : 'state_change', actions:definition.actions, context:{ requiredInputs:[], optionalInputs:[] }, permissions:definition.capability === 'emergency' ? ['guest_initial_help','authenticated_owner'] : ['authenticated_owner'], owner:definition.owner, risk, consentRequired:risk !== 'read_only' && confirmationRequired, confirmationRequired:risk !== 'read_only' && confirmationRequired, lifecycle:['requested','awaiting_confirmation','accepted','waiting','executing','completed','cancelled','failed'], canonicalFactsAvailable:['canonical_object_identity','lifecycle','evidence','external_activation'], executionStatus:['not_started','accepted','waiting','needs_user','executing','completed','failed'], evidenceStatus:['none','internal_record','canonical_service','provider_evidence','verified_external_evidence'], nextAllowedActions:definition.actions, failureStates:FAILURE_STATES, retryPolicy:['retry only through the canonical owner','preserve idempotency and exact identity','do not duplicate external effects'], recoveryActions:['clarify missing requirements','retry','resume','cancel','wait for activation','escalate'], continuationContext:['conversationId','contextId','canonicalObjectId','ownerScope','lifecycle'], externalDependencyState:definition.activationState === 'repository_ready_external_activation' ? ['External activation and evidence are not proven in this environment.'] : [], activationState:definition.activationState }; }
export function getCanonicalOperationDescriptor(capability: string): UniversalCapabilityDescriptor | undefined { ensureCapabilityFoundation(); const registration = getCapabilityRegistration(capability); if (registration) return registration.descriptor; const direct = CANONICAL_OPERATION_DEFINITIONS.find(item => item.capability === capability); return direct ? operationDescriptor(direct) : undefined; }
export async function listUniversalCapabilities(): Promise<UniversalCapabilityDescriptor[]> { ensureCapabilityFoundation(); const rows: UniversalCapabilityDescriptor[] = []; const seen = new Set<string>(); for (const registration of listCapabilityRegistrations()) { const descriptor = registration.descriptor as UniversalCapabilityDescriptor; if (descriptor.kind !== 'skill' && !seen.has(descriptor.capability)) { rows.push(descriptor); seen.add(descriptor.capability); } } for (const definition of CANONICAL_OPERATION_DEFINITIONS) { const descriptor = operationDescriptor(definition); if (!seen.has(descriptor.capability)) { rows.push(descriptor); seen.add(descriptor.capability); } } for (const skill of getKnownSkills()) { const descriptor = descriptorForSkill(skill, await getSkillFlow(skill)); if (!seen.has(descriptor.capability)) { rows.push(descriptor); seen.add(descriptor.capability); } } for (const tool of listAgentTools()) { const descriptor: UniversalCapabilityDescriptor = { kind:'agent_tool', capability:`agent.${tool.name}`, family:'agent-runtime', mode:tool.permission === 'read' ? 'read_only' : 'state_change', actions:['inspect','invoke','wait','resume','recover'], context:{ requiredInputs:Object.keys(tool.inputSchema).map(key => ({ key, label:key, required:true })), optionalInputs:[] }, permissions:[tool.authorization], owner:['agentRuntime','agentToolRegistry'], risk:tool.risk === 'read_only' ? 'read_only' : tool.risk === 'reversible' ? 'low_risk' : 'confirmation_required', consentRequired:tool.risk !== 'read_only', confirmationRequired:tool.risk === 'user_confirmation_required' || tool.risk === 'high_risk', lifecycle:['planned','waiting','needs_user','running','completed','failed','cancelled'], canonicalFactsAvailable:['goal','owner','timeline','tool_evidence'], executionStatus:['not_started','accepted','waiting','executing','completed','failed'], evidenceStatus:['none','internal_record','canonical_service'], nextAllowedActions:['inspect','invoke','wait','resume','recover'], failureStates:FAILURE_STATES, retryPolicy:['respect tool idempotency and runtime flags','retry only through agentRuntime'], recoveryActions:['wait','resume','pause','cancel','request user confirmation'], continuationContext:['goalId','conversationId','ownerScope'], externalDependencyState:[], activationState:tool.autonomous ? 'locally_available' : 'repository_ready_external_activation' }; if (!seen.has(descriptor.capability)) { rows.push(descriptor); seen.add(descriptor.capability); } } return rows; }
export function validateCapabilityProposal(proposal: CapabilityActionProposal, descriptor: UniversalCapabilityDescriptor | undefined, options: { ownerVerified:boolean; objectVerified:boolean; stale:boolean; confirmationGranted:boolean }): CapabilityValidationResult { if (!descriptor) return { valid:false, code:'missing_capability', message:'The requested capability is not registered.' }; if (!proposal.action || !descriptor.actions.includes(proposal.action)) return { valid:false, code:'unsupported_action', message:'That action is not supported by the canonical capability.' }; if (proposal.confidence !== undefined && (!Number.isFinite(proposal.confidence) || proposal.confidence < 0 || proposal.confidence > 1)) return { valid:false, code:'invalid_confidence', message:'The action proposal confidence is invalid.' }; if (proposal.contextId && !options.ownerVerified) return { valid:false, code:'foreign_context', message:'The referenced context is not owned by the current user.' }; if (proposal.canonicalObjectId && !options.objectVerified) return { valid:false, code:'foreign_context', message:'The referenced canonical object is not owned by the current user.' }; if (options.stale) return { valid:false, code:'stale_context', message:'The referenced context is no longer active.' }; if (proposal.confirmationRequired && !options.confirmationGranted) return { valid:false, code:'missing_confirmation', message:'This action requires explicit user confirmation.' }; if (proposal.arguments && Object.values(proposal.arguments).some(value => typeof value === 'function' || typeof value === 'symbol')) return { valid:false, code:'invalid_arguments', message:'The action arguments are not valid.' }; return { valid:true }; }
export function projectCapabilityResult(input: { capability?: string; action?: string; contextId?: string; canonicalObjectId?: string; cardData?: any; message:string; activationState?: CapabilityActivationState }): UniversalCapabilityResult { const card=input.cardData||{}; const raw=String(card.status||card.stage||card.state||'').toLowerCase(); const status: CapabilityResultStatus=input.activationState === 'unavailable_external_dependency' ? 'unavailable_external_dependency' : raw.includes('complete') || raw === 'completed' || raw === 'fulfilled' ? 'completed' : raw.includes('confirm') || raw === 'awaiting_confirmation' ? 'confirmation_required' : raw.includes('fail') || raw.includes('error') || raw === 'cancelled' ? 'failed' : raw.includes('wait') || raw.includes('pending') || raw.includes('match') ? 'waiting' : card.actions?.length ? 'needs_user' : 'accepted'; const externalActivation=input.activationState || (card.externalActivationState as CapabilityActivationState) || 'locally_available'; const nextActions=Array.isArray(card.actions)?card.actions.map((item:any)=>({ action:String(item.id||item.action||'continue'), label:String(item.label||item.title||item.id||'Continue'), confirmationRequired:Boolean(item.confirmationRequired) })):[]; const recovery=status==='failed'||status==='unavailable_external_dependency'?[{action:'retry',label:'Retry through the canonical service'},{action:'resume',label:'Keep this exact context and resume later'},{action:'cancel',label:'Cancel without creating a duplicate'}]:[]; return { status, capability:input.capability, action:input.action, contextId:input.contextId, canonicalObjectId:input.canonicalObjectId||card.requestId||card.goalId||card.objectId, canonicalFacts:{...card,status:card.status||card.stage||card.state||undefined}, evidenceLevel:card.evidenceLevel||card.evidence?'canonical_service':'none', externalActivation, nextActions, retryRecovery:recovery, continuationContext:{contextId:input.contextId,canonicalObjectId:input.canonicalObjectId||card.requestId||card.goalId||card.objectId,ownerScoped:true,lifecycle:card.status||card.stage||card.state||'active'}, message:input.message }; }
