apiVersion: v1
kind: Service
metadata:
  name: kurukoo
  namespace: kurukoo
spec:
  selector:
    app.kubernetes.io/name: kurukoo
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
