/**
 * Cross-client implementation contract for platform work added after the Expo
 * shell was created. This is deliberately a contract/registry, not a second
 * backend authority: native surfaces call the canonical web/API owners.
 */
export type MobileCapabilityArea =
  | "discover" | "chat" | "notifications" | "agents" | "economic_requests" | "memory"
  | "provider_network" | "ai_runtime" | "safety" | "credentials" | "admin"
  | "commerce" | "catalogue" | "communications";

export type MobileCapabilityStatus = "implemented" | "client_ready" | "server_only" | "external_required" | "admin_only";
export interface MobileCapabilityContract { id:string; area:MobileCapabilityArea; title:string; status:MobileCapabilityStatus; canonicalOwner:string; nativeRoute:string|null; api:string[]; notes:string; }

export const MOBILE_PLATFORM_CONTRACTS: readonly MobileCapabilityContract[] = [
  { id:"discover",area:"discover",title:"Discover / Daily Picks / Topics / Opportunities / Products / Agent Network",status:"implemented",canonicalOwner:"src/services/discoverExperience.ts + src/services/discoverCommercialComposition.ts",nativeRoute:"/(tabs)/discover",api:["/api/discover/home","/api/discover/category/:category","/api/discover/items/:type/:id/actions","/api/discover/promotions/:id/impression","/api/discover/promotions/:id/click"],notes:"Native consumes the same canonical feed, category placements and watch/follow/save action boundary as web." },
  { id:"chat-routing",area:"chat",title:"Canonical Chat and AI routing",status:"implemented",canonicalOwner:"src/services/canonicalChatTurnService.ts + src/services/fastTextService.ts + src/services/aiInferencePolicy.ts",nativeRoute:"/(tabs)/chat",api:["/api/chat/stream","/api/chat/messages","/api/chat/feedback"],notes:"Mobile never routes independently; backend remains the sole turn authority." },
  { id:"notifications",area:"notifications",title:"Notifications and background continuation",status:"client_ready",canonicalOwner:"src/services/pushNotificationsCanonical.ts + internal_notifications",nativeRoute:"/surface/notifications",api:["canonical notification endpoints"],notes:"Existing Expo notifications framework can receive Watch, reminder, request, lead and continuation events without a parallel queue." },
  { id:"agents",area:"agents",title:"First-class agents and bounded inference budgets",status:"client_ready",canonicalOwner:"src/services/agentRuntime.ts + src/services/agentInferenceBudgetService.ts",nativeRoute:"/surface/agents",api:["agent canonical routes"],notes:"Budget enforcement and authority remain server-side." },
  { id:"economic-requests",area:"economic_requests",title:"Economic Request lifecycle",status:"client_ready",canonicalOwner:"src/services/skillFlows.ts + economic request services",nativeRoute:"/surface/requests",api:["canonical Economic Request routes"],notes:"Payment, quote, escrow and evidence stay server-owned." },
  { id:"memory",area:"memory",title:"Owner-scoped Memory",status:"client_ready",canonicalOwner:"src/services/memoryProfile.ts + livingMemoryEngine",nativeRoute:"/surface/memory",api:["canonical memory routes"],notes:"Native never creates a competing memory store." },
  { id:"provider-network",area:"provider_network",title:"Provider discovery, verification and trust",status:"external_required",canonicalOwner:"src/services/discoveryNetwork.ts + providerVerificationLifecycle.ts",nativeRoute:"/surface/provider-network",api:["/api/discover/*","canonical provider verification routes"],notes:"UI can be built now; live provider availability/verification depends on backend evidence and deployment." },
  { id:"ai-runtime",area:"ai_runtime",title:"AI provider health, quotas, telemetry and fallback",status:"server_only",canonicalOwner:"src/services/unifiedAiEngine.ts + src/services/aiInferencePolicy.ts + provider health/quota services",nativeRoute:null,api:[],notes:"Operator telemetry belongs in protected Admin surfaces." },
  { id:"safety",area:"safety",title:"Safety, check-ins and escalation boundaries",status:"client_ready",canonicalOwner:"src/services/safetyService.ts",nativeRoute:"/surface/safety",api:["canonical safety routes"],notes:"Preserve explicit consent and trusted-contact boundaries." },
  { id:"provider-credentials",area:"credentials",title:"Provider credential lifecycle",status:"admin_only",canonicalOwner:"src/services/providerCredentialService.ts",nativeRoute:null,api:[],notes:"Secrets remain operator-only." },
  { id:"admin-convergence",area:"admin",title:"AI telemetry, provider health, agent budgets and platform controls",status:"admin_only",canonicalOwner:"src/routes/adminRoutes.ts + adminPlatformRoutes.ts",nativeRoute:null,api:[],notes:"Web Admin remains canonical." },
  { id:"commerce-network",area:"commerce",title:"Points, POS agents, provider lead charges and agent commissions",status:"client_ready",canonicalOwner:"src/services/pointsEngine.ts + src/services/agentNetworkCommerce.ts + src/services/commercialLedger.ts",nativeRoute:"/surface/commerce",api:["/api/agent-network/*","/api/commercial/*","canonical Points routes"],notes:"Top-up settlement requires verified payment evidence; provider lead charging stays tied to Economic Request matching." },
  { id:"catalogue",area:"catalogue",title:"Provider / business / WhatsApp / store / affiliate product inventory",status:"client_ready",canonicalOwner:"src/services/catalogueSourceRegistry.ts + src/services/catalogueInventoryMatcher.ts",nativeRoute:"/surface/catalogue",api:["/api/catalogue/sources","/api/catalogue/products","/api/catalogue/products/search","/api/discover/home","/api/discover/category/:category"],notes:"All sources converge into one catalogue authority; user declarations remain unverified until source evidence exists." },
  { id:"provider-communications",area:"communications",title:"Masked provider calling and real-time provider session/tracking",status:"external_required",canonicalOwner:"src/services/providerCommunicationService.ts + privacyBridge.ts + webrtcSignalling.ts + trickbridgeTrackingAdapter.ts",nativeRoute:"/surface/provider-communication",api:["/api/provider-communication/*","/api/webrtc/*","/api/voice/*"],notes:"Native UI can be built against canonical session/location state; live telephony and external tracking activate only through approved adapters." },
] as const;
export function getMobileCapability(id:string):MobileCapabilityContract|undefined{return MOBILE_PLATFORM_CONTRACTS.find(item=>item.id===id);}
export function assertMobileContractComplete(expectedIds:readonly string[]):void{const known=new Set(MOBILE_PLATFORM_CONTRACTS.map(item=>item.id));const missing=expectedIds.filter(id=>!known.has(id));if(missing.length)throw new Error(`Missing native platform contracts: ${missing.join(", ")}`);}
