import { useRouterState, Link } from "@tanstack/react-router";
import { Bell, Briefcase, ChevronLeft, ChevronRight, Compass, Brain, MapPin, MessageSquare, Sparkles, Tags, Target, Wallet, Zap } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { cn } from "@/lib/utils";
import { useKurukoo } from "@/lib/kurukoo-store";
import { fetchPulseReadiness, type PulseReadiness } from "@/lib/kurukoo-api";

type Icon = typeof Bell;
function Section({ title, icon: Icon, to, children }: { title: string; icon: Icon; to: string; children: ReactNode }) { return <section className="rounded-2xl border border-border bg-surface p-3"><div className="flex items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><Icon className="size-3.5 text-muted-foreground"/><h2 className="truncate text-[12.5px] font-semibold">{title}</h2></div><Link to={to as never} className="text-[10px] text-muted-foreground hover:text-foreground">Open</Link></div><div className="mt-2">{children}</div></section>; }
function Row({ icon: Icon, title, detail, to, live = false }: { icon: Icon; title: string; detail: string; to?: string; live?: boolean }) { const row=<div className="flex min-w-0 items-center gap-2.5 rounded-xl px-1.5 py-1.5"><span className={cn("grid size-7 shrink-0 place-items-center rounded-full",live?"bg-brand-tint text-brand-ink":"bg-elevated text-muted-foreground")}><Icon className="size-3.5"/></span><div className="min-w-0"><p className="truncate text-[11.5px] font-medium">{title}</p><p className="truncate text-[10px] text-muted-foreground">{detail}</p></div></div>; return to?<Link to={to as never} className="block rounded-xl hover:bg-elevated">{row}</Link>:row; }

export function ContextualTrustedRail({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const pathname = useRouterState({ select: (state) => state.location.pathname });
  const { work, memory, notifications } = useKurukoo();
  const [readiness, setReadiness] = useState<PulseReadiness | null>(null);
  const focus = work.find((item) => item.stage !== "done");
  const unread = notifications.filter((item) => !item.read).length;
  useEffect(() => { let cancelled=false; const load=()=>void fetchPulseReadiness().then((v)=>{if(!cancelled)setReadiness(v)}).catch(()=>{if(!cancelled)setReadiness(null)}); load(); const id=window.setInterval(load,30000); return ()=>{cancelled=true;window.clearInterval(id)}; }, []);
  const live = Boolean(readiness?.active); const eligible = Boolean(readiness?.eligibleToBroadcast);
  const workRow = focus ? <Row icon={Target} title={focus.title} detail={focus.stage === "needs_you" ? "Needs you" : "In progress"} to={"/work/" + focus.id} /> : <p className="px-1.5 py-2 text-[10px] text-muted-foreground">Nothing in motion.</p>;
  const defaultContent = <><Section title="What matters now" icon={Target} to="/desk"><Row icon={Target} title="For You" detail="Personal operating view"/><Row icon={Briefcase} title="Current work" detail={focus?.title ?? "No active work"}/></Section><Section title="Nearby Radar" icon={MapPin} to="/discover"><Row icon={Zap} title={live?"Live on Pulse":"Radar ready"} detail={live?"Your availability is visible nearby":"Useful local signals when available"} live/></Section><Section title="Memory" icon={Brain} to="/memory"><Row icon={Brain} title={memory.length?`${memory.length} active detail${memory.length===1?"":"s"}:` : "No active details"} detail="Private continuity"/></Section><Section title="Attention" icon={Bell} to="/activity"><Row icon={Bell} title={unread?`${unread} unread`:"Caught up"} detail="What needs your attention"/></Section></>;
  const nearbyContent = <><Section title="Your availability" icon={MapPin} to="/discover"><Row icon={Zap} title={live?"Live on Nearby Pulse":eligible?"Ready to Go Live":"Radar ready"} detail={live?"Your public presence is on":eligible?"Choose when to be discoverable":"Local attention is ready"} live={live}/></Section><Section title="Local attention" icon={Target} to="/activity"><Row icon={MapPin} title="Radar" detail="Useful signals nearby"/><Row icon={Tags} title="Local world" detail="Places, people, offers, events"/></Section><Section title="Your work" icon={Briefcase} to="/work">{workRow}</Section></>;
  const topicsContent = <><Section title="Topic context" icon={Tags} to="/topics"><Row icon={Tags} title="Community discussion" detail="Not provider or fulfilment proof"/><Row icon={MapPin} title="Nearby" detail="Local activity" to="/discover"/></Section><Section title="Opportunities" icon={Target} to="/opportunities"><Row icon={Sparkles} title="Ways to participate" detail="Useful network signals"/></Section><Section title="Explore" icon={Compass} to="/explore"><Row icon={Compass} title="Wider network" detail="People, providers, businesses"/></Section></>;
  const workContent = <><Section title="Current work" icon={Briefcase} to="/work">{workRow}</Section><Section title="Availability" icon={MapPin} to="/discover"><Row icon={Zap} title={live?"Live on Nearby Pulse":eligible?"Ready to Go Live":"Not live"} detail={live?"Nearby visibility on":eligible?"Choose when to broadcast":"Availability stays private"} live={live}/></Section><Section title="Messages & attention" icon={MessageSquare} to="/messages"><Row icon={Bell} title={unread?`${unread} unread`:"Caught up"} detail="Notifications and conversations"/></Section></>;
  const creatorContent = <><Section title="Channel activity" icon={Sparkles} to="/creators"><Row icon={MessageSquare} title="Audience" detail="Viewer activity and discussion"/></Section><Section title="Relevant Topics" icon={Tags} to="/topics"><Row icon={Tags} title="Topic placement" detail="Community context"/></Section><Section title="Monetisation" icon={Wallet} to="/wallet"><Row icon={Wallet} title="Earnings" detail="Value flows and payouts"/></Section></>;
  const businessContent = <><Section title="Your availability" icon={MapPin} to="/discover"><Row icon={Zap} title={live?"Live on Nearby Pulse":eligible?"Ready to Go Live":"Availability"} detail={live?"People nearby can discover you":"Choose when you are discoverable"} live={live}/></Section><Section title="Your work" icon={Briefcase} to="/work">{workRow}</Section><Section title="Commercial context" icon={Tags} to="/businesses"><Row icon={Tags} title="Products & offers" detail="What people can discover"/></Section><Section title="Attention" icon={Bell} to="/activity"><Row icon={Bell} title={unread?`${unread} unread`:"Nothing urgent"} detail="What needs attention"/></Section></>;
  let content = defaultContent;
  if (pathname.startsWith("/discover")) content=nearbyContent;
  else if (pathname.startsWith("/topics")) content=topicsContent;
  else if (pathname.startsWith("/work")) content=workContent;
  else if (pathname.startsWith("/creators")) content=creatorContent;
  else if (pathname.startsWith("/businesses") || pathname.startsWith("/providers")) content=businessContent;
  return <aside aria-label="Trusted context" className={cn("relative sticky top-0 hidden h-[calc(100vh-50px)] flex-col border-l border-border bg-surface py-4 lg:flex",open?"w-[224px] px-3":"w-[48px] px-1.5")}><button type="button" onClick={()=>onOpenChange(!open)} aria-label={open?"Close trusted context":"Open trusted context"} className="absolute left-0 top-5 z-10 grid size-9 -translate-x-1/2 place-items-center rounded-full border border-border bg-surface text-muted-foreground shadow-[var(--shadow-soft)] hover:bg-elevated">{open?<ChevronRight className="size-[17px]"/>:<ChevronLeft className="size-[17px]"/>}</button>{open?<div className="space-y-3">{content}</div>:null}</aside>;
}
