import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import { AuthModal, type AuthMode } from "@/components/kurukoo/auth";
import { PublicRail, RotatingPublicPrompt } from "@/components/public-kurukoo-rail";
import { PublicContextRail } from "@/components/public-kurukoo-context";
import { PublicMobileNavigation } from "@/components/public-kurukoo-mobile-nav";
export { PublicHome } from "@/components/public-kurukoo-home";

const nav = [["/explore", "Explore"], ["/discover", "Nearby"], ["/how-it-works", "How it works"], ["/capabilities", "Capabilities"], ["/topics", "Topics"]] as const;
const footer = [["/about", "About"], ["/blog", "Blog"], ["/help", "Help"], ["/legal", "Legal"]] as const;
const routerDestinations = new Set(["/explore", "/discover", "/capabilities", "/topics", "/about", "/blog", "/help", "/login", "/signup", "/how-it-works", "/contributors", "/partners", "/pricing", "/contact", "/use-cases", "/opportunities", "/advertising", "/topics"]);
function KurukooMark({ className = "size-6" }: { className?: string }) { return <span aria-hidden className={`grid shrink-0 place-items-center rounded-[10px] bg-brand-tint font-semibold leading-none text-brand-ink ${className}`}>K</span>; }
function PublicDestinationLink({ to, children, className, active = false }: { to: string; children: ReactNode; className: string; active?: boolean }) { if (!routerDestinations.has(to)) return <a href={to} className={className}>{children}</a>; return <Link to={to as never} activeProps={active ? { className: "text-foreground" } : undefined} className={className}>{children}</Link>; }
export function PublicKurukooShell({ children }: { children: ReactNode }) {
  const pathname = useRouterState({ select: (state) => state.location.pathname }); const navigate = useNavigate(); const routeMode: AuthMode | null = pathname === "/login" ? "login" : pathname === "/signup" ? "signup" : null; const [authMode, setAuthMode] = useState<AuthMode | null>(routeMode); const [railCollapsed, setRailCollapsed] = useState(false); useEffect(() => { setAuthMode(routeMode); }, [routeMode]); const openAuth = (mode: AuthMode) => setAuthMode(mode); const closeAuth = () => { setAuthMode(null); if (routeMode) navigate({ to: "/" }); };
  return <div className="min-h-screen overflow-hidden bg-background">
    <header className="sticky top-0 z-50 border-b border-border/70 bg-background/95 backdrop-blur"><div className="relative flex h-[50px] items-center px-5 md:px-7 lg:px-8"><Link to="/" className="flex shrink-0 items-center gap-2" aria-label="Kurukoo home"><KurukooMark className="size-8"/><span className="text-[17px] font-semibold tracking-[-0.025em]">Kurukoo</span></Link><nav aria-label="Kurukoo" className="absolute left-1/2 hidden -translate-x-1/2 items-center justify-center gap-7 text-[12.5px] text-muted-foreground md:flex">{nav.map(([to,label], index)=><><PublicDestinationLink key={to} to={to} active className="transition-colors hover:text-foreground">{label}</PublicDestinationLink>{index===nav.length-1?<RotatingPublicPrompt key="rotating-prompt"/>:null}</>)}</nav><div className="ml-auto flex items-center gap-2"><button type="button" onClick={()=>openAuth("login")} className="rounded-full px-3 py-1.5 text-[12px] font-medium text-muted-foreground hover:bg-elevated hover:text-foreground">Log In</button><button type="button" onClick={()=>openAuth("signup")} className="rounded-full bg-foreground px-3.5 py-1.5 text-[12px] font-medium text-background">Try for free</button></div></div></header>
    <div className={`h-[calc(100vh-50px)] min-h-0 overflow-hidden md:grid ${railCollapsed ? "md:grid-cols-[76px_minmax(0,1fr)]" : "md:grid-cols-[200px_minmax(0,1fr)]"}`}>
      <PublicRail collapsed={railCollapsed} onToggle={()=>setRailCollapsed((value)=>!value)} onAuth={openAuth}/>
      <div className="min-h-0 h-full overflow-y-auto scrollbar-none"><div className="grid min-h-full lg:grid-cols-[minmax(0,1fr)_224px]"><main className="flex min-w-0 min-h-full flex-col"><div className="mx-auto w-full max-w-[1120px] flex-1 px-5 py-9 md:px-8 md:py-12">{children}</div><footer className="sticky bottom-0 z-20 mx-auto flex w-full max-w-[1120px] flex-wrap items-center justify-between gap-3 border-t border-border/60 bg-background/95 px-5 py-7 text-[11px] text-muted-foreground backdrop-blur md:px-8"><p>Kurukoo · conversation-first coordination</p><nav aria-label="Information"><div className="flex flex-wrap gap-x-4 gap-y-2">{footer.map(([to,label])=><PublicDestinationLink key={to} to={to} className="hover:text-foreground">{label}</PublicDestinationLink>)}</div></nav></footer></main><aside className="hidden min-w-0 lg:block border-l border-border/45"><PublicContextRail/></aside></div></div>
    </div>
    <PublicMobileNavigation onAuth={openAuth}/>{authMode?<AuthModal mode={authMode} onClose={closeAuth} onModeChange={setAuthMode}/>:null}
  </div>;
}
