import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import initSqlJs from 'sql.js';

const require = createRequire(import.meta.url);

type Sql = any;

type MigrationOptions = {
  sourcePath: string;
  connectionString?: string;
  execute: boolean;
  verifyOnly: boolean;
};

function loadPostgres(): ((connectionString: string, options?: Record<string, unknown>) => Sql) | null {
  try {
    const module = require('postgres') as { default?: (connectionString: string, options?: Record<string, unknown>) => Sql } | ((connectionString: string, options?: Record<string, unknown>) => Sql);
    return (typeof module === 'function' ? module : module.default) || null;
  } catch {
    return null;
  }
}

function parseArgs(): MigrationOptions {
  const args = new Set(process.argv.slice(2));
  const sourcePath = process.env.DB_PATH || path.join(process.cwd(), 'kurukoo.sqlite');
  return {
    sourcePath,
    connectionString: process.env.DATABASE_URL || process.env.POSTGRES_URL,
    execute: args.has('--execute'),
    verifyOnly: args.has('--verify-only'),
  };
}

function translateSqliteDdl(sql: string): string {
  let ddl = sql.trim().replace(/^CREATE TABLE( IF NOT EXISTS)?/i, match => match);
  ddl = ddl.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  ddl = ddl.replace(/\bINT\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  ddl = ddl.replace(/\bAUTOINCREMENT\b/gi, '');
  ddl = ddl.replace(/\bDATETIME\b/gi, 'TEXT');
  ddl = ddl.replace(/\bBLOB\b/gi, 'BYTEA');
  return ddl;
}

async function readSourceDatabase(sourcePath: string) {
  if (!fs.existsSync(sourcePath)) throw new Error(`Source SQL.js database does not exist: ${sourcePath}`);
  const SQL = await initSqlJs();
  const db = new SQL.Database(fs.readFileSync(sourcePath));
  const tables = db.exec("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL ORDER BY name")[0]?.values || [];
  const records = tables.map(row => {
    const name = String(row[0]);
    const ddl = String(row[1]);
    const columns = db.exec(`PRAGMA table_info("${name.replace(/"/g, '""')}")`)[0]?.values || [];
    const rows = db.exec(`SELECT * FROM "${name.replace(/"/g, '""')}"`)[0];
    return { name, ddl, columns, rows: rows?.values || [], columnNames: rows?.columns || [] };
  });
  return { db, records };
}

function importantIntegrityChecks(records: Array<{ name: string; columnNames: string[]; rows: unknown[][] }>) {
  const checks = ['memory_profiles', 'messages', 'economic_requests', 'internal_notifications', 'orders', 'agent_goals', 'agent_goal_events', 'execution_requests'];
  return checks.map(name => {
    const table = records.find(item => item.name === name);
    return { table: name, present: Boolean(table), rows: table?.rows.length ?? 0, columns: table?.columnNames.length ?? 0 };
  });
}

async function executeImport(sql: Sql, records: Array<{ name: string; ddl: string; rows: unknown[][]; columnNames: string[] }>) {
  await sql.begin(async (tx: Sql) => {
    for (const record of records) {
      await tx.unsafe(translateSqliteDdl(record.ddl));
    }
    for (const record of records) {
      if (!record.rows.length || !record.columnNames.length) continue;
      const columns = record.columnNames.map(column => `"${column.replace(/"/g, '""')}"`).join(', ');
      const table = `"${record.name.replace(/"/g, '""')}"`;
      for (const row of record.rows) {
        const values = record.columnNames.map((_, index) => row[index]);
        const placeholders = values.map((_, index) => `$${index + 1}`).join(', ');
        await tx.unsafe(`INSERT INTO ${table} (${columns}) VALUES (${placeholders})`, values);
      }
    }
  });
}

async function verifyDestination(sql: Sql, checks: ReturnType<typeof importantIntegrityChecks>) {
  const results = [];
  for (const check of checks) {
    if (!check.present) {
      results.push({ ...check, destinationRows: 0, matches: false });
      continue;
    }
    const rows = await sql.unsafe(`SELECT COUNT(*)::bigint AS count FROM "${check.table}"`);
    const destinationRows = Number(rows[0]?.count || 0);
    results.push({ ...check, destinationRows, matches: destinationRows === check.rows });
  }
  return results;
}

const options = parseArgs();
const { records } = await readSourceDatabase(options.sourcePath);
const checks = importantIntegrityChecks(records);

console.log(JSON.stringify({
  source: options.sourcePath,
  schemaVersion: '2026-08-22-canonical-runtime-schema',
  mode: options.execute ? 'execute' : 'dry-run',
  tableCount: records.length,
  checks,
  note: 'No live migration is performed unless --execute is explicitly supplied. Dry-run never connects to PostgreSQL.',
}, null, 2));

if (options.verifyOnly && !options.connectionString) process.exit(0);
if (!options.execute) process.exit(0);
if (!options.connectionString) throw new Error('DATABASE_URL or POSTGRES_URL is required for --execute.');

const factory = loadPostgres();
if (!factory) throw new Error('PostgreSQL client is not installed. Install the pinned postgres dependency before executing a migration.');

const sql = factory(options.connectionString, {
  max: 2,
  connect_timeout: 10,
  ssl: String(process.env.KURUKOO_POSTGRES_SSL || 'true').toLowerCase() !== 'false' ? 'require' : false,
});
try {
  await sql`SELECT 1`;
  await executeImport(sql, records);
  const verification = await verifyDestination(sql, checks);
  if (verification.some(result => !result.matches)) {
    throw new Error(`PostgreSQL verification failed: ${JSON.stringify(verification)}`);
  }
  console.log(JSON.stringify({ status: 'verified', verification }, null, 2));
} finally {
  await sql.end({ timeout: 5 });
}
