import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import crypto from 'node:crypto';
import initSqlJs from 'sql.js';

const require = createRequire(import.meta.url);

type Sql = any;

type MigrationOptions = {
  sourcePath: string;
  connectionString?: string;
  execute: boolean;
  verifyOnly: boolean;
};

type SourceTable = {
  name: string;
  ddl: string;
  columns: unknown[][];
  rows: unknown[][];
  columnNames: string[];
};

type SourceIndex = { name: string; table: string; ddl: string };

function digest(value: unknown): string {
  return crypto.createHash('sha256').update(JSON.stringify(value), 'utf8').digest('hex');
}

function normalizeValue(value: unknown): unknown {
  if (value == null) return null;
  if (value instanceof Uint8Array || Buffer.isBuffer(value)) return Buffer.from(value).toString('base64');
  return String(value);
}

function rowDigest(rows: unknown[][]): string {
  return digest(rows.map(row => row.map(normalizeValue)));
}

function referencedTables(ddl: string): string[] {
  return [...ddl.matchAll(/\bREFERENCES\s+"?([A-Za-z_][A-Za-z0-9_]*)"?/gi)].map(match => match[1]);
}

function dependencyOrder(records: SourceTable[]): SourceTable[] {
  const known = new Set(records.map(record => record.name));
  const pending = new Map(records.map(record => [record.name, record]));
  const ordered: SourceTable[] = [];
  const resolved = new Set<string>();
  while (pending.size) {
    const next = [...pending.values()].find(record => referencedTables(record.ddl).filter(table => known.has(table)).every(table => resolved.has(table)));
    if (!next) throw new Error(`Unable to determine deterministic foreign-key order for: ${[...pending.keys()].join(', ')}`);
    pending.delete(next.name);
    resolved.add(next.name);
    ordered.push(next);
  }
  return ordered;
}

function quoteIdentifier(identifier: string): string {
  return `"${identifier.replace(/"/g, '""')}"`;
}

function primaryKeyColumn(record: SourceTable): string | null {
  const column = record.columns.find(columnInfo => Number(columnInfo[5]) === 1);
  return column ? String(column[1]) : null;
}

function loadPostgres(): ((connectionString: string, options?: Record<string, unknown>) => Sql) | null {
  try {
    const module = require('postgres') as { default?: (connectionString: string, options?: Record<string, unknown>) => Sql } | ((connectionString: string, options?: Record<string, unknown>) => Sql);
    return (typeof module === 'function' ? module : module.default) || null;
  } catch {
    return null;
  }
}

function parseArgs(): MigrationOptions {
  const args = new Set(process.argv.slice(2));
  const sourcePath = process.env.DB_PATH || path.join(process.cwd(), 'kurukoo.sqlite');
  return {
    sourcePath,
    connectionString: process.env.DATABASE_URL || process.env.POSTGRES_URL,
    execute: args.has('--execute'),
    verifyOnly: args.has('--verify-only'),
  };
}

function translateSqliteDdl(sql: string): string {
  let ddl = sql.trim().replace(/^CREATE TABLE( IF NOT EXISTS)?/i, 'CREATE TABLE IF NOT EXISTS');
  ddl = ddl.replace(/^CREATE UNIQUE INDEX( IF NOT EXISTS)?/i, 'CREATE UNIQUE INDEX IF NOT EXISTS');
  ddl = ddl.replace(/^CREATE INDEX( IF NOT EXISTS)?/i, 'CREATE INDEX IF NOT EXISTS');
  ddl = ddl.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  ddl = ddl.replace(/\bINT\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  ddl = ddl.replace(/\bAUTOINCREMENT\b/gi, '');
  ddl = ddl.replace(/\bDATETIME\b/gi, 'TEXT');
  ddl = ddl.replace(/\bBLOB\b/gi, 'BYTEA');
  ddl = ddl.replace(/\bTEXT\s+DEFAULT\s+CURRENT_TIMESTAMP\b/gi, 'TEXT DEFAULT CURRENT_TIMESTAMP::text');
  ddl = ddl.replace(/([,(]\s*)desc\b/gi, '$1"desc"');
  return ddl;
}

async function readSourceDatabase(sourcePath: string) {
  if (!fs.existsSync(sourcePath)) throw new Error(`Source SQL.js database does not exist: ${sourcePath}`);
  const SQL = await initSqlJs();
  const db = new SQL.Database(fs.readFileSync(sourcePath));
  const tables = db.exec("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL ORDER BY name")[0]?.values || [];
  const records: SourceTable[] = tables.map(row => {
    const name = String(row[0]);
    const ddl = String(row[1]);
    const columns = db.exec(`PRAGMA table_info("${name.replace(/"/g, '""')}")`)[0]?.values || [];
    const rows = db.exec(`SELECT * FROM "${name.replace(/"/g, '""')}" ORDER BY 1`)[0];
    return { name, ddl, columns, rows: rows?.values || [], columnNames: columns.map(column => String(column[1])) };
  });
  const discoveredIndexes = (db.exec("SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL ORDER BY name")[0]?.values || [])
    .map(row => ({ name: String(row[0]), table: String(row[1]), ddl: String(row[2]) })) as SourceIndex[];
  const sourceTables = new Set(records.map(record => record.name));
  const indexes = discoveredIndexes.filter(index => sourceTables.has(index.table));
  const skippedIndexes = discoveredIndexes.filter(index => !sourceTables.has(index.table)).map(index => ({ name: index.name, table: index.table }));
  return { db, records, indexes, skippedIndexes };
}

function importantIntegrityChecks(records: SourceTable[]) {
  const checks = ['memory_profiles', 'messages', 'economic_requests', 'internal_notifications', 'orders', 'agent_goals', 'agent_goal_events', 'execution_requests'];
  return checks.map(name => {
    const table = records.find(item => item.name === name);
    return {
      table: name,
      present: Boolean(table),
      rows: table?.rows.length ?? 0,
      columns: table?.columnNames.length ?? 0,
      sourceColumns: table?.columnNames ?? [],
      sourceDigest: table ? rowDigest(table.rows) : null,
    };
  });
}

async function executeImport(sql: Sql, records: SourceTable[], indexes: SourceIndex[], schemaChecksum: string) {
  const orderedRecords = dependencyOrder(records);
  await sql.begin(async (tx: Sql) => {
    for (const record of orderedRecords) {
      try {
        await tx.unsafe(translateSqliteDdl(record.ddl));
      } catch (error) {
        throw new Error(`Unable to create PostgreSQL table ${record.name}: ${error instanceof Error ? error.message : String(error)}`, { cause: error });
      }
    }
    for (const record of orderedRecords) {
      if (!record.rows.length || !record.columnNames.length) continue;
      const columns = record.columnNames.map(column => `"${column.replace(/"/g, '""')}"`).join(', ');
      const table = `"${record.name.replace(/"/g, '""')}"`;
      for (const row of record.rows) {
        const values = record.columnNames.map((_, index) => row[index]);
        const placeholders = values.map((_, index) => `$${index + 1}`).join(', ');
        await tx.unsafe(`INSERT INTO ${table} (${columns}) VALUES (${placeholders}) ON CONFLICT DO NOTHING`, values);
      }
    }
    for (const record of orderedRecords) {
      const primaryKey = primaryKeyColumn(record);
      if (!primaryKey || !/\bAUTOINCREMENT\b/i.test(record.ddl)) continue;
      const table = quoteIdentifier(record.name);
      const column = quoteIdentifier(primaryKey);
      await tx.unsafe(`SELECT setval(pg_get_serial_sequence($1, $2), GREATEST((SELECT COALESCE(MAX(${column}), 0) + 1 FROM ${table}), 1), false)`, [record.name, primaryKey]);
    }
    for (const index of indexes) {
      try {
        await tx.unsafe(translateSqliteDdl(index.ddl));
      } catch (error) {
        throw new Error(`Unable to create PostgreSQL index ${index.name} on ${index.table}: ${error instanceof Error ? error.message : String(error)}`, { cause: error });
      }
    }
    await tx.unsafe(`CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text)`);
    await tx.unsafe(`INSERT INTO schema_migrations(version, checksum) VALUES ($1, $2) ON CONFLICT(version) DO NOTHING`, [`sqljs-export-${schemaChecksum.slice(0, 16)}`, schemaChecksum]);
  });
}

async function verifyDestination(sql: Sql, checks: ReturnType<typeof importantIntegrityChecks>) {
  const results = [];
  for (const check of checks) {
    if (!check.present) {
      results.push({ ...check, destinationRows: 0, matches: false });
      continue;
    }
    const rows = await sql.unsafe(`SELECT COUNT(*)::bigint AS count FROM "${check.table}"`);
    const destinationRows = Number(rows[0]?.count || 0);
    const destinationColumns = (await sql.unsafe(`SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 ORDER BY ordinal_position`, [check.table])).map((row: any) => String(row.column_name));
    const table = `"${check.table.replace(/"/g, '""')}"`;
    const destinationDigestRows = await sql.unsafe(`SELECT * FROM ${table} ORDER BY 1`);
    const destinationDigest = rowDigest(destinationDigestRows.map((row: Record<string, unknown>) => check.sourceColumns.map(column => row[column])));
    const columnsMatch = JSON.stringify(destinationColumns) === JSON.stringify(check.sourceColumns);
    results.push({ ...check, destinationRows, destinationColumns, destinationDigest, columnsMatch, matches: destinationRows === check.rows && columnsMatch && destinationDigest === check.sourceDigest });
  }
  return results;
}

const options = parseArgs();
const { records, indexes, skippedIndexes } = await readSourceDatabase(options.sourcePath);
const checks = importantIntegrityChecks(records);
const schemaChecksum = digest({ tables: records.map(record => ({ name: record.name, ddl: record.ddl, columns: record.columnNames })), indexes });

console.log(JSON.stringify({
  source: options.sourcePath,
  schemaVersion: '2026-08-22-canonical-runtime-schema',
  mode: options.execute ? 'execute' : 'dry-run',
  tableCount: records.length,
  sourceTables: records.map(record => record.name),
  indexCount: indexes.length,
  skippedIndexes,
  schemaChecksum,
  checks,
  note: 'No live migration is performed unless --execute is explicitly supplied. Dry-run never connects to PostgreSQL.',
}, null, 2));

if (options.verifyOnly && !options.connectionString) process.exit(0);
if (!options.execute) process.exit(0);
if (!options.connectionString) throw new Error('DATABASE_URL or POSTGRES_URL is required for --execute.');

const factory = loadPostgres();
if (!factory) throw new Error('PostgreSQL client is not installed. Install the pinned postgres dependency before executing a migration.');

const sql = factory(options.connectionString, {
  max: 2,
  connect_timeout: 10,
  ssl: String(process.env.KURUKOO_POSTGRES_SSL || 'true').toLowerCase() !== 'false' ? 'require' : false,
});
try {
  await sql`SELECT 1`;
  await sql.unsafe(`CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text)`);
  const existing = await sql`SELECT checksum FROM schema_migrations WHERE version = ${`sqljs-export-${schemaChecksum.slice(0, 16)}`}`;
  if (existing.length === 1 && String(existing[0].checksum) === schemaChecksum) {
    console.log(JSON.stringify({ status: 'verified', repeated: true, note: 'This exact migration (identical deterministic schema checksum) has already been applied to this database; import skipped and no duplicate durable effects were created.', verification: [] }, null, 2));
    process.exit(0);
  }
  await executeImport(sql, records, indexes, schemaChecksum);
  const verification = await verifyDestination(sql, checks);
  if (verification.some(result => !result.matches)) {
    throw new Error(`PostgreSQL verification failed: ${JSON.stringify(verification)}`);
  }
  console.log(JSON.stringify({ status: 'verified', verification }, null, 2));
} finally {
  await sql.end({ timeout: 5 });
}
