/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import fs from 'fs';
import path from 'path';
const root=process.cwd();const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');const chat=read('public/chat/index.html');const primary=read('public/js/kurukoo-primary-chat.js');const nav=read('views/_partials/nav.ejs');const footer=read('views/_partials/footer.ejs');const routes=read('src/routes/publicRoutes.ts');const appRoutes=read('src/routes/appSurfaceRoutes.ts');const workspace=read('views/workspace.ejs');const workspaceClient=read('public/js/kurukoo-workspace.js');const fail:string[]=[];const mustInclude=(source:string,value:string,label:string)=>{if(!source.includes(value))fail.push(`${label}: missing ${value}`)};const mustNotInclude=(source:string,value:string,label:string)=>{if(source.includes(value))fail.push(`${label}: contains legacy ${value}`)};
mustInclude(chat,'/favicon.svg','chat branding');mustInclude(primary,"discover: ['Find useful things around you.'",'guest Discover copy');mustInclude(primary,"connect: ['Connect your access points.'",'guest Connect copy');mustInclude(primary,"topics: ['Useful community context.'",'guest Topics copy');mustInclude(chat,'/icons/kurukoo-icons.svg','chat icon system');mustInclude(chat,'/js/kurukoo-workspace.js','workspace controller');mustInclude(chat,'Tell Kurukoo what you need','conversation-first copy');mustInclude(chat,'Reminders','reminder workspace entry');mustInclude(chat,'Safety','safety workspace entry');mustInclude(chat,'Manage my safety contacts and check-ins','static safety quick action');mustInclude(primary,'Manage my safety contacts and check-ins','personalized safety quick action');mustNotInclude(chat,'Web Chat · other channels are shown only when connected','redundant channel footer');mustNotInclude(chat,'*7000#','chat shell');mustNotInclude(chat,'Economic OS','chat shell');mustInclude(primary,"document.dispatchEvent(new CustomEvent('kurukoo:workspace-surface'",'in-Chat workspace hydration dispatch');mustInclude(workspaceClient,"document.addEventListener('kurukoo:workspace-surface'",'workspace hydration listener');mustInclude(workspaceClient,"const hydrateWorkspaceSurface",'workspace hydration dispatch function');
mustInclude(nav,'Start chatting','global CTA');mustInclude(nav,'/channels','global channel navigation');mustInclude(nav,'/resources','global resource navigation');mustNotInclude(nav,'*7000#','global navigation');mustNotInclude(nav,'Chat on WhatsApp','global navigation');mustNotInclude(nav,'Start a Free Trial','global navigation');mustInclude(footer,'Start chatting','global footer CTA');mustNotInclude(footer,'*7000#','global footer');mustNotInclude(footer,'WhatsApp 7000','global footer');
mustInclude(routes,"router.get('/channels'",'public channels route');for(const route of ['/settings','/reminders','/discover'])mustInclude(appRoutes,`'${route}'`,'canonical workspace route');for(const alias of ['/settings','/reminders','/daily-picks'])mustNotInclude(routes,`router.get('${alias}'`,'public router');
for(const asset of ['public/icons/kurukoo-icons.svg','public/js/kurukoo-workspace.js','public/css/kurukoo-workspace.css','views/channels.ejs','views/workspace.ejs'])if(!fs.existsSync(path.join(root,asset)))fail.push(`missing asset: ${asset}`);
mustInclude(workspace,'Requests','workspace requests');mustInclude(workspace,'Reminders','workspace reminders');mustInclude(workspace,'Cart','workspace cart');mustInclude(workspace,'Memory','workspace memory');mustInclude(workspace,'Emergency contacts','workspace safety');mustNotInclude(workspace,'href="/daily-picks"','workspace template');mustNotInclude(workspace,'href="/subscription"','workspace template');
if(fail.length){console.error(fail.join('\n'));process.exit(1)}console.log('Conversation workspace contract passed.');
