import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { getKnownSkills } from '../src/services/skillFlows.js';

const base = path.join(process.cwd(), 'ml', 'datasets', 'kurukoo-core-v1');
const manifestPath = `${base}.manifest.json`;
assert.ok(fs.existsSync(manifestPath), 'generated dataset manifest must exist; run npm run ml:generate-universe');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
const readRows = (split: string) => {
  const filePath = `${base}.${split}.jsonl`;
  assert.ok(fs.existsSync(filePath), `missing ${split} split`);
  const content = fs.readFileSync(filePath, 'utf8');
  const hash = crypto.createHash('sha256').update(content).digest('hex');
  assert.equal(hash, manifest.fileSha256[split], `${split} split hash must match its manifest`);
  return content.trim().split('\n').filter(Boolean).map((line) => JSON.parse(line));
};
const allRows = readRows('all');
const trainRows = readRows('train');
const validationRows = readRows('validation');
const testRows = readRows('test');
const goldenRows = readRows('golden');
const adversarialRows = readRows('adversarial');
const skills = new Set(allRows.map((row) => row.labels?.skill));
const variants = new Set(allRows.map((row) => row.labels?.variant));
const actors = new Set(allRows.map((row) => row.labels?.actor));
const channels = new Set(allRows.map((row) => row.labels?.channel));
const locales = new Set(allRows.map((row) => row.labels?.locale));
const surfaces = new Set(allRows.map((row) => row.labels?.surface));
assert.equal(getKnownSkills().length, 205);
assert.equal(manifest.skillCount, 205);
assert.equal(manifest.exampleCount, 1845);
assert.equal(allRows.length, 1845);
assert.equal(trainRows.length + validationRows.length + testRows.length, allRows.length);
assert.equal(goldenRows.length, 205);
assert.ok(adversarialRows.length > 1000, 'adversarial candidate set must be substantially populated');
assert.equal(manifest.evaluationSets.golden.status, 'candidate_requires_human_curation');
assert.equal(manifest.evaluationSets.adversarial.status, 'candidate_requires_human_curation');
assert.ok(trainRows.length > 0 && validationRows.length > 0 && testRows.length > 0, 'all deterministic splits must be populated');
assert.equal(skills.size, 205);
for (const variant of ['normal', 'ambiguity', 'interruption', 'correction', 'unavailable', 'consent', 'channel', 'recovery', 'linked_device']) assert.ok(variants.has(variant), `missing variant ${variant}`);
for (const actor of ['consumer', 'provider', 'business', 'contributor', 'agent', 'support_operator']) assert.ok(actors.has(actor), `missing actor ${actor}`);
for (const channel of ['web_chat', 'pwa', 'whatsapp', 'telegram', 'sms', 'ussd', 'email', 'voice', 'linked_device']) assert.ok(channels.has(channel), `missing channel ${channel}`);
for (const locale of ['ng:en', 'ng:pidgin', 'ng:hausa-influenced', 'gh:en', 'gb:en', 'ca:en', 'ca:fr']) assert.ok(locales.has(locale), `missing locale ${locale}`);
for (const surface of ['memory', 'reminders', 'notifications', 'points', 'subscriptions', 'topics', 'media', 'support', 'products', 'orders', 'cart', 'discovery', 'provider_interaction', 'safety', 'consent', 'payment_boundary', 'locale', 'dialect']) assert.ok(surfaces.has(surface), `missing surface ${surface}`);
assert.equal(new Set(goldenRows.map((row) => row.labels?.skill)).size, 205);
assert.ok(adversarialRows.some((row) => row.labels?.variant === 'ambiguity'));
assert.ok(adversarialRows.some((row) => row.labels?.variant === 'recovery'));
assert.ok(allRows.every((row) => row.provenance?.productionUserData === false));
assert.ok(allRows.every((row) => row.labels?.authorityBoundary === 'canonical_domain_services'));
assert.ok(allRows.every((row) => row.labels?.forbiddenClaims?.includes('invented availability')));
assert.equal(manifest.trainingIsNotRuntimeAuthority, true);
assert.equal(manifest.teacherOutputTrustedAutomatically, false);
console.log(`SmolLM2 training-universe regression passed: ${allRows.length} candidate examples, ${skills.size} skills, ${variants.size} variants, ${locales.size} locales, deterministic split hashes, and canonical authority boundaries verified.`);
