import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { getKnownSkills } from '../src/services/skillFlows.js';

const datasetPath = path.join(process.cwd(), 'ml', 'datasets', 'kurukoo-core-v1.jsonl');
const manifestPath = path.join(process.cwd(), 'ml', 'datasets', 'kurukoo-core-v1.manifest.json');
assert.ok(fs.existsSync(datasetPath), 'generated candidate dataset must exist; run npm run ml:generate-universe');
assert.ok(fs.existsSync(manifestPath), 'generated dataset manifest must exist');
const rows = fs.readFileSync(datasetPath, 'utf8').trim().split('\n').filter(Boolean).map((line) => JSON.parse(line));
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
const skills = new Set(rows.map((row) => row.labels?.skill));
const variants = new Set(rows.map((row) => row.labels?.variant));
const actors = new Set(rows.map((row) => row.labels?.actor));
const channels = new Set(rows.map((row) => row.labels?.channel));
assert.equal(getKnownSkills().length, 205);
assert.equal(manifest.skillCount, 205);
assert.equal(manifest.exampleCount, 1845);
assert.equal(rows.length, 1845);
assert.equal(skills.size, 205);
for (const variant of ['normal', 'ambiguity', 'interruption', 'correction', 'unavailable', 'consent', 'channel', 'recovery', 'linked_device']) assert.ok(variants.has(variant), `missing variant ${variant}`);
for (const actor of ['consumer', 'provider', 'business', 'contributor', 'agent', 'support_operator']) assert.ok(actors.has(actor), `missing actor ${actor}`);
for (const channel of ['web_chat', 'pwa', 'whatsapp', 'telegram', 'sms', 'ussd', 'email', 'voice', 'linked_device']) assert.ok(channels.has(channel), `missing channel ${channel}`);
assert.ok(rows.every((row) => row.provenance?.productionUserData === false));
assert.ok(rows.every((row) => row.labels?.authorityBoundary === 'canonical_domain_services'));
assert.ok(rows.every((row) => row.labels?.forbiddenClaims?.includes('invented availability')));
assert.equal(manifest.trainingIsNotRuntimeAuthority, true);
assert.equal(manifest.teacherOutputTrustedAutomatically, false);
console.log('SmolLM2 training-universe regression passed: 1,845 candidate examples, 205 skills, 9 scenario variants, actor/channel coverage, and canonical authority boundaries verified.');
