/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DailyPicksRouteImport } from './routes/daily-picks'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WorkRouteImport } from './routes/work'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as ProfileEntityIdRouteImport } from './routes/profile.$entityId'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as WorkRouteImport } from './routes/work.'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPicksRoute = DailyPicksRouteImport.update({
  id: '/daily-picks',
  path: '/daily-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const ProfileEntityIdRoute = ProfileEntityIdRouteImport.update({
  id: '/profile/$entityId',
  path: '/profile/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TopicsRoute,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/advertising': typeof AdvertisingRoute
  '/artifacts': typeof ArtifactsRoute
  '/calls': typeof CallsRoute
  '/connect': typeof ConnectRoute
  '/contacts': typeof ContactsRoute
  '/daily-picks': typeof DailyPicksRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRouteWithChildren
  '/work/': typeof WorkRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/$entityId': typeof ProfileEntityIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/advertising': typeof AdvertisingRoute
  '/artifacts': typeof ArtifactsRoute
  '/calls': typeof CallsRoute
  '/connect': typeof ConnectRoute
  '/contacts': typeof ContactsRoute
  '/daily-picks': typeof DailyPicksRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/$entityId': typeof ProfileEntityIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/advertising': typeof AdvertisingRoute
  '/artifacts': typeof ArtifactsRoute
  '/calls': typeof CallsRoute
  '/connect': typeof ConnectRoute
  '/contacts': typeof ContactsRoute
  '/daily-picks': typeof DailyPicksRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRouteWithChildren
  '/work/': typeof WorkRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/$entityId': typeof ProfileEntityIdRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/advertising'
    | '/artifacts'
    | '/calls'
    | '/connect'
    | '/contacts'
    | '/daily-picks'
    | '/explore'
    | '/following'
    | '/memory'
    | '/messages'
    | '/notifications'
    | '/subscriptions'
    | '/topics'
    | '/wallet'
    | '/work'
    | '/work/'
    | '/messages/$threadId'
    | '/profile/$entityId'
    | '/topics/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/advertising'
    | '/artifacts'
    | '/calls'
    | '/connect'
    | '/contacts'
    | '/daily-picks'
    | '/explore'
    | '/following'
    | '/memory'
    | '/messages'
    | '/notifications'
    | '/subscriptions'
    | '/topics'
    | '/wallet'
    | '/work'
    | '/messages/$threadId'
    | '/profile/$entityId'
    | '/topics/$slug'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/advertising'
    | '/artifacts'
    | '/calls'
    | '/connect'
    | '/contacts'
    | '/daily-picks'
    | '/explore'
    | '/following'
    | '/memory'
    | '/messages'
    | '/notifications'
    | '/subscriptions'
    | '/topics'
    | '/wallet'
    | '/work'
    | '/work/'
    | '/messages/$threadId'
    | '/profile/$entityId'
    | '/topics/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdvertisingRoute: typeof AdvertisingRoute
  ArtifactsRoute: typeof ArtifactsRoute
  CallsRoute: typeof CallsRoute
  ConnectRoute: typeof ConnectRoute
  ContactsRoute: typeof ContactsRoute
  DailyPicksRoute: typeof DailyPicksRoute
  ExploreRoute: typeof ExploreRoute
  FollowingRoute: typeof FollowingRoute
  MemoryRoute: typeof MemoryRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  WalletRoute: typeof WalletRoute
  WorkRoute: typeof WorkRouteWithChildren
  ProfileEntityIdRoute: typeof ProfileEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-picks': {
      id: '/daily-picks'
      path: '/daily-picks'
      fullPath: '/daily-picks'
      preLoaderRoute: typeof DailyPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/profile/$entityId': {
      id: '/profile/$entityId'
      path: '/profile/$entityId'
      fullPath: '/profile/$entityId'
      preLoaderRoute: typeof ProfileEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface TopicsRouteChildren {
  TopicsSlugRoute: typeof TopicsSlugRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsSlugRoute: TopicsSlugRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

interface WorkRouteChildren {
  WorkRoute: typeof WorkRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkRoute: WorkRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdvertisingRoute: AdvertisingRoute,
  ArtifactsRoute: ArtifactsRoute,
  CallsRoute: CallsRoute,
  ConnectRoute: ConnectRoute,
  ContactsRoute: ContactsRoute,
  DailyPicksRoute: DailyPicksRoute,
  ExploreRoute: ExploreRoute,
  FollowingRoute: FollowingRoute,
  MemoryRoute: MemoryRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TopicsRoute: TopicsRouteWithChildren,
  WalletRoute: WalletRoute,
  WorkRoute: WorkRouteWithChildren,
  ProfileEntityIdRoute: ProfileEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
