/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentsAmbassadorsRouteImport } from './routes/agents-ambassadors'
import { Route as AiTermsRouteImport } from './routes/ai-terms'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ArtistBookingRouteImport } from './routes/artist-booking'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as DailyPicksRouteImport } from './routes/daily-picks'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KurukooAiRouteImport } from './routes/kurukoo-ai'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LocalAgentsRouteImport } from './routes/local-agents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PerchRouteImport } from './routes/perch'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as QuickActionsRouteImport } from './routes/quick-actions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SecureExecutionRouteImport } from './routes/secure-execution'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as YouRouteImport } from './routes/you'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as ArtifactsArtifactIdRouteImport } from './routes/artifacts.$artifactId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogTheCallThatGetsThingsMovingRouteImport } from './routes/blog.the-call-that-gets-things-moving'
import { Route as EarnTopicRouteImport } from './routes/earn.$topic'
import { Route as ExploreCommunityRouteImport } from './routes/explore/community'
import { Route as ExploreEventsRouteImport } from './routes/explore/events'
import { Route as ExploreFoodRouteImport } from './routes/explore/food'
import { Route as ExploreGovernmentRouteImport } from './routes/explore/government'
import { Route as ExploreGroceriesRouteImport } from './routes/explore/groceries'
import { Route as ExploreHealthRouteImport } from './routes/explore/health'
import { Route as ExploreHomeRouteImport } from './routes/explore/home'
import { Route as ExploreLearningRouteImport } from './routes/explore/learning'
import { Route as ExploreMobilityRouteImport } from './routes/explore/mobility'
import { Route as ExploreMoneyCircleRouteImport } from './routes/explore/money-circle'
import { Route as ExplorePrayerRouteImport } from './routes/explore/prayer'
import { Route as ExploreRepairsRouteImport } from './routes/explore/repairs'
import { Route as ExploreSafetyRouteImport } from './routes/explore/safety'
import { Route as ExploreSellingRouteImport } from './routes/explore/selling'
import { Route as ExploreWorkRouteImport } from './routes/explore/work'
import { Route as LegalSectionRouteImport } from './routes/legal.$section'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as ProfileEntityIdRouteImport } from './routes/profile.$entityId'
import { Route as ProfileSlugRouteImport } from './routes/profile.$slug'
import { Route as ProfileKurukooAiRouteImport } from './routes/profile/kurukoo-ai'
import { Route as ProfileTemeAiRouteImport } from './routes/profile/teme-ai'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as TopicsCreateRouteImport } from './routes/topics.create'
import { Route as TopicsMineRouteImport } from './routes/topics.mine'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkWorkIdRouteImport } from './routes/work.$workId'
import { Route as TopicsCategoryCategorySlugRouteImport } from './routes/topics.category.$categorySlug'
import { Route as TopicsEditIdRouteImport } from './routes/topics.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAmbassadorsRoute = AgentsAmbassadorsRouteImport.update({
  id: '/agents-ambassadors',
  path: '/agents-ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTermsRoute = AiTermsRouteImport.update({
  id: '/ai-terms',
  path: '/ai-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistBookingRoute = ArtistBookingRouteImport.update({
  id: '/artist-booking',
  path: '/artist-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPicksRoute = DailyPicksRouteImport.update({
  id: '/daily-picks',
  path: '/daily-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KurukooAiRoute = KurukooAiRouteImport.update({
  id: '/kurukoo-ai',
  path: '/kurukoo-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAgentsRoute = LocalAgentsRouteImport.update({
  id: '/local-agents',
  path: '/local-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PerchRoute = PerchRouteImport.update({
  id: '/perch',
  path: '/perch',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickActionsRoute = QuickActionsRouteImport.update({
  id: '/quick-actions',
  path: '/quick-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureExecutionRoute = SecureExecutionRouteImport.update({
  id: '/secure-execution',
  path: '/secure-execution',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: '/$artifactId',
  path: '/$artifactId',
  getParentRoute: () => ArtifactsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogTheCallThatGetsThingsMovingRoute =
  BlogTheCallThatGetsThingsMovingRouteImport.update({
    id: '/the-call-that-gets-things-moving',
    path: '/the-call-that-gets-things-moving',
    getParentRoute: () => BlogRoute,
  } as any)
const EarnTopicRoute = EarnTopicRouteImport.update({
  id: '/earn/$topic',
  path: '/earn/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCommunityRoute = ExploreCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreEventsRoute = ExploreEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreFoodRoute = ExploreFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreGovernmentRoute = ExploreGovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreGroceriesRoute = ExploreGroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreHealthRoute = ExploreHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreHomeRoute = ExploreHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreLearningRoute = ExploreLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreMobilityRoute = ExploreMobilityRouteImport.update({
  id: '/mobility',
  path: '/mobility',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreMoneyCircleRoute = ExploreMoneyCircleRouteImport.update({
  id: '/money-circle',
  path: '/money-circle',
  getParentRoute: () => ExploreRoute,
} as any)
const ExplorePrayerRoute = ExplorePrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreRepairsRoute = ExploreRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreSafetyRoute = ExploreSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreSellingRoute = ExploreSellingRouteImport.update({
  id: '/selling',
  path: '/selling',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreWorkRoute = ExploreWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => ExploreRoute,
} as any)
const LegalSectionRoute = LegalSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => LegalRoute,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const ProfileEntityIdRoute = ProfileEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSlugRoute = ProfileSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileKurukooAiRoute = ProfileKurukooAiRouteImport.update({
  id: '/kurukoo-ai',
  path: '/kurukoo-ai',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileTemeAiRoute = ProfileTemeAiRouteImport.update({
  id: '/teme-ai',
  path: '/teme-ai',
  getParentRoute: () => ProfileRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TopicsRoute,
} as any)
const TopicsCreateRoute = TopicsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TopicsRoute,
} as any)
const TopicsMineRoute = TopicsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => TopicsRoute,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => VideosRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkWorkIdRoute = WorkWorkIdRouteImport.update({
  id: '/$workId',
  path: '/$workId',
  getParentRoute: () => WorkRoute,
} as any)
const TopicsCategoryCategorySlugRoute =
  TopicsCategoryCategorySlugRouteImport.update({
    id: '/category/$categorySlug',
    path: '/category/$categorySlug',
    getParentRoute: () => TopicsRoute,
  } as any)
const TopicsEditIdRoute = TopicsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => TopicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/advertise': typeof AdvertiseRoute
  '/advertising': typeof AdvertisingRoute
  '/agents': typeof AgentsRouteWithChildren
  '/agents-ambassadors': typeof AgentsAmbassadorsRoute
  '/ai-terms': typeof AiTermsRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/api-docs': typeof ApiDocsRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/artist-booking': typeof ArtistBookingRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/calls': typeof CallsRoute
  '/capabilities': typeof CapabilitiesRoute
  '/cards': typeof CardsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/contributors': typeof ContributorsRoute
  '/cookies': typeof CookiesRoute
  '/creators': typeof CreatorsRoute
  '/credentials': typeof CredentialsRoute
  '/daily-picks': typeof DailyPicksRoute
  '/developer': typeof DeveloperRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/following': typeof FollowingRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/kurukoo-ai': typeof KurukooAiRoute
  '/legal': typeof LegalRouteWithChildren
  '/local-agents': typeof LocalAgentsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/people': typeof PeopleRoute
  '/perch': typeof PerchRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/provider': typeof ProviderRoute
  '/providers': typeof ProvidersRoute
  '/quick-actions': typeof QuickActionsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/safety': typeof SafetyRoute
  '/secure-execution': typeof SecureExecutionRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/topics': typeof TopicsRouteWithChildren
  '/trust': typeof TrustRoute
  '/usage': typeof UsageRoute
  '/use-cases': typeof UseCasesRoute
  '/videos': typeof VideosRouteWithChildren
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/you': typeof YouRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/the-call-that-gets-things-moving': typeof BlogTheCallThatGetsThingsMovingRoute
  '/earn/$topic': typeof EarnTopicRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/government': typeof ExploreGovernmentRoute
  '/explore/groceries': typeof ExploreGroceriesRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/home': typeof ExploreHomeRoute
  '/explore/learning': typeof ExploreLearningRoute
  '/explore/mobility': typeof ExploreMobilityRoute
  '/explore/money-circle': typeof ExploreMoneyCircleRoute
  '/explore/prayer': typeof ExplorePrayerRoute
  '/explore/repairs': typeof ExploreRepairsRoute
  '/explore/safety': typeof ExploreSafetyRoute
  '/explore/selling': typeof ExploreSellingRoute
  '/explore/work': typeof ExploreWorkRoute
  '/legal/$section': typeof LegalSectionRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/$entityId': typeof ProfileEntityIdRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/profile/kurukoo-ai': typeof ProfileKurukooAiRoute
  '/profile/teme-ai': typeof ProfileTemeAiRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/topics/create': typeof TopicsCreateRoute
  '/topics/mine': typeof TopicsMineRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/work/': typeof WorkIndexRoute
  '/topics/category/$categorySlug': typeof TopicsCategoryCategorySlugRoute
  '/topics/edit/$id': typeof TopicsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/advertise': typeof AdvertiseRoute
  '/advertising': typeof AdvertisingRoute
  '/agents': typeof AgentsRouteWithChildren
  '/agents-ambassadors': typeof AgentsAmbassadorsRoute
  '/ai-terms': typeof AiTermsRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/api-docs': typeof ApiDocsRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/artist-booking': typeof ArtistBookingRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/calls': typeof CallsRoute
  '/capabilities': typeof CapabilitiesRoute
  '/cards': typeof CardsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/contributors': typeof ContributorsRoute
  '/cookies': typeof CookiesRoute
  '/creators': typeof CreatorsRoute
  '/credentials': typeof CredentialsRoute
  '/daily-picks': typeof DailyPicksRoute
  '/developer': typeof DeveloperRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/following': typeof FollowingRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/kurukoo-ai': typeof KurukooAiRoute
  '/legal': typeof LegalRouteWithChildren
  '/local-agents': typeof LocalAgentsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/people': typeof PeopleRoute
  '/perch': typeof PerchRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/provider': typeof ProviderRoute
  '/providers': typeof ProvidersRoute
  '/quick-actions': typeof QuickActionsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/safety': typeof SafetyRoute
  '/secure-execution': typeof SecureExecutionRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/topics': typeof TopicsRouteWithChildren
  '/trust': typeof TrustRoute
  '/usage': typeof UsageRoute
  '/use-cases': typeof UseCasesRoute
  '/videos': typeof VideosRouteWithChildren
  '/wallet': typeof WalletRoute
  '/workspace': typeof WorkspaceRoute
  '/you': typeof YouRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/the-call-that-gets-things-moving': typeof BlogTheCallThatGetsThingsMovingRoute
  '/earn/$topic': typeof EarnTopicRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/government': typeof ExploreGovernmentRoute
  '/explore/groceries': typeof ExploreGroceriesRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/home': typeof ExploreHomeRoute
  '/explore/learning': typeof ExploreLearningRoute
  '/explore/mobility': typeof ExploreMobilityRoute
  '/explore/money-circle': typeof ExploreMoneyCircleRoute
  '/explore/prayer': typeof ExplorePrayerRoute
  '/explore/repairs': typeof ExploreRepairsRoute
  '/explore/safety': typeof ExploreSafetyRoute
  '/explore/selling': typeof ExploreSellingRoute
  '/explore/work': typeof ExploreWorkRoute
  '/legal/$section': typeof LegalSectionRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/$entityId': typeof ProfileEntityIdRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/profile/kurukoo-ai': typeof ProfileKurukooAiRoute
  '/profile/teme-ai': typeof ProfileTemeAiRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/topics/create': typeof TopicsCreateRoute
  '/topics/mine': typeof TopicsMineRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/work': typeof WorkIndexRoute
  '/topics/category/$categorySlug': typeof TopicsCategoryCategorySlugRoute
  '/topics/edit/$id': typeof TopicsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/advertise': typeof AdvertiseRoute
  '/advertising': typeof AdvertisingRoute
  '/agents': typeof AgentsRouteWithChildren
  '/agents-ambassadors': typeof AgentsAmbassadorsRoute
  '/ai-terms': typeof AiTermsRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/api-docs': typeof ApiDocsRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/artist-booking': typeof ArtistBookingRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRouteWithChildren
  '/businesses': typeof BusinessesRoute
  '/calls': typeof CallsRoute
  '/capabilities': typeof CapabilitiesRoute
  '/cards': typeof CardsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/contributors': typeof ContributorsRoute
  '/cookies': typeof CookiesRoute
  '/creators': typeof CreatorsRoute
  '/credentials': typeof CredentialsRoute
  '/daily-picks': typeof DailyPicksRoute
  '/developer': typeof DeveloperRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/following': typeof FollowingRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/kurukoo-ai': typeof KurukooAiRoute
  '/legal': typeof LegalRouteWithChildren
  '/local-agents': typeof LocalAgentsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/messages': typeof MessagesRouteWithChildren
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/people': typeof PeopleRoute
  '/perch': typeof PerchRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/provider': typeof ProviderRoute
  '/providers': typeof ProvidersRoute
  '/quick-actions': typeof QuickActionsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/safety': typeof SafetyRoute
  '/secure-execution': typeof SecureExecutionRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/topics': typeof TopicsRouteWithChildren
  '/trust': typeof TrustRoute
  '/usage': typeof UsageRoute
  '/use-cases': typeof UseCasesRoute
  '/videos': typeof VideosRouteWithChildren
  '/wallet': typeof WalletRoute
  '/work': typeof WorkRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/you': typeof YouRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/the-call-that-gets-things-moving': typeof BlogTheCallThatGetsThingsMovingRoute
  '/earn/$topic': typeof EarnTopicRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/government': typeof ExploreGovernmentRoute
  '/explore/groceries': typeof ExploreGroceriesRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/home': typeof ExploreHomeRoute
  '/explore/learning': typeof ExploreLearningRoute
  '/explore/mobility': typeof ExploreMobilityRoute
  '/explore/money-circle': typeof ExploreMoneyCircleRoute
  '/explore/prayer': typeof ExplorePrayerRoute
  '/explore/repairs': typeof ExploreRepairsRoute
  '/explore/safety': typeof ExploreSafetyRoute
  '/explore/selling': typeof ExploreSellingRoute
  '/explore/work': typeof ExploreWorkRoute
  '/legal/$section': typeof LegalSectionRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/$entityId': typeof ProfileEntityIdRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/profile/kurukoo-ai': typeof ProfileKurukooAiRoute
  '/profile/teme-ai': typeof ProfileTemeAiRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/topics/create': typeof TopicsCreateRoute
  '/topics/mine': typeof TopicsMineRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/work/': typeof WorkIndexRoute
  '/topics/category/$categorySlug': typeof TopicsCategoryCategorySlugRoute
  '/topics/edit/$id': typeof TopicsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/advertise'
    | '/advertising'
    | '/agents'
    | '/agents-ambassadors'
    | '/ai-terms'
    | '/ambassadors'
    | '/api-docs'
    | '/artifacts'
    | '/artist-booking'
    | '/audit'
    | '/blog'
    | '/businesses'
    | '/calls'
    | '/capabilities'
    | '/cards'
    | '/careers'
    | '/cart'
    | '/chat'
    | '/connect'
    | '/contact'
    | '/contacts'
    | '/contributors'
    | '/cookies'
    | '/creators'
    | '/credentials'
    | '/daily-picks'
    | '/developer'
    | '/discover'
    | '/explore'
    | '/following'
    | '/help'
    | '/how-it-works'
    | '/integrations'
    | '/kurukoo-ai'
    | '/legal'
    | '/local-agents'
    | '/login'
    | '/memory'
    | '/messages'
    | '/network'
    | '/notifications'
    | '/opportunities'
    | '/partners'
    | '/people'
    | '/perch'
    | '/pricing'
    | '/profile'
    | '/provider'
    | '/providers'
    | '/quick-actions'
    | '/resources'
    | '/safety'
    | '/secure-execution'
    | '/settings'
    | '/signup'
    | '/subscriptions'
    | '/surveys'
    | '/tasks'
    | '/topics'
    | '/trust'
    | '/usage'
    | '/use-cases'
    | '/videos'
    | '/wallet'
    | '/work'
    | '/workspace'
    | '/you'
    | '/agents/$agentId'
    | '/artifacts/$artifactId'
    | '/blog/$slug'
    | '/blog/the-call-that-gets-things-moving'
    | '/earn/$topic'
    | '/explore/community'
    | '/explore/events'
    | '/explore/food'
    | '/explore/government'
    | '/explore/groceries'
    | '/explore/health'
    | '/explore/home'
    | '/explore/learning'
    | '/explore/mobility'
    | '/explore/money-circle'
    | '/explore/prayer'
    | '/explore/repairs'
    | '/explore/safety'
    | '/explore/selling'
    | '/explore/work'
    | '/legal/$section'
    | '/messages/$threadId'
    | '/profile/$entityId'
    | '/profile/$slug'
    | '/profile/kurukoo-ai'
    | '/profile/teme-ai'
    | '/resources/$slug'
    | '/topics/$slug'
    | '/topics/create'
    | '/topics/mine'
    | '/videos/$videoId'
    | '/work/$workId'
    | '/work/'
    | '/topics/category/$categorySlug'
    | '/topics/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/advertise'
    | '/advertising'
    | '/agents'
    | '/agents-ambassadors'
    | '/ai-terms'
    | '/ambassadors'
    | '/api-docs'
    | '/artifacts'
    | '/artist-booking'
    | '/audit'
    | '/blog'
    | '/businesses'
    | '/calls'
    | '/capabilities'
    | '/cards'
    | '/careers'
    | '/cart'
    | '/chat'
    | '/connect'
    | '/contact'
    | '/contacts'
    | '/contributors'
    | '/cookies'
    | '/creators'
    | '/credentials'
    | '/daily-picks'
    | '/developer'
    | '/discover'
    | '/explore'
    | '/following'
    | '/help'
    | '/how-it-works'
    | '/integrations'
    | '/kurukoo-ai'
    | '/legal'
    | '/local-agents'
    | '/login'
    | '/memory'
    | '/messages'
    | '/network'
    | '/notifications'
    | '/opportunities'
    | '/partners'
    | '/people'
    | '/perch'
    | '/pricing'
    | '/profile'
    | '/provider'
    | '/providers'
    | '/quick-actions'
    | '/resources'
    | '/safety'
    | '/secure-execution'
    | '/settings'
    | '/signup'
    | '/subscriptions'
    | '/surveys'
    | '/tasks'
    | '/topics'
    | '/trust'
    | '/usage'
    | '/use-cases'
    | '/videos'
    | '/wallet'
    | '/workspace'
    | '/you'
    | '/agents/$agentId'
    | '/artifacts/$artifactId'
    | '/blog/$slug'
    | '/blog/the-call-that-gets-things-moving'
    | '/earn/$topic'
    | '/explore/community'
    | '/explore/events'
    | '/explore/food'
    | '/explore/government'
    | '/explore/groceries'
    | '/explore/health'
    | '/explore/home'
    | '/explore/learning'
    | '/explore/mobility'
    | '/explore/money-circle'
    | '/explore/prayer'
    | '/explore/repairs'
    | '/explore/safety'
    | '/explore/selling'
    | '/explore/work'
    | '/legal/$section'
    | '/messages/$threadId'
    | '/profile/$entityId'
    | '/profile/$slug'
    | '/profile/kurukoo-ai'
    | '/profile/teme-ai'
    | '/resources/$slug'
    | '/topics/$slug'
    | '/topics/create'
    | '/topics/mine'
    | '/videos/$videoId'
    | '/work/$workId'
    | '/work'
    | '/topics/category/$categorySlug'
    | '/topics/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/advertise'
    | '/advertising'
    | '/agents'
    | '/agents-ambassadors'
    | '/ai-terms'
    | '/ambassadors'
    | '/api-docs'
    | '/artifacts'
    | '/artist-booking'
    | '/audit'
    | '/blog'
    | '/businesses'
    | '/calls'
    | '/capabilities'
    | '/cards'
    | '/careers'
    | '/cart'
    | '/chat'
    | '/connect'
    | '/contact'
    | '/contacts'
    | '/contributors'
    | '/cookies'
    | '/creators'
    | '/credentials'
    | '/daily-picks'
    | '/developer'
    | '/discover'
    | '/explore'
    | '/following'
    | '/help'
    | '/how-it-works'
    | '/integrations'
    | '/kurukoo-ai'
    | '/legal'
    | '/local-agents'
    | '/login'
    | '/memory'
    | '/messages'
    | '/network'
    | '/notifications'
    | '/opportunities'
    | '/partners'
    | '/people'
    | '/perch'
    | '/pricing'
    | '/profile'
    | '/provider'
    | '/providers'
    | '/quick-actions'
    | '/resources'
    | '/safety'
    | '/secure-execution'
    | '/settings'
    | '/signup'
    | '/subscriptions'
    | '/surveys'
    | '/tasks'
    | '/topics'
    | '/trust'
    | '/usage'
    | '/use-cases'
    | '/videos'
    | '/wallet'
    | '/work'
    | '/workspace'
    | '/you'
    | '/agents/$agentId'
    | '/artifacts/$artifactId'
    | '/blog/$slug'
    | '/blog/the-call-that-gets-things-moving'
    | '/earn/$topic'
    | '/explore/community'
    | '/explore/events'
    | '/explore/food'
    | '/explore/government'
    | '/explore/groceries'
    | '/explore/health'
    | '/explore/home'
    | '/explore/learning'
    | '/explore/mobility'
    | '/explore/money-circle'
    | '/explore/prayer'
    | '/explore/repairs'
    | '/explore/safety'
    | '/explore/selling'
    | '/explore/work'
    | '/legal/$section'
    | '/messages/$threadId'
    | '/profile/$entityId'
    | '/profile/$slug'
    | '/profile/kurukoo-ai'
    | '/profile/teme-ai'
    | '/resources/$slug'
    | '/topics/$slug'
    | '/topics/create'
    | '/topics/mine'
    | '/videos/$videoId'
    | '/work/$workId'
    | '/work/'
    | '/topics/category/$categorySlug'
    | '/topics/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AdvertisingRoute: typeof AdvertisingRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AgentsAmbassadorsRoute: typeof AgentsAmbassadorsRoute
  AiTermsRoute: typeof AiTermsRoute
  AmbassadorsRoute: typeof AmbassadorsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  ArtistBookingRoute: typeof ArtistBookingRoute
  AuditRoute: typeof AuditRoute
  BlogRoute: typeof BlogRouteWithChildren
  BusinessesRoute: typeof BusinessesRoute
  CallsRoute: typeof CallsRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CardsRoute: typeof CardsRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  ContributorsRoute: typeof ContributorsRoute
  CookiesRoute: typeof CookiesRoute
  CreatorsRoute: typeof CreatorsRoute
  CredentialsRoute: typeof CredentialsRoute
  DailyPicksRoute: typeof DailyPicksRoute
  DeveloperRoute: typeof DeveloperRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FollowingRoute: typeof FollowingRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KurukooAiRoute: typeof KurukooAiRoute
  LegalRoute: typeof LegalRouteWithChildren
  LocalAgentsRoute: typeof LocalAgentsRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PartnersRoute: typeof PartnersRoute
  PeopleRoute: typeof PeopleRoute
  PerchRoute: typeof PerchRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProviderRoute: typeof ProviderRoute
  ProvidersRoute: typeof ProvidersRoute
  QuickActionsRoute: typeof QuickActionsRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SafetyRoute: typeof SafetyRoute
  SecureExecutionRoute: typeof SecureExecutionRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SurveysRoute: typeof SurveysRoute
  TasksRoute: typeof TasksRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  TrustRoute: typeof TrustRoute
  UsageRoute: typeof UsageRoute
  UseCasesRoute: typeof UseCasesRoute
  VideosRoute: typeof VideosRouteWithChildren
  WalletRoute: typeof WalletRoute
  WorkRoute: typeof WorkRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRoute
  YouRoute: typeof YouRoute
  EarnTopicRoute: typeof EarnTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-ambassadors': {
      id: '/agents-ambassadors'
      path: '/agents-ambassadors'
      fullPath: '/agents-ambassadors'
      preLoaderRoute: typeof AgentsAmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-terms': {
      id: '/ai-terms'
      path: '/ai-terms'
      fullPath: '/ai-terms'
      preLoaderRoute: typeof AiTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-booking': {
      id: '/artist-booking'
      path: '/artist-booking'
      fullPath: '/artist-booking'
      preLoaderRoute: typeof ArtistBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-picks': {
      id: '/daily-picks'
      path: '/daily-picks'
      fullPath: '/daily-picks'
      preLoaderRoute: typeof DailyPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurukoo-ai': {
      id: '/kurukoo-ai'
      path: '/kurukoo-ai'
      fullPath: '/kurukoo-ai'
      preLoaderRoute: typeof KurukooAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-agents': {
      id: '/local-agents'
      path: '/local-agents'
      fullPath: '/local-agents'
      preLoaderRoute: typeof LocalAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perch': {
      id: '/perch'
      path: '/perch'
      fullPath: '/perch'
      preLoaderRoute: typeof PerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-actions': {
      id: '/quick-actions'
      path: '/quick-actions'
      fullPath: '/quick-actions'
      preLoaderRoute: typeof QuickActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-execution': {
      id: '/secure-execution'
      path: '/secure-execution'
      fullPath: '/secure-execution'
      preLoaderRoute: typeof SecureExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/artifacts/$artifactId': {
      id: '/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/the-call-that-gets-things-moving': {
      id: '/blog/the-call-that-gets-things-moving'
      path: '/the-call-that-gets-things-moving'
      fullPath: '/blog/the-call-that-gets-things-moving'
      preLoaderRoute: typeof BlogTheCallThatGetsThingsMovingRouteImport
      parentRoute: typeof BlogRoute
    }
    '/earn/$topic': {
      id: '/earn/$topic'
      path: '/earn/$topic'
      fullPath: '/earn/$topic'
      preLoaderRoute: typeof EarnTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/community': {
      id: '/explore/community'
      path: '/community'
      fullPath: '/explore/community'
      preLoaderRoute: typeof ExploreCommunityRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/events': {
      id: '/explore/events'
      path: '/events'
      fullPath: '/explore/events'
      preLoaderRoute: typeof ExploreEventsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/food': {
      id: '/explore/food'
      path: '/food'
      fullPath: '/explore/food'
      preLoaderRoute: typeof ExploreFoodRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/government': {
      id: '/explore/government'
      path: '/government'
      fullPath: '/explore/government'
      preLoaderRoute: typeof ExploreGovernmentRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/groceries': {
      id: '/explore/groceries'
      path: '/groceries'
      fullPath: '/explore/groceries'
      preLoaderRoute: typeof ExploreGroceriesRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/health': {
      id: '/explore/health'
      path: '/health'
      fullPath: '/explore/health'
      preLoaderRoute: typeof ExploreHealthRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/home': {
      id: '/explore/home'
      path: '/home'
      fullPath: '/explore/home'
      preLoaderRoute: typeof ExploreHomeRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/learning': {
      id: '/explore/learning'
      path: '/learning'
      fullPath: '/explore/learning'
      preLoaderRoute: typeof ExploreLearningRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/mobility': {
      id: '/explore/mobility'
      path: '/mobility'
      fullPath: '/explore/mobility'
      preLoaderRoute: typeof ExploreMobilityRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/money-circle': {
      id: '/explore/money-circle'
      path: '/money-circle'
      fullPath: '/explore/money-circle'
      preLoaderRoute: typeof ExploreMoneyCircleRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/prayer': {
      id: '/explore/prayer'
      path: '/prayer'
      fullPath: '/explore/prayer'
      preLoaderRoute: typeof ExplorePrayerRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/repairs': {
      id: '/explore/repairs'
      path: '/repairs'
      fullPath: '/explore/repairs'
      preLoaderRoute: typeof ExploreRepairsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/safety': {
      id: '/explore/safety'
      path: '/safety'
      fullPath: '/explore/safety'
      preLoaderRoute: typeof ExploreSafetyRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/selling': {
      id: '/explore/selling'
      path: '/selling'
      fullPath: '/explore/selling'
      preLoaderRoute: typeof ExploreSellingRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/work': {
      id: '/explore/work'
      path: '/work'
      fullPath: '/explore/work'
      preLoaderRoute: typeof ExploreWorkRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/legal/$section': {
      id: '/legal/$section'
      path: '/$section'
      fullPath: '/legal/$section'
      preLoaderRoute: typeof LegalSectionRouteImport
      parentRoute: typeof LegalRoute
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/profile/$entityId': {
      id: '/profile/$entityId'
      path: '/$entityId'
      fullPath: '/profile/$entityId'
      preLoaderRoute: typeof ProfileEntityIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$slug': {
      id: '/profile/$slug'
      path: '/$slug'
      fullPath: '/profile/$slug'
      preLoaderRoute: typeof ProfileSlugRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/kurukoo-ai': {
      id: '/profile/kurukoo-ai'
      path: '/kurukoo-ai'
      fullPath: '/profile/kurukoo-ai'
      preLoaderRoute: typeof ProfileKurukooAiRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/teme-ai': {
      id: '/profile/teme-ai'
      path: '/teme-ai'
      fullPath: '/profile/teme-ai'
      preLoaderRoute: typeof ProfileTemeAiRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/create': {
      id: '/topics/create'
      path: '/create'
      fullPath: '/topics/create'
      preLoaderRoute: typeof TopicsCreateRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/mine': {
      id: '/topics/mine'
      path: '/mine'
      fullPath: '/topics/mine'
      preLoaderRoute: typeof TopicsMineRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$workId': {
      id: '/work/$workId'
      path: '/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof WorkWorkIdRouteImport
      parentRoute: typeof WorkRoute
    }
    '/topics/category/$categorySlug': {
      id: '/topics/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/topics/category/$categorySlug'
      preLoaderRoute: typeof TopicsCategoryCategorySlugRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/edit/$id': {
      id: '/topics/edit/$id'
      path: '/edit/$id'
      fullPath: '/topics/edit/$id'
      preLoaderRoute: typeof TopicsEditIdRouteImport
      parentRoute: typeof TopicsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ArtifactsRouteChildren {
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogTheCallThatGetsThingsMovingRoute: typeof BlogTheCallThatGetsThingsMovingRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogTheCallThatGetsThingsMovingRoute: BlogTheCallThatGetsThingsMovingRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ExploreRouteChildren {
  ExploreCommunityRoute: typeof ExploreCommunityRoute
  ExploreEventsRoute: typeof ExploreEventsRoute
  ExploreFoodRoute: typeof ExploreFoodRoute
  ExploreGovernmentRoute: typeof ExploreGovernmentRoute
  ExploreGroceriesRoute: typeof ExploreGroceriesRoute
  ExploreHealthRoute: typeof ExploreHealthRoute
  ExploreHomeRoute: typeof ExploreHomeRoute
  ExploreLearningRoute: typeof ExploreLearningRoute
  ExploreMobilityRoute: typeof ExploreMobilityRoute
  ExploreMoneyCircleRoute: typeof ExploreMoneyCircleRoute
  ExplorePrayerRoute: typeof ExplorePrayerRoute
  ExploreRepairsRoute: typeof ExploreRepairsRoute
  ExploreSafetyRoute: typeof ExploreSafetyRoute
  ExploreSellingRoute: typeof ExploreSellingRoute
  ExploreWorkRoute: typeof ExploreWorkRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreCommunityRoute: ExploreCommunityRoute,
  ExploreEventsRoute: ExploreEventsRoute,
  ExploreFoodRoute: ExploreFoodRoute,
  ExploreGovernmentRoute: ExploreGovernmentRoute,
  ExploreGroceriesRoute: ExploreGroceriesRoute,
  ExploreHealthRoute: ExploreHealthRoute,
  ExploreHomeRoute: ExploreHomeRoute,
  ExploreLearningRoute: ExploreLearningRoute,
  ExploreMobilityRoute: ExploreMobilityRoute,
  ExploreMoneyCircleRoute: ExploreMoneyCircleRoute,
  ExplorePrayerRoute: ExplorePrayerRoute,
  ExploreRepairsRoute: ExploreRepairsRoute,
  ExploreSafetyRoute: ExploreSafetyRoute,
  ExploreSellingRoute: ExploreSellingRoute,
  ExploreWorkRoute: ExploreWorkRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface LegalRouteChildren {
  LegalSectionRoute: typeof LegalSectionRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalSectionRoute: LegalSectionRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEntityIdRoute: typeof ProfileEntityIdRoute
  ProfileSlugRoute: typeof ProfileSlugRoute
  ProfileKurukooAiRoute: typeof ProfileKurukooAiRoute
  ProfileTemeAiRoute: typeof ProfileTemeAiRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEntityIdRoute: ProfileEntityIdRoute,
  ProfileSlugRoute: ProfileSlugRoute,
  ProfileKurukooAiRoute: ProfileKurukooAiRoute,
  ProfileTemeAiRoute: ProfileTemeAiRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface TopicsRouteChildren {
  TopicsSlugRoute: typeof TopicsSlugRoute
  TopicsCreateRoute: typeof TopicsCreateRoute
  TopicsMineRoute: typeof TopicsMineRoute
  TopicsCategoryCategorySlugRoute: typeof TopicsCategoryCategorySlugRoute
  TopicsEditIdRoute: typeof TopicsEditIdRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsSlugRoute: TopicsSlugRoute,
  TopicsCreateRoute: TopicsCreateRoute,
  TopicsMineRoute: TopicsMineRoute,
  TopicsCategoryCategorySlugRoute: TopicsCategoryCategorySlugRoute,
  TopicsEditIdRoute: TopicsEditIdRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

interface VideosRouteChildren {
  VideosVideoIdRoute: typeof VideosVideoIdRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosVideoIdRoute: VideosVideoIdRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

interface WorkRouteChildren {
  WorkWorkIdRoute: typeof WorkWorkIdRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkWorkIdRoute: WorkWorkIdRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AdvertiseRoute: AdvertiseRoute,
  AdvertisingRoute: AdvertisingRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AgentsAmbassadorsRoute: AgentsAmbassadorsRoute,
  AiTermsRoute: AiTermsRoute,
  AmbassadorsRoute: AmbassadorsRoute,
  ApiDocsRoute: ApiDocsRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  ArtistBookingRoute: ArtistBookingRoute,
  AuditRoute: AuditRoute,
  BlogRoute: BlogRouteWithChildren,
  BusinessesRoute: BusinessesRoute,
  CallsRoute: CallsRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CardsRoute: CardsRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  ContributorsRoute: ContributorsRoute,
  CookiesRoute: CookiesRoute,
  CreatorsRoute: CreatorsRoute,
  CredentialsRoute: CredentialsRoute,
  DailyPicksRoute: DailyPicksRoute,
  DeveloperRoute: DeveloperRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FollowingRoute: FollowingRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntegrationsRoute: IntegrationsRoute,
  KurukooAiRoute: KurukooAiRoute,
  LegalRoute: LegalRouteWithChildren,
  LocalAgentsRoute: LocalAgentsRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PartnersRoute: PartnersRoute,
  PeopleRoute: PeopleRoute,
  PerchRoute: PerchRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProviderRoute: ProviderRoute,
  ProvidersRoute: ProvidersRoute,
  QuickActionsRoute: QuickActionsRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SafetyRoute: SafetyRoute,
  SecureExecutionRoute: SecureExecutionRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SurveysRoute: SurveysRoute,
  TasksRoute: TasksRoute,
  TopicsRoute: TopicsRouteWithChildren,
  TrustRoute: TrustRoute,
  UsageRoute: UsageRoute,
  UseCasesRoute: UseCasesRoute,
  VideosRoute: VideosRouteWithChildren,
  WalletRoute: WalletRoute,
  WorkRoute: WorkRouteWithChildren,
  WorkspaceRoute: WorkspaceRoute,
  YouRoute: YouRoute,
  EarnTopicRoute: EarnTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
