import { Bot, ExternalLink, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { actionClass } from "@/components/kurukoo/primitives";
import { SurfaceStatus } from "@/components/kurukoo/surface-status";

type Agent = { id: string; name: string; description: string; status?: "connected" | "available" | "needs-attention" | "not-configured"; capabilities?: string[] };

export function AgentSurface({ agents }: { agents: Agent[] }) {
  if (!agents.length) return <div className="rounded-[22px] border border-dashed border-border bg-elevated/25 px-5 py-10 text-center"><Bot className="mx-auto size-6 text-muted-foreground" /><p className="mt-3 text-[14px] font-semibold">No agents are configured yet.</p><p className="mx-auto mt-1.5 max-w-md text-[11.5px] leading-5 text-muted-foreground">When an agent exists, Kurukoo can show what it can do, what it can access and which work it is currently helping with.</p><Link to="/chat" search={{ prompt: "Help me understand what agents I can use" } as never} className={`${actionClass("primary")} mt-4`}>Ask Kurukoo</Link></div>;
  return <div className="grid gap-3 md:grid-cols-2">{agents.map((agent) => <article key={agent.id} className="rounded-[22px] border border-border bg-surface p-5"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-tint text-brand-ink"><Sparkles className="size-[18px]" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-[14px] font-semibold">{agent.name}</h3><SurfaceStatus status={agent.status ?? "available"} /></div><p className="mt-1.5 text-[11.5px] leading-5 text-muted-foreground">{agent.description}</p></div></div>{agent.capabilities?.length ? <div className="mt-4 flex flex-wrap gap-1.5">{agent.capabilities.slice(0, 6).map((capability) => <span key={capability} className="rounded-full bg-elevated px-2.5 py-1 text-[9.5px] text-muted-foreground">{capability}</span>)}</div> : null}<div className="mt-4 flex flex-wrap gap-2"><Link to="/chat" search={{ prompt: `Ask ${agent.name} to help me` } as never} className={actionClass("primary")}><Bot className="size-3.5" />Ask agent</Link><Link to="/connect" className={actionClass()}><ShieldCheck className="size-3.5" />Permissions</Link><Link to="/work" className={actionClass()}>Work <ExternalLink className="size-3" /></Link></div></article>)}</div>;
}
