import { AudioLines, Check, Mic2, Settings, X, Volume2, Waves } from "lucide-react";
import { createPortal } from "react-dom";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { createVoiceSession, endVoiceSession, streamKurukooChat } from "@/lib/kurukoo-api";

type LiveVoiceProps = { triggerIcon?: ReactNode; triggerLabel?: string; triggerClassName?: string; overlayTargetId?: string };
type Recognition = { lang: string; interimResults: boolean; continuous: boolean; start: () => void; stop: () => void; onresult: ((event: any) => void) | null; onend: (() => void) | null; onerror: (() => void) | null };
function getRecognition(): Recognition | null { if (typeof window === "undefined") return null; const Ctor = (window as any).SpeechRecognition ?? (window as any).webkitSpeechRecognition; if (!Ctor) return null; const rec: Recognition = new Ctor(); rec.interimResults = true; rec.continuous = false; return rec; }
const VOICE_PREFS_KEY = "kurukoo-voice-preferences";
const WAKE_PREF_KEY = "kurukoo-voice-wake";
const voiceLanguages = [["en-GB","English (UK)"],["en-US","English (US)"],["fr-FR","Français"],["es-ES","Español"],["pt-BR","Português"],["sw-KE","Kiswahili"]] as const;
const voiceStyles = [["calm","Calm"],["clear","Clear"],["warm","Warm"]] as const;

export function LiveVoice({ triggerIcon = <Mic2 className="size-[17px] text-muted-foreground" />, triggerLabel = "Talk to Kurukoo", triggerClassName = "grid size-9 place-items-center rounded-full hover:bg-elevated", overlayTargetId }: LiveVoiceProps) {
  const [open,setOpen]=useState(false); const [settingsOpen,setSettingsOpen]=useState(false); const [listening,setListening]=useState(false); const [wakeListening,setWakeListening]=useState(false); const [wakeEnabled,setWakeEnabled]=useState(false); const [status,setStatus]=useState("Voice mode is ready. Say “Hey Kurukoo” or start talking."); const [heard,setHeard]=useState(""); const [reply,setReply]=useState(""); const [style,setStyle]=useState<"calm"|"clear"|"warm">("calm"); const [language,setLanguage]=useState("en-GB");
  const recognitionRef=useRef<Recognition|null>(null); const sessionRef=useRef<{sessionId:string;conversationId?:string}|null>(null); const wakeArmedRef=useRef(false); const closingRef=useRef(false);
  useEffect(()=>{const onPrefs=(event:Event)=>{const d=(event as CustomEvent<{style?:string;language?:string}>).detail||{}; if(d.style==="calm"||d.style==="clear"||d.style==="warm")setStyle(d.style); if(d.language)setLanguage(d.language)}; window.addEventListener("kurukoo-voice-preferences",onPrefs); return()=>window.removeEventListener("kurukoo-voice-preferences",onPrefs)},[]);
  useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(VOICE_PREFS_KEY)||"{}"); if(p.style==="calm"||p.style==="clear"||p.style==="warm")setStyle(p.style); if(typeof p.language==="string")setLanguage(p.language); setWakeEnabled(localStorage.getItem(WAKE_PREF_KEY)==="true")}catch{}},[]);
  useEffect(()=>{window.dispatchEvent(new CustomEvent("kurukoo-voice-state",{detail:{open,listening,wakeListening,style,language}})); if(open)localStorage.setItem("kurukoo-voice-open","1");else localStorage.removeItem("kurukoo-voice-open")},[open,listening,wakeListening,style,language]);
  useEffect(()=>()=>{closingRef.current=true; recognitionRef.current?.stop(); if(sessionRef.current)void endVoiceSession(sessionRef.current.sessionId,"client_unmount")},[]);
  function savePrefs(nextStyle=style,nextLanguage=language){localStorage.setItem(VOICE_PREFS_KEY,JSON.stringify({style:nextStyle,language:nextLanguage}));window.dispatchEvent(new CustomEvent("kurukoo-voice-preferences",{detail:{style:nextStyle,language:nextLanguage}}))}
  async function ensureSession(){if(sessionRef.current)return sessionRef.current;setStatus("Starting your voice session…");const s=await createVoiceSession();sessionRef.current=s;return s}
  async function speak(text:string){if(!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=language;u.rate=style==="clear"?.94:style==="warm"?.98:.9;u.pitch=style==="warm"?1.04:style==="clear"?.98:.92;window.speechSynthesis.speak(u)}
  async function submitSpokenRequest(text:string){const clean=text.replace(/^[,.:;\s]+/,"").trim();if(!clean){setStatus("I'm listening for what you need.");return}try{const s=await ensureSession();setStatus("Kurukoo is working on it…");setReply("");const result=await streamKurukooChat({message:clean,conversationId:s.conversationId,channel:"web_voice",onEvent:e=>{if(e.type==="conversation"&&e.conversationId)s.conversationId=e.conversationId}});s.conversationId=result.conversationId;setReply(result.reply);setStatus("You can keep talking.");if(result.reply)await speak(result.reply)}catch(error){setStatus(error instanceof Error?error.message:"Voice conversation is unavailable right now.")}}
  function startListening(){const r=getRecognition();if(!r){setStatus("Voice input is not available in this browser. You can use the text composer instead.");return}wakeArmedRef.current=false;r.continuous=false;r.lang=language;setHeard("");setStatus("Listening…");r.onresult=e=>setHeard(Array.from(e.results||[]).map((x:any)=>x?.[0]?.transcript||"").join(" ").trim());r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setStatus("I couldn't hear that clearly. Try again.")};recognitionRef.current=r;try{r.start();setListening(true)}catch{setListening(false)}}
  function startWakePhraseListener(){const r=getRecognition();if(!r){setStatus("Wake phrase listening is not available in this browser.");return}closingRef.current=false;wakeArmedRef.current=false;r.continuous=true;r.lang=language;setHeard("");setStatus("Listening for “Hey Kurukoo”…");r.onresult=e=>{const text=Array.from(e.results||[]).map((x:any)=>x?.[0]?.transcript||"").join(" ").trim();const wake=/\bhey\s+kurukoo\b/i.exec(text);if(wake){const after=text.slice((wake.index??0)+wake[0].length).trim();setHeard(after||"Hey Kurukoo");wakeArmedRef.current=!after;if(after){r.stop();setWakeListening(false);void submitSpokenRequest(after)}else setStatus("I'm listening for what you need.")}else if(wakeArmedRef.current&&text){r.stop();setWakeListening(false);wakeArmedRef.current=false;setHeard(text);void submitSpokenRequest(text)}};r.onend=()=>{setWakeListening(false);if(!closingRef.current)setStatus("Wake phrase listening stopped. Start it again when ready.")};r.onerror=()=>{setWakeListening(false);wakeArmedRef.current=false;setStatus("Wake phrase listening stopped. Try again.")};recognitionRef.current=r;try{r.start();setWakeListening(true)}catch{setWakeListening(false)}}
  function stopListening(){recognitionRef.current?.stop();setListening(false);setWakeListening(false);wakeArmedRef.current=false}
  async function handleStopListening(){recognitionRef.current?.stop();setListening(false);const text=heard.trim();if(!text){setStatus("No spoken request was captured.");return}await submitSpokenRequest(text)}
  function toggleWakeEnabled(){const next=!wakeEnabled;setWakeEnabled(next);localStorage.setItem(WAKE_PREF_KEY,String(next));if(next&&open)startWakePhraseListener();if(!next)stopListening()}
  function close(){closingRef.current=true;stopListening();window.speechSynthesis?.cancel();setSettingsOpen(false);if(sessionRef.current)void endVoiceSession(sessionRef.current.sessionId,"user_closed");sessionRef.current=null;setOpen(false)}
  const browserVoice=typeof window!=="undefined"&&( "SpeechRecognition"in window || "webkitSpeechRecognition"in window);
  const overlay=open?<div role="dialog" aria-modal="true" aria-label="Kurukoo voice mode" className={overlayTargetId?"absolute inset-0 z-[100] flex min-h-full flex-col overflow-hidden bg-background/98 backdrop-blur-xl":"fixed inset-0 z-[100] flex min-h-screen flex-col bg-background lg:right-[224px]"}>
    <header className="relative flex h-14 shrink-0 items-center justify-between border-b border-border px-5 md:px-8"><div className="flex items-center gap-2"><div className="grid size-7 place-items-center rounded-lg bg-brand-tint text-brand-ink"><AudioLines className="size-4"/></div><div><p className="text-[13px] font-semibold">Kurukoo</p><p className="text-[10px] text-muted-foreground">Voice conversation</p></div></div><div className="flex items-center gap-1"><button type="button" onClick={()=>setSettingsOpen(v=>!v)} aria-label="Voice settings" aria-expanded={settingsOpen} className="grid size-9 place-items-center rounded-full hover:bg-elevated"><Settings className="size-[17px]"/></button><button type="button" onClick={close} aria-label="Close voice mode" className="grid size-9 place-items-center rounded-full hover:bg-elevated"><X className="size-[18px]"/></button></div>
    {settingsOpen?<div className="absolute right-5 top-[62px] z-[120] w-[min(340px,calc(100vw-40px))] rounded-2xl border border-border bg-surface p-4 text-left shadow-[var(--shadow-lift)]"><div className="flex items-center gap-2"><Settings className="size-4 text-primary"/><p className="text-[12px] font-semibold">Voice settings</p></div><label className="mt-4 block text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Language<select value={language} onChange={e=>{const n=e.target.value;setLanguage(n);savePrefs(style,n)}} className="mt-1.5 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-[12px] font-medium outline-none">{voiceLanguages.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-3 block text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Voice style<select value={style} onChange={e=>{const n=e.target.value as "calm"|"clear"|"warm";setStyle(n);savePrefs(n,language)}} className="mt-1.5 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-[12px] font-medium outline-none">{voiceStyles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button type="button" onClick={toggleWakeEnabled} disabled={!browserVoice} className="mt-4 flex w-full items-start gap-3 rounded-xl border border-border bg-background p-3 text-left disabled:opacity-50"><span className={`grid size-8 shrink-0 place-items-center rounded-lg ${wakeEnabled?"bg-primary text-primary-foreground":"bg-elevated text-muted-foreground"}`}>{wakeEnabled?<Check className="size-4"/>:<Waves className="size-4"/>}</span><span><span className="block text-[11.5px] font-semibold">Hey Kurukoo wake phrase</span><span className="mt-0.5 block text-[10.5px] leading-4 text-muted-foreground">Listens only while this Voice screen is active.</span></span></button><p className="mt-3 text-[10px] text-muted-foreground">Preferences are saved on this device.</p></div>:null}</header>
    <div className="flex min-h-0 flex-1 flex-col items-center justify-center overflow-y-auto px-6 py-8 text-center"><div className={`relative grid size-36 shrink-0 place-items-center rounded-full bg-brand-tint text-brand-ink transition-all duration-500 ${listening||wakeListening?"scale-110 shadow-[0_0_0_18px_var(--brand-tint)]":""}`}><div className={`grid size-24 place-items-center rounded-full bg-background/80 ${listening||wakeListening?"animate-pulse":""}`}><AudioLines className="size-9" strokeWidth={1.5}/></div></div><p className="mt-8 text-[24px] font-semibold tracking-tight">{wakeListening?"Listening for Hey Kurukoo":listening?"I'm listening":"Voice mode"}</p><p className="mt-2 max-w-md text-[13px] leading-relaxed text-muted-foreground">{status}</p>{heard?<p className="mt-5 max-w-xl rounded-2xl border border-border bg-surface px-4 py-3 text-[13px]">“{heard}”</p>:null}{reply?<div className="mt-4 max-w-xl rounded-2xl bg-elevated px-4 py-3 text-left text-[13px] leading-relaxed"><div className="mb-2 flex items-center gap-2 text-[10.5px] font-medium text-muted-foreground"><Volume2 className="size-3.5"/> Spoken reply</div>{reply}</div>:null}<div className="mt-8 flex flex-wrap items-center justify-center gap-2"><button type="button" onClick={()=>listening?void handleStopListening():wakeListening?stopListening():startListening()} disabled={!browserVoice} className="inline-flex items-center gap-2 rounded-full bg-foreground px-6 py-3 text-[12px] font-medium text-background disabled:opacity-40"><Mic2 className="size-4"/>{listening?"Finish speaking":wakeListening?"Stop listening":"Start talking"}</button><button type="button" onClick={()=>wakeListening?stopListening():startWakePhraseListener()} disabled={!browserVoice} className={`inline-flex items-center gap-2 rounded-full border px-5 py-3 text-[12px] font-medium disabled:opacity-40 ${wakeListening?"border-primary/30 bg-brand-tint text-brand-ink":"border-border bg-surface hover:bg-elevated"}`}><Waves className="size-4"/>{wakeListening?"Listening…":"Hey Kurukoo"}</button></div>{!browserVoice?<p className="mt-3 text-[10.5px] text-muted-foreground">This browser does not expose speech recognition.</p>:null}</div>
    <footer className="shrink-0 pb-7 text-center text-[10px] text-muted-foreground">Voice uses the same Kurukoo conversation relationship as text. Sessions continue in Chat history.</footer></div>:null;
  useEffect(()=>{if(open&&wakeEnabled&&browserVoice&&!wakeListening&&!listening)startWakePhraseListener()},[open,wakeEnabled]);
  return <><span className="relative inline-flex"><button type="button" aria-label={triggerLabel} title={triggerLabel} onClick={()=>{closingRef.current=false;setOpen(true)}} className={triggerClassName}>{triggerIcon}</button></span>{overlayTargetId&&typeof document!=="undefined"?createPortal(overlay,document.getElementById(overlayTargetId)||document.body):overlay}</>;
}
