import { CheckCircle2, FileCheck2, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { fetchEconomicCoordination, type EconomicCoordination } from "@/lib/kurukoo-api";
function label(value: string) { return value.replace(/[_-]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()); }
function formatEvidence(value: unknown): string { if (typeof value === "string") return value; if (value === null || value === undefined) return ""; try { return JSON.stringify(value, null, 2); } catch { return String(value); } }
export function OutcomeEvidence({ requestId }: { requestId: string }) {
  const [coordination, setCoordination] = useState<EconomicCoordination | null>(null);
  useEffect(() => { let cancelled = false; void fetchEconomicCoordination(requestId).then((next) => { if (!cancelled) setCoordination(next); }).catch(() => { if (!cancelled) setCoordination(null); }); return () => { cancelled = true; }; }, [requestId]);
  const evidence = (coordination?.participants ?? []).filter((item) => item.evidence && Object.keys(item.evidence).length > 0);
  if (!evidence.length && !coordination?.offer) return null;
  return <section className="mt-6 rounded-2xl border border-border bg-surface p-5" aria-label="Outcome evidence"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-primary">Proof & outcome</p><h2 className="mt-1 text-[18px] font-semibold">What has actually been reported</h2><p className="mt-1 text-[11.5px] leading-relaxed text-muted-foreground">Kurukoo separates a provider's evidence from your confirmation of the final outcome.</p></div><ShieldCheck className="size-5 text-primary"/></div>{coordination?.offer ? <div className="mt-4 rounded-xl bg-elevated/50 p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Offer</p><p className="mt-1 text-[12.5px] font-medium">{coordination.offer.description || "Offer returned"}</p>{coordination.offer.priceMinor != null ? <p className="mt-1 text-[11px] text-muted-foreground">{coordination.offer.currency || ""} {(coordination.offer.priceMinor / 100).toFixed(2)}</p> : null}</div> : null}<div className="mt-3 space-y-2">{evidence.map((participant) => <article key={String(participant.id ?? participant.providerPhone)} className="rounded-xl border border-border p-3"><div className="flex items-center gap-2"><FileCheck2 className="size-4 text-primary"/><p className="text-[12px] font-medium">{label(participant.role || "Provider")}</p><span className="ml-auto rounded-full bg-elevated px-2 py-0.5 text-[9.5px] text-muted-foreground">{label(participant.status || "reported")}</span></div><div className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries(participant.evidence || {}).filter(([key]) => key !== "quote").slice(0, 6).map(([key, value]) => <div key={key} className="rounded-lg bg-elevated/50 px-2.5 py-2"><p className="text-[9.5px] uppercase tracking-[0.08em] text-muted-foreground">{label(key)}</p><p className="mt-0.5 whitespace-pre-wrap break-words text-[11.5px]">{formatEvidence(value)}</p></div>)}</div>{participant.status === "completion_reported" ? <div className="mt-3 flex items-center gap-2 rounded-lg border border-primary/15 bg-brand-tint/10 px-2.5 py-2 text-[10.5px] text-muted-foreground"><CheckCircle2 className="size-3.5 shrink-0 text-primary"/>Provider reported completion. Your confirmation is still separate.</div> : null}</article>)}</div></section>;
}
