import { Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { useKurukoo } from "@/lib/kurukoo-store";

export function WorkspaceHome() {
  const { work } = useKurukoo();
  const active = work.filter((item) => item.stage !== "done").slice(0, 5);
  const needsYou = active.filter((item) => item.stage === "needs_you");
  return <div className="min-w-0 space-y-6">
    <section className="rounded-[24px] border border-border bg-surface p-6 md:p-8"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-brand-tint text-brand-ink"><Sparkles className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Personal workspace</p><h1 className="mt-1 font-serif text-[32px] leading-tight tracking-[-0.04em]">Your Kurukoo, at work.</h1><p className="mt-2 max-w-2xl text-[13.5px] leading-relaxed text-muted-foreground">A private control surface for conversations, active work, approvals and trusted context. The public Kurukoo homepage is separate.</p></div><Link to="/chat" className="hidden shrink-0 items-center gap-1 rounded-full bg-primary px-4 py-2 text-[12px] font-medium text-primary-foreground sm:inline-flex">Start something <ArrowRight className="size-3.5" /></Link></div></section>
    <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><section className="overflow-hidden rounded-2xl border border-border bg-surface"><div className="flex items-center justify-between gap-3 border-b border-border/70 px-4 py-3.5"><div><h2 className="text-[14px] font-semibold">Active work</h2><p className="mt-0.5 text-[11.5px] text-muted-foreground">Things Kurukoo is currently handling.</p></div><Link to="/work" className="text-[11.5px] font-medium text-muted-foreground hover:text-foreground">View all</Link></div>{active.length ? <div className="divide-y divide-border/70">{active.map((item) => <Link key={item.id} to="/work/$workId" params={{ workId: item.id }} className="flex items-center gap-3 px-4 py-3.5 hover:bg-elevated/60"><span className="grid size-8 shrink-0 place-items-center rounded-[10px] bg-elevated"><CheckCircle2 className="size-4 text-primary" /></span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{item.title}</p><p className="truncate text-[11.5px] text-muted-foreground">{item.detail}</p></div><span className="shrink-0 text-[11px] text-muted-foreground">{item.updated}</span></Link>)}</div> : <div className="px-4 py-8 text-[12px] text-muted-foreground">Nothing is active yet. Tell Kurukoo what you want to accomplish.</div>}</section><div className="space-y-4"><section className="rounded-2xl border border-border bg-surface p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-elevated"><MessageCircle className="size-4" /></span><div><h2 className="text-[14px] font-semibold">Conversation</h2><p className="text-[11.5px] text-muted-foreground">Your main way into Kurukoo.</p></div></div><Link to="/chat" className="mt-4 inline-flex items-center gap-1 text-[12px] font-medium">Open conversation <ArrowRight className="size-3.5" /></Link></section><section className="rounded-2xl border border-border bg-surface p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-elevated"><ShieldCheck className="size-4" /></span><div><h2 className="text-[14px] font-semibold">Trusted context</h2><p className="text-[11.5px] text-muted-foreground">{needsYou.length ? `${needsYou.length} item${needsYou.length === 1 ? "" : "s"} need${needsYou.length === 1 ? "s" : ""} your attention.` : "Nothing needs your attention right now."}</p></div></div><Link to="/memory" className="mt-4 inline-flex text-[12px] font-medium">Review context <ArrowRight className="ml-1 size-3.5" /></Link></section></div></div>
  </div>;
}
